### ISSUE TITLE
Wrong question type in Hashing quiz in the Data Structures and Algorithms course

### ISSUE THREAD

**Issue by zmakrevski** [LeetCode-Feedback/LeetCode-Feedback#10013]
#### Your LeetCode username
t5810m

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
You have wrong label on the third question. It says Multiple Choice Question, and it is Single Choice question

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for your time. The problem says "Multiple Choice Question" because there are multiple choices, but that doesn't mean there are "Multiple Answers", the interface only allows you to select one answer anyways as indicated by the radio buttons... This is already a single-answer question. We appreciate your support!

**Comment by vovacha** [comment]
@LC-Pam, I also agree with @zmakrevski. What is the opposite then? One choice question with one option?
You end up having "Multiple Choice Question" label for every question, and with the current explanation, it's just a redundant piece of information.
Also, it's misleading. Usually when you see "multiple choice" it means there is more than one choice for an answer.
I think you should either remove or rename this label for the questions with only one choice.
