### ISSUE TITLE
Discussion Page's Menubar Still Showing The Old UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10239]
When you click on the discussion page, the menubar is still the old UI from years ago. See image below.
![image](https://user-images.githubusercontent.com/90146234/206728745-f6074dfb-9325-4216-b3e9-1678b385255a.png)

The discussion page should be showing the new UI for menubar like the other pages below.
![image](https://user-images.githubusercontent.com/90146234/206729675-21e1b70f-d0aa-4451-a55b-5e3481d1af30.png)

**Comment by ThomasShaw1** [comment]
After brief exploration, it seems that additional pages also show the old menubar UI. See the links below:
https://leetcode.com/profile/
https://leetcode.com/explore/
https://leetcode.com/store/
https://leetcode.com/contest/weekly-contest-322/
https://leetcode.com/playground/
https://leetcode.com/list/
https://leetcode.com/notes/
https://leetcode.com/points/
https://leetcode.com/subscription/
https://leetcode.com/submissions/
https://leetcode.com/store/orders
https://leetcode.com/profile/

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/create?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3357390?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by ThomasShaw1** [comment]
Updated the list of links to pages.

**Comment by ThomasShaw1** [comment]
Updated again.

**Comment by ThomasShaw1** [comment]
Updated again.

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
