### ISSUE TITLE
Inconsistent submitted Runtime in python 3

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [LeetCode-Feedback/LeetCode-Feedback#10289]
#### Your LeetCode username
professionalismismymiddlename

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Runtime of a submitted solution varies wildly between submitted runs.  
Submitting the same code multiple times can bring as much as 50% more or less milliseconds of Runtime.  
Only tested in python 3.  
Tested on [124. Binary Tree Maximum Path Sum](https://leetcode.com/problems/binary-tree-maximum-path-sum/), [420. Strong Password Checker](https://leetcode.com/problems/strong-password-checker/), [1480. Running Sum of 1d Array](https://leetcode.com/problems/running-sum-of-1d-array/).  
Below is my answer for 124, with four submitted runs at 306, 140, 223 and 213ms. Please disregard the quality of the code itself.

#### Code you used for Submit/Run operation

```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    globalmax = 0

    def maxPathSumrec(self, root: Optional[TreeNode]) -> int:
        possibles = []
        brokenpossibles = []
        if (root.left != None):
            lres = self.maxPathSumrec(root.left)
            possibles.append(lres + root.val)
            brokenpossibles.append(lres)

        if (root.right != None):
            rres = self.maxPathSumrec(root.right)
            possibles.append(rres + root.val)
            brokenpossibles.append(rres)

        if (root.left != None and root.right != None):
            brokenpossibles.append(rres + lres + root.val)

        possibles.append(root.val)

        pmax = max(possibles)
        if (len(brokenpossibles) > 0):
            bmax = max(brokenpossibles)
            if (bmax > pmax and bmax > self.globalmax):
                self.globalmax = bmax
            
        return(pmax)

    def maxPathSum(self, root: Optional[TreeNode]) -> int:
        self.globalmax = root.val
        
        r = self.maxPathSumrec(root)
        if (r > self.globalmax):
            return (r)
        return self.globalmax
```

#### Language used for code
Python 3

#### Expected behavior
The Runtime should be the same for each submission. Otherwise, it makes it impossible to accurately compare your efficiency with other users. A small amount of variation is to be expected in most languages. A variation of double (or half) the runtime is not.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), and O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors also affect the runtime of the same program, introducing some level of discrepancy.

I hope this helps. Should you have any other questions, please let us know.
