### ISSUE TITLE
Missing constraints - 231. Power of Two

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1032]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Please add constraints to this problem.

231. Power of Two
https://leetcode.com/problems/power-of-two/

- Does it include -ves?
- Looks like, all -ve numbers & 0 will yield false as return value.
- Is it 32 bit integer?
- Is the range? -2147483648 <= n <= 2147483647

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior
A question must include constraints to get a 100% runtime.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thanks for reaching out to us. I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem! I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
