### ISSUE TITLE
Missing Constraints - 653. Two Sum IV - Input is a BST

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1043]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

653. Two Sum IV - Input is a BST
https://leetcode.com/problems/two-sum-iv-input-is-a-bst/

Please add constraints to the above problem:

- What is the range of values?
- What is the max height of the tree?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

All problems must have constraints to avoid TLE errors.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thanks for reaching out to us. I have relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thanks for your feedback regarding this problem. Upon review, we have added the missing constraints. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
