### ISSUE TITLE
Missing test case - 1375. Number of Times Binary String Is Prefix-Aligned (63/63 test cases passed but there is an TLE)

### ISSUE THREAD

**Issue by MIT4893-Projects** [LeetCode-Feedback/LeetCode-Feedback#10475]
#### Your LeetCode username
Minh4893IT

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

When I submitted my code on problem 1375, (the console show up "63/63 testcases passed" but also give me "Time Limit Exceed" message. Also, there is no input argument vector in the flips argument box.

#### Code you used for Submit/Run operation

```
class Solution
{
public:
    vector<bool> binaryString;
    bool prefixAlignedBinary(int idx)
    {
        for (int i = 0; i <= idx; ++i)
        {
            if (!binaryString[i])
            {
                return false;
            }
        }
        return true;
    }

    int numTimesAllBlue(vector<int> &flips)
    {
        int count = 0;
        binaryString = vector<bool>(flips.size(), 0);
        for (int i = 0; i < flips.size(); ++i)
        {
            binaryString[flips[i] - 1] = !binaryString[flips[i] - 1];
            if (prefixAlignedBinary(i))
            {
                ++count;
            }
        }
        return count;
    }
};
```

#### Language used for code
C++

#### Screenshots

![image](https://user-images.githubusercontent.com/116936560/209102180-8b5313b4-ac97-4c0e-9c91-35ec54a4f0da.png)

#### Additional context

Submission details: https://leetcode.com/problems/number-of-times-binary-string-is-prefix-aligned/submissions/863673976/

**Comment by nskybytskyi** [comment]
The old design has a more elaborate message: "63 / 63 test cases passed, but took too long." There is no "last executed input" because no _individual_ test case caused the TLE. Instead, it is the _total_ running time that is just a little bit too slow. The "last executed input" field shows a specific test case only if running this test case alone will TLE. The user experience would be even more confusing otherwise: you get a test that works fine when you run it but TLEs upon submission.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. Please consider above comment as the reference. If you have any questions, please let us know. Thank you.
