### ISSUE TITLE
 213. House Robber II: Wrong solution explanation provided

### ISSUE THREAD

**Issue by devilsuse** [LeetCode-Feedback/LeetCode-Feedback#1048]
I found a possible bug in the explanation of solution for the problem  213. House Robber II.
Solution says: 

`If there are three houses, you can either pick the middle house or the sum of the first and the last house. Therefore, it boils down to max(house3 + house1, house2).`

But actually it should be max(house1, house2, house3). In fact, if you run testcase [5,6,8] you will get 8 and not 13.
Please correct it.

**Comment by lc-ivan** [comment]
Hi @devilsuse ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate. #

**Comment by lc-ivan** [comment]
Hi @devilsuse ,
Thank you for your feedback regarding this problem. Upon review, our team has noted the solution is correct and the above statement applies to the case where the input is a linear list as in the previous problem of House Robber, not the ring as for this problem.

Therefore, for the input [5, 6, 8], in the previous problem of House Robber, we can rob the first and the third houses since they are not adjacent to each other. While for the problem of House Robber II, the first and the third(also the last) house are adjacent to each other, as a result, we cannot rob them together.
