### ISSUE TITLE
tree visualization tool

### ISSUE THREAD

**Issue by Johan1974** [LeetCode-Feedback/LeetCode-Feedback#10615]
#### Your LeetCode username
Johanlijffijt

#### Category of the bug
- [ X] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In your instructions\video i read and see about a tree visualization tool. 
Only this button is not available in my environement.
Do i need to activate this somewhere?

#### Language used for code
JavaScript

#### Expected behavior
To ee the button for the tree visualization tool

#### Screenshots
I am reading these instructions 
https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/678/sql-data-structure/4353/

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
