### ISSUE TITLE
TLE for optimal Ruby solution for #2476. Closest Nodes Queries in a Binary Search Tree

### ISSUE THREAD

**Issue by revug** [LeetCode-Feedback/LeetCode-Feedback#10730]
#### Problem
2476: Closest Nodes Queries in a Binary Search Tree
https://leetcode.com/problems/closest-nodes-queries-in-a-binary-search-tree/description/

#### Your LeetCode username
codingstar1

#### Category of the bug
- [x] Solution
- [x] Language

#### Description of the bug
An optimal iterative solution for ruby doesn't get accepted going to TLE.

#### Code you used for Submit/Run operation

```ruby
def closest_nodes(root, queries)
    ready = Array.new(1000_001)
    queries.map do |query|
        next ready[query] if ready[query]
        min = max = -1
        node = root
        while node
            val = node.val
            break min = max = query if val == query
            if val > query
                max = val
                node = node.left
            else
                min = val
                node = node.right
            end
        end
        ready[query] = [min, max]
    end
end
```

#### Language used for code
Ruby

#### Expected behavior
This solution should be accepted without doubt.

#### Screenshots

https://i.ibb.co/RBfqzGh/TLE.png

#### Additional context

Proof: https://leetcode.com/problems/closest-nodes-queries-in-a-binary-search-tree/submissions/870437245/
Solution using recursion goes to TLE also.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

**Comment by revug** [comment]
I have to reopen this issue since your comment seems to be irrelevant. My algorithm should be optimal, it is logarithmic, while your Swift code is of another problem totally different and completely irrelevant problem.
Current problem is about binary search tree. Look what problem is solved by that Swift solution. You will be surprised.
