### ISSUE TITLE
LeetCode Interview And Online Assessment Editor Still Using The Old Editor UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#10815]
https://interview.leetcode.com/interview/
https://leetcode.com/assessment/

When I do a mock assessment, I noticed that the editor are still using the old editor UI. When I do a mock interview session, I noticed that the editor is using a different editor UI than the one in problems tab of the current release. Honestly, the new editor UI in mock interview session is much better than the one for problems tab of the current release, we should just replace it.

**Comment by ThomasShaw1** [comment]
On another note, It seems that the code displayer in contest ranking is also using the old code displaying UI.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
https://project.feishu.cn/leetcode/us_tickets/detail/3621047?parentUrl=%2Fleetcode%2FworkObjectView%2Fus_tickets%2FvHtNOOSVR

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
