### ISSUE TITLE
Missing Test Case - 670. Maximum Swap

### ISSUE THREAD

**Issue by Musheera** [LeetCode-Feedback/LeetCode-Feedback#10907]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by siddiki002** [comment]
## LeetCode Username:
siddki02

## Category:
Missing Test Case

## Description

The test case is 1993, which would become a maximum of 9193 after one swap whereas in the expected outcome it is 9913. The question clearly says that there could be a maximum of one swap possible but here two are done.
## Code:
    def convertTonum(temp):

    number = 0

    for i in range(len(temp)):
        number*=10
        number+=int(temp[i])
    return number
    class Solution:
    def maximumSwap(self, num: int) -> int:

        temp = str(num)
        temp = list(temp)
        swap_count = 0
        swap_index = -1
        for i in range(len(temp)):
            key = temp[i]

            for j in range(i+1,len(temp)):
                if temp[j] > temp[i]:
                    if swap_index == -1:
                        swap_index = j
                    else:
                        if (temp[j] > temp[swap_index]):
                            swap_index = j
            if swap_index != -1:
                temp[i] = temp[swap_index]
                temp[swap_index] = key
                break
            #     swap_index = -1
            #     swap_count+=1
            # if swap_count==2:
            #     break

        temp = convertTonum(temp)
        return temp
# Language used:
Python
# Expected behavior
Stated above
## Screenshots:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/78559233/e2662650-8276-4f00-a753-ce86813b0cd8)
