### ISSUE TITLE
Missing Test Case - 2139. Minimum Moves to Reach Target Score

### ISSUE THREAD

**Issue by stupidly-logical** [LeetCode-Feedback/LeetCode-Feedback#10928]
#### Your LeetCode username
stupidly_logical

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
After submitting the code, 145/145 test case pass but last case seems to be incorrectly formatted or some other error and judge returns TLE.

#### Code you used for Submit/Run operation

```
// 2139. Minimum Moves to Reach Target Score
class Solution {
public:
    int minMoves(int t, int md) {
        if (md == 0)
            return t-1;
        int ans = 0;
        while(t > 1) {
            if (t % 2 == 0 && md > 0) {
                t /= 2;
                md--;
            }
            else
                t--;
            ans++;
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
As the screenshot depicts, all the test case pass so my solution should get accepted but judge outputs TLE.

#### Screenshots
![Screenshot from 2023-01-10 17-47-23](https://user-images.githubusercontent.com/17554626/211551400-59c47157-726e-46de-b750-1c8824d7bcf9.png)

#### Additional context
NA

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary
