### ISSUE TITLE
Hidden Test Case in problem №16  3Sum Closest 

### ISSUE THREAD

**Issue by SolovievViacheslav** [LeetCode-Feedback/LeetCode-Feedback#10936]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem: 3Sum Closest
After submit I have got this:
Time Limit Exceeded
98 / 98 testcases passed
Last Executed Input
nums =

#### Code you used for Submit/Run operation

```
// 3Sum Closest 
#define max(a,b) ((a>b)?a:b)
#define min(a,b) ((a<b)?a:b)

#define dist(a,b) (max(a,b)-min(a,b))
class Solution {
public:
    int threeSumClosest(vector<int>& nums, int target) {
       int res;
              
        sort(nums.begin(),nums.end());

        int s=nums[0]+nums[1]+nums[2];
        int prev_s=s;
        int prev_s2=s;
        if(nums.size()==3)return s;

        unsigned int prev_dist=(unsigned int)-1;
        unsigned int prev_dist2=(unsigned int)-1;
  
        for(int i=0;(i<nums.size()-2);i++)
        {
            prev_dist=(unsigned int)-1;

            for(int j=i+1;(j<nums.size()-1);j++)
            {
                prev_dist=(unsigned int)-1;
                for(int k=j+1;(k<nums.size());k++)
                {
                    s=nums[i]+nums[j]+nums[k];

                    if(i==1&&j==6)
                    {
                        int t;
                        t++;
                    }
                    if(s==target)return s;
                    int d=dist(s,target);
                    if(d<prev_dist){prev_dist=d;prev_s=s;}
                    else if(d>=prev_dist)
                    {
                       break;
                    }

                    if(prev_dist<prev_dist2)
                    {
                        prev_dist2=prev_dist;
                        prev_s2=prev_s;
                    }
                    //cout<<prev_s2<<endl;
                }

            }

        }

        res=prev_s2;
        return res;
    }
};
```

#### Screenshots

![Untitled](https://user-images.githubusercontent.com/114352818/211629261-4edb91f2-8507-456a-8fcf-023ddc161322.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

**Comment by SolovievViacheslav** [comment]
Thanks for answer. It's clear for me now, I am going to optimize my code.

ср, 11 янв. 2023 г., 00:42 LC_M ***@***.***>:
