### ISSUE TITLE
Unwanted TLE in Question 201 Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by joshi248** [LeetCode-Feedback/LeetCode-Feedback#11006]
#### Category of the bug
- [ 👍] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

This is clearly a fail of the online judge since the test case is not there and then also it is saying that all test case passed

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    int rangeBitwiseAnd(int left, int right) {
        if(5>=left && 10<=right) return 0;
        else{
            int ans=right;
            for(int i=left;i<right;++i) ans = ans&i;
            return ans;
        }
        return -1;
    }
};
```

#### Expected behavior

Not TLE should be there. Its simple and straight forward implementation. If 5 and 10 are there then their AND is 0 which in turn makes the whole AND 0. Simple

#### Screenshots

![image](https://user-images.githubusercontent.com/109964271/212364383-945a082c-7442-48c1-b45f-50dd95d972f3.png)

#### Additional context

Where is the test case (Basically all test cases are passed as can be seen from there) But the last test case is not there

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary
