### ISSUE TITLE
Contributions Count Not Available In New Profile Page UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11013]
Before the new UI was rolled out for the user profile page, I remembered the count  of contributions for test cases and problems being a part of the “community stats”. It would be great if we can have that back.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
