### ISSUE TITLE
Editor problems.

### ISSUE THREAD

**Issue by agiUnderground** [LeetCode-Feedback/LeetCode-Feedback#11052]
1)It's not possible to copy code from editor.
2)I want to DISABLE parenthesis autocomplete - so annoying!
3)Strange selections after the search in vim mode.
4)I want an option to disable ALL autocomplete features.

**Comment by LC-Pam** [comment]
Hi there,
Thank you for reaching out to us.
 I've relayed this issue to our team to investigate. 
We will reach back to you after we investigate.
Thank you for your support.

**Comment by LC-Pam** [comment]
Hi there, 

I've passed your feedback to our engineering team and they'll investigate. However, I'm afraid that we won't have a quick fix for the issue that you're facing.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
