### ISSUE TITLE
binary search template 2 ,right =length is wrong

### ISSUE THREAD

**Issue by ajayyewale96** [LeetCode-Feedback/LeetCode-Feedback#11112]
#### Your LeetCode username

BladeRunner_2049

#### Category of the bug
- [ ] Question

#### Description of the bug

for the following  link -->https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/    I can see that for template 2 of binary search **right** variable is initialized as **right=length** which is wrong according to me because we run the while loop for the condition where **left<right**.So once the loop breaks we will check the condition i.e try to access the **left** variable like **nums[left]** which according to above initialization of **right** variable will be equal to length of  array which will give "**index out of range error**"

#### Language used for code

C++

#### Expected behavior

According to me the correct initialization of the **right** variable should be **right=length-1**

#### Screenshots

![image](https://user-images.githubusercontent.com/71272513/213187392-04119a6f-a177-4d20-998a-5b2941c75c6d.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The explaniation as below: 

The condition of left < right will prevent the template from having an out-of-bounds error. mid can never be equal to right, just look at a few examples:

left = 2, right = 3. mid = 2 because its floor division.
left = 3, right = 4. mid = 3 because its floor division.

The only way that mid can be equal to the right is if left = right, but when that happens, the loop will break.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
