### ISSUE TITLE
Accepted code (After 2 wrong submission) in Weekly Contest 328 is now not shown and so my 3rd question is shown unsolved with 1 wrong submission

### ISSUE THREAD

**Issue by AyushBabbar** [LeetCode-Feedback/LeetCode-Feedback#11138]
#### Your LeetCode username

ayushbabbar

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My code for 3rd question in Weekly Contest 328 got accepted after 2 wrong submissions during the contest but now it is not showing accepted on contest page. But if I open the question in practice panel it is showing the original 2 wrong +2 correct submissions. 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    long long countGood(vector<int>& nums, int k) {
        long long left = 0, right = 0, count = 0, pairs = 0,n=nums.size();
        unordered_map<long long, long long> freq;
        while (right < nums.size()) 
        {
            freq[nums[right]]++;
            if(freq[nums[right]] > 1) 
                pairs += freq[nums[right]] - 1;
            while (pairs >= k && left<right) 
            {
                count+=(n-right);
                if(freq[nums[left]] > 1) 
                    pairs -= freq[nums[left]] - 1;
                freq[nums[left]]--;

                left++;
            }   
            right++;
        }
        return count;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Contest Page should have shown the third ques accepted but it is showing wrong answer (dropping my rank from ~3k to ~9k)

#### Screenshots

![contest](https://user-images.githubusercontent.com/76393139/213656206-91234263-cdc6-40b0-b621-702af4fd6496.jpg)
![accepted](https://user-images.githubusercontent.com/76393139/213656251-c9ada2df-4f9c-4563-8ebd-dd8edead1b1e.jpg)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

Thank you for reaching out to us, the same code could be TLE or AC because it's on the verge of not passing. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. We apologize for the inconvenience and thank you for your support!

In addition, every submission history will show on your submissions page. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
