### ISSUE TITLE
Incorrect Problem Description - 381. Insert Delete GetRandom O(1) - Duplicates allowed

### ISSUE THREAD

**Issue by stormsunshine** [LeetCode-Feedback/LeetCode-Feedback#11146]
#### Your LeetCode username
stormsunshine

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
In [381. Insert Delete GetRandom O(1) - Duplicates allowed](https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed), the problem description mentions: "It should support inserting and removing specific elements and also removing a random element."

The term "removing a random element" is incorrect, since `getRandom` returns a random element without removing it. Therefore, "removing a random element" should be changed to "returning a random element".

#### Expected behavior
The term "removing a random element" should be changed to "returning a random element".

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. Also, we think it's better to use "report" instead of "return" here.

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
