### ISSUE TITLE
BST visualizer not working in question: 426

### ISSUE THREAD

**Issue by gupta-sanyam** [LeetCode-Feedback/LeetCode-Feedback#11174]
#### Your LeetCode username
gssanyam12

#### Category of the bug
- [ ] Question

#### Description of the bug
tree visualizer works for some questions but not for others.
it is not working in - https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list/description/
but works in - https://leetcode.com/problems/binary-tree-inorder-traversal/

what I mean by visualizer is, in test cases, I can add input and it'll show me a visual. Its very helpful for debugging

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

Looks like this issue only happens on the new vision of the Leetcode website. 

I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
