### ISSUE TITLE
Contest 329 - 2547. Minimum Cost to Split an Array - Unfair Timing for Python

### ISSUE THREAD

**Issue by Zackhardtoname** [LeetCode-Feedback/LeetCode-Feedback#11200]
#### Your LeetCode username
sampleaccountpage

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For t4, my n^2 solution timed out while the same solution in CPP passed. That's so unfair. LeetCode please rejudge the contest!
Python: https://leetcode.com/problems/minimum-cost-to-split-an-array/submissions/882838190/
Same code in CPP: https://leetcode.com/problems/minimum-cost-to-split-an-array/submissions/882860955/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The above Python code received AC when we submit it, please check it here: https://leetcode.com/submissions/detail/883880783/

The same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
