### ISSUE TITLE
142. Linked List Cycle II (C#)

### ISSUE THREAD

**Issue by dmitryartuh** [LeetCode-Feedback/LeetCode-Feedback#11204]
#### Your LeetCode username
dmitryartux

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

A classic solution "fast/slow" for this problem doesn't fit the time limit for C#.

- [Time limit submission](https://leetcode.com/problems/linked-list-cycle-ii/submissions/883161136/)
- [Hashmap solution which works](https://leetcode.com/problems/linked-list-cycle-ii/submissions/883166050/)

Do you want to extend the time limit?

#### Code you used for Submit/Run operation

```
/**
 * Definition for singly-linked list.
 * public class ListNode {
 *     public int val;
 *     public ListNode next;
 *     public ListNode(int x) {
 *         val = x;
 *         next = null;
 *     }
 * }
 */
public class Solution {
    public ListNode DetectCycle(ListNode head) {
        var fast = head;
        var slow = head;
        while (fast != null && slow != null) {
            fast = fast.next?.next;
            slow = slow.next;
            if (fast?.val == slow?.val && fast != null) {
                break;
            }
        }

        if (slow == null || fast == null) {
            return null;
        }

        slow = head;
        while (slow != fast) {
            slow = slow.next;
            fast = fast.next;
        }

        return fast;
    }
}
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's on the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary
