### ISSUE TITLE
No permission to solve question from bonus problems

### ISSUE THREAD

**Issue by rusnikolaev1** [LeetCode-Feedback/LeetCode-Feedback#11238]
#### Your LeetCode username
rusnikolaev1

#### Category of the bug
- [ ] Question

#### Description of the bug
I go through LeetCode's Interview Crash Course. There are bonus tasks in the end of each chapter. And at end of chapter Binary Search there are bonus problems as well. But one the problems is unavailable due to lack of premium permissions. This task is unavailable: [1533. Find the Index of the Large Integer](https://leetcode.com/problems/find-the-index-of-the-large-integer/)

#### Expected behavior
Previously all bonus problems were available

#### Screenshots

![image](https://user-images.githubusercontent.com/49721892/214329123-89ea4f35-5146-4827-b943-c59d9dabf07e.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
