### ISSUE TITLE
Language Display in Recent AC

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11231]
https://leetcode.com/66bro-CUNY/

It used to be the case that you can see the language right next to your submissions under "Recent AC", now is gone. Can we bring it back?

**Comment by LC-Pam** [comment]
Hi ThomasShaw1,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature or function feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our feature support agent will reply to you within 24 hours and report those issues. 

Best,

LC

We really appreciate your support.
