### ISSUE TITLE
Missing Constraints - 110. Balanced Binary Tree

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#1124]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

110. Balanced Binary Tree
https://leetcode.com/problems/balanced-binary-tree/

Please add constraints
- What is the maximum number of nodes in the tree?
- What range of values each node will take? Is it `-3000 <= node.val <= 3000`

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

- The question must have constraints to avoid TLE or other errors for the user.
( I am submitting the code now, can't wait for more time on the number of questions, I hope that there won't be errors. )

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
