### ISSUE TITLE
Router Error on Notification 

### ISSUE THREAD

**Issue by Pragnesh2208** [LeetCode-Feedback/LeetCode-Feedback#11241]
#### Category of the bug
- [ ] UI Related

#### Description of the bug

Getting the notification from different posts , but when I click in that notification it redirects to leetcode/discussion/interview-question

#### Screenshots

![image](https://user-images.githubusercontent.com/67188152/214349323-43a470a7-350b-4013-a527-8a6708e2154f.png)

#### Additional context

Resolve it as soon as possible , I'm not able to go to the post , which I subscribed

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
