### ISSUE TITLE
Can't switch badge

### ISSUE THREAD

**Issue by byegates** [LeetCode-Feedback/LeetCode-Feedback#11272]
#### Your LeetCode username

byegates

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I was trying to switch my badge to the latest one I earned, but it stuck, and can't be changed, can you help? I tried multiple times with different browser. I know this might not be the right channel for this issue, but I dont know where to submit this issue, could you help with forwarding if this is not the best way? Would really appreciate it.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
