### ISSUE TITLE
532. K-diff Pairs in an Array: Not very clear what question condition variables `a` and `b` are

### ISSUE THREAD

**Issue by nebhagat** [LeetCode-Feedback/LeetCode-Feedback#1132]
#### Your LeetCode username

nehalbhagat29

#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

In conditions section of question description section two variables, `a` and `b` are used.
But it's not very clear what these two variables refer to.

```
A k-diff pair is an integer pair (nums[i], nums[j]), where the following are true:

- 0 <= i, j < nums.length
- i != j
- a <= b
- b - a == k

```

#### Expected behavior

Question description should mention what `a` and `b` represent.

#### Screenshots

![image](https://user-images.githubusercontent.com/40790634/94994536-c824b380-05b5-11eb-9d75-e792c74a140c.png)

**Comment by matthewchao** [comment]
To add onto this, it is not clear from to me from the problem statement alone what role `i` and `j` play in the definition: for instance, should `[5,5,7]` with `k=2` return 1 because the pair (5,7) appears only once, or should it return 2 because we can use indices (0,2) or (1,2)?

Coming from a math background I would probably re-word the definition as:

 A **k-diff pair** is an unordered pair `{a,b}`  such that:

1) there exists distinct indices `i, j` such that `nums[i]=a` and `nums[j]=b`, and
2) `|a-b| = k`

**Comment by lc-kay** [comment]
Hi @nebhagat @matthewchao 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
Hi @nebhagat 
Thank you for your time. We've used your feedback to update the problem. We appreciate your support!

**Comment by nebhagat** [comment]
Hi @lc-kay 

Will I be receiving LeetCoins for reporting this issue?

Thanks!

**Comment by lc-kay** [comment]
Hi @nebhagat, Our team thought this problem was very cleared already and only made minor changes, therefore, no points will be rewarded. Thank you for your time!
