### ISSUE TITLE
2550. Count Collisions of Monkeys on a Polygon - incorrect question, the legitimate reason to unrate the weekly contest 330

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#11357]
#### Your LeetCode username
przemysaw2

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The [URL](https://leetcode.com/problems/count-collisions-of-monkeys-on-a-polygon/) to the problem. It explicitly says that: "A collision happens if at least two monkeys reside on the same vertex after the movement.".

Let's consider the example with 4 vertices and the moves: clockwise (CK) and counterclockwise (CCK).

1 2
4 3

If the monkeys make the following moves:
{ 1 CK, 2 CK, 3 CK, 4 CK }
{ 1 CCK, 2 CCK, 3 CCK, 4 CCK }
{ 1 CK, 2 CCK, 3 CK, 4 CCK }
{ 1 CCK, 4 CK, 2 CK, 3 CCK }

We can observe that there is no collision according to the statement. There are 2^4 = 16 possible moves and 12 of them result in the collision. The test in the example is incorrect.

Based on the above, a rejudge is requested. For an even number of monkeys: all the 2^n-4 solutions should get "Accepted" and all 2^n-2 solutions should get "Wrong Answer". However, based on the contest rule:
"Incorrect test cases
Incorrect test cases that cause some correct submissions to be judged as “Wrong Answer” and incorrect submissions to be judged as “Accepted”.

The contest will be marked as unrated if more than 10% of the submissions’ result change after the rejudge of the incorrect test cases."

I am pretty sure, that much more than 10% of the submissions will be affected after changing the test cases. Hence, the contest should be unrated.

**Comment by w43322** [comment]
> Example 1:
> 
> Input: n = 3
> Output: 6
> Explanation: There are 8 total possible movements.
> Two ways such that they collide at some point are:
> - Monkey 1 moves in a clockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 2 collide.
> - Monkey 1 moves in an anticlockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 3 collide.
> It can be shown 6 total movements result in a collision.

The wording of the problem description is kinda iffy, but if you take a close look at `Example 1` it tells you that a collision while moving (when two monkeys run into each other) is what actually counts. Because when there're 3 vertices, and monkeys move {1 CK, 2 CCK, 3 CK}, apparently monkeys 2 and 3 end up on the same vertex. However it says monkeys 1 and 2 collide, which is in line with all test cases.

**Comment by w43322** [comment]
> A collision happens if at least two monkeys reside on the same vertex after the movement.

I guess it's not *technically* wrong, but rather incomplete. It didn't say `if and only if`, just `if`, which leaves out the occasions where monkeys run into each other while moving. But it's somewhat clarified in the examples that's given.

**Comment by przemek3d88** [comment]
Ok, thanks for the response.

**Comment by przemek3d88** [comment]
Reopening, let the leetcode stuff close it. There are still complaints from the community, that this contest should be unrated.

**Comment by przemek3d88** [comment]
And actually, I can also agree with their argument. If you did not precisely specify the condition, when the collision happens, there could be multiple factors taken into account. The only sure thing is that if 2 monkeys reside at the same vertex, there is a collision. You may argue, that there might be also a collision if the monkeys numbered 1,2,3,4 cross an edge with each other. But maybe if monkeys 5,6,7,8 do that, there is no collision, etc.

**Comment by grawlixes** [comment]
> The wording of the problem description is kinda iffy, but if you take a close look at Example 1 it tells you that a collision while moving (when two monkeys run into each other) is what actually counts. Because when there're 3 vertices, and monkeys move {1 CK, 2 CCK, 3 CK}, apparently monkeys 2 and 3 end up on the same vertex. However it says monkeys 1 and 2 collide, which is in line with all test cases.

It's not "kinda iffy" it's straight up misleading. They state very clearly that they're talking about monkeys landing on the same vertices, but the examples contradict that. There's no ambiguity, the problem expects a wrong answer and the contest should be unrated.

**Comment by Simon-Sandrew** [comment]
I don't understand. Is this contest going to be marked as unrated? The problem very clearly states the definition

**A collision happens if at least two monkeys reside on the same vertex after the movement.**

Even if the examples hint at what the solution is to the problem, you cannot expect one to ignore a literal definition in the problem statement and instead make assumptions about what the contest maker meant to say. Every person who got points for this problem by the problem statements parameters is incorrect. To not mark this problem wrong and this contest unrated is to imply that one should focus more on the test cases of a problem than the statement. This completely contradicts the purpose of Leetcode - if you are in a job interview and you provide a solution that fits the problem statement but not specific test cases that are given, an interviewer would consider your argument and if it is correct change their answer, or at the VERY LEAST discard the question, and certainly not penalize someone who got the question right.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by Simon-Sandrew** [comment]
> Hi there,
> 
> Thank you for reaching out to us.
> 
>  We've relayed this issue to our team to investigate. 
> 
> We will reach back to you after we have the results.
> 
> Thank you for your support.

Sounds good. Thank you for the speedy response!

**Comment by Aritra8438** [comment]
Hi everyone, the wording of question 2 is indeed incorrect to some extent (rather incomplete). 
But let us take the example 1 of the question:
```
Input: n = 3
Output: 6
Explanation: There are 8 total possible movements.
Two ways such that they collide at some point are:
- Monkey 1 moves in a clockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 2 collide.
- Monkey 1 moves in an anticlockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 3 collide.
It can be shown 6 total movements result in a collision.
```
Now,
```
Monkey 1 moves in a clockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 2 collide.
```
Here, it's CLEARLY mentioned that ```Monkeys 1 and 2 collide.``` , even when they (Monkey 1 and Monkey 2) are not residing on the same vertex for any moment.
So another part of the collision is completely depicted through the test cases (which is a part of the question).
Moreover, there are around 5000 competitors who solved this question during the contest (which kind of proves that the definition of ```collision``` is self-explanatory). 

Lastly a request: **I hope there would be an extra contest to compensate for this one, iff this contest gets unrated.**



> > The wording of the problem description is kinda iffy, but if you take a close look at Example 1 it tells you that a collision while moving (when two monkeys run into each other) is what actually counts. Because when there're 3 vertices, and monkeys move {1 CK, 2 CCK, 3 CK}, apparently monkeys 2 and 3 end up on the same vertex. However it says monkeys 1 and 2 collide, which is in line with all test cases.
> 
> ?? Nothing you're saying provides any evidence that the problem statement is not wrong. It's not "kinda iffy", it's straight up misleading. They state very clearly that they're talking about monkeys landing on the same vertices, but the examples contradict that. There's no ambiguity, the problem expects a wrong answer and the contest should be unrated. Not really sure what you're getting at here.

**Comment by Simon-Sandrew** [comment]
> Here, it's CLEARLY mentioned that `Monkeys 1 and 2 collide.` , even when they (Monkey 1 and Monkey 2) are not residing on the same vertex for any moment. So another part of the collision is completely depicted through the test cases (which is a part of the question). Moreover, there are around 5000 competitors who solved this question during the contest (which kind of proves that the definition of `collision` is self-explanatory).

I completely disagree. When n = 3, the swapping does not apply since it is an odd number. Additionally, while I agree that monkeys 1 and 2 do not collide on the same vertex as stated in the test case, you cannot completely contradict the definition of a collision in a test case and expect people to simply side with a test case over the definition. The definition of collision is quite literally not self-explanatory, in fact, it is the exact opposite, as it completely contradicts what is said in the problem statement. Additionally, just because 5000 competitors solved the question says nothing as to their understanding of the question: I myself when solving the question came up with a 2^n -2 solution with the correct, defined definition of collision and it was only until I messed up the modulo and failed a test case that I began to think more critically about the question, eventually noticing the difference. It shouldn't even matter if a test case describes the problem correctly, the fact that there exists an inconsistency like this is reason alone for this contest to be unrated.

> Lastly a request: I hope there would be an extra contest to compensate for this one, iff this contest gets unrated.

Agreed. This would be nice.

**Comment by Aritra8438** [comment]
> in fact, it is the exact opposite, as it completely contradicts what is said in the problem statement.

Is it true? It is stated that ``` A collision happens if at least two monkeys reside on the same vertex after the movement.```, but that doesn't mean that there aren't any other cases which might lead to a ```collision```. So, the question is wrong will be an overstatement, rather it's dubious or incomplete.


> The definition of collision is quite literally not self-explanatory

I meant normally a collision will happen when they cross each other, but true, it isn't a valid argument to justify the question statement.

**Comment by Simon-Sandrew** [comment]
> Is it true? It is stated that ` A collision happens if at least two monkeys reside on the same vertex after the movement.`, but that doesn't mean that there aren't any other cases which might lead to a `collision`. So, the question is wrong will be an overstatement, rather it's dubious or incomplete.

Now that I think about it more, especially when you put it this way,  the definition being incomplete is a way better way to describe it, but I would still say that that is a very large thing to leave out and is still confusing especially to people who did 2^n-2 % modulo and failed the test case when n = 55 due to overflow, not realizing they were failing due to overflow.
 
> I meant normally a collision will happen when they cross each other, but true, it isn't a valid argument to justify the question statement.

Yea I agree with this, their using the word "collision" is definitely more of an indicator of the movement, not the final answer. That being said, the way I visualized it was if they were going clockwise, it would be outside the edges of the polygon, and if they were going counterclockwise, it would be on the inside of the polygon, which doesn't result in any collisions if you picture it that way. I think the use of clockwise and counter-clockwise particularly lends itself well to that way of visualization as well, but could just be me.  Perhaps a better way to say this would be something like "Each monkey rotates inside of the polygon. If a monkey collides in air..." etc.

**Comment by Aritra8438** [comment]
> If a monkey collides in air..."

That seems perfect. 

> I would still say that that is a very large thing to leave out and is still confusing especially to people who did 2^n-2 % modulo and failed the test case when n = 55 due to overflow, not realizing they were failing due to overflow.

I completely agree with this. some of my friends had the same mistake as they forgot to return 
```cpp
((and % mod) + mod) % mod
```
But considering **leetcode contests are so sparse**, it would be better not to declare it unrated.

**Comment by Simon-Sandrew** [comment]
> But considering leetcode contests are so sparse, it would be better not to declare it unrated.
Maybe for you haha - I 1/4 which is going to tank my rating, unfortunately.

**Comment by Aritra8438** [comment]
> > But considering leetcode contests are so sparse, it would be better not to declare it unrated.
> 
> Maybe for you haha - I 1/4 which is going to tank my rating, unfortunately.

Very sorry to hear that. It's completely my view and interest that ```it would be better not to declare it unrated.```, but considering all the responses leetcode got, I hope they take the steps accordingly.

**Comment by bogoconic1** [comment]
The intended solution is incorrect, from the problem statement itself. Not everyone is going to "guess" the solution from the test cases. The problem statement should not be ignored, the example test cases and the jury's solution contradict it.

The same thing happened in Codeforces (wrong intended solution) in the same week lol https://codeforces.com/blog/entry/111737 and the contest was unrated.

That issue is bad enough to declare a contest unrated and leetcode should do it.

**Comment by grawlixes** [comment]
It's kind of unbelievable that you two managed to make the situation appear so complicated when it's really so straightforward.

> It is stated that A collision happens if at least two monkeys reside on the same vertex after the movement., but that doesn't mean that there aren't any other cases which might lead to a collision. So, the question is wrong will be an overstatement, rather it's dubious or incomplete.

This is an incomprehensible argument. If a problem statement doesn't completely explain the problem, then **it is wrong**!! Are you so much of a masochistic competitive programmer that you think a problem statement which doesn't give all information deserves to be rated? That is absolutely nuts lol

>Moreover, there are around 5000 competitors who solved this question during the contest (which kind of proves that the definition of collision is self-explanatory).

No it doesn't, because although there were around 5500 accepted submissions, **there were over 23,000 incorrect submissions**. You don't think that any of those were due to the problem statement which failed to describe the actual problem?

I feel like I have monkeys jumping around in my brain after trying to rationalize this. It's fine if you did well on the contest and you don't want it to be unrated, but c'mon man, your position in this discussion is really not a winning one.

**Comment by Aritra8438** [comment]
> No it doesn't, because although there were around 5500 accepted submissions, **there were over 23,000 incorrect submissions**.

Seriously? I have watched many live streams of famous competitive programmers and most of them just try their codes on the example testcases before submission. ***You are saying there are 23000 submissions just because most of the competitors submitted without trying the example testcases?***  So sorry to hear that. For your information, most of the solutions were rejected because of ```signed integer overflow``` or returning a negative answer.


> If a problem statement doesn't completely explain the problem, then **it is wrong**!!

But, the explanation of the examples completely explains the problem. That's why they are provided to understand the question better. And they are also part of the question. 


> when it's really so straightforward.

No, it's not that straightforward, there is a huge difference between ```iff``` and ```if```. If you are familiar with codeforces, you should be knowing this.

Lastly, where does this come from?? I mean, it's super irrelevant and nowhere near explaining myself, haha.

> masochistic competitive programmer

**Comment by qtwcqtwc** [comment]
The Example is part of the desciprtion, the example is clearly indicating the there is a collision if two monkey cross each other.

If you take a look to "Question 4" in Biweekly contest 64 https://leetcode.com/contest/biweekly-contest-64/, you have no idea what does the problem mean without taking a look to the example, so **the example is part of the problem description**. And nobody says that the biweekly contest 64 should be unrated.

**If you didn't get a good rating in this contest, I am sorry about that, but please don't make it as an excuse to ask Leetcode team to unrate the contest.**

**Comment by NP-Prob** [comment]
> Hi there,
> 
> Thank you for reaching out to us.
> 
>  We've relayed this issue to our team to investigate. 
> 
> We will reach back to you after we have the results.
> 
> Thank you for your support.

I think this contest should be rated.
Of course, there are some inaccurate expressions in Q2, but both 2 examples clearly indicate the meaning of the question.
Example 1 points it out that "Monkey 1 moves in a clockwise direction; monkey 2 moves in an anticlockwise direction; monkey 3 moves in a clockwise direction. Monkeys 1 and 2 collide." which clearly means that a collision happens between monkeys 1 and 2 during jumping across each other, rather than monkey 2 and 3 who are on the same point after the movement.
Example 2 clearly counts the "jumping across each other" event as a collision happens, or you will get 12 rather than 14 as a result.
Example cases are meant to express the meaning of a question clearly, in this case, apparently both of the examples are very clear. All of the other test cases are also consistent with the meaning expressed by the examples.
It is very common that the meaning of the question is unclear, so we rely on examples to clarify the meaning of the question. The contestants should also take the meaning expressed by examples as the standard. This is true for all questions on all platforms. Otherwise, why are there examples for each question?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
