### ISSUE TITLE
Missing Test Case - 292. Nim Game

### ISSUE THREAD

**Issue by Shiv-Expert2503** [LeetCode-Feedback/LeetCode-Feedback#11402]
#### Your LeetCode username

Shivansh Singh

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug

I think there is a problem in this question. In one of the test case the output is incorrect. I have an issue regarding n=8 and above.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool canWinNim(int n) {
        if(n%4==0)            //if n is divisible by 4 then the output Should be false
            return false;

        return true;        //else in every case the output must be true
        
    }
};
```

#### Language used for code

C++

#### Expected behavior

For n=8  the output must be TRUE instead of FASLE. As according to the question if the last stone is picked by me then the output will be true and I will always go first to pick the stone and I and my friend can either pick 1 or 2 or 3 stones at a time and for n=8 lets assume a case when I first took 3 stones and then my friend also picks 3 stones then if all the left stones that is 2 stones were picked by me then the actual output under the given conditions must be TRUE but the answer it is showing is FALSE. Let's take one more case for n=8 suppose I took 2 stones and then my friend took 3 and then I took only 1 stone and then my friend took also 1 stone and then I took the left stone . In this case also the output must be TRUE. So please correct it.

#### Additional context

I think same also applies for n=12,n-16,n=20 So the actual output for these values of n must be TRUE instead of FALSE.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by stormsunshine** [comment]
First, if n = 4, then the correct answer is false.

Next, consider the case where n = 8.

- If Player 1 takes 1 stone, then Player 2 takes 3 stones.
- If Player 1 takes 2 stones, then Player 2 takes 2 stones.
- If Player 1 takes 3 stones, then Player 2 takes 1 stone.

For any case, Player 2 can always make the remaining number of stones be 4.

Since the result for n = 4 is false, Player 1 will lose with the remaining number of stones being 4.

So the correct answer for n = 8 is false.

You may use a dynamic programming approach for small values of n.
