### ISSUE TITLE
Anonymous Post Option Not Available For General Discussion and Support & Feedback

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11552]
The option to make an Anonymous Post is not available for the following:
https://leetcode.com/discuss/general-discussion
https://leetcode.com/discuss/feedback

**Comment by ThomasShaw1** [comment]
I have Windows 11 with Chrome Browser.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
