### ISSUE TITLE
177. Nth Highest Salary

### ISSUE THREAD

**Issue by AxelB1011** [LeetCode-Feedback/LeetCode-Feedback#11565]
#### Category of the bug
- [1 ] Question
- [ ] Solution
- [1 ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Runtime error, okay. But what is the error and why am I not able to find it?

#### Code you used for Submit/Run operation

```
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
SET N = N-1; #offset n-1 elems so we can get nth elem
  RETURN (
      # Write your MySQL query statement below.
      SELECT distinct salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET N
  );
```

#### Language used for code

mySQL

#### Expected behavior

Should have ran fine.

#### Screenshots

Added
<img width="1357" alt="Screenshot 2023-02-06 at 2 03 46 PM" src="https://user-images.githubusercontent.com/64097524/217062085-d7781406-92a5-40b9-978a-f08cc096a9f1.png">

#### Additional context

The new SQL course is horrendous(leap of faith jumps to topics never explained), the SQL questions are also lacking in official solutions but I did not expect that the questions would not even work with sound logic.

EDIT - I am able to submit it and it accepts my submission so I am assuming something wrt the runtime compiler broke, idk.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 

For more details, please check: https://leetcode.com/submissions/detail/893588946/

It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), and O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors also affect the runtime of the same program, introducing some level of discrepancy.

I hope this helps. Should you have any other questions, please let us know.
