### ISSUE TITLE
User's Reputation No Longer Visible in the Comment Section For the New Discussion UI

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#11571]
You can no longer see a user's reputation in the comment section for the new discussion UI: https://leetcode.com/problems/fruit-into-baskets/solutions/3153492/easy-explanation-with-animation-and-video-java-c-python/comments/1791411

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
