### ISSUE TITLE
Wrong behavior of LeetCode Contest

### ISSUE THREAD

**Issue by Rad0miR** [LeetCode-Feedback/LeetCode-Feedback#11621]
#### Your LeetCode username

Rad0miR

#### Category of the bug
- [X] Wrong behavior

#### Description of the bug

There are some strange bugs with [Weekly Contest 317](https://leetcode.com/contest/weekly-contest-317). On my contests page it says I have got 193th place. On Ranking of [Weekly Contest 317](https://leetcode.com/contest/weekly-contest-317) it is saying for me that I’ve got 98th place. But actually my place is 192. 

This is all very strange. 
But the main thing that bothers me is that I’ve made it to the top 200, but I didn't receive +50 LeetCoins.

#### Screenshots

![MyContests](https://user-images.githubusercontent.com/72408888/217770398-316e4a36-d175-42b3-9bf7-e1022538a5e6.png)
![ranking](https://user-images.githubusercontent.com/72408888/217770435-0e0404fb-c35c-4021-a234-467f1209f3e2.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
