### ISSUE TITLE
Missing Test Case - 2562. Find the Array Concatenation Value

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#11682]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets Runtime Error on the following testcase:
[7018]

#### Code you used for Submit/Run operation

```
class Solution:
    def findTheArrayConcVal(self, nums: List[int]) -> int:
        res = 0
        for i in range(len(nums) // 2):
            res += nums[-(1 + i)]
            res += nums[i] * (10 ** len(str(nums[-(1 + i)])))
        if len(nums) % 2 == 1:
            res += nums[i+1]
        return res
```

#### Language used for code

Python3

#### Expected behavior

The code gets Runtime Error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code AC submission link since the code received Runtime Error after submit: https://leetcode.com/submissions/detail/897371819/

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by hqztrue** [comment]
Seems that new testcases were added. I'll close this issue.
