### ISSUE TITLE
Binary Search Template Analysis page: Color of "length - 1" should be black in 'right' initialization.

### ISSUE THREAD

**Issue by cornelius1** [LeetCode-Feedback/LeetCode-Feedback#11754]
Continuing from #11658 (since I'm not able to reopen that issue):
Since the initialization of `right` in Template#2 on [the Binary Search Template Analysis page](https://leetcode.com/explore/learn/card/binary-search/136/template-analysis/935/) is no longer different from those in Template#1 and Template#3 on that page, and the red color is supposed to show differences there, you should probably also change the color of "length - 1" to black in that initialization line of all templates, i.e. in the current version of [this image](https://assets.leetcode.com/uploads/2023/02/13/template_diagram.png).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem again. 

We reject this feedback right now since it needs a very high effort, but we will keep this valuable feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
