### ISSUE TITLE
Reverse Linked List 206-Time Limit Exceeded

### ISSUE THREAD

**Issue by CursedSpiderBoi** [LeetCode-Feedback/LeetCode-Feedback#11876]
LeetCode Username: BlueSatanBabe

#### Category of the bug
- [ ] Question
- Solution I Used
```
ListNode* reverseList(ListNode* head) {
        ListNode* cur = head,* pre = NULL,* next = cur->next;
        while (cur) {
            cur->next = pre;
            pre = cur;
            cur = next;
        }
        return pre;
    }
```
- Language
  C++
- Issue
     The Code is Working properly but when run in leetcode shows "Time Limit Exceeded"

![Bug](https://user-images.githubusercontent.com/104762132/220010324-1e792912-167a-49ee-826f-2bc397cc4564.PNG)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
