### ISSUE TITLE
Missing Test Case 43. Concatenated Words

### ISSUE THREAD

**Issue by warcayac** [LeetCode-Feedback/LeetCode-Feedback#11889]
#### Your LeetCode username

warcayac

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I'm getting a TLE message after apparently passing all of 43 test cases.

#### Code you used for Submit/Run operation

```Dart
class Solution {
  var minLength = 0;
  var noSinglesLowerIndex = 0;
  var wordList = <String>[];
  var results = <String>[];
  /* ---------------------------------------------------------------------------- */
  List<String> findAllConcatenatedWordsInADict(List<String> words) {
    if (words.length < 2) return [];
    
    makeSorting(words);
    final length = words.length;
    minLength = words.first.length;
    noSinglesLowerIndex = words.indexWhere((w) => w.length > minLength);
    wordList = words;

    results.clear();
    for (var i = noSinglesLowerIndex; i < length; i++) {
      if (isCompoundStr(wordList[i])) results.add(wordList[i]);
    }

    return results;
  }
  /* ---------------------------------------------------------------------------- */
  bool isCompoundStr(String base, [String? subPart]) {
    if (subPart != null) {
      if (subPart.isEmpty || results.contains(subPart)) return true;
      if (subPart.length < minLength) return false;
      if (subPart.length == minLength) {
        return wordList.getRange(0, noSinglesLowerIndex).contains(subPart);
      }
    }

    var target = subPart ?? base;
    var length = target.length;
    var candidates = <String>[];
    for (var word in wordList) {
      if (word.length > length || (base == target && word == target)) break;
      if (target.startsWith(word)) candidates.add(word);
    }
    if (candidates.isEmpty) return false;
    var start = candidates.first;
    candidates = candidates
      .map((e) => RegExp('^(?:$start)*($start(?!$start).*)').firstMatch(e)![1]!)
      .toSet()
      .toList()
    ;

    if (candidates.isEmpty) return false;

    return candidates.any((e) => isCompoundStr(base, target.substring(e.length)));
  }
  /* ---------------------------------------------------------------------------- */
  void makeSorting(List<String> words) {
    words.sort((a, b) {
      var result = a.length.compareTo(b.length);
      if (result == 0) result = a.compareTo(b);
      return result;
    });
  }
}
```

#### Language used for code

Dart

#### Expected behavior

An answer-accepted message or the array used for test case 43 which raised TLE message

#### Screenshots

![image](https://user-images.githubusercontent.com/7342885/220214639-2fbc4876-39d2-4dfd-a90d-c167c0a269da.png)

#### Additional context

It would be quite useful if for every problem posted you could indicate the maximum expected time limit.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
