### ISSUE TITLE
Bug in Test Cases, Problem 3 (#1616), Weekly Contest 210.

### ISSUE THREAD

**Issue by MrPositron** [LeetCode-Feedback/LeetCode-Feedback#1191]
#### Your LeetCode username

MrPositron

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
During contest I solved probem 3 (#1616). But now, previously accepted solution is not accepted anymore. Furthermore, it says that my code should return True when in fact my code returns True.

#### Code you used for Submit/Run operation

```
class Solution:
    def checkPalindromeFormation(self, a: str, b: str) -> bool:
        if len(a) == 1:
            return True
        
        ab = a + b
        if len(ab) == 1:
            return True
        i, j = 0, len(ab) -1
        if ab[i] == ab[j]:
            return True
        
        ba = b + a
        i, j = 0, len(ba) - 1 
        if ba[i] == ba[j]:
            return True
        
        return False
```

#### Language used for code
Python3

#### Expected behavior
Either it should say that my expected result is False, and my result is True or otherwise if my code did not pass. 

#### Screenshots
![image](https://user-images.githubusercontent.com/42044624/95678680-9d56e280-0be7-11eb-8277-0cc721e68978.png)

**Comment by MrPositron** [comment]
And by the way. Why are you adding test cases during contest?

![image](https://user-images.githubusercontent.com/42044624/95680187-1dce1100-0bf1-11eb-8deb-2a4fb5b49182.png)

![image](https://user-images.githubusercontent.com/42044624/95680179-11e24f00-0bf1-11eb-8882-e044f9406d71.png)

**Comment by lc-pam** [comment]
Hi @MrPositron ,
Thanks for reaching out to us. I've relayed the issue to the team to investigate.

**Comment by lc-pam** [comment]
Hi @MrPositron 
Thank you for your time. 

After the investigation, we found that there is an issue when displaying the failed test case for submission made during the contest. Your submission failed for one of the test cases but not the one we displayed. I'm sorry that we are not able to fix the already caused error but the team will deploy a fix to prevents it from happening again. However, it didn't impact the contest. The reason is that during the contest it was showing the correct failed testcase. The issue occurred after the contest got over, due to some bug, your submissions started to show the incorrect testcase.

I'm sorry for the confusion it has caused and appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
