### ISSUE TITLE
LeetCode Contributions Status Hasn't Moved Since January 2023

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#12008]
Hello, LeetCode Contributions since January 2023 is still in 'pending' state. Usually contributions get reviewed less than 2 weeks. Do we know when will they get reviewed?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
