### ISSUE TITLE
No Save as PDF Button on the LICC Cheatsheets Page

### ISSUE THREAD

**Issue by omaryaya** [LeetCode-Feedback/LeetCode-Feedback#12125]
#### Your LeetCode username

omaryaya

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

On the [LICC Cheatsheets card](https://leetcode.com/explore/interview/card/cheatsheets/720/resources/), I'm unable to save the resources as PDF. The native browser dialog shows only a clipped portion of the first two (screenshot below).

#### Code you used for Submit/Run operation

```
N/A
```

#### Language used for code

N/A

#### Expected behavior

Being able to download the cheatsheet content as PDF natively OR via a button on LC.

#### Screenshots

![image](https://user-images.githubusercontent.com/47383263/222885297-ae8ba116-d5a8-473a-ba8a-65b157607479.png)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
