### ISSUE TITLE
 My solution does not appear!

### ISSUE THREAD

**Issue by ab-elhaddad** [LeetCode-Feedback/LeetCode-Feedback#12291]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I have added a solution but it does not appear to others. When the solution link is opened it gives "That topic does not exist.". I am the only one who can see it through my account.

Solution Link: https://leetcode.com/problems/linked-list-random-node/solutions/3279651/c-typescript-javascript-very-easy-soultion-no-extra-space-no-recursion/

#### Screenshots
![Leetcode solution bug](https://user-images.githubusercontent.com/113056556/224366313-467af91c-d675-4b00-b1eb-22d27b74d015.JPG)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
