### ISSUE TITLE
Missing Test Case - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by YakovL** [LeetCode-Feedback/LeetCode-Feedback#12357]
#### Your LeetCode username
[IakovL](https://leetcode.com/IakovL/)

#### Description of the bug
While my solution passed, it currently has a flow as it is slower than O(log (m+n)) in a specific case. Hense I believe that case is missing.

Here's the case where it will be O(m):

    nums1 = [1,2,3, ..., 1000]
    nums2 = [333,666]

The main feature of this case is: the second array consists of 2 numbers that are far from both ends of the first array (and also far from the median, which is not that important).

#### Code you used for Submit/Run operation
Note the `TODO` (which actually has to cover that case).

```
function findMedianSortedArrays(nums1: number[], nums2: number[]): number {
    const findMedian = (nums: number[]): number | null => {
        if(nums.length === 0) return null
        if(nums.length % 2 === 1) return nums[(nums.length - 1) / 2]
        return (nums[nums.length / 2 - 1] + nums[nums.length / 2]) / 2
    }

    const median1 = findMedian(nums1)
    const median2 = findMedian(nums2)
    if(nums1.length === 0) return median2
    if(nums2.length === 0) return median1
    if(median1 === median2) return median2

    // now we aim to cut off some numbers and get 2 new arrays
    // that have the same pair median
    const [higherNums, lesserNums] = median1 > median2 ?
        [nums1, nums2] : [nums2, nums1]

    const lesserNumsTailLength = lesserNums.length % 2 === 1 ?
        (lesserNums.length - 1) / 2 : (lesserNums.length - 2) / 2
    const higherNumsTailLength = higherNums.length % 2 === 1 ?
        (higherNums.length - 1) / 2 : (higherNums.length - 2) / 2
    const minimalTailLength = Math.min(
        lesserNumsTailLength, higherNumsTailLength)
    
    if(minimalTailLength > 0) {
        const lesserNumsSliced = lesserNums.slice(minimalTailLength)
        const higherNumsSliced = higherNums.slice(0, -minimalTailLength)
        return findMedianSortedArrays(lesserNumsSliced, higherNumsSliced)
    }

    // minimalTailLength === 0
    if(lesserNumsTailLength === 0 && higherNumsTailLength === 0) {
        const smallArray = lesserNums.concat(higherNums).sort((a,b) => a - b)
        return findMedian(smallArray)
    }

    const longNums = lesserNumsTailLength === 0 ?
        higherNums : lesserNums
    const shortNums = lesserNumsTailLength === 0 ?
        lesserNums : higherNums

    if(shortNums[0] > longNums[longNums.length - 1])
        return findMedian(longNums.concat(shortNums))
    if(shortNums.length === 2 && shortNums[1] < longNums[0] ||
        shortNums.length === 1 && shortNums[0] < longNums[0]
    )
        return findMedian(shortNums.concat(longNums))
    if(shortNums.length === 2) {
        if(shortNums[1] > longNums[longNums.length - 1]) {
            longNums.push(shortNums.pop())
        }
        if(shortNums[0] < longNums[0]) {
            longNums.unshift(shortNums.shift())
        }
    }
    if(shortNums.length === 0) return findMedian(longNums)

    // both are "inside" longNums
    // TODO: try to make logarithmic by dichotomy
    longNums.pop()
    longNums.shift()
    return findMedianSortedArrays(longNums, shortNums)
};
```

#### Language used for code
TypeScript

#### Expected behavior
The code above should be rejected as it works with a linear speed in this case.

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

A quote from the statement:
> The overall run time complexity SHOULD be O(log (m+n)).

A quote from [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119):

> 3. **SHOULD**   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

It is theoretically possible to enforce `O(log (n + m))` time complexity in this particular case. However, it is not worth it in practice. In particular, it is difficult for the testing system to avoid the `O(n + m)` cost of generating the inputs.

Thank you for your support.

**Comment by YakovL** [comment]
Thanks for clarifying the wording! While it's clear that this is not an important issue due to the "should" bit, I don't think I've understood the "it is difficult for the testing system to avoid the `O(n + m)` cost of generating the inputs" bit. I mean, generating the input will probably have the `O(n + m)` cost, but what has this to do with the measurement of the solution cost? If js/ts is run in a container and uses standard IO, what's the problem with sending a special message with a timestamp to stdout on "input generation finished" and on "code run finished" events and substracting the former from the latter, getting the execution time?

This is a question out of curiosity, so feel free not to answer and to close the issue, if you don't have time for this.

**Comment by nskybytskyi** [comment]
This is a good question, so I will elaborate.

We have to check two things about each submitted solution:
- is it correct?
- is it fast?

In my personal projects, I use (unit) testing for the correctness part and benchmarking for the performance part. The primary difference is that, in testing, a test case only runs _once_, whereas, in benchmarking, it runs _multiple_--often thousands or millions--times. This performance overhead is necessary to obtain statistical confidence. Such overhead is easy to justify if you rarely run your benchmarks. For example, executing them on every push is cheap since the number of pushes per day is limited.

However, as an online judge, LeetCode has to process hundreds of thousands of submissions daily. Therefore, benchmarking every submission comes at a very high price. Other popular platforms such as codeforces, atcoder, codechef, or topcoder don't perform proper benchmarking. In particular, codeforces executes a submission at most three times and only does so in case of borderline AC/TLE performance.

Therefore, another approach to performance evaluation is preferred. In this approach, test cases are designed so that it is easy to differentiate between _fast_ and _slow_ submissions based on a limited number of tests. It makes sense when fast means O(n) and slow means O(n^2). Specifically, even one test case with n = 10^5 results in drastically different execution times. On a hypothetical machine that performs 10^9 operations per second, the former will take 10 milliseconds, whereas the latter will take 10 seconds.

However, if fast means O(log n), then even for n = 10^5, execution times will have an order of microseconds. In such cases, the running time is severely impacted by low-level factors. Hence it becomes burdensome to confidently evaluate performance based on a singular data point. 

In general, this approach works well if the running time of a slow solution is in the order of seconds. However, if input generation is as slow as a slow solution, then evaluating fast solutions is slow too. Sadly, this is another performance overhead that is easy to justify in small projects but becomes unbearable as you scale up.

**Comment by YakovL** [comment]
Right, thanks for the details! Did I get you right in that, basically, LeetCode doesn't measure the execution time of single tests at all, and against that background, it's not possible to distinguish whether all tests were `O(log(m + n))` or some were `O(m + n)`?
