### ISSUE TITLE
1501. Countries You Can Safely Invest In - SQLII

### ISSUE THREAD

**Issue by Parth261993** [LeetCode-Feedback/LeetCode-Feedback#12458]
#### Your LeetCode username
Dragon26

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug
AI am trying to run a solution but it throws this message -- Phone number of the person with id = 3 doesn't exist in the Country table

#### Code you used for Submit/Run operation

```SELECT
 co.name AS country
FROM
 person p
 JOIN
     country co
     ON SUBSTRING(phone_number,1,3) = country_code
 JOIN
     calls c
     ON p.id IN (c.caller_id, c.callee_id)
GROUP BY
 co.name
HAVING
 AVG(duration) > (SELECT AVG(duration) FROM calls)
```

#### Language used for code
SQL

#### Expected behavior
Even if my code is wrong, it should show me the wrong answer, but it just throws test case error.

#### Screenshots
If applicable, add screenshots to explain your issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by guyueli** [comment]
Running into the same problem. Leet code you are missing test cases, this is not some runtime question, OPEN YOUR EYES.

**Comment by Parth261993** [comment]
Hi,

I tried submitting a different code by looking at the answers of other
people, but nothing seems to work, I think there is a problem with the test
cases. I have two days to complete the SQl II to get my batch. I am keen to
complete the SQL II and more to SQL III. If you don't resolve the issue
then I cannot get my batch. Please do the needful.

Best,
Parth

**Comment by vivian1970** [comment]
I'm getting the same error. Please fix this soon. This is the issue with the test cases
