### ISSUE TITLE
Missing Test Case - 2564. Substring XOR Queries

### ISSUE THREAD

**Issue by arg2k** [LeetCode-Feedback/LeetCode-Feedback#12452]
#### Your LeetCode username

argha_kole 

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Even though a solution for the problem <a href="https://leetcode.com/problems/substring-xor-queries/">2564. Substring XOR Queries</a> passed all the test cases and was accepted,
it gets TLE for the following testcase : [test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11010707/test_case.txt)

#### Code you used for Submit/Run operation

```
// 2564. Substring XOR Queries
class Solution {
    public int[][] substringXorQueries(String s, int[][] q) {
        // vector<vector<int>> v(q.size(),{-1,-1});
        int[][] v = new int[q.length][2];
        Map<Integer,Integer> l=new HashMap<>();
        Map<Integer,Integer> r=new HashMap<>();
        int n=s.length();
        for(int i=0;i<n;i++)
        {
            int j=i;
            int val=0;
            while(j<n && val<=1e9+7)
            {
                val<<=1;
                if(s.charAt(j)=='1')
                {
                    ++val;
                }
                if(l.containsKey(val)==false)
                {
                    l.put(val,i);
                    r.put(val,j);
                }
                else if(r.get(val)-l.get(val)>j-i)
                {
                    l.put(val,i);
                    r.put(val,j);
                }
                ++j;
            }
        }
        for(int i=0;i<q.length;i++)
        {
            int req=q[i][0]^q[i][1];
            if(l.containsKey(req)==true)
            {
                v[i][0]=l.get(req);
                v[i][1]=r.get(req);
            }
            else
            {
                v[i][0]=-1;
                v[i][1]=-1;
            }
        }
        return v;
    }
}
```

#### Language used for code

 Java

#### Expected behavior

The code gets TLE for the following testcase : [test_case.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11010707/test_case.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the code received TLE right now: https://leetcode.com/submissions/detail/920352849/

The same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
