### ISSUE TITLE
Explore - Quick Union -Disjoint Set

### ISSUE THREAD

**Issue by hjwanga** [LeetCode-Feedback/LeetCode-Feedback#12531]
#### Your LeetCode username

hanjyun

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [V] Explore

#### Description of the bug

In this explore, there are two videos:
1. Explanation of Quick Union
2. Why is Quick Union More Efficient than Quick Find

The code snippet about the Quick Union version in video1 **[Timestamp=4:20]** and video2 **[Timestamp=0:25]** is obviously incoherent and wrong.
incoherent: In "find" function, video1 and video2 are different.
wrong: In "union" function,
```
if(rootX != rootY):
    root[rootY] = x; // rhs should be rootX instead
```

#### Screenshots

**video1**
![video1](https://user-images.githubusercontent.com/40780658/227290832-8cd3bba6-206d-45ed-b8bb-be8d4818aed4.jpg)

**video2**
![video2](https://user-images.githubusercontent.com/40780658/227290851-6e42cc7f-fa1c-4c59-b85a-d7ca345e870a.jpg)

**Comment by hjwanga** [comment]
Same issue on "Path Compression Optimization - Disjoint Set" video
The code snippet in the video is wrong.

if(rootX != rootY):
    root[rootY] = x; // rhs should be rootX instead

**Comment by hjwanga** [comment]
Quick Union-Disjoint Set:
https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3840/

Path Compression Optimization-Disjoint Set:
https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3880/

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The videos and all codes are correct. The discrepancy between the "find" function in video1 and video2 is intentional. The first video's find function does not implement path compression, while the second one does. Path compression is a major optimization to union-find.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
