### ISSUE TITLE
Wrong Expected Result in one Testcase - 551 Student Attendance Record I

### ISSUE THREAD

**Issue by Vikkivi** [LeetCode-Feedback/LeetCode-Feedback#1255]
#### Your LeetCode username

https://leetcode.com/vikkivi/

#### Category of the bug
- [x] Question

#### Description of the bug

The testcase produces the wrong expected result. For example, when
input is "LALL" the output should be false because the student was late three times. But now expected result is true

#### Code you used for Submit/Run operation

```
/**
 * @param {string} s
 * @return {boolean}
 */
var checkRecord = function(s) {
    const sArr = s.split('');
    const absent = sArr.filter(item => item === 'A').length;
    const late = sArr.filter(item => item === 'L').length;
    
    return (absent < 2 && late < 3);
};
```

#### Language used for code

JavaScript

#### Expected behavior

In case when input is "LALL", output should be false

**Comment by lc-kay** [comment]
@Vikkivi Since the problem description states that a student could be rewarded if his attendance record doesn't contain **more than two continuous 'L' (late)**, the correct output for the above test case is true. Although the student was late 3 times, only 2 of them were consecutive. Therefore, the student can still be rewarded.
