### ISSUE TITLE
49. Wrong solution for a certain testcase

### ISSUE THREAD

**Issue by thewallandme** [LeetCode-Feedback/LeetCode-Feedback#12570]
#### Your LeetCode username

thewallandme

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Testcase `strs = ["",""]` was provided.

The problem specifies that all elements of the `strs` list are supposed to be lower case English letters, hence the interpretation of this list is equivalent to `['', '' ]` where there are 2 elements, string type, both empty. However, in the solution to the test case, the expected response is `[["",""]]` suggesting that the string being considered is `'","'`, but `","` is not a lowercase English letter. Even without this type constraint, the interpretation of such a list is unclear.

#### Code you used for Submit/Run operation

```
from collections import defaultdict

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        """
        anagrams have same counts of same letters
        so 1) group by number of letters
        2) count +- for the alphabet counts to check if anagram, find parent 
        """

        def isAnagram(s1, s2):
            cnt = defaultdict(int)
            for i in s1: cnt[i] +=1 
            for j in s2: cnt[j] -=1
            if set(cnt.values()) == set([0]):  return True
            else: return False

        res = defaultdict(list)
        for s in strs:
            l = len(s)
            if l not in res:  res[l].append([s]); continue
            # compare with existing anagram groups. only need to compare with parent, so grp[0]
            newanagram = True
            for grp in res[l]:  
                if s in grp: newanagram = False; break
                if isAnagram(s, grp[0]):  grp.append(s); newanagram = False; break
            # if you don't find it in anywhere, it's an anagram group of its own
            if newanagram:  res[l].append([s])
        
        return sum(res.values(), [])
```

#### Language used for code
Python3

#### Expected behavior

Unclear, but would expect to read `strs = ["",""]` as a list of 2 elements.

#### Screenshots

![image](https://user-images.githubusercontent.com/32356987/227731729-083bc8f1-ed94-41c9-89fa-769a3cf9ae8c.png)
![image](https://user-images.githubusercontent.com/32356987/227731744-7cbef11b-ee0c-4450-999c-6c543a771d83.png)

**Comment by nskybytskyi** [comment]
Hi there,

Thank you for reaching out to us.

The expected response is `[["",""]]` because there are two empty strings which are anagrams. Hence they should be grouped. We get one group `["",""]`, so the list of all groups is `[["",""]]`.

The issue with your solution is that it discards any duplicates, not just empty strings. For example, it also gets a Wrong Answer verdict on `strs = ["a", "a"]`, outputting `[["a"]]` instead of the expected `[["a", "a"]]`. Hopefully, the test case will help you to debug your solution.

Thank you for your support. If you have any other questions, please don't hesitate to let us know.
