### ISSUE TITLE
Regarding inconvinience faced during the weekly contest 338

### ISSUE THREAD

**Issue by ajitesh-git007** [LeetCode-Feedback/LeetCode-Feedback#12593]
#### Your LeetCode username
ajitesh_k_k

I have registered for the weekly contest 338, but the site was crashed for nearly 40 mins, after 40 mins only I could log in and started giving the contest and could solve only one problem due to shortage of time. from out of 90 mins , i get only 50 mins to solve. It is highly unfair because my ratings were be strictly affected due to this. plz do something.
![Screenshot 2023-03-26 082022](https://user-images.githubusercontent.com/79281223/227787481-89b6c3d7-80e8-4886-999c-2ddd806b3ff1.jpg)

![Screenshot 2023-03-26 080834](https://user-images.githubusercontent.com/79281223/227787503-da5fd9b0-af64-49de-905e-1dd69ae4bef3.jpg)

**Comment by LC-Pam** [comment]
Hi there,
 
I'm so sorry this occurred to you and thank you for taking the time to reach out to us!
 
Weekly Contest 338 is unrated for the LCUS users due to the site being down for a significant amount of time during Weekly Contest 338.
 
This contest will not impact your ranking.
 
We sincerely apologize for the inconvenience this may have caused.
 
We are committed to providing the best possible user experience, and we are taking steps to prevent similar incidents from happening in the future.
 
Thank you for your continued support.
 
Please let us know if there is anything else we can do to assist.
 
Warm regards,
 
LC
