### ISSUE TITLE
Leetcode Profile Submission Graph Bug

### ISSUE THREAD

**Issue by AnmolVerma404** [LeetCode-Feedback/LeetCode-Feedback#12778]
#### LeetCode username
anmolverma404

#### Category of the bug
- UI/UX 

#### Description of the bug
In leetcode public profile submissions graph shows incorrect data.
April 1st, 2022 shows 0 submissions, but when we change Current(2023) to 2022 it does have submissions 

![image](https://user-images.githubusercontent.com/77019763/230082690-c98cf6bc-3a5e-46f2-a2e5-df2b08e37536.png)
![image](https://user-images.githubusercontent.com/77019763/230082926-af5203b1-9269-439e-8042-da4ac4386399.png)
![image](https://user-images.githubusercontent.com/77019763/230082947-cc8ffb20-34c0-4d2d-98ec-dd39db328913.png)

### Problems
I have the April batch, but only in UI (Submittion Graph), it's now showing the April batch (As can be seen in the previous screenshot).

#### Expected behavior
April batch and submission should be visible when the range is set to the Current

#### Additional context
The bug might be caused due to range error(Index Out of Bound). 

Hope this issue is clear, if any mistake on my side you can leave a comment....

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
