### ISSUE TITLE
Global Ranking is out of date (several weeks?)

### ISSUE THREAD

**Issue by alantudyk** [LeetCode-Feedback/LeetCode-Feedback#12826]
#### Your LeetCode username
0x81

#### Description of the bug
https://leetcode.com/contest/globalranking/

The numbers (ranking, contests attended) do not match in the table and on the users' profile pages.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
