### ISSUE TITLE
Weekly 340 - Same code. But one is time limit error, and one is accepted

### ISSUE THREAD

**Issue by kyaryunha** [LeetCode-Feedback/LeetCode-Feedback#12844]
#### Your LeetCode username
kyaryunha

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Same code. but one is time limit error, and one is accepted

#### Code you used for Submit/Run operation
Problem is this. https://leetcode.com/contest/weekly-contest-340/problems/prime-in-diagonal/

and my tle code is https://leetcode.com/contest/weekly-contest-340/submissions/detail/930426238/
and my ac code is https://leetcode.com/contest/weekly-contest-340/submissions/detail/930452489/ 

The only difference between the two codes is that the debugging code int cnt = 0 is not deleted from the correct code.
Rather, the ac code should have been slower because of the debugging code.

#### Language used for code
C++

#### Expected behavior
Because the two codes are identical, the scoring results should be identical.

#### Additional context
I spent a lot of time thinking about this on Weekly. 
I spent 30 minutes on Easy Problem for that reason.
So, I didn't have enough time to solve the next problems :(

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
