### ISSUE TITLE
724 & 1991 Find Pivot Index: Wrong return type in Rust

### ISSUE THREAD

**Issue by mks-h** [LeetCode-Feedback/LeetCode-Feedback#12919]
#### Your LeetCode username

mks-h

#### Category of the bug
- [x] Question
- [x] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The problem requires wrong return type for Rust — it asks to return an index of type `i32` while the index is actually a `usize`, and these cannot be converted losslessly. Furthermore, it asks to return `-1` for a faulty case, which is an awful practice and it should be `Option<T>` instead. So, the proper return type would be `Option<usize>`.

#### Code you used for Submit/Run operation

```
impl Solution {
    pub fn pivot_index(nums: Vec<i32>) -> i32 {
        match nums.into_iter().enumerate().next() {
            Some((i, v)) => return i,
            None => return -1
        }
    }
}
```
#### Language used for code

Rust

#### Expected behavior

If it's possible to modify the problem description for a specific language — for Rust it should say "If no such index exists, return `None`". The return type of the solution method must be `Option<usize>` and the test cases should be updated accordingly.
```
impl Solution {
    pub fn pivot_index(nums: Vec<i32>) -> Option<usize> {
        match nums.into_iter().enumerate().next() {
            Some((i, v)) => return Some(i),
            None => return None
        }
    }
}
```

#### Additional context

This blocks me from working on the [LeetCode 75 Study Plan to Ace Interviews](https://leetcode.com/study-plan/leetcode-75/)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by mks-h** [comment]
> The team decided to reject this feedback after the evaluation.

Please provide your reasoning.
