### ISSUE TITLE
Missing test case in 2617. Minimum Number of Visited Cells in a Grid

### ISSUE THREAD

**Issue by prakash7720** [LeetCode-Feedback/LeetCode-Feedback#12937]
#### Your LeetCode username
prakash_26

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
I saw that some solutions in last Weekly Contest (340) problem D got accepted even after rejudging happened. They didn't have the intended complexity. I tested some solutions and they failed on my test case.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int minimumVisitedCells(vector<vector<int>>& grid) {
        
        int m= grid.size();
        int n= grid[0].size();
       vector<vector<int>> vis(m, vector<int> (n,0));
        queue<pair<int, int>> q;
        q.push({0,0});
        vis[0][0]=1;
        int ans=0;
        while(!q.empty())
        {
            int s= q.size();
             ans++;
            while(s--)
            {
                int x= q.front().first;
                int y= q.front().second;

                q.pop();
               
                if(x==m-1 and y==n-1)return ans;
                 if(grid[x][y]==0)
                continue;
                for(int j=grid[x][y]+y; j>=y ; j--)
                {
                    if(j>=0 and j<= n-1 and !vis[x][j])
                    {
                        vis[x][j]=1;
                        q.push({x,j});
                    }
                }
                for(int i=grid[x][y]+x; i>=x; i--)
                {
                    if(i>=0 and i<= m-1 and !vis[i][y])
                    {
                        vis[i][y]=1;
                        q.push({i,y});
                    }
                }


            }
           
        }
        return -1;
        
    }
};
```

#### Language used for code
C++ 

#### Expected behavior
This code shouldn't have got Accepted.

#### Additional context
Below is the test case that should fail the above code.
[out.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/11214267/out.txt)

[](url)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link since the above code received TLE right now: https://leetcode.com/submissions/detail/932712052/


We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by prakash7720** [comment]
It'd be difficult for me to reproduce the submission link because I saw this submission on the submission details page on the graph (my own code got AC with different approach, so I was able to see other's submissions from submissions graph). It shows sample submissions of other users. It's still there if you open the graph at (504.00, 0.42). I'm attaching some screenshots for reference.
![Screenshot from 2023-04-13 16-12-57](https://user-images.githubusercontent.com/124239858/231736057-8a800535-1a88-48ef-a4b2-5bfb30e3b93b.png)
![Screenshot from 2023-04-13 16-12-54](https://user-images.githubusercontent.com/124239858/231736074-dd00ba4c-389c-4314-93b9-01c28f9e8899.png)
![Screenshot from 2023-04-13 16-12-42](https://user-images.githubusercontent.com/124239858/231736079-77098857-ca09-4794-b02d-14b886faf9de.png)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
