### ISSUE TITLE
System Design

### ISSUE THREAD

**Issue by TariqTawalbeh** [LeetCode-Feedback/LeetCode-Feedback#12941]
I've bought the System Design course and I have issues with the content, first, the voice of the lecturer is not clear and his accent as well, also, the written content doesn't meet the full content of the video, I don't see any benefits from this course! is there any other clearer videos or resources?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
