### ISSUE TITLE
Please review the question I contributed, it's been on pending for long, or decline if not suitable

### ISSUE THREAD

**Issue by YashGovindani** [LeetCode-Feedback/LeetCode-Feedback#12961]
#### Your LeetCode username
vaathi

#### Category of the bug
- [ ] Question

#### Description of the bug
Please review the question I contributed, it's been on pending for long, or decline if not suitable.

**Comment by YashGovindani** [comment]
@LC-Pam please have a look.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
