### ISSUE TITLE
Tab size Bug on Text Editor!

### ISSUE THREAD

**Issue by davitescobedo** [LeetCode-Feedback/LeetCode-Feedback#13205]
#### Your LeetCode username

eldavimost

#### Category of the bug
- [X] Text Editor

#### Description of the bug

Google Java coding style specifies 2 spaces for tabs. So everyone preparing for it should always use that (which is a big audience). However, the text editor in LeetCode is designed for 4 tabs and all examples start with 4 tabs. The text editor tab size functionality gets reset to 4 spaces every time you open a new window.

Open any problem, go to the text editor settings > tab size and change it to 2.
Now, open any other problem in a different window (maybe with shift + click) and you'll see that even though the editor settings says the tab size is 2, when you hit tab, it adds 4 spaces! The only way around it is to 

It would be great too if you could apply some linter to change the number of spaces tabs have in the 'default code definition' (the code that appears the first time you open a problem or when you click on 'Reset to default code definition'.

Every single problem I open right now I have to: select the 4 tabs setting, then the 2 tabs setting (so it'll take effect in the text editor) and then select the different lines in the default code and use Shift+tab to put them to 2 spaces. It is an unbelievable nightmare.

#### Expected behavior

Tab size to follow your settings without having to change it ever again!
Tab size in default code to have the tab space size you select.

#### Screenshots

[https://snipboard.io/2t7NG4.jpg](https://snipboard.io/2t7NG4.jpg)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
