### ISSUE TITLE
2661.test bug

### ISSUE THREAD

**Issue by Ronlikesleep** [LeetCode-Feedback/LeetCode-Feedback#13229]
#### Category of the bug
- [ ] Solution
- [ ] Missing Test Cases 

#### Description of the bug

I can passed the 1058/1058 tests but still can not ac. The only TLE is for an emtpy arr test. But it is not legal to have an empty test.

#### Code you used for Submit/Run operation

```
class Solution {
    public int firstCompleteIndex(int[] arr, int[][] mat) {
        if(arr.length ==0)return 0;
        Map<Integer, int[]> map = new HashMap<>();
        for(int i = 0;i<mat.length;i++){
            for(int j = 0;j<mat[0].length;j++){
                map.put(mat[i][j], new int[]{i ,j});
            }
        }
        boolean[][] mark = new boolean[mat.length][mat[0].length];
        for(int i = 0;i<arr.length;i++){
            int[] target = map.get(arr[i]);
            mark[target[0]][target[1]] = true;
            if(checker(mat, arr[i], map, mark))return i;
        }
        return -1;
        
    }
    
    public boolean checker(int[][] mat, int num, Map<Integer, int[]> map, boolean[][] mark){
        int[] target = map.get(num);
        boolean row = true;
        boolean column = true;
        for(int i = 0;i<mat[0].length;i++){
            if(mark[target[0]][i]==false){
                row = false;
                break;
            }
        }
        for(int i = 0;i<mat.length;i++){
            if(mark[i][target[1]]==false){
                column = false;
                break;
            }
        }
        return row || column;
    }
}
```

#### Language used for code

Java

#### Expected behavior

pass this question

#### Screenshots

<img width="970" alt="image" src="https://user-images.githubusercontent.com/29923635/235383881-608ade91-51ac-4100-be1d-ba01e55a31ea.png">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us.

The judger appears to be running correctly.

The code received TLE after submission: https://leetcode.com/submissions/detail/942741870/

The same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!

Please feel free to refer to the discussion section of the problem to see how other users have optimized their codes!

**Comment by Ronlikesleep** [comment]
Thanks you so much
