### ISSUE TITLE
Unable to remove social links from basic info on profile page

### ISSUE THREAD

**Issue by tannerdolby** [LeetCode-Feedback/LeetCode-Feedback#13299]
#### Your LeetCode username
`@gnawlix`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Website 

#### Description of the bug
There isn't an option to remove social links from the basic info of a users profile. The only option is to "Edit", and if attempting to save an empty string when editing it displays an error message.

#### Expected behavior
I would expect there to be a trashcan icon (or 'Remove' text) next to edit in order to remove a social link. If I'm not looking in the right place and this functionality already exists, please let me know. Thanks!

#### Screenshots
<img width="909" alt="Screen Shot 2023-05-04 at 6 51 24 PM" src="https://user-images.githubusercontent.com/48612525/236362943-87aedf0f-1b85-4980-a5fa-de7d348e5e3a.png">

<img width="932" alt="Screen Shot 2023-05-04 at 6 51 33 PM" src="https://user-images.githubusercontent.com/48612525/236362942-de82ba2e-2c37-42a8-b4c3-72f7985c93aa.png">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
