### ISSUE TITLE
Update the TypeScript & JavaScript PriorityQueue library version

### ISSUE THREAD

**Issue by genepg** [LeetCode-Feedback/LeetCode-Feedback#13306]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Please update the version of `@datastructures-js/priority-queue`. Now is `6.2.0`

#### reference
-  #5147
- https://github.com/datastructures-js/priority-queue/pull/31

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
