### ISSUE TITLE
LeetCode UI Bug

### ISSUE THREAD

**Issue by jwala-anirudh** [LeetCode-Feedback/LeetCode-Feedback#13314]
#### Your LeetCode username
jwalaanirudh

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases
- [x] UI Bug

#### Description of the bug
Tool tip of the feedback button when hovered on the icon feedback icon is out of place

#### Expected behavior
Tool tip to come on below the feedback button, instead of the top-left corner of the page

#### Screenshots
<img width="1429" alt="Screenshot" src="https://user-images.githubusercontent.com/25549847/236609029-310b1d44-40e1-48f9-80b2-a7ee8929582f.png">

#### Additional context
Sorry this issue is not related to any of the questions/test cases of the leetcode but though of sharing it with your team.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
