### ISSUE TITLE
Time Limit Exceeded

### ISSUE THREAD

**Issue by radhouene101** [LeetCode-Feedback/LeetCode-Feedback#13312]
#### Category of the bug
- [x] Question
- [x] Solution
- [x] Missing Test Cases 

#### Code  used for Submit/Run operation

```
class Solution {
    public int maxVowels(String s, int k) {
        int precMax=0;
        int max=0;
        String word="";
        for(int i=0;i<=s.length();i++){
            if(i+k<=s.length()){
            word=s.substring(i,i+k);
            }else{
                word=s.substring(i,s.length());
            }
            if(numberOfVowels(word)>precMax){
                max=numberOfVowels(word);
                precMax=max;
                System.out.println(word);
            }

    }
    return max;
}
    public int numberOfVowels(String ch){
        int nbr=0;
        for(int i=0;i<ch.length();i++){
            if(ch.charAt(i)=='a' || ch.charAt(i)=='e' || ch.charAt(i)=='i' || ch.charAt(i)=='o' || ch.charAt(i)=='u'){
                nbr++;
            }
        }
        return nbr;
        
    }
}
```

#### it fails test case number 99 problem link : https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/
I couldn't think of a better clear approach using complexity of O(n) can anyone explain why this constraint and how can I improve the code with a better approach?

#### Screenshots

![image](https://user-images.githubusercontent.com/94876121/236586046-fdccab73-5210-4676-87a4-818c85688421.png)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
