### ISSUE TITLE
Accept invalid test case and give wrong output for invalid test case!!

### ISSUE THREAD

**Issue by bghanchi** [LeetCode-Feedback/LeetCode-Feedback#1337]
#### Your LeetCode username
BharatKumar1997

#### Category of the bug
- [x] Question: Accept invalid test case
- [ ] Solution
- [ ] Language

#### Description of the bug
**Testcase**: "Leetc0de"

For above test case, The output should be **False** but Leetcode give output is **True**  which is wrong because input only contains small and capital alphabets so when we give digit or other characters then the output should be false, not true. So for this test cases, Leetcode needs to change excepted output.

#### Code you used for Submit/Run operation

```
class Solution:
    def detectCapitalUse(self, word: str) -> bool:
        small,big=0,0
        n=len(word)
        if n<=0:
            return True
        for ch in word:
            if ord(ch)>=ord('a') and ord(ch)<=ord('z'):
                small+=1
            else:
                big+=1
        
        if small==n or big==n:
            return True
        if big==1 and ord(word[0])<ord('a'):
            return True
        return False
```

#### Expected behavior
**Your input**:-
 "Leetc0de"
**Output**:-
 false
**Expected**:-
true

#### Additional context
Problem: https://leetcode.com/problems/detect-capital/
Contribution: https://leetcode.com/contribute/22722

**Comment by lc-kay** [comment]
@bghanchi Upon running your test case, I received invalid test case because 'word' must consist of values in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] only. Thank you for your time and support!

**Comment by bghanchi** [comment]
Hi, I think now added this output!!
