### ISSUE TITLE
2073 call to return will not return to function caller

### ISSUE THREAD

**Issue by Tully-cmd** [LeetCode-Feedback/LeetCode-Feedback#13424]
#### Your LeetCode username
tillsix

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
Return from function will not work.

#### Code you used for Submit/Run operation
```
class Solution {

    /**
     * @param Integer[] $tickets
     * @param Integer $k
     * @return Integer
     */

    function timeRequiredToBuy($tickets, $k) {

        $size = count($tickets);
        $totalTime = 1;
        
        while(true) {
            for ($i = 0; $i < $size; $i = $i + 1) {
                if($tickets[$i] > 0) {
                    $tickets[$i] = $tickets[$i] - 1;
                    $totalTime = $totalTime + 1;
                }
                if($tickets[$i] == 0 && $i != $k) {    
                    $tickets = array_merge(array_slice($tickets,0,$i),array_slice($tickets,$i + 1));
                    $size = $size - 1;
                    $k = $k - 1;
                    $i = $i - 1;
                    echo "continue"."\n";
                    continue;
                }
                if($tickets[$i] == 0 && $i == $k) {
                    echo "MADE IT HERE ".implode($tickets)." i: ".strval($i)." k: $k"." tickets[i]: $tickets[$i]"."\n";
                    echo "totalTime: $totalTime\n";
                    return $totalTime;
                }
            }
        }
    }
}
```

#### Language used for code
PHP

#### Expected behavior
Return returns from function when reached in code.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54709821/9a68a508-4504-4cfd-b0ae-2d0f0faf8720)

#### Additional context

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
