### ISSUE TITLE
User profile submission map bug with pagination

### ISSUE THREAD

**Issue by albertininm** [LeetCode-Feedback/LeetCode-Feedback#13432]
#### Your LeetCode username
albertinin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] General bug on website

#### Description of the bug

When I select the current year in the contribution map, it says I had no submission on the first cel of the map (the oldest one), which today is 12 May, 2022. However, I had submitted 7 times in this day and I can see it when I filter it by the last year (2022):

#### Screenshots
Current year:
<img width="949" alt="Screenshot 2023-05-12 at 09 16 43" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19316913/6a5c7e80-aa8e-4a83-81db-332e3e58d84b">

Previous year:
<img width="846" alt="Screenshot 2023-05-12 at 09 17 39" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19316913/de7ecae8-736c-4174-b582-2a6bbd3e10e7">

#### Expected behavior
Values in the map to be correct for any selected date filter.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by albertininm** [comment]
@LC-Pam , sorry about the confusion! I'll open a conversation on Zendesk then. Thanks for the feedback 🙂
