### ISSUE TITLE
Comment notification leads to interview page. 

### ISSUE THREAD

**Issue by vaibhavsinghz** [LeetCode-Feedback/LeetCode-Feedback#13471]
<img width="381" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/95747953/e10b2985-65bb-463b-8e8a-99d53fa4a55f"> 

> Leetcode comment notification on any solution leads to [Interview Discussion](https://leetcode.com/discuss/interview-question?currentPage=1&orderBy=hot&query=) of leetcode.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
