### ISSUE TITLE
Search for a non-existing question title doesn't work properly

### ISSUE THREAD

**Issue by vinitamaloo-asu** [LeetCode-Feedback/LeetCode-Feedback#13493]
#### Your LeetCode username

jethalel

#### Category of the bug
Search filter issue

#### Description of the bug

When searched for a title which does not exist in problemQuestionList, it should either show an empty screen or maybe something else. But right now, when I search with string like MRU or ZXSDFSD.., the search takes a long time to get the response and finally it shows me a list of all the questions which comes by default without the search string. In addition, the list now does not even have the green tick marks which shows that I have already submitted this question.

#### Expected behavior

Searching for a string which does not have a matching question should either show a blank list or something else but definitely not the default list without the green tick marks and the frequency is also changed. See image 1 and 2 to compare.

#### Screenshots

Before search
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97632954/f90fbeed-c8e9-44c6-bf84-13a21654f6c5)
After search
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/97632954/66ca28db-ad57-4646-9133-fbee67ac011d)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
