### ISSUE TITLE
Companies option bug : Companies are visible even without subscription for any problem

### ISSUE THREAD

**Issue by RitvikSaranS** [LeetCode-Feedback/LeetCode-Feedback#13524]
#### Your LeetCode username
PSYC0DER

#### Category of the bug
- [ ] Subscription option bug

#### Description of the bug

When solving a question there is a subscription to premium option and one would be able to view the companies in which the question was asked only if the subscription is done. But after clicking the companies button and a modal window pops up with the companies list blurred out. If in the elements section of browser developer tools one removes the "backdrop-blur-sm" class the companies list would be visible without subscription.

#### Expected behavior
The list of companies should only be visible after subscription.

#### Screenshots

Before:

![Screenshot (26)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88278326/bfa25d83-4fe0-421a-a125-e5d8a532ba96)
After:

![Screenshot (27)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88278326/accc33bb-2c6c-4864-9bfa-11ad930e092b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
