### ISSUE TITLE
703: Kth Largest Element - No Input on final test case causes C++ to Exceed Time Limit

### ISSUE THREAD

**Issue by PowersOfEight** [LeetCode-Feedback/LeetCode-Feedback#13644]
#### Your LeetCode username
PowersOfEight

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ *] Missing Test Cases 

#### Description of the bug

When submitting solutions for C++, the final test case appears to have no input and causes a Time Limit Exceeded.

#### Code you used for Submit/Run operation

```
class KthLargest {
    vector<int> nums;
    int k;
    void swap(int i, int j) {
        int tmp = nums[i];
        nums[i] = nums[j];
        nums[j] = tmp;
    }
    int partition(int left, int right, int pivot) {
        swap(right, pivot);
        int i = left - 1;
        int j = right;
        while(i < j) {
            while(i < right && nums[++i] < nums[right]);
            while(j > left && nums[--j] > nums[right]);
            swap(i, j);
        }
        swap(i, j);
        swap(i, right);
        return i;
    }
    void quickselect(int left, int right, int k_th_largest) {
        if(left < right) {
            int pivot_idx = left + (rand() % (right - left + 1));
            pivot_idx = partition(left, right, pivot_idx);
            if(pivot_idx != nums.size() - k_th_largest) {
                if(pivot_idx < nums.size() - k_th_largest) {
                    quickselect(pivot_idx + 1, right, k_th_largest);
                } else {
                    quickselect(left, pivot_idx - 1, k_th_largest);
                }
            }
        }
    }
public:
    KthLargest(int _k, vector<int>& _nums) {
        for(int num : _nums) {
            nums.push_back(num);
        }
        this->k = _k;
    }
    
    int add(int val) {
        this->nums.push_back(val);
        quickselect(0, nums.size() - 1, k);
        return nums[nums.size() - k];

    }
};
```

#### Expected behavior

If this exceeded the time limit, there should be some input showing what input the code failed under. 

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/57668126/84cbb24c-5680-4af5-9a2c-c3f69a353a7f)

#### Additional context

I attempted to use the priority_queue<int> solution in C++ for this problem and was greeted with a "Memory Limit Exceeded" for that code.  Doing each of these solutions in Java, however, results in an accepted solution.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
