### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by YuviCrypter** [LeetCode-Feedback/LeetCode-Feedback#13716]
#### Your LeetCode username
YuviCrypter

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The Problem no. 1470. Shuffle the Array always gives a runtime of 0 ms. It is showing like that for 100% of people. I guess it is a bug since the problem cannot be solved in 0 ms runtime. I hope you find this post and this helps you.

#### Code you used for Submit/Run operation

```
// Shuffle the Array
class Solution {
    public int[] shuffle(int[] nums, int n) {
        int [] res = new int[2*n];
        int j=0;
        for(int i=0;i<2*n;i++){
            res[i] = nums[j];
            j+=n;
            if(j>=2*n){
                j-=2*n-1;
            }
        }
        return res;
    }
}
```

#### Language used for code
Java

#### Expected behavior

I expect there should be some non-zero runtime value.

#### Screenshots

![Runtime Submission Bug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/98221859/48d11a6b-afc9-447e-ad4b-42e59d78c6bf)

**Comment by LC-Pam** [comment]
Thank you for raising this concern to our attention! I am sorry about the confusion! 0ms is because the program took too less time to execute. It took time in microseconds but we only support precision up to milli-seconds in the display, therefore the time is 0ms. 

We appreciate your timely feedback and support! If you spot any other irregular site activities, please don't hesitate to let us know!

**Comment by YuviCrypter** [comment]
I will let you know if I find any more bugs. By the way, How can I earn the 100 leet coins for filing issue in the repo?
