### ISSUE TITLE
Link Redirects to Wrong Set of Problems

### ISSUE THREAD

**Issue by akhil0903** [LeetCode-Feedback/LeetCode-Feedback#13732]
#### Your LeetCode username
Ak939

#### Category of the bug
- Link Redirects to Wrong Problem

#### Description of the bug
When clicked on " [random easy problems] ''' in the page " https://leetcode.com/explore/learn/card/the-leetcode-beginners-guide/679/sql-syntax/4357/ ''' it redirects to a hard problem where as it should redirect to easy problems

#### Screenshots

When clicked on " [random easy problems](https://leetcode.com/problemset/all/?difficulty=Easy&page=1) " it redirects to wrong page as shown below.

<img width="1280" alt="Screenshot 2023-05-27 at 3 59 58 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/53147586/794ec51d-e0a1-4948-9543-f5fcf9fd0210">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
