### ISSUE TITLE
Report Solution Bug for First Missing Positive (#41)

### ISSUE THREAD

**Issue by redcodebluecode** [LeetCode-Feedback/LeetCode-Feedback#13830]
#### Your LeetCode username

svand
https://leetcode.com/svand/

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I believe my code should be accepted as the correct answer, but the feedback is time exceeded limit and thus it didn't accept my solution. However, I think the equivalent solution is accepted. Thus, I think it is a solution bug.

#### Code you used for Submit/Run operation

```
// First Missing Positive
class Solution:
    def firstMissingPositive(self, nums: List[int]) -> int:
        n = len(nums)
        for i in range(n):
            while 1 <= nums[i] <= n and nums[i] != nums[nums[i] - 1]:
                nums[i] , nums[nums[i] - 1] = nums[nums[i] - 1], nums[i] 
        
        for i in range(n):
            if nums[i] != i + 1:
                return i + 1
        
        return n + 1
```

#### Expected behavior

The system should accept my solution above instead of stating it exceeds the time limit and thus won't accept it.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4648979/4c1041f5-0e6c-472a-bcf9-e94a55788e2c)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/4648979/ef1bcaff-a8ac-44c7-b0c5-a27df3c81a19)

#### Additional context

# As shown in the screenshots above, the first solution exceeds time limits while the second one is accepted. The only difference of line of code is highlighted in the screenshots. It is to swap two numbers and I don't think the order matters. So the first solution should also be accepted.

# Could you please grant leetcode coins if this bug report is accepted? Thanks!

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
