### ISSUE TITLE
Invalid test case

### ISSUE THREAD

**Issue by guyfrompluto** [LeetCode-Feedback/LeetCode-Feedback#13973]
#### Your LeetCode username

guyfrompluto 

#### Category of the bug
  - [ ] TLE

  - [ ] Wrong testcase

#### Description of the bug

 when i submit the code it rus for 200/200 test cases but for one invalid test case where (referring to the qs) n and k both are not given the code says TLE

#### Code you used for Submit/Run operation

```
// 60. Permutation Sequence
class Solution {
public:
    void solve(string nums, string &output, vector<string>& ans, vector<bool>& used, int &count, int k) {
        if (output.size() == nums.size()) {
            count++;
            if (count == k) {
                ans.push_back(output);
                return;
            }
        }

        for (int i = 0; i < nums.size(); i++) {
            if (used[i] == false) {
                used[i] = true;
                output.push_back(nums[i]);
                solve(nums, output, ans, used, count, k);
                output.pop_back();
                used[i] = false;
            }
        }
    }

    string getPermutation(int n, int k) {
        if(n<=0)
            return NULL;
        string nums = "";
        for (int i = 1; i <= n; i++) {
            nums += to_string(i);
        }

        string output = "";
        vector<string> ans;
        vector<bool> used(n, false);
        int count = 0;
        solve(nums, output, ans, used, count, k);

        if (ans.empty()) {
            return "";
        }

        return ans.back();
    }
};
```

#### Language used for code

C++

#### Expected behavior

 the test case was not given i wanted either n or k to be given but none was there whih caused TLE.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/120249077/934bfa59-f49e-43a7-9df8-18bf76993dc5)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
