### ISSUE TITLE
All test cases passed still giving TLE

### ISSUE THREAD

**Issue by ipratham101** [LeetCode-Feedback/LeetCode-Feedback#13998]
#### Your LeetCode username

justdoitt

#### Category of the bug
- [ ] Missing Test Cases -> all test cases are passing still gives TLE

#### Description of the bug

Question link -> https://leetcode.com/problems/online-stock-span/description/
Question Number -> 901
I submitted this code and it passed all test cases 
but still gives TLE total test cases are 99 it passed all the test cases using the below code:-

#### Code you used for Submit/Run operation

```
class StockSpanner {
public:
vector<int> ans;

    StockSpanner() {
        
    }
    
    int next(int price) {
 
        ans.push_back(price);
      if(ans.size()==1){
          return 1;
      }
        int k =0;
        bool flag = false;
        for(int i = ans.size()-1; i>=0; i--){
            if(price>=ans[i] && flag == false){
                k++;
                flag = false;
            }
            else{
                flag = true;
            }
        }
        return k;
    }

};

/**
 * Your StockSpanner object will be instantiated and called as such:
 * StockSpanner* obj = new StockSpanner();
 * int param_1 = obj->next(price);
 */
```

#### Language used for code

C++

#### Expected behavior

I expected to either pass the test cases or display the test cases that are giving TLE.

#### Screenshots

![lc bug](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/105946829/345a53ef-abf3-4e3d-87f9-fc7c64649e00)

#### Additional context

It should either pass the code or mention the test case at which the TLE occurs
as passing all the test cases and giving TLE is ambiguous.
Hope it gets fixed.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
