### ISSUE TITLE
Inconsistent o/p for Ques 162 while using C++

### ISSUE THREAD

**Issue by UjjwalT1** [LeetCode-Feedback/LeetCode-Feedback#14171]
**Question 162. Find Peak Element**

#### Your LeetCode username
UjjwalLK4D4

#### Category of the bug
- Language 

#### Description of the bug

I didn't used Global/ Static Variable
When I submitted the solution for question 162. using C++ then I got runtime error for the example test case that run smootly during test Run. When I used same logic using kotlin then solution was accepted.

#### Code you used for Submit/Run operation
```
//162. Find Peak Element
//CPP code which had runtime error
class Solution {
public:
    int findPeakElement(vector<int>& nums) {
        for(int i=0;i<nums.size();i++){
            if( nums[i]>nums[(i+1)%nums.size()]  && nums[i] > nums[i-1==-1?(nums.size()-1):i-1])
            return i;
        }

        return 0;
    }
};
```

#### Language used for code
C++

#### Expected behavior
I initially ran the above provided code using C++ for test case [1,2,3,1]  then I ran smoothly.
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121283901/15b795fb-6a24-4734-b467-83799a81d11d)

But when I submitted it I got run time error for the same test case [1,2,3,1]: 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/121283901/9f037c45-d3f7-4693-812e-d63db2197303)

But when I submitted my code using Another language (KOTLIN) with same logic , It worked perfectly fine
```
//KOTLIN CODE with same logic as CPP which worked fine
class Solution {
    fun findPeakElement(nums: IntArray): Int {
        for(i in 0..(nums.size-1)){
            if( nums[i]>nums[(i+1)%nums.size]  && nums[i] > nums[if(i-1==-1) nums.size-1 else i-1])
            return i;
        }

        return 0;
    }
}
```

#### Additional context
My code didnt have globlal/static variable .

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the code received Accept after the submission:https://leetcode.com/submissions/detail/975831579/. 

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
