### ISSUE TITLE
Violation of contest rules on Weekly Contest 349

### ISSUE THREAD

**Issue by B10732006** [LeetCode-Feedback/LeetCode-Feedback#14187]
#### Your LeetCode username

Shane55688

#### Category of the bug
Violation of contest

#### Description of the bug

I participated the Weekly Contest 349 and finished 3 questions.
However, after the the contest it say that I violate the rule and banned me.
I finish 3 questions all by myself and I don't know which rule I violated.

Please check again and see if there is any misjudge.
If I do violate the rule please tell me which one I violated.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71718508/b01ba7f4-7f50-4393-95a0-0df5841b1386)

The followings are the answer I submit during the contest.
question 1
https://leetcode.com/problems/neither-minimum-nor-maximum/submissions/968461642/
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71718508/ebe9a11b-bc69-4edf-8daf-537fd9ab8aac)

question 2
https://leetcode.com/problems/lexicographically-smallest-string-after-substring-operation/submissions/968510423/
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71718508/63ea54c8-ce72-4471-8e7c-76b67da7f120)

question 3
https://leetcode.com/problems/collecting-chocolates/submissions/968565671/
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/71718508/9e6d78c2-089e-423a-b4b4-04def834782b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
