### ISSUE TITLE
3Sum - Cant show testcase 312 and fails with TLE

### ISSUE THREAD

**Issue by Tookser** [LeetCode-Feedback/LeetCode-Feedback#14201]
#### Your LeetCode username
Tookser

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

Task 3Sum https://leetcode.com/problems/3sum/description/.

I try to submit solution, but it fails on 312/312 testcase with Time Limit Exceeded. Also, it doesnt't show testcase.

#### Code you used for Submit/Run operation

```python3
from bisect import bisect_left
class Solution:
    def threeSum(self, nums: List[int]) -> List[List[int]]:
        
        def index(a, lo, hi, x):
            if lo > hi:
                return False
            i = bisect_left(a, x, lo=lo, hi=hi)
            if i != len(a) and a[i] == x:
                return True
            return False

        nums = list(sorted(nums))
        # print(nums)
        n = len(nums)
        res = set()
        if len(nums) < 3 or not isinstance(nums, list):
            return []
        for i in range(n):
            for j in range(n-1, i, -1):
                # print(i, j)
                pred = nums[i] + nums[j]

                if index(nums, i+1, j-1, -pred):
                    # print('ok')
                    res.add(tuple(sorted([nums[i], nums[j], -(nums[i] + nums[j])])))
        print(res)
        return res
```

#### Language used for code
Python 3

#### Expected behavior
It shows input of failed testcase.

#### Screenshots
![изображение](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/46273803/a3764652-2806-4059-a199-1edda9c2cdf7)

#### Additional context
There are no any text in that tags.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
