### ISSUE TITLE
Missing Test Case - 724. Find Pivot Index

### ISSUE THREAD

**Issue by RitikHans** [LeetCode-Feedback/LeetCode-Feedback#14230]
I want to contribute a new TestCase  which is given below :
[1,6,3,4,8,2,5,4,3]

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
