### ISSUE TITLE
Strange behaviour for C++submissions in 1027. Longest Arithmetic Subsequence

### ISSUE THREAD

**Issue by AnkitRupal** [LeetCode-Feedback/LeetCode-Feedback#14310]
#### Your LeetCode username
Ankit_Rupal

#### Category of the bug
- [*] Question

#### Description of the bug
When you submit the C++ solution for the 1027. Longest Arithmetic Subsequence, the last testcase i.e., 63 is giving TLE. When you see the input it shows no input. Also, when you try to "Use Testcase", It just has an empty line in the input.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int longestArithSeqLength(vector<int>& nums) {
        int n = nums.size(), ans = 0;
        if(n == 0)
            return 0;
        unordered_map<int,unordered_map<int, int>> diffMapping;
        for(int right = 0 ; right < n ; right++){
            for(int left = 0 ; left < right ; left++){
                int diff = nums[right] - nums[left];
                diffMapping[right][diff] = 1 + diffMapping[left][diff];
                ans = max(ans, 1 + diffMapping[right][diff]);
            }
        }
        return ans;
    }
};
```

#### Language used for code
C++

#### Expected behavior
There shouldn't be any invalid testcase in this problem, because when I tried to submit using Java, there is no such testcase thing arriving, although the code logic remained exactly the same.
There must an issue at the backend regarding evaluation of C++ submissions on Leetcode. I had seen another issue related to another question which depicts the same thing happening to C++ submissions only!.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support! (https://leetcode.com/problems/longest-arithmetic-subsequence/discuss/?currentPage=1&orderBy=hot&query=&tag=c)
