### ISSUE TITLE
Heat Map Issue

### ISSUE THREAD

**Issue by Pb1923** [LeetCode-Feedback/LeetCode-Feedback#14374]
#### Your LeetCode username

PRB_4937

#### Category of the bug
Question
- [x] Question 
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Question no. 2745  Construct The Longest New String
Although I have submitted the solution for this problem on 25th June but its showing 0 submissions on that day and it is not reflecting on heat map as well. Hence, my daily streak paused. Please retrieve it ASAP.
![Screenshot (60)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114418627/95c528ae-8987-4dc4-97b8-f25dc871f845)
![Screenshot (61)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114418627/765f0f16-40a1-4174-b8da-daddb749173d)
![Screenshot (62)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114418627/86a063c9-3431-4080-ba60-bd8e07322037)
![Screenshot (63)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114418627/cec69a7f-0fd8-4d93-b831-17056888cef8)

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
