### ISSUE TITLE
the output for [2,4,1] is 0,but showing as 2 . Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by vikaslellapalli** [LeetCode-Feedback/LeetCode-Feedback#14386]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission AC link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
