### ISSUE TITLE
I can't make any topics for 4 hours or even longer

### ISSUE THREAD

**Issue by JackLi-CS** [LeetCode-Feedback/LeetCode-Feedback#14446]
#### Your LeetCode username
jackli6428

#### Description of the bug
I can't make any topics, and I waited for almost 4 hours but it still doesn't work.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/138118954/809a2ade-6f90-4e2a-b508-3dae517f6306)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
