### ISSUE TITLE
TLE question - 65. Valid Number

### ISSUE THREAD

**Issue by cgsgak1** [LeetCode-Feedback/LeetCode-Feedback#1463]
#### Your LeetCode username
cgsgak1

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I received time limit exceeded message from leetcode after sending my solution. According to information presented the TLE happens on 1411 testcase (because 1410 / 1481 test cases passed). But when I tried to run this testcase locally, it took only 4ms to pass successfully.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool isNumber(string s) {
        regex r(R"((\s*)[-+]?(((\d+)(\.\d*)?)|(\.\d+))(e[-+]?\d+)?(\s*)?)");
        
        return regex_match(s, r);
    }
};
```

#### Language used for code

C++

#### Expected behavior

My question is: "Do I have a TLE because the summary time, that took all testcases to pass exceeds some value? Or TLE happens separately for each test?" I believe that my submit was correct, because I was not able to get TLE by running my code on leetcode.

#### Screenshots

![Capture](https://user-images.githubusercontent.com/34144576/100290781-2efa9380-2f8d-11eb-8b21-2d9fae8ff8d4.JPG)
![Capture2](https://user-images.githubusercontent.com/34144576/100290787-31f58400-2f8d-11eb-926e-9a935b12d54d.JPG)

#### Additional context

This looks quiet strange to me if solution has a summary time limit for all testcases. Because I believe this is exactly my case.

**Comment by lc-kay** [comment]
@cgsgak1 When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
- Your code has an underlying infinite loop.
- Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page, or posting your code there to get support from other users!
