### ISSUE TITLE
Problem With Test Case : 15. 3Sum

### ISSUE THREAD

**Issue by vv2002may** [LeetCode-Feedback/LeetCode-Feedback#14717]
#### Your LeetCode username

carrysec

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

It is showing TLE even when all test cases are passed.

#### Code you used for Submit/Run operation

```
class Solution
{
public:
    vector<vector<int>> threeSum(vector<int> &a)
    {
        vector<vector<int>> ans;
        int n = a.size();
        if (n == 0)
            return ans;
        map<vector<int>, int> m;
        sort(a.begin(), a.end());
        for (int i = 0; i < n - 1; i++)
        {
            int left = i + 1, right = n - 1;
            int target = -a[i];
            while (left < right)
            {
                int temp = a[left] + a[right];
                if (temp < target)
                    left++;
                else if (temp > target)
                {
                    right--;
                }
                else
                {
                    vector<int> dp;
                    dp.push_back(a[i]);
                    dp.push_back(a[left]);
                    dp.push_back(a[right]);
                    m[dp]++;
                    if (m[dp] == 1)
                        ans.push_back(dp);
                    left++;
                    right--;
                }
            }
        }
        return ans;
    }
};

```

#### Language used for code

C++

#### Expected behavior

My code should be accepted but it gives TLE on submit.

#### Screenshots

<img width="1280" alt="Screenshot 2023-07-12 at 10 52 11 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/85130915/47edded1-bea5-4ad9-aa8d-a6fa2c07ef44">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
