### ISSUE TITLE
Solution Thread Notification on/off button is missing

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#14780]
![Screenshot 2023-07-14 235535](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/ac13cb1a-5f40-40ce-8af1-ac1215e8fcec)
In the old UI, we can use this button to turn off notification for a specific thread.

Now in the new UI for solution thread, this feature is gone for some reason...
![Screenshot 2023-07-14 235605](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/90146234/bb4e8db0-3485-4bbe-8e5f-c2e15ef044f0)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
