### ISSUE TITLE
Invalid Test Case - 212. Word Search II

### ISSUE THREAD

**Issue by WahajJaved20** [LeetCode-Feedback/LeetCode-Feedback#14859]
#### Your LeetCode username
Wahaj Javed
user6969WN

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ ✅] Invalid Test Case

#### Description of the bug

I have written a complete solution and its passing all of the test cases, yet there is a random test case where it shows that my answer is wrong, yet the test case is empty.

#### Code you used for Submit/Run operation

```
class TrieNode{
    public:
        map<char,TrieNode*> children;
        bool endOfWord;
        TrieNode(){
            endOfWord = false;
        }
};
class Trie {
public:
TrieNode* root;
    Trie() {
        root = new TrieNode();
    }
    
    void insert(string word) {
        TrieNode* curr = root;
        for(int i=0;i<word.length();i++){
            if(!curr->children[word[i]]){
                curr->children[word[i]] = new TrieNode();
            }
            curr = curr->children[word[i]];
        }
        curr->endOfWord = true;
    }
};

class Solution {
public:
    Trie dictionary;
    vector<string> findWords(vector<vector<char>>& board, vector<string>& words) {
        set<string> res;
        if(board.size() == 0){
            return vector<string>(res.begin(),res.end());
        }
        for(int i=0;i<words.size();i++){
            dictionary.insert(words[i]);
        }
        int ROWS = board.size(), COLS = board[0].size();
        
        for(int r=0;r< ROWS;r++){
            for(int c=0;c<COLS;c++){
                dfs(r, c, dictionary.root, "",ROWS,COLS,board,res);
            }
        }
        return vector<string>(res.begin(),res.end());
    }
    void dfs(int row,int col, TrieNode* node, string word,int &ROWS,int &COLS,vector<vector<char>>& board,set<string>& res){
        if(row < 0 || col < 0){
            return;
        }
        if(row >= ROWS || col >= COLS || board[row][col] == '#'){
            return;
        }
        if(!node->children[board[row][col]]){
            return;
        }
        char cha = board[row][col];
        node = node->children[board[row][col]];
        word += board[row][col];
        if(node->endOfWord){
            res.insert(word);
        }
        board[row][col] = '#';
        dfs(row + 1, col, node, word, ROWS, COLS, board, res);
        dfs(row - 1, col, node, word, ROWS, COLS, board, res);
        dfs(row, col + 1, node, word, ROWS, COLS, board, res);
        dfs(row, col - 1, node, word, ROWS, COLS, board, res);
        board[row][col] = cha;
    }
};
```

#### Language used for code

C++

#### Expected behavior

This should have gotten the answer accepted. Since all test cases are passing

#### Screenshots

<img width="1073" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/84095994/55ab55da-c01c-4353-8e72-ea1ccd2d6bf9">

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

Your code received TLE :  https://leetcode.com/submissions/detail/997871549/

This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
