### ISSUE TITLE
Missing Test Case - 435. Non-overlapping Intervals

### ISSUE THREAD

**Issue by RahulSurana123** [LeetCode-Feedback/LeetCode-Feedback#14876]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
-  [x] Missing Test Cases 

#### Description of the bug
the last testcase of the question does not have any input in it its a blanktestcase. Due to which we are not able to pass all the testcase

#### Code you used for Submit/Run operation

'''
class Solution {
public:
    
    int eraseOverlapIntervals(vector<vector<int>>& intervals) {
        
        if(intervals.size()==0) return 0;
        sort(intervals.begin(),intervals.end(),[&](auto a, auto b){ return a[1]<b[1]; });
        int k = -1e9, ans = 0;
        for(auto a: intervals){
            int x = a[0], y = a[1];
            if(x>=k){
                k = y;
            }
            else ans++;
        }
        return ans;
    }
};'
'''

#### Language used for code
 C++

#### Expected behavior
 Atleast One iput should be there in the testcase

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35515322/d8ac3d61-74b7-4b58-905f-b13d72c77305)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, your code received TLE because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!

**Comment by RahulSurana123** [comment]
I would like you to try an empty testcase with no brackets or anything and run it you will find that validation of the testcase is not happening on that input which should not be the case 
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/35515322/941c4807-54b9-4de7-9aac-9660b5865a30)

Can you please add check on this kind of testcase
