### ISSUE TITLE
How to change the address for prizes?

### ISSUE THREAD

**Issue by Yawn-Sean** [LeetCode-Feedback/LeetCode-Feedback#14892]
I have moved to a different place last month, and I found some of my prizes are sent to my original place. I wonder how to change the address for prizes.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
