### ISSUE TITLE
Missing Test Case - 115. Distinct Subsequences

### ISSUE THREAD

**Issue by subodh-kasaudhan** [LeetCode-Feedback/LeetCode-Feedback#14901]
#### Your LeetCode username
shivamiitk

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
The last test case( 65th test case) is not visible and gives TLE

#### Code you used for Submit/Run operation

```
// 115. Distinct Subsequences

class Solution {
private:
int mod = 1e9 + 7;
    int rec(int ind1, int ind2, string s1, string s2, vector<vector<int> > &dp){
        if(ind2 == 0)return 1;
        if(ind1 == 0)return 0;
        if(dp[ind1][ind2] != -1)return dp[ind1][ind2];
        int Take = 0;
        if(s1[ind1 - 1]==s2[ind2 - 1]){
            Take = rec(ind1 - 1, ind2 - 1, s1, s2, dp);
        }
        int notTake = rec(ind1 - 1, ind2, s1, s2, dp);
        return dp[ind1][ind2] = (Take + notTake)%mod;
    }
public:
    int numDistinct(string s1, string s2) {
        int n1 = s1.size(), n2 = s2.size();
        if(n2 > n1)return 0;
        vector<vector<int> > dp(n1 + 1, vector<int>(n2 + 1, -1));
        return rec(n1, n2, s1, s2, dp);
    }
};
```

#### Language used for code
C++

#### Expected behavior
The last test case is not visible and shows as empty. This should not be considered as valid test case if the two string are of 0 length. So I assume that est cases are not visible to me. When I try "use Testcase" option then it gives All correct result but shows TLE when I submit for last test case.

#### Screenshots
![Screenshot (197)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75174930/a2c64825-7132-4a89-b6a9-cb4d83e9b36c)

![Screenshot (198)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/75174930/fbdce901-7cd3-41b6-879f-0bd09d401abc)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
