### ISSUE TITLE
CSS Bug

### ISSUE THREAD

**Issue by taurusdcruz** [LeetCode-Feedback/LeetCode-Feedback#14949]
#### Your LeetCode username:
zurCalleD_suruaT

#### Category of the bug:
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug:
There appears to be some css alignment issue in the scrollbar of the implementation code snippet for approach 3 in the editorial of [this](https://leetcode.com/problems/ternary-expression-parser/editorial/) problem.

#### Expected behavior:

When there are large number of languages in which the implementation is available in the editorial :-
- I should be able to see all the languages clearly. Right now I cant see the programming languages that are hidden past the width of the editor.
- The scrollbar and copy button alignment should not get distorted

####  Possible root cause:
I suspect it is happening when there are large number of programming languages tabs in which the implementation is available and the width of the tabs exceed the width of the editor . You can see the language - Typescript is truncated.

#### Possible resolution:
(i) Provide a horizontal scrollbar to scroll in case the implementation is available in a large number of programming languages.
(ii) Wrap the programming languages to a new line if the width of the programming languages overflows the width of the editor.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/20740303/26ac38b2-96c8-45d1-b178-094efb44fb7a)

#### Additional context

- I also created [this](https://leetcode.com/discuss/feedback/3802343/CSS-bug-in-leetcode) post describing the issue

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
