### ISSUE TITLE
Incorrect testcase

### ISSUE THREAD

**Issue by thakurnitesh27** [LeetCode-Feedback/LeetCode-Feedback#15159]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ Y] Missing Test Cases 

#### Description of the bug
 43/43 testcases passed but submission fails with empty testcase.See screenshot attached

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
     public double[] medianSlidingWindow(int[] nums, int k) {
           PriorityQueue<Integer> maxHeap=new PriorityQueue<>(Collections.reverseOrder());
        PriorityQueue<Integer> minHeap=new PriorityQueue<>();
        boolean even=true;

        double[] ans=new double[nums.length-k+1];
        int index=0;
        for(int i=0;i<k;i++){

            if(even){
                minHeap.offer(nums[i]);
                maxHeap.offer(minHeap.poll());
            }else {
                maxHeap.offer(nums[i]);
                minHeap.offer(maxHeap.poll());
            }
            even=!even;

        }


            if(even){
                ans[index++]=  (double)((double) ((double)minHeap.peek()+(double)maxHeap.peek()))/2;
            }
            else {
                ans[index++]=(double)maxHeap.peek();
            }

            for(int i=k;i< nums.length;i++){

                int numToRemove=nums[i-k];
                int numToAdd=nums[i];

              
             
                      if(! maxHeap.remove(numToRemove)){
                       minHeap.remove(numToRemove);
                       minHeap.add(numToAdd);
                   }else
                   maxHeap.add(numToAdd);
              //  }
                rebalance(maxHeap,minHeap);
               // even=!even;


                    if(maxHeap.size()==minHeap.size()){
                    ans[i-k+1]=(double) ((double)minHeap.peek()+(double)maxHeap.peek())/2;;
                }
                else {
                    ans[i-k+1]=(double)maxHeap.peek();
                }


            }

            return ans;

     }

      private void rebalance(PriorityQueue<Integer> maxHeap, PriorityQueue<Integer> minHeap) {
        if(minHeap.size()>0 && maxHeap.peek()<minHeap.peek()){
            while (maxHeap.size()<minHeap.size()){
                maxHeap.add(minHeap.poll());
            }
            while (maxHeap.size()>minHeap.size()+1){
                minHeap.add(maxHeap.poll());
            }

        }else {
            minHeap.add(maxHeap.poll());
            maxHeap.add(minHeap.poll());
        }
    }

   
}   
```

#### Language used for code
 Java

#### Expected behavior
It should either pass all or show which testcase resulted in failure.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/40829558/5f794bd5-2dbb-4287-b4d3-fb63ed1b668f)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
