### ISSUE TITLE
biweekly-contest-27 Q1 link is not working

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#15163]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Q1 link here
https://leetcode.com/contest/biweekly-contest-27/ranking/

is going to
https://leetcode.com/contest/biweekly-contest-27/problems/make-two-arrays-equal-by-reversing-sub-arrays/
it should go to
https://leetcode.com/contest/biweekly-contest-27/problems/make-two-arrays-equal-by-reversing-subarrays/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by manoharreddyporeddy** [comment]
Thanks. Created - https://support.leetcode.com/hc/en-us/requests/190495
