### ISSUE TITLE
Minor UI issue/bug in 'Tag' search filter

### ISSUE THREAD

**Issue by YogeshP93** [LeetCode-Feedback/LeetCode-Feedback#15368]
#### Your LeetCode username

Baymax_

#### Category of the bug
- [ ] Question
- [ x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

While submitting the solutions, we generally attach 'tags' to them. We have list of tags that we can select from, which also has a search filter associated with that list. But this has a minor bug.
When we use this search feature and let's say we type in 'string', it filters down to possible matches. But if we simply click anywhere 'out-side', this list gets hidden, the search text is cleared out in the search box, **_but_** the filtered search list still maintains its state and is not reverted. Meaning, when you open the search filter again, even when the text is cleared out, the list is still filtered, and it is little annoying to write something and clear it again to get the initial state of the tag list.

#### Expected behavior

The filtered tag list should also revert to its initial un-filtered state or should retain the previous search text when we click outside, to avoid any confusion.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/3265b25d-a9b5-4d27-8508-84ed5a6cdc00)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122779284/3fd09c74-2e7e-4ed8-8e8b-be46a09022cb)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by YogeshP93** [comment]
Thanks @LC-Pam , I have raised the same via above mentioned channel.
