### ISSUE TITLE
Missing Test Case - 912. Sort an Array

### ISSUE THREAD

**Issue by RedCrazyGhost** [LeetCode-Feedback/LeetCode-Feedback#15527]
> 若您之前未通过 GitHub 提交测试用例，原来在主站上提交的测试用例情况可通过 https://leetcode.cn/contribute/ 查看

**你的 LeetCode 用户名**
RedCrazyGhsot

**Bug 类型**
- [ ] 题目
- [ ] 题解
- [ ] 编程语言
- [X] 缺少测试用例

**描述**
提交代码后，显示无法通过21号用例，可能空的数组或者极大数组，无法通过添加测试用例进行测试

**你使用的语言**
Java

**你提交或者运行的代码**
```Java
 public int[] sortArray(int[] nums) {
        if (nums!=null) quickSort(0,nums.length-1,nums);
        return nums;
    }

    private void quickSort(int left,int right,int[] nums){
        if (left<right){
            int mid=partition(left,right,nums);
            quickSort(left,mid-1,nums);
            quickSort(mid+1,right,nums);
        }
    }

    private int partition(int left,int right,int[] nums){
        // 第一个作为基准参数
        int p=nums[left];
        while(left<right){
            while(left<right&&nums[right]>=p) right--;
            nums[left]=nums[right];
            while(left<right&&nums[left]<=p)++left;
            nums[right]=nums[left];
        }
        nums[left]=p;
        return left;
    }
```

**期望行为**
通过？
可进行用例测试

**屏幕截图**
<img width="701" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49381700/559d2b87-d6ed-4a65-b7fc-956e08759e54">

**额外的上下文**
添加额外的上下文信息

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission link since we received [Compile Error](https://leetcode.com/submissions/detail/1022385964/)after submit. 

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by RedCrazyGhost** [comment]
> Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:
> 
> The code submission link since we received [Compile Error](https://leetcode.com/submissions/detail/1022385964/)after submit.
> 
> We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

[Submit results](https://leetcode.com/problems/sort-an-array/submissions/1022762704/)

I tried to replicate the same problem using the OJ environment from Leetcode.com. No compilation issues occurred, but timeouts still occurred and we were unable to test the 21st test case.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
