### ISSUE TITLE
Suddenly emptied of accounts and banned for a year with no violations

### ISSUE THREAD

**Issue by jackielics** [LeetCode-Feedback/LeetCode-Feedback#15530]
Without violating any rules, I was suddenly deleted from LeetCode China. I just posted my own solutions and discussions on leetcode.cn and LeetCode.com at the same time, which did not violate any rules. Moreover, my LeetCode China account was banned and emptied during the Premium membership period, and all original questions and discussions were directly emptied without any notice, reminder or warning. Does LeetCode China disregard the rights and interests of users and members to such a degree?

Here's the link to my Leetcode China account：https://leetcode.cn/u/jackie-cs-b/，Please contact me as soon as possible and give a reasonable explanation! Otherwise your company will face lawsuits!
<img width="1267" alt="2023-08-12_200144" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/55891169/37c98740-84d1-4301-8100-3ae0e0db7505">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
