### ISSUE TITLE
Submission history is impossible to navigate

### ISSUE THREAD

**Issue by asarkar** [LeetCode-Feedback/LeetCode-Feedback#15600]
#### Your LeetCode username
number42

#### Category of the bug
Website error.

#### Description of the bug
Since the submission history alternates between white and gray rows, it is impossible to tell which row in highlighted when a gray row is selected. A white row shows a faint blue color. When there are many submissions, this makes it impossible to review the history one by one because as soon as a gray row is selected, you lose track of which submission you were looking into.

#### Code you used for Submit/Run operation
Not relevant.

#### Language used for code
Not relevant.

#### Expected behavior
Highlight the row using a stronger color that shows up over the gray background.

#### Screenshots
White row selected.
![white](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1302775/764496d6-c012-4cd3-a21d-15b4a362edc7)

Gray row selected.
![gray](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1302775/ef60d954-ee93-4308-bb5c-4b5218e64152)

As you can see, there's no visual difference between a gray row selected vs not selected.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by asarkar** [comment]
The support ticket link for reference.

https://support.leetcode.com/hc/en-us/requests/192633
