### ISSUE TITLE
239 Sliding Window Maximum

### ISSUE THREAD

**Issue by tonytang0909-grl** [LeetCode-Feedback/LeetCode-Feedback#15627]
#### Your LeetCode username

TonyTang99

#### Category of the bug
- [1] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I have passed all the test cases, but still got an Limit Time exceeded error.
Please help me take a look at my code and solution. Thanks a lot for the help

#### Code you used for Submit/Run operation

```
public int[] maxSlidingWindow(int[] nums, int k) {

        if (nums == null || k == 0) {
            return new int[0];
        }
        //dp[i] = 
        int len = nums.length;
        if (len == 1) {
            return nums;
        }
        
        if (k == len) {
            int max = Integer.MIN_VALUE;
            for (int num : nums) {
                max = Math.max(max, num);
            }
            return new int[]{max};
        }
        int[] dp = new int[len - k + 1];
        for (int i = 0; i < k; i++) {
            dp[0] = Math.max(dp[0], nums[i]);
        }
        //dp[0] = Math.max(Math.max(nums[0], nums[1]), nums[2]);
        for (int i = 1; i < len - k + 1; i++) {
            if (nums[i - 1] == dp[i - 1]) {
                dp[i] = findMax(nums, i, k);
            } else {
                dp[i] = Math.max(dp[i - 1], nums[i + k - 1]);
            }
        }
        return dp;
    }

    private int findMax(int[] arr, int start, int len) {
        int max = arr[start];
        for (int i = start + 1; i < start + len; i++) {
            max = Math.max(arr[i], max);
        }
        return max;
    }
```

#### Expected behavior

I have passed all the test cases within the time limit. Should have been accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
