### ISSUE TITLE
 201. Bitwise AND of Numbers Range...Submission error

### ISSUE THREAD

**Issue by VedantRawale** [LeetCode-Feedback/LeetCode-Feedback#15624]
#### Your LeetCode username

 vedant_rawale

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

201 . Bitwise AND of Numbers Range

My solution is passing all the 8269/8269 testcases after submitting but still it is showing a bug of a 
type of empty testcase giving TIME LIMIT EXCEEDED while no such testcase is valid as per the constraints.

#### Code you used for Submit/Run operation

```
// Bitwise AND of Numbers Range
class Solution {
public:
    int rangeBitwiseAnd(int left, int right) {
        int ans = left;
        int i = left;
        if(left==0 && right==0) return 0;
        while(ans && i<right){
            ans&=i;
            i++;
        }
        if(i==right) return ans&right;
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Expected to be able to submit the code successfully for my solution which is correct !
But what I realized that it is a bug as some solutions are being accepted while some are 
being stuck for no reason...

#### Screenshots

![Screenshot (51)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122515373/bdd7dcd1-36f4-4685-8e19-6199583bc12b)

![Screenshot (52)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/122515373/05bd6965-fd1c-4708-b5a6-e68d70f22474)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
