### ISSUE TITLE
Missing Test Cases1466. Reorder Routes to Make All Paths Lead to the City Zero

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#15632]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310/)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

For this problem, I studied the fastest submission but found out it used the order of inputs to get `Accepted`.

Here is the idea: for each edge, it adds to the queue if no vertex is visited. It iterates over the queue and counts the result until it is empty.  The worst case time complexity, obviously is O(E^2), as we may only update one edge with one visited vertex each time and push the remaining edges back to the queue. The tricky part is, that it reverses the visit order of the queue after it adds unvisited edges the first time. So when a test case like [0, 1] [3, 4] [2, 3] [1, 2] is tested, it will run fast like O(E).

How did I prove my assumption? I randomly switched the order of some edges in the input, and this solution got TLE with 
75 / 76 test cases passed. Even if I reduce the random pairs size to just 50, it still got TLE. The correct solution passed the test case even with random switched input.

Actually, this is the second time I found out that the fastest submission sometimes should not be fast in theory. Like the first problem, `1. Two Sum`. You can get pretty fast results if you iterate the difference between the pairs first in a two-loop O(n^2) solution. I assume this is because the test cases have many cases with the pair placed at [n-2, n-1], so the O(n^2) solution runs faster than the real O(n) hash map solution which needs extra operations.

But the two sum problem you can still pass with O(n^2) method. For this problem, the situation is much worse. The 'fastest' solution got TLE just after rearranging the order of input.

I found some other submissions with the same time cost using two stacks. The idea is similar. I think they would also fail the test if the input has a structure like [0, 1] [3, 4] [1, 2] [4, 5] [2, 3] or just some random order.

#### Code you used for Submit/Run operation

```Java
class Solution {
    public int minReorder(int n, int[][] arr) {
        boolean[] visited = new boolean[n];
        visited[0] = true;
        LinkedList<int[]> q = new LinkedList<>();
        int count = 0;
        // Rearrange the input order 
        Random rand = new Random();
        for (int i = 0; i < 50; i++) {
            int l = rand.nextInt(n - 1);
            int r = rand.nextInt(n - 1);
            int[] temp = arr[l];
            arr[l] = arr[r];
            arr[r] = temp;
        }
        for (int[] a : arr) {
            // System.out.println(Arrays.toString(c));
            if (visited[a[0]]) {
                ++count;
                visited[a[1]] = true;
            } else {
                
                if (visited[a[1]]) {
                    visited[a[0]] = true;
                } else {
                    q.add(a);
                }
            }
        }
        while (!q.isEmpty()) {
            int[] a = q.pollLast();
            if (visited[a[0]]) {
                ++count;
                visited[a[1]] = true;
            } else {
                
                if (visited[a[1]]) {
                    visited[a[0]] = true;
                } else {
                    q.addFirst(a);
                }
            }
        }
        return count;
    }
}
```

#### Language used for code

Java

#### Expected behavior

If this solution has no problem, it should pass the test after random switches. But it got TLE for last test case now.

#### Screenshots

![Screenshot 2023-08-16 002947](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/3740139/3d98c6c2-bd47-4df6-b54a-cf2bca9dc531)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. Currently, the code received TLE after submission: https://leetcode.com/submissions/detail/1023361624/
The same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Ming91** [comment]
https://leetcode.com/submissions/detail/1023465394/

Thanks for your reply. This is the AC submission link after I deleted the `random switch` part. It just goes faster than any other solution. I think you will get the TLE result if manually change the order of input in the last test case.

How could a reasonable solution pass with just 4ms and then get TLE after I just add a 50-reps loop?

**Comment by LC-Pam** [comment]
The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.

**Comment by Ming91** [comment]
[testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/12387341/testcase.txt)

I understand what you mean by the `runtime variation`. Please try to understand this problem and the structure of the test case. Could you try to use this test case? I shuffled the last test case that has 50000 entries. It failed when I used the code in the AC submission (https://leetcode.com/submissions/detail/1023465394/).

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
