### ISSUE TITLE
Bug : Not showing failed Testcase in submitted tab

### ISSUE THREAD

**Issue by bansal3103** [LeetCode-Feedback/LeetCode-Feedback#15802]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation
```class Solution {
    static boolean finding(int m,int n,int currRow, int currCol, String word, int len,int idx,char[][] board){
        if(idx==len){
            return true;
        }
        char c=word.charAt(idx);
        if(idx==0){
            for(int i=0;i<m;i++){
                for(int j=0;j<n;j++){
                    if(board[i][j]==c){
                        board[i][j]='0';
                        boolean subAns=finding(m,n,i,j,word,len,idx+1,board);
                        board[i][j]=c;
                        if(subAns==true){
                            return true;
                        }
                    }
                }
            }
            return false;
        }else{
            for(int i=currRow-1;i<=currRow+1;i++){
                if(i==currRow || i<0 || i>=m){
                    continue;
                }else if(board[i][currCol]==c){
                    board[i][currCol]='0';
                    boolean subAns=finding(m,n,i,currCol,word,len,idx+1,board);
                    board[i][currCol]=c;
                    if(subAns==true){
                        return true;
                    }
                }
            }
            for(int j=currCol-1;j<=currCol+1;j++){
                if(j==currCol || j<0 || j>=n){
                    continue;
                }else if(board[currRow][j]==c){
                    board[currRow][j]='0';
                    boolean subAns=finding(m,n,currRow,j,word,len,idx+1,board);
                    board[currRow][j]=c;
                    if(subAns==true){
                        return true;
                    }
                }
            }
            return false;
        }
    }
    public List<String> findWords(char[][] board, String[] words) {
        List<String> res=new ArrayList<String>(0);
        int m=board.length;
        int n=board[0].length;
        int wordsLen=words.length;
        for(int i=0;i<wordsLen;i++){
            String word=words[i];
            int len=word.length();
            boolean subAns=finding(m,n,0,0,word,len,0,board);
            if(subAns==true){
                res.add(word);
            }
        }
        return res;
    }
}
```

#### Language used for code
Java

#### My above code gave TLE but when i clicked on the button ' Use testcase '  it didn't work , later i tried copying the testcase from the submissions tab but it didn't showed up there. Please fix this asap.

Problem number 212 ( Word Search II )
Link to that  submission : https://leetcode.com/problems/word-search-ii/submissions/1028460253/

![Screenshot (190)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/126455936/227e6575-6b23-4bf8-a662-947b1d49ae2f)

**Comment by LC-Pam** [comment]
The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variations.

When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
