### ISSUE TITLE
There is a glitch when changing from the new version to old version.

### ISSUE THREAD

**Issue by ANUKULJHA1506** [LeetCode-Feedback/LeetCode-Feedback#15839]
#### Your LeetCode username
user5333h

#### Description of the bug
when changing from new version to old version of website , there is  a stutter faced on the monitor  screen.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
