### ISSUE TITLE
Premium video content isn't captioned

### ISSUE THREAD

**Issue by ifjorissen** [LeetCode-Feedback/LeetCode-Feedback#15852]
#### Your LeetCode username
oh_bells

#### Category of the bug
- [ ] Question
- [ ] Solution
- [X] Language
- [ ] Missing Test Cases 

#### Description of the bug
None of the videos in the _premium_ content (the explore cards, editorial solutions, etc) are captioned!

I rely on captions to understand video content (especially if there isn't a clear picture of the speaker's lips). 

I subscribed to premium for in-depth explanations, and in many cases, the explanation is in the video and not written anywhere. I haven't found transcriptions for the videos, either. Can LeetCode's premium content be made more accessible so that paying folks who are Deaf and/or hard of hearing can learn too?

e.g., https://leetcode.com/explore/learn/card/graph/619/depth-first-search-in-graph/3847/

#### Additional Context
I see there have been requests for this for over 1 year (https://leetcode.com/discuss/feedback/1943439/captions-on-videos), but there has been no update that I am aware of.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The video works correctly, please check your browser settings.

![Screen Shot 2023-08-24 at 1 40 01 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103138242/d0cb9017-95b0-43a1-aaf2-0824113cbb36)


If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!

**Comment by ifjorissen** [comment]
Sorry, where is the button or setting to enable captions in that image?

**Comment by LC-Pam** [comment]
Hi there,
 
Thank you for bringing this matter to our attention and for sharing your concerns regarding the accessibility of LeetCode's premium content. Your feedback is greatly valued, and I apologize for any frustration or disappointment you may have experienced.
 
First and foremost, I want to apologize for the lack of captions or transcriptions for some of our premium content videos and editorial materials. Your point about the importance of accessibility for the d/Deaf and hard-of-hearing communities is absolutely valid, and we fully acknowledge that everyone should have equal opportunities to learn, especially when they are paying for our premium content.
 
"It's really disheartening to see that none of LeetCode's premium content videos or editorial content have captions or video transcriptions available." This is not true.
 
For some premium editorial content, we do have captions on the editorial content, please explore more:
 
https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/solution/
 
https://leetcode.com/problems/reverse-words-in-a-string-ii/solution/
 
https://leetcode.com/problems/shortest-word-distance-ii/solution/
 
https://leetcode.com/problems/meeting-rooms-ii/solution/
 
https://leetcode.com/problems/find-leaves-of-binary-tree/solution/
......
 
I deeply apologize for the closure of your issue on our LeetCode Feedback GitHub without proper consideration. This was an oversight, and I assure you that we are actively working to improve our internal processes to ensure that every user's feedback is treated with the attention and respect it deserves.
 
Regarding the lack of captions in some of our premium content videos, I want to explain the current situation. We utilize a third-party video player to host our content, and adding captions to these videos requires coordination with the content authors. Unfortunately, the automatic subtitle function provided by the third-party video player has been canceled, which has made the process more complex. 
 
We completely agree with you that captions should be available for all users, and we're actively working to address this issue. However, I want to be transparent about the fact that implementing captions will take some time due to the need to involve content authors and find the best way to provide accurate and meaningful captions.
 
We're committed to taking the necessary steps to ensure that captions are provided for all premium content videos and editorial materials. Your patience and understanding as we work through these changes are greatly appreciated.
 
The Leetcode Team

**Comment by LC-Pam** [comment]
Hi there,
 
Thank you for bringing this matter to our attention and for sharing your concerns regarding the accessibility of LeetCode's premium content. Your feedback is greatly valued, and I apologize for any frustration or disappointment you may have experienced.
 
First and foremost, I want to apologize for the lack of captions or transcriptions for some of our premium content videos and editorial materials. Your point about the importance of accessibility for the d/Deaf and hard-of-hearing communities is absolutely valid, and we fully acknowledge that everyone should have equal opportunities to learn, especially when they are paying for our premium content.
 
"It's really disheartening to see that none of LeetCode's premium content videos or editorial content have captions or video transcriptions available." This is not true.
 
For some premium editorial content, we do have captions on the editorial content, please explore more:
 
https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/solution/
 
https://leetcode.com/problems/reverse-words-in-a-string-ii/solution/
 
https://leetcode.com/problems/shortest-word-distance-ii/solution/
 
https://leetcode.com/problems/meeting-rooms-ii/solution/
 
https://leetcode.com/problems/find-leaves-of-binary-tree/solution/
......
 
I deeply apologize for the closure of your issue on our LeetCode Feedback GitHub without proper consideration. This was an oversight, and I assure you that we are actively working to improve our internal processes to ensure that every user's feedback is treated with the attention and respect it deserves.
 
Regarding the lack of captions in some of our premium content videos, I want to explain the current situation. We utilize a third-party video player to host our content, and adding captions to these videos requires coordination with the content authors. Unfortunately, the automatic subtitle function provided by the third-party video player has been canceled, which has made the process more complex. 
 
We completely agree with you that captions should be available for all users, and we're actively working to address this issue. However, I want to be transparent about the fact that implementing captions will take some time due to the need to involve content authors and find the best way to provide accurate and meaningful captions.
 
We're committed to taking the necessary steps to ensure that captions are provided for all premium content videos and editorial materials. Your patience and understanding as we work through these changes are greatly appreciated.
 
The Leetcode Team

**Comment by ifjorissen** [comment]
Hi,

Thanks for the quick reply, a few follow-up questions... mostly curious if there are ways to make it easier to find the content that _is_ captioned while the longer-term process of captioning everything is in progress.

re: the editorial solutions for problems, thanks for sharing those. One possible request-- is there a possibility of adding a "captioned" tag to problems that have captions in their solutions? (Especially if it is not the majority of them?) Many problems also have other category tags e.g., "backtracking", "BFS" etc.

1) Are there any videos in the Explore section that have captions? I haven't been able to find any.
2) Do you know approx. what % of videos include captions or transcripts? Is there any way to surface those more easily?
3) Is there a timeline for when videos might be updated with captions? It looks like there was a request about this a year ago (https://leetcode.com/discuss/feedback/1943439/captions-on-videos). I am a longtime user of Leetcode and would love to be updated when e.g., the Graphs Explore cards are updated with captions.
