### ISSUE TITLE
Empty Test Case TLE - 146. LRU Cache 

### ISSUE THREAD

**Issue by 0x87c0** [LeetCode-Feedback/LeetCode-Feedback#15929]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
My code TLE's on test case 22. However, the testcase appears to be empty.

#### Code you used for Submit/Run operation

```
using System.Collections.Generic;
public class LRUCache {

    Dictionary<int, int[]> cache = new Dictionary<int,int[]>();
    int cap;
    int cnt;
    int lru;
    int mru;
    public LRUCache(int capacity) {
        cap = capacity;
        cnt = 0;
        cache[-1] = new int[]{-1, -1, -1};
    }
    
    public int Get(int key) {
        try {
            int val = cache[key][1];
            if(key != mru) {
                Put(key, val);
            }
            return val;
        }
        catch (KeyNotFoundException e) {
            return -1;
        }
    }
    
    public void Put(int key, int value) {
        if (cnt == cap && !cache.ContainsKey(key) && cap > 1) {
            //return;
            int[] lruVal = cache[lru];
            cache.Remove(lru);
            lru = lruVal[2];
            cache[lru][0] = -1;
            cache[mru][2] = key;
            cache[key] = new int[]{mru, value, -1};
            mru = key;
        } else if (cnt == 0 || cap == 1) {
            if (cnt > 0) { cache.Remove(lru); }
            cache[key] = new int[]{-1, value, -1};
            lru = key;
            mru = key;
            cnt = 1;
        } else {
            if(key == mru) {
                cache[key][1] = value;
                return;
            } else if (cache.ContainsKey(key)) {
                if (key == lru) {
                    lru = cache[key][2];
                }
                cache[cache[key][0]][2] = cache[key][2];
                cache[cache[key][2]][0] = cache[key][0];
                cnt--;
            }
            cache[mru][2] = key;
            cache[key] = new int[]{mru, value, -1};
            mru = key;
            cnt++;
        }
    }
}

/**
 * Your LRUCache object will be instantiated and called as such:
 * LRUCache obj = new LRUCache(capacity);
 * int param_1 = obj.Get(key);
 * obj.Put(key,value);
 */
```

#### Language used for code
C#

#### Expected behavior
Either the code should not TLE, or it should return a non-empty testcase so I can further debug why my code doesn't work on that particular testcase.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/123863198/9e12a6e7-353d-44ad-871d-0639ad0a6b00)

#### Additional context
Even clicking "Use Testcase" adds an empty testcase to my tests.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, your code received TLE after submission: https://leetcode.com/submissions/detail/1043266495/. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
