### ISSUE TITLE
Two Sum - BufferOverflow occurring?

### ISSUE THREAD

**Issue by mgrove-wwu** [LeetCode-Feedback/LeetCode-Feedback#16]
**What kind of the bug**
- [x] problem
- [ ] solution

**Describe the bug**
The bug seems to be a buffer overflow...

I attached a screenshot for u guys. Should include all important info.

**The code you submit/run**
```
class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        
        vector<int> arr (2);
        
        for (int i = 0; i < sizeof(nums); i++) {
            
            if (int x = nums[i]; x < target) {
                for (int j = i; j < sizeof(nums); j++)
                    
                    if (int y = nums[j]; y < target) {
                        if (x + y == target) {
                            string solution = "Solution found:" + std::to_string(x) + ";" + std::to_string(y);
                            cout << solution;
                            arr[0] = i;
                            arr[1] = j;
                            break;
                        }
                    }
                    else {
                        break;
                    }
            }
            else {
                break;
            }
        }
        
        return arr;
    }
};
```

**Expected behavior**
Should accept my submitted solution.

**Screenshots**
Screenshot attached

**Additional context**
I dont know that much about computers :p
![Anmerkung 2020-03-06 172229](https://user-images.githubusercontent.com/22619113/76102146-d7b42d80-5fcf-11ea-8ca7-5492faa7c51e.png)

**Comment by CooperCooperCooper** [comment]
Hi @mgrove-wwu,

Address sanitizer errors mean that during C/C++ runtime it caught invalid memory access in the program and this most commonly caused by an out of bounds array index access. 

To give you some inspiration on overcoming this error, please check out this post: https://leetcode.com/problems/two-sum/discuss/449565/Easy-to-understand-C%2B%2B-Soution-0ms-beats-100.

Hope this helps! We appreciate your time and patience. If you have any other questions, please don't hesitate to let us know.

**Comment by mgrove-wwu** [comment]
Hi @CooperCooperCooper,
Thank you for the fast feedback! Appreciate the help.

Sincerely, Max
