### ISSUE TITLE
All testcases pass but solution is not accepted. 

### ISSUE THREAD

**Issue by sanketwadekar** [LeetCode-Feedback/LeetCode-Feedback#16075]
#### Your LeetCode username
sanketmw

#### Category of the bug
- [ ☑️ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

For question no. [494](https://leetcode.com/problems/target-sum/), my solution passes all testcases (140/140) when I submit it but shows `Time Limit Exceeded` on UI.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    int findTargetSumWays(vector<int>& nums, int target) {
        int n = nums.size();
        if (!n) {
            return 0;
        }
        vector<vector<vector<int>>> dp(n, vector<vector<int>>(2));

        dp[n - 1][0].push_back(nums[n-1]);
        dp[n - 1][1].push_back(-1 * nums[n-1]);

        for (int i = n - 2; i >= 0; i--) {
            vector<int>store_result;
            for (auto j: dp[i + 1][0]) {
                dp[i][0].push_back(nums[i] + j);
            }
            for (auto j: dp[i + 1][1]) {
                dp[i][0].push_back(nums[i] + j);
            }
            for (auto j: dp[i + 1][0]) {
                dp[i][1].push_back(-1 * nums[i] + j);
            }
            for (auto j: dp[i + 1][1]) {
                dp[i][1].push_back(-1 * nums[i] + j);
            }
            // printing
            // cout <<"dp["<<i<<"][0]\n";
            // for (auto k: dp[i][0]) {
            //     cout<<k<<" ";
            // }
            // cout << endl;

            // cout <<"dp["<<i<<"][1]\n";
            // for (auto k: dp[i][1]) {
            //     cout << k << " ";
            // }
            // cout << endl;
        }
        int count = 0;
        for (auto k: dp[0][0]) {
            if (k == target) {
                count++;
            }
        }
        for (auto k: dp[0][1]) {
            if (k == target) {
                count++;
            }
        }
        return count;
    }
};
```

#### Language used for code
C++

#### Expected behavior

Solution should get accepted or else the test-case for which "Time Limit Exceeded" error occurs should be clearly visible.

#### Screenshots

<img width="704" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/67091512/0af0ebd3-4d06-4c43-84c8-c63257ed4c0a">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
