### ISSUE TITLE
Weekly premium UI bug

### ISSUE THREAD

**Issue by nineonine** [LeetCode-Feedback/LeetCode-Feedback#16090]
#### Your LeetCode username

dnox (https://leetcode.com/dnox/)

I noticed some UI defect on the Problems page. Specifically, the "weekly premium" widget would render incorrect countdown time.
This happened exactly at the end of the month.

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8581663/35645e7c-4bb2-4325-ae19-042e4318b9a9)

Next day it was fine

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/8581663/25bd1dc0-3cf4-4156-b0ce-2625099e0992)

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the issue. 

This is expected behavior as the countdown is in UTC while the user is probably in some north american timezone.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
