### ISSUE TITLE
Incorrect Day - Day 17 being shown on HomePage on 04/19

### ISSUE THREAD

**Issue by NishadKumar** [LeetCode-Feedback/LeetCode-Feedback#161]
Day 17 is being shown currently for the 30 Day challenge. I thought it was Day 19 today(04/19/20).

<img width="653" alt="Screen Shot 2020-04-19 at 8 15 31 PM" src="https://user-images.githubusercontent.com/18685836/79705222-8a87d480-827a-11ea-993c-77c4268241cc.png">

**Comment by CooperCooperCooper** [comment]
Hi @NishadKumar,
Thank you for raising this issue to our attention! This issue has been fixed. Since this Github Channel is for content issues only (you may check out what issues should be filed here by clicking on [this post](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!) ), we will be closing this ticket now.

**Comment by NishadKumar** [comment]
Thanks for the response @CooperCooperCooper. My bad for using this platform.

**Comment by CooperCooperCooper** [comment]
Hi @NishadKumar,
No worries! You can always file this kind of issue to our main support channel: support@leetcode.com. We look forward to seeing more of your submissions in the future :)
