### ISSUE TITLE
interview-crash-course-data-structures-and-algorithms contains premium question(s)

### ISSUE THREAD

**Issue by etischler** [LeetCode-Feedback/LeetCode-Feedback#16119]
#### Your LeetCode username

etischler

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Bonus question in Stacks contains premium question:
https://leetcode.com/explore/interview/card/leetcodes-interview-crash-course-data-structures-and-algorithms/706/stacks-and-queues/4708/
https://leetcode.com/problems/number-of-valid-subarrays/

#### Expected behavior

Paid product shouldn't list premium locked questions or they should be unlocked as part of paid product

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
