### ISSUE TITLE
Contest problems are not in the same problem list anymore

### ISSUE THREAD

**Issue by Ming91** [LeetCode-Feedback/LeetCode-Feedback#16137]
#### Your LeetCode username

[wming9310](https://leetcode.com/wming9310)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I noticed LeetCode upgraded the UI layout this September. And I found a useful feature that is missing after the weekly contest this weekend.  The problems of the contest used to be in the same problem list when you clicked the "Discuss" button on the contest page. The top left corner just shows "Problem List" right now, which is used to show "Weekly Contest xxx" when you visit the problem from the contest page. In the past, I could easily track all the problems in the same contest without going back to the contest page every time.  The contest page is good for the contest. But for reviewing the problems, the normal page has more convenient features.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
