### ISSUE TITLE
30. Substring with Concatenation of All Words (testcase parameter missing) 

### ISSUE THREAD

**Issue by Harshil0309** [LeetCode-Feedback/LeetCode-Feedback#16173]
harshil_gupta

#### Category of the bug
- [x] Missing Test Cases 

#### Description of the bug

 I was attempting the 30th question on leetcode (https://leetcode.com/problems/substring-with-concatenation-of-all-words/description/) , when I submitted my solution it is showing that it gave TLE and it is written that 179/179 testcases are passed , the testcase in which it gave TLE is totally empty which should be an invalid testcase according to the constraints . I am attaching the screenshot for your reference.

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool validSubstring(string t,unordered_map<string,int> mp,int len){
      // cout<<t<<endl;
			for(int i=0;i+len<=t.size();i=i+len){
				// cout<<i<<endl;
				string temp=t.substr(i,len);
				// cout<<temp<<endl;
				if(mp.find(temp)!=mp.end()){
					--mp[temp];
					if(mp[temp]<0){
						// cout<<temp<<endl;
						return false;
					}
				}else{
					return false;
				}
				
				// cout<<"hihi"<<endl;
			}
			return true;
		}

    vector<int> findSubstring(string s, vector<string>& words) {
        int wordLen=words[0].size();
				unordered_map<string,int> mp;
				for(int i=0;i<words.size();++i){
					mp[words[i]]++;
				}

				int i=0;
				int totalsize=wordLen * words.size();
				// cout<<totalsize<<endl;
				vector<int> ans;
				while(i+totalsize<=s.size()){
					string temp=s.substr(i,totalsize);
					// cout<<temp<<endl;
					if(validSubstring(temp,mp,wordLen)){
						ans.push_back(i);
					}
					++i;
				}
				return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code should have been submitted 179/179 were passed but it gave TLE

#### Screenshots

![Screenshot (212)](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/91473777/9a2506e6-4f89-4aac-8494-e4b4acbbef5b)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us,your code received TLE after submission. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
