### ISSUE TITLE
Missing Test Case - 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by Insomniac2904** [LeetCode-Feedback/LeetCode-Feedback#16213]
#### Your LeetCode username
username : adarsh_7478

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug

In testcase 141 the string is notdefined/null;

#### Code you used for Submit/Run operation

```
class Solution {
public:
    bool checkPal(string s){
        int i=0,j=s.size()-1;
        while(i<j){
            if(s[i]!=s[j]){
            return false;
            }
            i++;j--;
        }
        return true;
    }
    string longestPalindrome(string s) {
        int n=s.size();
        if(n==0) return "";
        string maxPal="";
        for(int i=0;i<n;i++){
            int j=n-1;
            for(j;j>=i;j--){
                while(j>i){
                    if(s[j]==s[i]){
                        break;
                    }
                    j--;
                }
                string k = s.substr(i,j-i+1);
                // cout<<k<<endl;
                bool check=checkPal(k);
                // cout<<check<<endl;
                if(check){
                    if(k.size()>maxPal.size()){
                        maxPal=k;
                    }
                }
            }
        }
        return maxPal;
    }
};
```

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/109868197/6ebfedc2-4429-4581-9cb3-6e1a83a68071)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, your code received TLE after submission: https://leetcode.com/submissions/detail/1041601682/. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
