### ISSUE TITLE
Solution is not submitting

### ISSUE THREAD

**Issue by udilbar** [LeetCode-Feedback/LeetCode-Feedback#16211]
#### Your LeetCode username

UDN

#### Category of the bug
- [ ] Question
- [ +] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

When I submit my solution, I get "Time Limit Exceeded" error. And when I submit it again without changing anything in my code, it works. I had such kind of situation twice in two different problems.

#### Code you used for Submit/Run operation

```
/**
 * // Definition for a Node.
 * function Node(val, next, random) {
 *    this.val = val;
 *    this.next = next;
 *    this.random = random;
 * };
 */

/**
 * @param {Node} head
 * @return {Node}
 */
var copyRandomList = function(head) {
    if (!head) return null;
    
    let map = new Map(), curr = head;

    while(curr) {
        let clone = new Node(curr.val);
        map.set(curr, clone);
        curr = curr.next;
    }

    curr = head;
    while(curr) {
        let clone = map.get(curr);
        clone.next = map.get(curr.next) || null;
        clone.random = map.get(curr.random) || null;
        curr = curr.next;
    }

    return map.get(head);
};
```

#### Language used for code

JavaScript

#### Expected behavior

The solution I have provided must be submitted without any error. But I got "Time Limit Exceeded".

#### Screenshots

[Bug](https://photos.app.goo.gl/AL74dbYz4N9Wmm1Y6)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
