### ISSUE TITLE
2293. Min Max Game [Rust]

### ISSUE THREAD

**Issue by RiadhAdrani** [LeetCode-Feedback/LeetCode-Feedback#16568]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug
The compilers always yells at me saying that my function is not found (when called recursively), tried it in the Rust playground and it works fine, this is my code .

#### Code you used for Submit/Run operation
```rust
impl Solution {
    pub fn min_max_game(nums: Vec<i32>) -> i32 {
        let mut result = nums[0];
        
        if nums.len() > 1 {
            let mut new_nums : Vec<i32> = vec![];

            for i in 0..nums.len()/2 {
                let n1 = nums[i * 2];
                let n2 = nums[i * 2 + 1];

                let mut entry : i32 = if i % 2 == 0 {n1.min(n2)} else {n1.max(n2)};

                new_nums.push(entry);
            }

            result = min_max_game(new_nums);
        }

        result
    }
}
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
Rust

#### Expected behavior
Should compile and work, as I mentioned earlier it works in the playground.

#### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/54232641/3b10e723-198e-43e4-8e7e-cf7ce7ae06d2)

Thanks.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The problem here is that you are trying to make a recursive call to the min_max_game function, but the function is not defined in the current scope. To fix this issue, you need to specify the full path to the function, including the module it belongs to (if applicable).

Assuming that min_max_game is defined within the same module, you should replace the recursive call with Self::min_max_game(new_nums):

https://leetcode.com/submissions/detail/1055706960/

Unfortunately, we are unable to troubleshoot the different behavior between your Rust playground and the LeetCode environment.

For this issue, please raise this as a discussion post in the problem discussion section as other users may have run into the same issue and resolved it.

We appreciate your time and support.
