### ISSUE TITLE
Leetcode web app consistently fires request to sockets.leetcode.com but this URL has no DNS record at all

### ISSUE THREAD

**Issue by Meowzz95** [LeetCode-Feedback/LeetCode-Feedback#16560]
#### Your LeetCode username

jjzzzmd

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Web App (sorry I don't find other place to feedback this, and I hope this issue can be found by others searching too)

#### Description of the bug

Leetcode web app consistently fires request to sockets.leetcode.com but this URL has no DNS record at all. Why is the web app doing this? 

<img width="1110" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22430379/c84afe76-ad94-43f2-a55f-b7109d22d823">
<img width="880" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/22430379/c6526834-4543-4ba6-9665-279b2fb5ca95">

#### Expected behavior

Leetcode web app should stop calling this

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
