### ISSUE TITLE
every time passes all the test, it become faster than 100% and less memory than 100% 

### ISSUE THREAD

**Issue by Calls4ever** [LeetCode-Feedback/LeetCode-Feedback#1659]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@Calls4ever Please provide the code and the issue. Thank you!

**Comment by lc-kay** [comment]
Hi @Calls4ever 
Thank you again for reaching out to us previously! Since we have not heard from you for a while, I will close this ticket for now. If you have more information to add to this issue, please tag me in a new comment. Thank you.

**Comment by Calls4ever** [comment]
Thank you so much for closing that ticket for me, as if you are doing favor
for me!!
And plus are customer supposed to find the root of problem and help the
company to solve it for free?? Good luck Leetcode, i am loving it and i
will buy premium membership immediately!

**Comment by lc-pam** [comment]
Hi @Calls4ever , thank you for your feedback! For valid content-issues, LeetCode provides LeetCoins rewards for the users, and we truly thank the user's contribution. I'm sorry that we are not able to understand the issue you raised because of the lack of information, and that's why our customer support asked for more details 6 days ago. We apologize if it makes you feel like not being supported. Would you mind providing more details on the issue you raised?
