### ISSUE TITLE
Improvement to New UI

### ISSUE THREAD

**Issue by raghavrambo007** [LeetCode-Feedback/LeetCode-Feedback#16666]
Can you make the new UI testcases/results tab to open up automatically when we click run/submit button? Like it used to open up automatically and occupy half of the left screen before?
It is so annoying to place my cursor manually and drag up that pane everytime I click run/submit?
Or atleast add a shortcut to open that up to the half of the screen?

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
