### ISSUE TITLE
Unexpected behavior of site

### ISSUE THREAD

**Issue by vivekiet22** [LeetCode-Feedback/LeetCode-Feedback#16686]
#### Your LeetCode username
vivekiet22

#### Category of the bug

- [ ] Unexpected behavior of site

#### Description of the bug
when I click on any solution of any problem with ctrl, it opens on a new tab and the same page as well

#### Expected behavior
It should open in the same tab when clicked without **ctrl** 
and open in new tab when clicked with **ctrl**

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
