### ISSUE TITLE
chrome not responding while applying fiters

### ISSUE THREAD

**Issue by SubhadipKundu1999** [LeetCode-Feedback/LeetCode-Feedback#16771]
#### Your LeetCode username
subhadipkundu_2cr

#### Category of the bug
website 

#### Description of the bug
whenever I trying to filter problems based on dificulty. chrome is not responding for  a while.

#### Screenshots

<img width="960" alt="Screenshot 2023-09-28 220229" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/110739434/19a671f6-7322-4d32-8e35-ab2f3a144491">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
