### ISSUE TITLE
Bump Go version from 1.18 to Latest

### ISSUE THREAD

**Issue by rajenderK7** [LeetCode-Feedback/LeetCode-Feedback#16798]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

The `Go` version on the Leetcode server is still 1.18 however, Go has brought some great changes in the standard library in the latest versions. One example is the `math` module, where the functions have become generic giving an easier and faster api than the current `Go` version leetcode is running.

#### Language used for code

Go

#### Additional context

Upgrading the Go version to the latest minor version will solve the problem.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/Product/Vision feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
