### ISSUE TITLE
diff in running tests is 150%

### ISSUE THREAD

**Issue by andreev-max** [LeetCode-Feedback/LeetCode-Feedback#16797]
#### Your LeetCode username
andreev-dev

#### Category of the bug
- [ ] Question
- [ ] Solution

#### Description of the bug
Don’t know what type of issue this one. So could you please check my 2 submissions:
https://leetcode.com/submissions/detail/1062766488/
https://leetcode.com/submissions/detail/1062765433/
The code snippets in both submissions are the same and I submitted the second one in 2 minutes ( when I found out that the fastest solution is the same as mine)
And I have plenty of such examples. So I submit my solution and I beat 10-30% of other users solutions, but other faster solutions either worse or the same.
And when I resubmit in 2 minutes my submission gets faster without any changes.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
TypeScript

#### Expected behavior
I understand that maybe it is even impossible to run all tests for the same amount of time, but inaccuracy might be 10-20% but not > 50%
Maybe it is just because I am not a premium user, idk

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this helps. Should you have any other questions, please let us know.

Regards,

LC_Pam
