### ISSUE TITLE
Missing Test Case - 743. Network Delay Time

### ISSUE THREAD

**Issue by ArshiaAggarwal749** [LeetCode-Feedback/LeetCode-Feedback#16790]
#### Your LeetCode username
beelzebub79 

#### Category of the bug
- [ ] Missing Test Cases 

#### Description of the bug
A new, small test-case which shows that an old node might have to be re-evaluated later. 
Testcase proposed: [[1,2,100],[1,3,1],[3,2,2],[2,4,1]]; k=1, n=4

#### Code you used for Submit/Run operation

```
//Network Delay Time:THE CODE THAT HIGHLIGHTS THESE BOTTLENECK TESTCASES (it runs wrong for the last two testcases)
class Solution {
public:
    int networkDelayTime(vector<vector<int>>& times, int n, int k) {
        map<int,vector<pair<int,int>>>  map;
        vector<int> vals(n+1,INT_MAX);
        for(auto it : times)
        {
            map[it[0]].push_back({it[1],it[2]});
        } 
        queue<int> q;
        q.push(k);
        vector<int> visited(n+1,0);
        visited[k]=1;
        vals[k]=0;

        while(!q.empty())
        {
            int top=q.front();
            q.pop();
            visited[top]=1;
            for(auto it:map[top])
            {
                int dist=vals[top]+it.second;
                vals[it.first]=min(vals[it.first],dist);
                if(visited[it.first]==0) q.push(it.first);
            }
        }

        int t=*max_element(vals.begin()+1,vals.end());
        if(t==INT_MAX) return -1;
        return t;
    }
};
```

#### Language used for code
C++ 

#### Expected behaviour
There is no easy and efficient testcase that highlights this issue discussed above, so I have created a small testcase that will highlight this for someone facing the same logical error.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by ArshiaAggarwal749** [comment]
Thank you for your consideration; but the test case I suggested doesn't cater to the requirements listed, it was just a suggestive test case for someone who might be stuck due to a logical inconsistency. A correctly implemented code will pass the correct test cases, there is no faulty test case.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

The team decided to reject this feedback after the evaluation. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
