### ISSUE TITLE
Question Contribution

### ISSUE THREAD

**Issue by masterujjval** [LeetCode-Feedback/LeetCode-Feedback#16803]
I have contributed a question in Leetcode website please review it.
Question id: 48923

P.S i have also contributed other two questions and its been a month the questions are still in pending state.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
