### ISSUE TITLE
Display Error When Editing Test Case in Source Mode

### ISSUE THREAD

**Issue by wwwld1** [LeetCode-Feedback/LeetCode-Feedback#16847]
#### Category of the bug
- [ ] Question

#### Description of the bug

When I try to edit the test case in source mode, the test cases source page just displays nothing, no test cases are shown anymore.

The first screenshot is the status that shows test cases normally, but after I tried to edit it, everything just disappeared. 

#### Screenshots

<img width="786" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/116049361/61baae05-69e0-4129-b226-9c6b70f3d86f">
<img width="783" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/116049361/98ff073f-ff0b-4e3a-ac74-df96886de505">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
