### ISSUE TITLE
Missing Test Case - 2038. Remove Colored Pieces if Both Neighbors are the Same Color

### ISSUE THREAD

**Issue by shreyashHake** [LeetCode-Feedback/LeetCode-Feedback#16859]
#### Your LeetCode username
`Shreyash_`

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

for the test case `"BBBAAA"`, `Alice` should win and not `Bob`

#### Code you used for Submit/Run operation

```
// 2038. Remove Colored Pieces if Both Neighbors are the Same Color

class Solution {
    public boolean winnerOfGame(String s) {
        
        int a = 0, b = 0;
        
        for(int i=1; i<s.length()-1; i++){
            if(s.charAt(i) == s.charAt(i-1) && s.charAt(i) == s.charAt(i+1)){
                if(s.charAt(i) == 'A')
                    a++;
                else
                    b++;
			}
        }
                    
        return a>b;
    }
}
```

#### Expected behavior

For the test case `"BBBAAA"`, `Alice` should win and so the result should be `true` 
let me explain : 

* first `Alice` will remove `A`, to visualize removed `A` I will mark it as 1 so the string will look like 
       --> `"BBB1AA"`
* now `Bob` will remove 
      --> `"B1B1"`

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/81287478/005f227a-dc0b-4916-8afa-864a8d98ee1b)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by kenlau46** [comment]
@shreyashHake, your algorithm is incorrect.

The following are direct quote from the problem, the key constrains are in _italic_:
* Alice is only allowed to remove a piece colored 'A' if _**both its neighbors are also colored 'A'**_. She is not allowed to remove pieces that are colored 'B'.
* Bob is only allowed to remove a piece colored 'B' if _**both its neighbors are also colored 'B'**_. He is not allowed to remove pieces that are colored 'A'.

In your example `"BBB[A]AA"`, the first A (enclosed in `[ ]`) cannot be taken because the left side neighbour is 'B', the only possible move for Alice will be taken the middle A, i.e. `"BBBA[A]A"`
After Alice's term, Bob can only takes the middle "B" with the same reason, as other "B"s are either at border or having a neighbour "A".
So after Bob's term the result becomes `"B[]BA[]A"`. Alice has no valid move now because the remaining "A"s are are either at border or having a neighbour "B".

**Comment by shreyashHake** [comment]
@kenlau46, after reviewing it once again I understood it, and thank you for your explanation :)
