### ISSUE TITLE
assert_eq! in Rust does not produce meaningful message

### ISSUE THREAD

**Issue by stepancheg** [LeetCode-Feedback/LeetCode-Feedback#16975]
Add

```
assert_eq!(1, 2);
```

to any solution code.

Error is just "Runtime Error" without error message or location.

<img width="600" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/28969/13d36161-6b98-4eec-9881-d9ec640c2056">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
We only add new test cases when some solution gets accepted but shouldn't because it fails on the suggested test case. This minimizes the test suite and optimizes the grader's performance. We could stress-test each solution for minutes instead of relying on hardcoded test cases if performance was not an issue.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by stepancheg** [comment]
> The problem name or number.

Any of them. Just paste this code `assert_eq!(1, 2)` into the solution and click run.

But for example, this: https://leetcode.com/problems/bulb-switcher/

**Comment by LC-Pam** [comment]
Hi there,

Thank you for reaching out to us.

 We've relayed this issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to check the problem. 

This is an educational site. Please respect the limitations of the question.

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
