### ISSUE TITLE
Assertion Error with 'Leftmost Column with at Least a One'

### ISSUE THREAD

**Issue by stacy79** [LeetCode-Feedback/LeetCode-Feedback#172]
**What kind of the bug**
- [ *] problem
- [ ] solution
- [ ] language

**Describe the bug**
When I run the code in my machine it works fine, when I try to submit it on leetcode, it gives me assertion Error.

**what language is your code written in**
Java

**The code you submit/run**

     	
   public int leftMostColumnWithOne(BinaryMatrix binaryMatrix) {
        List<Integer> d = binaryMatrix.dimensions();
    	int answer = -1;
    	for (int col=0; col<d.get(0); col++) {
    		for (int row=0; row<d.get(1); row++) {
    			if (binaryMatrix.get(row, col) == 1) {
    				answer = col;
    				break;
    			}
    		}
    		if (answer != -1) {
    			break;
    		}
    	}
        return answer;
    }

**Expected behavior**

When I ran the code in my local eclipse it gave me '1'.

**Screenshots**

![image](https://user-images.githubusercontent.com/57686718/79944488-98ba3880-84a6-11ea-9353-2d3b86db4f60.png)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @stacy79,
Thank you for reaching out to us! I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @stacy79,
Thank you for reaching out to us. Our team took a thorough look at this issue and found the code you've submitted shown in the screenshot is not the same as the code you've shared here. Your code got the error as shown on the screenshot because it confused rows with columns.

Please make sure your code is correct and formatted before sharing it in the future. We appreciate your time and support.
