### ISSUE TITLE
Contributed question not yet reviewed, pending for 2 months

### ISSUE THREAD

**Issue by cy2000yadav** [LeetCode-Feedback/LeetCode-Feedback#17204]
I contributed a question to LeetCode 2 months ago, but it is still showing a pending status.
I have attached a screenshot of my contribution page, showing the pending status:
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/77014258/45d1d67a-e959-4ea5-8634-10ba5056a148)

I am requesting that LeetCode please review my question as soon as possible.

Leetcode username: cy2000yadav

I am happy to provide any additional information that is needed. Please let me know if you have any questions.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by cy2000yadav** [comment]
Sure Thank you so much
