### ISSUE TITLE
Missing Test Case - 2095. Delete the Middle Node of a Linked List

### ISSUE THREAD

**Issue by AKB2102** [LeetCode-Feedback/LeetCode-Feedback#17274]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by AKB2102** [comment]
lass Solution {
    public ListNode deleteMiddle(ListNode head) {
        ListNode fast= head;
        ListNode slow= head;
        while(fast.next!= null&&fast.next.next!=null && fast.next.next.next!=null){
                
                slow= slow.next;
                fast=fast.next.next;


        }
        if(slow.next==null)return null;
        slow.next=slow.next.next;
        return head;
    }
}

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The code submission Accepted link. 
The missing test case.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by LC-Pam** [comment]
Since we have not heard from you for a while, we will close this ticket now. 

If you have any new information to share with us, please don't hesitate to share them here with us. 

Thank you again for your support and understanding.

**Comment by ExploiTR** [comment]
@LC-Pam there is some issue with the solution verification, for single linkedlist if we delete the node, that means we return null pointer, but the verification is trying to access the null pointer and crashing the solution. Now if we don't delete the head itself, then it shows correct - but we're expected to delete the head itself in case it's the middle node which is true for a single valued linkedlist.
Otherwise it's a memory leak.

```
if (!head || !head->next) {
    delete head;
    return nullptr;
}
```
![Image](https://github.com/user-attachments/assets/dd2602ba-2988-456c-80e6-240b010d3ae5)

to just test, I made `return it head` itself. then :

![Image](https://github.com/user-attachments/assets/e84f6b9f-27e7-4e11-a60d-cfc01dfc2760)

if I dont delete head 

![Image](https://github.com/user-attachments/assets/4ad3ddfa-4277-4ff7-86fc-d2f19a7964ce)
