### ISSUE TITLE
Tree view does not support larger values

### ISSUE THREAD

**Issue by prompt-07** [LeetCode-Feedback/LeetCode-Feedback#17322]
#### Your LeetCode username
prompt_07

#### Category of the bug
 - Question
 - Test Case UX

#### Description of the bug
Tree view does not support larger values
Question - https://leetcode.com/problems/path-sum-iii/description/

#### Expected behavior
Tree view should support all values.

#### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/65489912/8290f1cd-0bb5-44f0-9b7c-e0b5d693d3e5)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
