### ISSUE TITLE
371. Sum of Two Integers - Solution Article - Sol 1 runtime err for C#

### ISSUE THREAD

**Issue by yang203000** [LeetCode-Feedback/LeetCode-Feedback#1750]
#### Category of the bug
- [ ] Question
- [x] Solution
- [] Language

#### Description of the bug

Solution 1 convert Java to C# got runtime error on submit:
```
System.OverflowException: Negating the minimum value of a twos complement number is invalid.
Line 0: System.Math.Abs (System.Int32 value) in 

Last executed input
2147483647
-2147483648 
```

But I run code on my local visual studio it works for the input.  Could you check why local works, but submit show error?

#### Code you used for Submit/Run operation

```

		class Solution
		{
			public int GetSum(int a, int b)
			{
				int x = Math.Abs(a), y = Math.Abs(b);
				// ensure that.Abs(a) >=.Abs(b)
				if (x < y) return GetSum(b, a);

				//.Abs(a) >=.Abs(b) --> 
				// a dete.Mines the sign
				int sign = a > 0 ? 1 : -1;

				if (a * b >= 0)
				{
					// sum of two positive integers x + y
					// where x > y
					while (y != 0)
					{
						int answer = x ^ y;
						int carry = (x & y) << 1;
						x = answer;
						y = carry;
					}
				}
				else
				{
					// difference of two positive integers x - y
					// where x > y
					while (y != 0)
					{
						int answer = x ^ y;
						int borrow = ((~x) & y) << 1;
						x = answer;
						y = borrow;
					}
				}
				return x * sign;
			}
		}

```

#### Language used for code

C#

**Comment by lc-kay** [comment]
@yang203000 Your solution got Runtime Error because it is not optimal. In addition, 'run code' only runs your code against one test case. However, 'submit' runs your code against ALL test cases. Here's the full error message for your code. 

System.OverflowException: Negating the minimum value of a twos complement number is invalid.
Line 0: System.Math.Abs (System.Int32 value) in <9f0df102fe6e4cfea29d2e46f585d8a5>
Line 5: Solution.GetSum (System.Int32 a, System.Int32 b) in Solution.cs
Line 18: __DriverSolution__.__Helper__ (System.Int32 param_1, System.Int32 param_2) in __Driver__.cs
Line 35: __Driver__.Main (System.String[] args) in __Driver__.cs
[ERROR] FATAL UNHANDLED EXCEPTION: System.OverflowException: Negating the minimum value of a twos complement number is invalid.
Line 0: System.Math.Abs (System.Int32 value) in <9f0df102fe6e4cfea29d2e46f585d8a5>
Line 5: Solution.GetSum (System.Int32 a, System.Int32 b) in Solution.cs
Line 18: __DriverSolution__.__Helper__ (System.Int32 param_1, System.Int32 param_2) in __Driver__.cs
Line 35: __Driver__.Main (System.String[] args) in __Driver__.cs
