### ISSUE TITLE
timer feature enhancement request

### ISSUE THREAD

**Issue by daregula** [LeetCode-Feedback/LeetCode-Feedback#17534]
#### Your LeetCode username
daregula

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Add a pause button to the timer

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
