### ISSUE TITLE
Wrong Output at given test case  in problem "1668. Maximum Repeating Substring"

### ISSUE THREAD

**Issue by gm271312** [LeetCode-Feedback/LeetCode-Feedback#1754]
#### Your LeetCode username

Input:
"aaabaaaabaaabaaaabaaaabaaaabaaaaba"
"aaaba"
Output:
6
Expected:
5
THis output must be 6 according to logic mention in question.

#### Category of the bug
- [ ] Question

#### Code you used for Submit/Run operation
<!-- 
Please make sure you wrap your code with ``` tags. 
Otherwise we may reject your request.

**Comment by lc-kay** [comment]
Hi @gm271312 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@gm271312 The expected output is correct. The reason why the output is 5 is because
"aaabaaaabaaaabaaaabaaaabaaaaba" is a substring of "aaabaaaabaaabaaaabaaaabaaaabaaaaba"
The reason why the output is not 6 is because
"aaabaaaabaaaabaaaabaaaabaaaabaaaaba" is not a substring of "aaabaaaabaaabaaaabaaaabaaaabaaaaba"
