### ISSUE TITLE
2925. Maximum Score After Applying Operations on a Tree

### ISSUE THREAD

**Issue by neilnaveen** [LeetCode-Feedback/LeetCode-Feedback#17932]
### LeetCode Username 
[neilnaveen](https://leetcode.com/neilnaveen)

### Problem number, title, and link

2925. Maximum Score After Applying Operations on a Tree  https://leetcode.com/problems/maximum-score-after-applying-operations-on-a-tree/description/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

I have submitted my code, and it TLE's yet other people get AC's, even though my code has the same time complexity of the solutions that get AC's
### Language used for code

Golang 

### Code used for Submit/Run operation

```
func maximumScoreAfterOperations (edges [][]int, values []int) int64 {
    m := map[int][]int{}

    for _, i := range edges {
        m[i[0]] = append( m[i[0]], i[1])
        m[i[1]] = append( m[i[1]], i[0])
    }
    vis := map[int]bool{}
    vis[0] = true

    return int64(max(dfs(m, vis , values, 0,0, -1 ), dfs(m, vis, values, -1,0, -1 ) + values[0]))
}
func dfs(m map[int][]int, visited map[int]bool, values []int, p int, cur int, parent int) int {  
  sum := 0
  ted := true
  for _, n := range m[cur] {
    if n == parent{
      continue
    }
    ted = false
    t := 0
    if p == -1 {
      t = dfs(m, visited, values, n, n, cur)
    }
    t = max(t, dfs(m, visited, values, p, n, cur)+ values[n])
    sum += t
  }
  if ted  {
    if p == -1 {
      return math.MinInt32
    }  else {
      return 0
    }
  }
  return sum
  
}
func max(i, j int)int {
  if i > j {
    return i 
  }
  return j 
}
```

### Expected behavior

I expect that this code should pass without TLE'ing.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
