### ISSUE TITLE
Dislikes count of the problems

### ISSUE THREAD

**Issue by TiagoDiass** [LeetCode-Feedback/LeetCode-Feedback#17959]
The problem I want to report is: 

**Why did you guys remove the dislikes counter for the problems in the platform?**

I just wasted almost 30 minutes solving a question that people are solving with only a `return False` statement (yes, the problem itself does not have too much sense and is lacking test cases, this is the problem: https://leetcode.com/problems/strictly-palindromic-number/)

If I could see the dislikes count (as I could just some weeks ago), I wouldn't have wasted my time solving a useless question, instead, I would've solved a good question.

I sincerely ask you guys to come back with the dislikes counter for the problems inside the platform.

Thanks in advance.

### LeetCode Username
TiagoDiass

### Screenshots
<img src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/49597377/f81ad73f-51d5-4318-909d-46124da6c959" width="500" />

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
