### ISSUE TITLE
Missing reverse method - 2. Add Two Numbers

### ISSUE THREAD

**Issue by daniel-luan-tran** [LeetCode-Feedback/LeetCode-Feedback#1804]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
var addTwoNumbers = (l1, l2) => {
    let _l1 = l1.reverse();
    let _l1_ = parseInt(_l1.join(""));
    let _l2 = l2.reverse();
    let _l2_ = parseInt(_l2.join(""));
    let sum = _l1_ + _l2_;
    let sum_ = sum.toString().split("");
    return sum_.map(item => { return parseInt(item); }).reverse();
};
```

#### Screenshots

![image](https://user-images.githubusercontent.com/56869242/103277268-359c8080-49fb-11eb-87fa-2aa4e3166042.png)

**Comment by daniel-luan-tran** [comment]
Missing reverse method in javascript

**Comment by Sky-Nik** [comment]
@daniel-luan-tran, please read the definition of a singly linked list (above the code in the comments) again. It is a custom data structure that does not provide the same interface as the standard singly-linked list in js. You are expected to solve this problem with explicit list manipulation, instead of hiding the most complex details behind the standard library.

**Comment by lc-kay** [comment]
@daniel-luan-tran Please refer to @Sky-Nik comment. In addition, please check out the discuss tab for accepted JavaScript solutions. Thank you for your time.
