### ISSUE TITLE
Rust compiler is ancient.

### ISSUE THREAD

**Issue by kaarelen** [LeetCode-Feedback/LeetCode-Feedback#18078]
### LeetCode Username
kaarelen

### Category of the bug
- [ ] Programming language support

### Description of the bug
Rust compiler is ancient (it's still growing pretty fast, so it's a huge difference), while it could be updated without any problems - It's fully backward compatible. New versions of rust brings us so many quality-of-life things, so, please update it!
Thanks!

### Additional context

current version: Rust 1.73.0 (Oct 2023)
current version on leetcode: 1.45 (Sep 2020)

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC

**Comment by kaarelen** [comment]
@LC-Pam Will do it!
Thanks!
