### ISSUE TITLE
Missing Test Case - 236. Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by jasonhn1** [LeetCode-Feedback/LeetCode-Feedback#18128]
### Problem number, title, and link

https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ X] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The last testcase doesnt display Q and P in the input.
Last test case is wrong my logic is right

### Language used for code

Python

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

**Comment by janoma** [comment]
Here we can see the test case from the description. The first element of the input is the graph, while the second and third are node values. This test case is working correctly.
<img width="377" alt="Screenshot 2023-11-17 at 8 32 05 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1223453/8933f303-8b43-4d2c-9b78-26101f7a0bb7">

However, the broken test case has wrong inputs. When I click on "Use testcase", I get this, with a `4` instead of the graph, the graph instead of `p`, and no value for `q`.
<img width="370" alt="Screenshot 2023-11-17 at 8 31 57 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/1223453/ee993c57-3971-40cb-8adb-1af2c6b03b45">

**Comment by mygithubzz1** [comment]
I also encountered this issue, the first parameter should be a binary tree, not 4

**Comment by FlorianLR** [comment]
I got this too. As you may expect, all solutions in the editorial fail this testcase as well.

**Comment by FlorianLR** [comment]
The title of this issue is not correct, though. The problem is not a missing test case but an incorrect one.

**Comment by FlorianLR** [comment]
The faulty test case may also be causing the problem underlying this issue:
https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/18126

**Comment by janoma** [comment]
> The title of this issue is not correct, though. The problem is not a missing test case but an incorrect one.

Thank you Florian. That's why I added the screenshots, also found the title and description lacking.

**Comment by vivek0079** [comment]
@janoma Yes, please. The 32nd testcase is incorrect. Pleaes fix the same. Thanks

**Comment by jasonhn1** [comment]
Could we get some coins for our testcase contribution? Want to get that
free shirt lol

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
