### ISSUE TITLE
2938. Separate Black and White Balls

### ISSUE THREAD

**Issue by ash543210** [LeetCode-Feedback/LeetCode-Feedback#18202]
### Leetcode Username 
ash54321

### Category of the bug
- [ ] Test case gives TLE during submit

### Description of the bug
When I submitted my code I got a TLE, later I copied the test case to run it along with the default test cases and it runs fine. But gives a TLE when I submit my code.

### Language used for code
Java

### Code used for Submit/Run operation

```
class Solution {
    public long minimumSteps(String s) {
        int count = 0;
        int l = -1, r = -1;
        for (int i = s.length() - 1; i > -1; i--) {
            if (s.charAt(i) == '0') {
                r = i;
                break;
            }
        }
        for (int i = r - 1; i > -1; i--) {
            if (s.charAt(i) == '1') {
                l = i;
                break;
            }
        }
        if (r == -1 || l == -1) return 0;
        while (l > -1 && l < r) {
            count += r - l;
            s = s.substring(0, l) + "0" + s.substring(l + 1, r) + "1" + s.substring(r + 1, s.length());
            l -= 1;
            while (l > -1 && s.charAt(l) != '1') l--;
            r--;
            while (s.charAt(r) != '0') r--;
        }
        return count;
    }
}
```

### Screenshots

<img width="1439" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/103955093/f81190c3-66b9-41a0-a3e0-7768fcc7acdf">

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. 

Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

I hope this helps. If you have any other questions about this case, please don't hesitate to let us know!
