### ISSUE TITLE
fix small bug in ui

### ISSUE THREAD

**Issue by Mohamedate** [LeetCode-Feedback/LeetCode-Feedback#18233]
### Category of the bug

- [ ] fix small bug in ui

### Description of the bug
In "https://leetcode.com/store/" page, there are seven boxes, but the last one has a div issue that makes the UI less than optimal. Simply remove the height property in the CSS, specifically, height: 0;, and the problem will be resolved. The box will then look amazing.
please look at screenshot

### Screenshots

![issue](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/88455397/a4363fac-eab6-43d8-91c5-f36bf8f4f8e9)

### Additional context
Thank you, Leetcode, for everything. I love Leetcode very much.

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
