### ISSUE TITLE
Typo and problem constraint - 2756. Query Batching

### ISSUE THREAD

**Issue by kentshenlim** [LeetCode-Feedback/LeetCode-Feedback#18272]
### LeetCode Username
soyukotoda

### Problem number, title, and link

[2756. Query Batching](https://leetcode.com/problems/query-batching/)

### Category of the bug
- [ ] Problem description
- [ ] Problem constraints

### Description of the bug

1. Small typo?
"An **asyncronous** function `queryMultiple` which ..."
"asyncronous" → asynchronous

2. Problem constraints. Accepted on test but TLE on submission. [This submission](https://leetcode.com/problems/query-batching/submissions/1105764159).
And in fact, all solutions posted by someone else yield TLE. Not sure is because the time out of test cases is too long either individually or collectively, or simply because all solutions are suboptimal (in which case I apologize).

### Language used for code

JavaScript

### Code used for Submit/Run operation

```JS
// Paste your code here. Don't remove ``` given
// above and below the code.
class QueryBatcher {
    constructor(queryMultiple, t) {
        this.queryMultiple = queryMultiple;
        this.t = t;
        this.arr = []; // Pending queries
        this.cooldown = null;
        this._cooldownEnd = this._cooldownEnd.bind(this);
    }

    async getValue(key) {
        // Must always return resolved value
        if (!this.cooldown) { // Idling
            this.cooldown = setTimeout(() => { // Set to cooling down because will call qM
                this._cooldownEnd();
            }, this.t);
            const res = await this.queryMultiple([key]);
            return res;
        }
        else { // Cooling down
            return new Promise((resolve) => {
                this.arr.push({ key, resolve }); // Store the key and resolve function
            })
        }
    }

    async _cooldownEnd() {
        if (!this.arr.length) this.cooldown = null; // Switch to idling
        else { // Run then reset cooldown
            this.cooldown = setTimeout(() => {
                this._cooldownEnd();
            }, this.t);
            const tasks = [...this.arr];
            this.arr = [];
            const keys = tasks.map(obj => obj.key);
            const resolves = tasks.map(obj => obj.resolve);
            const res = await this.queryMultiple(keys);
            for (let i = 0; i < keys.length; i++) resolves[i](res[i]); // Resolve the promises now
        }
    }
}
```

### Expected behavior

Described above.

### Screenshots

![lcis5](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/89fca3d2-757c-486f-bdcb-154a4a96fac8)
![lcis6](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/37e6b19d-8243-4a7e-bb35-4d5f3999b143)
![lcis7](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/106628390/560ba236-7ee3-44da-a562-40b11e48b33b)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us, the same code could TLE or AC because it's at the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" run all of the test cases for this problem at once, whereas "Run Code" only run one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. I found a Swift solution in the problem discuss section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.
 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!

**Comment by LC-Pam** [comment]
We've relayed the typo issue to our team to investigate. 

We will reach back to you after we have the results.

Thank you for your support.

**Comment by kentshenlim** [comment]
> ot mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test case

Thank you for your detailed reply. The problem is about asynchronous JavaScript; this simulates some real time delays during the function execution. Could it be the case that, the time delays (decided by test cases) are too long that even the optimized, intended answer can never get accepted when all the test cases are ran at once?

**Comment by LC-Pam** [comment]
Thank you for your time. 

We've used your feedback to update the problem. 

Your LeetCode account has received 100 LeetCoins as a reward for this feedback. 

If you have any other questions or feedback, please don't hesitate to let us know! 

We appreciate your support!
