### ISSUE TITLE
Blank screen issue

### ISSUE THREAD

**Issue by debug-arun** [LeetCode-Feedback/LeetCode-Feedback#18348]
### Description of the bug

After the new version release i.e., resizable, tab-able components have come, most of the times I get to see this blank screen in parts and pieces of the screen. 

### Screenshots

<img width="933" alt="image" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/70369284/0a748959-2fbb-4d3f-977c-5896d115b6f2">

**Comment by LC-Pam** [comment]
Hi there,

Thank you for your feedback.

GitHub repo mainly focuses on helping users to solve content/solution-related issues.

In order to fix your feedback timely, if you have any feature/function/Course Access/product feedback, please feel free to submit them through our Zendesk Support Channel.

https://leetcode.com/support

Normally, our support agent will reply to you within 24 hours and report those issues to the correct department for investigation. 

We really appreciate your support.

Best,

LC
