### ISSUE TITLE
Wrong Test Case in the Contest Problem

### ISSUE THREAD

**Issue by Silvia42** [LeetCode-Feedback/LeetCode-Feedback#18565]
### LeetCode Username
Sil42

### Problem number, title, and link
100147. Length of Longest Subarray With at Most K Frequency

### Category of the bug
- [ ] Problem description
- [ ] Problem constraints
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*

### Description of the bug
In the contest, I had wrong answer on test case. I used the same test case and got the warning, that my test case is incorrect:

### Language used for code
Python3

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
```

### Screenshots
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37594365/f164e5b8-d3de-4ab0-8898-d6c93a6b96b9)

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/37594365/fd05837d-2e01-4224-bcce-e03875d85f1d)

**Comment by LC-Pam** [comment]
Hello,
 
Thank you for your inquiry and for bringing the issue with the 3rd question to our attention.
 
We have rejudged all the submissions for Q3 in BC119. 
 
If your code received "Wrong Answer" due to the invalid test case, the rejudge will indeed impact the contest submission results. 
 
The corrected results will be reflected in their overall contest rankings.
 
If you have any further questions or if there's anything else you'd like clarification on, please feel free to let me know.
 
We appreciate your understanding and cooperation in resolving this matter.
 
The Leetcode Team

**Comment by Silvia42** [comment]
Thanks for addressing the test cases. I haven't received 100 points for
reporting this issue. Could you confirm my eligibility for the reward
points and provide an update on when they'll be credited to my account?
Appreciate it!

My Leetcode account is Sil42
https://leetcode.com/Sil42/

Thank you
Silvia
