### ISSUE TITLE
790. Domino and Tromino Tiling

### ISSUE THREAD

**Issue by jprakash** [LeetCode-Feedback/LeetCode-Feedback#1877]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Explanation of the solution in Approach#1 is not clear. Can you please update it with diagrams and better explanation?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
Hi @jprakash 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@jprakash  Thanks for letting us know. As a whole, the explanations in this article are below our quality requirements, and we're really sorry about that. We've added it to our rewrite list so that one of our solution article authors can rewrite the article when they have time. Thanks for letting us know :-)
