### ISSUE TITLE
7. Reverse Integer - Infinite while loop even if the condition is false

### ISSUE THREAD

**Issue by JetonGjonbalaj** [LeetCode-Feedback/LeetCode-Feedback#18891]
### LeetCode Username
jgjonb

### Problem number, title, and link

7. Reverse Integer https://leetcode.com/problems/reverse-integer

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug
This is a weird problem. I'm getting a `Time Limit Exceeded` message. When I log variables I see that there is an infinite loop when the code executes in server. But it works fine in console. It also works file in node v18.15.0

### Language used for code
JS/TS

### Code used for Submit/Run operation

```
/**
 * @param {number} x
 * @return {number}
 */
var reverse = function(x) {
  let rev = 0;

  while (x !== 0) {
    const num = x % 10;
    x = Math.floor(x / 10);
    rev = rev * 10 + num;

    console.log({num, x, rev}, x !== 0)
  }

  return rev;
};
```

### Expected behavior

Should break from the loop when condition is met.

### Screenshots

![problem](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31703284/98be7786-0ba3-4daf-994c-a85732665fdd)
![problem2](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/31703284/90085bd2-bd9b-4ec4-9940-27814d6d78df)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 

Thank you for reaching out to us, the same code could be TLE or AC because it's on the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" runs all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. 

I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

The runtime variation issue, as you described, is indeed a complex challenge. We've shared your feedback with our engineering team, and they will investigate to enhance the consistency of results for our users. While we strive for improvements, please understand that a quick fix may not be immediately available.

In the meantime, we appreciate your understanding and encourage you to continue optimizing your code to meet the time limit. We apologize for any inconvenience caused and thank you for your ongoing support!

If you have further questions or if there's anything else we can assist you with, please don't hesitate to let us know.

Best regards,
The LeetCode Team
