### ISSUE TITLE
[Incorrect TLE response] 2977. Minimum Cost to Convert String II 

### ISSUE THREAD

**Issue by jywyq** [LeetCode-Feedback/LeetCode-Feedback#18918]
Issue: The response shows TLE but when I run the test case it shows runtime less then 400ms

The issue I met could be reproduced by:

- Go to https://leetcode.com/contest/weekly-contest-377/problems/minimum-cost-to-convert-string-ii/ 
- Paste the solution code
- Found it TLE
- Copy over the test case, and hit Run Code
- Found it passed very nicely

My solution:

``` python
from collections import defaultdict
from queue import PriorityQueue

class Solution:
    def minimumCost(self, source: str, target: str, original: List[str], changed: List[str], cost: List[int]) -> int:
        l2d = defaultdict(dict)
        l2str = defaultdict(set)
        for i in range(len(original)):
            a = original[i]
            b = changed[i]
            l = len(a)
            l2str[l].add(a)
            l2str[l].add(b)
            dist = l2d[l]
            if a not in dist:
                dist[a] = dict()
            if b not in dist[a]:
                dist[a][b] = cost[i]
            else:
                dist[a][b] = min(dist[a][b], cost[i])
        
        for l, dist in l2d.items():
            for k in l2str[l]:
                if k not in dist:
                    continue
                for i in l2str[l]:
                    if i not in dist:
                        continue
                    for j in dist[k]:
                        if j in dist[i] and k in dist[i]:
                            dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])
                        if j not in dist[i] and k in dist[i]:
                            dist[i][j] = dist[i][k]+dist[k][j]
        
        n = len(source)
        min_cost = [1<<63] * (n+1)

        q = PriorityQueue()
        q.put((0,0))
        while not q.empty():
            cur_i, cur_c = q.get()
            if cur_c >= min_cost[cur_i]:
                continue
            else:
                min_cost[cur_i] =cur_c
            # print(cur_i,cur_c)
            if cur_i==n:
                return cur_c
            for i in range(cur_i+1, n+1):
                subs = source[cur_i:i]
                targ = target[cur_i:i]
                dist = l2d[i-cur_i]
                nextc = 1<<63
                if subs == targ and cur_c < min_cost[i]:
                    nextc = cur_c
                elif subs in dist and targ in dist[subs]:
                    nextc = cur_c + l2d[len(subs)][subs][targ]
                if nextc < min_cost[i]:
                    q.put((i, nextc))
        
        return -1
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 

Thank you for reaching out to us, the same code could be TLE or AC because it's on the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" runs all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. 

I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

The runtime variation issue, as you described, is indeed a complex challenge. We've shared your feedback with our engineering team, and they will investigate to enhance the consistency of results for our users. While we strive for improvements, please understand that a quick fix may not be immediately available.

In the meantime, we appreciate your understanding and encourage you to continue optimizing your code to meet the time limit. We apologize for any inconvenience caused and thank you for your ongoing support!

If you have further questions or if there's anything else we can assist you with, please don't hesitate to let us know.

Best regards,
The LeetCode Team
