### ISSUE TITLE
Runtime varies too much - 2610. Convert an Array Into a 2D Array With Conditions

### ISSUE THREAD

**Issue by DoTheBestMayB** [LeetCode-Feedback/LeetCode-Feedback#19058]
### LeetCode Username

[DoTheBestMayb](https://leetcode.com/DoTheBestMayb)

### Problem number, title, and link
 2610. Convert an Array Into a 2D Array With Conditions
https://leetcode.com/problems/convert-an-array-into-a-2d-array-with-conditions

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

There is a big random difference in runtime for the same code, .
I'm wondering why there be a big time difference. 274ms vs. 415ms

### Language used for code

Kotlin

### Code used for Submit/Run operation

```kotlin
class Solution {
    fun findMatrix(nums: IntArray): List<List<Int>> {
        val numHash = HashMap<Int, Int>()
        val answers = ArrayList<MutableList<Int>>()
        answers.add(mutableListOf())

        for (num in nums) {
            numHash[num] = numHash.getOrDefault(num, 0) + 1
        }

        for ((num, size) in numHash) {
            while (size > answers.size) {
                answers.add(mutableListOf())
            }
            for (index in 0 until size) {
                answers[index].add(num)
            }
        }
        return answers
    }
}
```

### Expected behavior

I think the time difference should be reduced to within +-10%.
Kotlin has a small number of submission samples. The random run time is very different, so it is difficult to check if my code is efficient.

### Screenshots

![runtime](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/48354989/f7178654-69ed-48d2-a0ae-7c292061425d)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
