### ISSUE TITLE
Run time error - 1701. Average Waiting Time

### ISSUE THREAD

**Issue by yashporwal11** [LeetCode-Feedback/LeetCode-Feedback#1913]
#### Your LeetCode username

yashporwal11

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

I submitted the same code twice and it shows different run time, why does this happen?

#### Code you used for Submit/Run operation

```
class Solution {
public:
    double averageWaitingTime(vector<vector<int>>& customers) {
        if(customers.size()==0)
            return 0.00;
        if(customers.size()==1)
            return (double)customers[0][1];
        double res=customers[0][1];
        int cur=customers[0][0]+customers[0][1];
        for(int i=1;i<customers.size();i++){
            if(customers[i][0]<cur){
                cur+=customers[i][1];
                res+=(cur-customers[i][0]);
            }
            else{
                cur=customers[i][0]+customers[i][1];
                res+=customers[i][1];
            }
        }
        return res/customers.size();
    }
};
```

#### Language used for code

C++

#### Expected behavior

Run time should have been same for both the cases since the code was same.

**Comment by lc-kay** [comment]
@yashporwal11 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this clarifies your doubts. Thank you for your time!
