### ISSUE TITLE
Missing Test Case - 1704. Determine if String Halves Are Alike

### ISSUE THREAD

**Issue by Glorybaranwal** [LeetCode-Feedback/LeetCode-Feedback#19319]
### Category of the bug
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Code used for Submit/Run operation

```
 const countVowels = (str) => {
    const vowels = new Set(["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"]);
    let count = 0;

    for (let char of str) {
      if (vowels.has(char)) {
        count++;
      }
    }

    return count;
  };

  var halvesAreAlike = function (s) {
    const data = Object.values(s);
    if (data.length % 2 == 0) {
      const midpoint = Math.floor(data.length / 2);
      const firstHalf = data.slice(0, midpoint);
      const secondHalf = data.slice(midpoint);
      const countFirstHalf = countVowels(firstHalf);
      const countSecondHalf = countVowels(secondHalf);
      return countFirstHalf === countSecondHalf;
    } else {
      return false;
    }
  };
```

### Expected behavior
odd number should return false before checking the vowels

**Comment by LC-Pam** [comment]
Hello,

Since we have not received further updates from you, we are closing this ticket. If you have any new information or additional details to share, please feel free to provide them at any time.

Thank you once again for your support and understanding. Should you have any more questions or encounter any issues in the future, do not hesitate to reach out. We're here to assist you.

Best regards,
LeetCode Support Team
