### ISSUE TITLE
Missing Test Case - 618. Students Report By Geography

### ISSUE THREAD

**Issue by DaraDadachanji** [LeetCode-Feedback/LeetCode-Feedback#19489]
### LeetCode Username
dara_dadachanji

### Problem number, title, and link  
618. Students Report By Geography https://leetcode.com/problems/students-report-by-geography

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [x] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug

The test cases to not include examples in which Asia or Europe have the most students, allowing answers to be accepted which would only return correctly if America has the most students.

The problem involves joining 3 lists of numbers together. One of the difficult edge cases to solve is that you do not know which list is the longest. Not having test cases covering all possibilities trivializes this aspect of the problem

### Language used for code
SQL

### Code used for Submit/Run operation

```
with ordered as (select 
    name,
    continent,
    row_number() over (partition by continent order by name) row_num
from Student
),
asia as (select * from ordered where continent = 'Asia'),
america as (select * from ordered where continent = 'America'),
europe as (select * from ordered where continent = 'Europe')

select 
    america.name as "America",
    asia.name as "Asia",
    europe.name as "Europe"
from asia
    right outer join america on 
        america.row_num = asia.row_num
    left join europe 
        on america.row_num = europe.row_num
order by coalesce(america.row_num, asia.row_num, europe.row_num)
```

### Expected behavior
This should not be accepted as it would return an incorrect answer if their were more students in Europe than in America or Asia

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

This is part of the question: “The test cases are generated so that the student number from America is not less than either Asia or Europe.”

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
