### ISSUE TITLE
submission error - problem 20

### ISSUE THREAD

**Issue by Lav12122** [LeetCode-Feedback/LeetCode-Feedback#20]
**What kind of the bug**
Submission error- Please refer screenshots in comment

**Describe the bug**
Problem 20 - valid parantheses submission error:
Bug 1. Running fine for test case when given manually but shows wrong result on submission 
Bug 2. Shows accepted where it should not accept.

Test case 1. - "{[]}"  for Bug 1.
Test case 2. - "{" for Bug 2.
```
pairing_map = {'}':'{',']':'[',')':'('}
stack = []
class Solution:
    def isValid(self, s: str) -> bool:
        for char in s:
            if char in ['(','{','[']:
                stack.append(char)
            else:
                if stack == []:
                    return False
                deleted = stack.pop()
                if deleted != pairing_map[char]:
                    return False
        if stack == []:
            return True # not returning anything in other case , but still result comes False for test case 2 raising bug 2. 
            
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Lav12122** [comment]
![IMG_20200308_000638](https://user-images.githubusercontent.com/61917214/76150714-5333de80-60a5-11ea-8297-c6ac2235ffe6.jpg)

**Comment by CooperCooperCooper** [comment]
Hi @Lav12122,

Thank you for reaching out to us! The output mismatch is caused by "Run Code" and "Submit" running differently. When you click on "Run Code", it runs your code on only 1 test case; and when you click on "Submit", it runs your code on all of the test cases for this problem (i.e. for "Valid Parentheses", it runs all 76 test cases at once).

When you look at the different outcomes of "Run Code" and "Submit" for this test case, you can see the same input and expected values but different output values. We've documented the cause and solutions of this kind of issue in this [ARTICLE](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-).

Hope this helps! We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by Lav12122** [comment]
But, as you can see from the attached screenshot, both run test case and
submission test cases are same where mismatch is happening.

**Comment by Lav12122** [comment]
Thanks.
Any specific reason for why Leetcode is designed this way?
