### ISSUE TITLE
Time limit exceeded for all solutions :  1633. Percentage of Users Attended a Contest

### ISSUE THREAD

**Issue by patvins** [LeetCode-Feedback/LeetCode-Feedback#20230]
### LeetCode Username

caesarjuliuslp

### Problem number, title, and link

1633. Percentage of Users Attended a Contest

### Category of the bug
- [ X]  solutions not getting accepted

### Description of the bug

Tried multiple possible solutions but every solution gets time limit exceeded even though all test cases get passed. 
tried solutions present as well.

### Language used for code
 SQL

### Code used for Submit/Run operation

```
// Paste your code here. Don't remove ``` given
// above and below the code.
/* Write your T-SQL query statement below */
select contest_id,
round(count(user_id) *100.00/(select count(1)  from users) ,2) 
                                as percentage
from register
group by contest_id
order by percentage desc, contest_id asc
```

### Expected behavior

submission should be accepted.

### Screenshots

![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83172312/b7f426f4-e4fb-41fc-936b-d4636643dceb)
![image](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/83172312/2d38dad1-d259-4035-9973-b137b3459863)

**Comment by patvins** [comment]
Hi 
One additional note. I am using MS SQL Server.
But when i use the same code in MySQL the submission gets accepted.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. 

Thank you for reaching out to us, the same code could be TLE or AC because it's on the verge of not passing. This could occur because the code is not optimized. When you run your code by "Submit", it's very different from running it with "Run Code". "Submit" runs all of the test cases for this problem at once, whereas "Run Code" only runs one test case at a time. Furthermore, getting Time Limit Exceeded from "Submit" does not mean that your code is not passing a certain test case; it simply means that your code is taking too long to run all of the test cases at once. 

I found a Swift solution in the problem discussion section and hope it can provide some inspiration to how your code can be improved to overcome this TLE issue: https://leetcode.com/problems/elimination-game/discuss/245342/Swift-keep-left-and-right-boundary

The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

The runtime variation issue, as you described, is indeed a complex challenge. We've shared your feedback with our engineering team, and they will investigate to enhance the consistency of results for our users. While we strive for improvements, please understand that a quick fix may not be immediately available.

In the meantime, we appreciate your understanding and encourage you to continue optimizing your code to meet the time limit. We apologize for any inconvenience caused and thank you for your ongoing support!

If you have further questions or if there's anything else we can assist you with, please don't hesitate to let us know.

Best regards,
The LeetCode Team
