### ISSUE TITLE
Extremely variable and (therefore) inaccurate runtime execution ranking, sometimes wildly.

### ISSUE THREAD

**Issue by bencodesall** [LeetCode-Feedback/LeetCode-Feedback#20513]
### LeetCode Username

bencodesall

### Problem number, title, and link

[595. Big Countries](https://leetcode.com/problems/big-countries/)

### Category of the bug
- [ ] Problem description
- [x] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [x] Programming language support

### Description of the bug

Runtime execution of solution and the percent calculation of how fast it is compared to other submissions (i.e., "beats X% of other solutions") are not accurate and can be misleading.

The calculation is dependent on the parsing phase of the SQL query, which can be thrown off by more or less comments. Technically this "parsing" is not required "per sé" as queries could be placed into stored procedures which would remove the comments in the executable run plan of the query. This give a better indication of the exact running time of the query.

I noticed this on the listed problem. However, assuming this is an issue across other problems, this leads the submitter to falsely conclude their solution is relatively slow/fast.

### Language used for code

SQL

... though potentially others. Haven't explored.

### Code used for Submit/Run operation

```
# Write your MySQL query statement below
SELECT name, population, area 
FROM World 
WHERE area >= 3000000 OR population >= 25000000;
```

### Expected behavior

Since this is such a tightly scoped query against a tiny dataset (presumably), I would expect minuscule variability in the runtime results, regardless of the amount of comments.

### Screenshots

**Strangely low result with comments included in code**
<img width="703" alt="Arbitrarily low runtime with comment parsing" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47954098/eaa703ae-ae8f-4c33-922f-032f0654a09d">

**Showing the drastically different timing with comments stripped**
<img width="691" alt="Still lower than expected with comments removed" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47954098/4a03f855-007b-466c-bca5-f483863a4d5a">

**A shockingly low result**
<img width="713" alt="Potentially wildly inaccurate running time results" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47954098/3ed789ba-e09d-4306-94d0-68a024f1dac3">

**Illustrating the variability differential**
<img width="695" alt="Same one line with drastically different time reported" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/47954098/23df4b61-047a-413b-9958-a8817210d4f0">

### Additional context

Even subsequent code submissions of the exact same code produce wildly disparate results. While, theoretically, extra (wasted) space in the parsing phase COULD introduce some variability, the extreme nature of these results indicates an issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
 
It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.
 
The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.
 
I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
