### ISSUE TITLE
Missing Test Case - 70. Climbing Stairs

### ISSUE THREAD

**Issue by segreb** [LeetCode-Feedback/LeetCode-Feedback#20648]
### LeetCode Username
segreb

### Problem number, title, and link
70. Climbing Stairs  https://leetcode.com/problems/climbing-stairs/

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [ ] Editorial
- [ ] Programming language support

### Description of the bug
Every time tests run they show different runtime for the same source code - from 17 ms to 35 ms.
It is true for the Python at least, I did not check for other languages.

### Language used for code
Python

### Code used for Submit/Run operation
```
class Solution(object):


    def climbStairs(self, n):
        """
        :type n: int
        :rtype: int
        """
        if n <= 0:
            return 0

        variants = 0
        step1 = 1
        step2 = 0
        k = 1
        while k <= n:
            variants = step1 + step2
            step1, step2 = variants, step1
            k += 1
        return variants
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
