### ISSUE TITLE
Editorial issue - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by Darpan313** [LeetCode-Feedback/LeetCode-Feedback#20685]
### LeetCode Username
Darpan31

### Problem number, title, and link
https://leetcode.com/problems/remove-nth-node-from-end-of-list

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
In Editorial, Approach 2: One pass algorithm. Line number 11 should have condition while (first.next != null) instead of while (first != null).

### Language used for code
Java

### Code used for Submit/Run operation

```
    public ListNode removeNthFromEnd(ListNode head, int n) {
        ListNode dummy = new ListNode(0);
        dummy.next = head;
        ListNode first = dummy;
        ListNode second = dummy;

        //Advance first pointer
        for(int i=0; i<n; i++){
            first = first.next;
        }

        while(first.next!=null){
            first = first.next;
            second = second.next;
        }

        second.next = second.next.next;
        return dummy.next;

    }
```

### Screenshots
![Screenshot 2024-02-24 at 4 12 38 PM](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/17558606/889c4284-31c3-47b6-bff8-2efba77261ed)

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thank you for your time.

We've carefully considered your feedback and thoroughly examined the problem in question. After a comprehensive evaluation, the team has decided to reject this feedback.

The editorial code works as is. Your code needed to use the condition while(first.next!=null) because you use for(int i=0; i<n; i++) instead of for(int i=0; i<n + 1; i++)

If you have any further questions or if there's additional feedback you'd like to share, please don't hesitate to let us know. Your input is valuable, and we appreciate your continued support!

Best regards,
The LeetCode Team
