### ISSUE TITLE
Issue with Diameter of Binary Tree 

### ISSUE THREAD

**Issue by MadhanVibeeshanan** [LeetCode-Feedback/LeetCode-Feedback#21]
**What kind of the bug**
- [x] Diameter of binary tree

**Describe the bug**
I was trying to solve the problem Diameter of binary tree https://leetcode.com/problems/diameter-of-binary-tree. I submitted the solution but for one test case, I'm getting the wrong answer. When I see tree visualization, it looks like my solution is correct but the expected output is different. 

**The code you submit/run**
```
class Solution:
    def diameterOfBinaryTree(self, root: TreeNode) -> int:
        
        def path_calculator(root, count, count_list):
            count += 1
            if root.left:
                path_calculator(root.left, count, count_list)
            if root.right:
                path_calculator(root.right, count, count_list)
            if not root.left and not root.right:
                count_list.append(count)
                print(count_list)
            return max(count_list)

        return (path_calculator(root.left, 0, []) if root.left else 0) + (path_calculator(root.right, 0, []) if root.right else 0) if root else 0
'''

**Expected behavior**
Testcase: [4,-7,-3,null,null,-9,-3,9,-7,-4,null,6,null,-6,-6,null,null,0,6,5,null,9,null,null,-1,-4,null,null,null,-2]
output: 7
Expected: 8

**Screenshots**
![image](https://user-images.githubusercontent.com/17287153/76153547-8ddc4d80-608a-11ea-8be5-d414d73c3ae9.png)


**Additional context**
Add any other context about the problem here.

**Comment by idealism-xxm** [comment]
> Given a binary tree, you need to compute the length of the diameter of the tree. The diameter of a binary tree is the length of the **longest** path between any two nodes in a tree. **This path may or may not pass through the root.**

The last sentence explains that the path **may not** include the root.
So the longest path is [-1, 0, 6, 9, -9, -7, 6, 9, -2] whose length is 8.

**Comment by CooperCooperCooper** [comment]
Hi @MadhanVibeeshanan,

Thank you for reaching out to us! We've tested your solution. The test case you pointed out has output as "7" and expected output as "8" for both "Run Code" and "Submit". Please make sure you scroll down for all of "Run Code" results because sometimes the expected output might be lower than usual. Please check out [this code](https://leetcode.com/problems/diameter-of-binary-tree/discuss/328480/Python3-solution-beats-89) for some more inspiration to solve this problem. We appreciate your time and support.
