### ISSUE TITLE
Incorrect editorial - 1750. Minimum Length of String After Deleting Similar Ends

### ISSUE THREAD

**Issue by przemek3d88** [LeetCode-Feedback/LeetCode-Feedback#21001]
### LeetCode Username
przemysaw2

### Problem number, title, and link  
1750. Minimum Length of String After Deleting Similar Ends https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends

### Category of the bug
- [ ] Problem description
- [ ] Solved examples
- [ ] Problem constraints
- [ ] Problem hints
- [ ] Incorrect or missing "Related Topics"
- [ ] Incorrect test Case *(Output of test case is incorrect as per the problem statement)*
- [ ] Missing test Case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*
- [x] Editorial
- [ ] Programming language support

### Description of the bug
The ending of the tail recursion editorial is incorrect. It says that the space is $O(n)$ because of the call stack, but the editorial mentions that tail recursion reuses the frame, hence the space is $O(1)$.

**Comment by LC-Pam** [comment]
Hello,

Thank you for reaching out to us.

Your reported issue has been promptly relayed to our dedicated team for thorough investigation. We appreciate your patience and understanding as we work to address and resolve this matter.

Rest assured, we will reach out to you as soon as we have the results and updates regarding the issue.

Once again, thank you for your support and cooperation. If you have any further questions or concerns in the meantime, please feel free to let us know.

Best regards,
LeetCode Support Team

**Comment by LC-Pam** [comment]
Thanks for bringing up this potential point of confusion. Tail recursion is an optimization that may reduce the space necessary, but the the worst-case complexity will remain the same. Because it is situation dependent compiler-level optimization, asymptotic notation cannot accurately measure it. The availability of tail recursion optimization(TRO) depends on the compiler and its optimization settings. Not all compilers or compiler configurations perform TRO, and some may only do so under certain conditions.
