### ISSUE TITLE
Provided Solution is failing - [907. Sum of Subarray Minimums]

### ISSUE THREAD

**Issue by rishabhsairawat** [LeetCode-Feedback/LeetCode-Feedback#2103]
#### Your LeetCode username
RishabhSairawat

#### Category of the bug
- [x] Question

#### Description of the bug

The solution provided in the Solution tab is failing for every large test case. Either that needs to be fixed or removed.

#### Code you used for Submit/Run operation

```
class Solution {
    public int sumSubarrayMins(int[] A) {
        int MOD = 1_000_000_007;
        int N = A.length;

        // prev has i* - 1 in increasing order of A[i* - 1]
        // where i* is the answer to query j
        Stack<Integer> stack = new Stack();
        int[] prev = new int[N];
        for (int i = 0; i < N; ++i) {
            while (!stack.isEmpty() && A[i] <= A[stack.peek()])
                stack.pop();
            prev[i] = stack.isEmpty() ? -1 : stack.peek();
            stack.push(i);
        }

        // next has k* + 1 in increasing order of A[k* + 1]
        // where k* is the answer to query j
        stack = new Stack();
        int[] next = new int[N];
        for (int k = N-1; k >= 0; --k) {
            while (!stack.isEmpty() && A[k] < A[stack.peek()])
                stack.pop();
            next[k] = stack.isEmpty() ? N : stack.peek();
            stack.push(k);
        }

        // Use prev/next array to count answer
        long ans = 0;
        for (int i = 0; i < N; ++i) {
            ans += (i - prev[i]) * (next[i] - i) % MOD * A[i] % MOD;
            ans %= MOD;
        }
        return (int) ans;

    }
}
```

#### Language used for code
Java

#### Expected behavior

Solution using approach 1 from the solution tab needs to be fixed or removed.

#### Screenshots

NA

#### Additional context

If the reason for this failure can be explained, then it would also be great. I spent a lot of time debugging this still unable to figure out.

**Comment by lc-kay** [comment]
Hi @rishabhsairawat 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@rishabhsairawat Thank you for your time. Here's why the code failed:
The issue is on line 31.
ans += (i - prev[i]) (next[i] - i) % MOD A[i] % MOD;

The (i - prev[i]) * (next[i] - i) part is causing an integer overflow because of the way programs are evaluated. All of the variables in that calculation are int, so Java does multiplication on them as that. It doesn't matter that it's going into a long variable (have a read about int overflow during calculations).

Here is a (not so elegant, but it works) fix to the problem.

ans += (i - (long)prev[i]) ((long)next[i] - i) % MOD A[i] % MOD;

**Comment by rishabhsairawat** [comment]
@lc-kay Thanks for the explanation. I thought there was something wrong with the solution.

**Comment by ManaswitaDatta** [comment]
Have been looking all over the place for the solution. Ty guys!!
