### ISSUE TITLE
Missing Test Case - 1800. Concatenation of Consecutive Binary Numbers

### ISSUE THREAD

**Issue by srivatsapillutla** [LeetCode-Feedback/LeetCode-Feedback#2158]
#### Your LeetCode username

srivatsapillutla

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

Java solution using BigInteger function

#### Description of the bug

When submitted, compiler is showing memory limit for one test case, when same code is submitted again it is showing tle for some other case (42904) and same code is showing tle for another case (9757), all these errors are giving correct output when given as CUSTOM INPUT.

#### Code you used for Submit/Run operation

```import java.util.*;
import java.lang.*;
import java.math.*;
class Solution {
    public int concatenatedBinary(int n) {
        
        int p=1, q=0;
        String ss = "";
        while(p<=n)
        {   
            ss += Integer.toBinaryString(p);     
            p++;  
        }
        BigInteger ty = new BigInteger(ss,2);
        BigInteger b1 = new BigInteger("1000000007");
        
        ty = ty.mod(b1);
        int ans = ty.intValue();
        
        return ans;
  
    }
}
```

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};```

#### Language used for code
<!-- C++ -->
JAVA


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->
It was supposed to execute or show an error for aa particular testcase which is not supposed to run when tried as custom input, but in contrast it is running in custom input but not when submitted.



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->



#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by lc-kay** [comment]
@srivatsapillutla When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page, or posting your code there to get support from other users!
