### ISSUE TITLE
[BUG] - Missing Critical Assumtion Description For 30. Substring with Concatenation of All Words

### ISSUE THREAD

**Issue by Fenardle** [LeetCode-Feedback/LeetCode-Feedback#21771]
### LeetCode Username

James_Jone

### Problem Number, Title, and Link

https://leetcode.com/problems/substring-with-concatenation-of-all-words/submissions/1210347169/

### Bug Category

Problem description, Problem constraints

### Bug Description

I'm trying to reopen a closed issue here because is closed withou actually solving the issue.

The official solution won't be correct for the following input:

s = "ooooooooooooooooooooooooooooooo" word = ["oo", "oo"]

The official solution would have the following answer: `[0, 2, 4, 6, 8...]` because it is making an assumtion that every substring starts at n * wordLength, which is not in the problem description

However, The correct answer should be `[0, 1, 2, 3, 4, 5...]` instead of `[0, 2, 4, 6, 8...]`.

Hope you can fix this by adding the assumtion to the problem description so other people don't get confused.

### Language Used for Code

None

### Expected behavior

The official solution would have the following answer: `[0, 2, 4, 6, 8...]` because it is making an assumtion that every substring starts at n * wordLength, which is not in the problem description.

However, The correct answer should be `[0, 1, 2, 3, 4, 5...]` instead of `[0, 2, 4, 6, 8...]`.

**Comment by sahil-a333** [comment]
The official solution has the answer as [0,2,4,6,8,10,12,14,16,18,20,22,24,26,1,3,5,7,9,11,13,15,17,19,21,23,25,27]  and according to this issue the answer should be [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27] 

Just notice that after covering the index in multiple of  "word size" which is "2"  here the code is covering other indices too and it is reflecting in the "official solution". As shown in image below.

![Screenshot 2024-04-18 032454](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/114415059/0cb05be7-6ded-4497-bdc4-38fcf9128047)




And in description its mentioned that "Return an array of the starting indices of all the concatenated substrings in s. You can return the answer in any order"  so order dosent matter.

The issue is that there is less space on screen so the full output is not visible on leetcode "_Test Result" window. 
Just recheck it on leetcode.
