### ISSUE TITLE
[BUG] - The state of variables saves between test cases in the same run

### ISSUE THREAD

**Issue by apischan** [LeetCode-Feedback/LeetCode-Feedback#21821]
### LeetCode Username

apischan

### Problem Number, Title, and Link

House Robber https://leetcode.com/problems/house-robber/

### Bug Category

Incorrect test case *(Output of test case is incorrect as per the problem statement)*

### Bug Description

Having couple of consecutive test-cases each next text will reuse the same instance of `accum` (see 'Used code'). It is unexpected that the state of object will be kept.
Tried similar code in Java - it creates every time the new object with a fresh inner instances (in my case `HashMap`).

### Language Used for Code

Scala

### Code used for Submit/Run operation

```bash
object Solution {
    val accum = new java.util.HashMap[Int, Int]()
    
    def rob(nums: Array[Int]): Int = {
        dp(nums.length - 1, nums)
    }

    def dp(i: Int, nums: Array[Int]): Int = {
        if (i == 0) nums(0)
        else if (i == 1) Math.max(nums(0), nums(1))
        else {
            if (!accum.containsKey(i)) {
                val a = Math.max(dp(i - 1, nums), dp(i - 2, nums) + nums(i))
                accum.put(i, a)
            }
            accum.get(i)
        }
    }
}
```

### Expected behavior

Each test-case will be run in a fresh environment.

**Comment by andrescmasmas** [comment]
This issue has been closed for two years, but for what it’s worth, the root cause is that @apischan’s solution uses a Scala `object` (as provided by the LeetCode Scala template).

In Scala, `object`s are singletons, so the same instance is reused for the entire lifecycle of the program. As a result, any mutable state (like `accum`) persists across test cases unless it is explicitly reset.

In contrast, the Java template uses a `class`. This allows the LeetCode runner to instantiate a new object (`new`) for each test case and invoke `rob` on that fresh instance. Because each instance has its own state, there’s no leakage between test cases.

That’s why the Java version "_creates every time the new object with a fresh inner instances_" each time, while the Scala version does not.
