### ISSUE TITLE
Incorrect value as per description of the problem

### ISSUE THREAD

**Issue by adityarar** [LeetCode-Feedback/LeetCode-Feedback#21874]
### LeetCode Username

BlueSpirit

### Problem Number, Title, and Link

2444. Count Subarrays With Fixed Bounds leetcode.com/problems/count-subarrays-with-fixed-bounds/

### Bug Category

Problem description

### Bug Description

I have a testcase which gives incorrect o/p when run against Leetcode's test code.

Test input that gives incorrect result:
nums: [1,2,3,4,5,3,4,5]
minK: 3
maxK: 5

Possible valid sub arrays in this case are these 19 sub arrays:
<pre>

1 2 3 4 5
  2 3 4 5
    3 4 5
1 2 3 4 5 3
  2 3 4 5 3
    3 4 5 3
      4 5 3
        5 3
1 2 3 4 5 3 4
  2 3 4 5 3 4
    3 4 5 3 4
      4 5 3 4
        5 3 4
1 2 3 4 5 3 4 5
  2 3 4 5 3 4 5
    3 4 5 3 4 5
      4 5 3 4 5
        5 3 4 5
          3 4 5
</pre>

One can see here that the output should be 19.

### Language Used for Code

None

### Code used for Submit/Run operation

```bash
Code not submitted as this issue comes with an example test case.
```

### Expected behavior

Expected result should be 19. Leetcode expects 11 instead.

### Screenshots

![2444 Wrong output](https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/23469679/94dc9200-703f-46a0-be97-71bba35bc871)

**Comment by TrickyCat** [comment]
@adityarar Please try to read the problem statements carefully.

> You are given an integer array nums and two integers minK and maxK.
> 
> A fixed-bound subarray of nums is a subarray that satisfies the following conditions:
> 
> - The minimum value in the subarray is equal to minK.
> - The maximum value in the subarray is equal to maxK.
>
> Return the number of fixed-bound subarrays.
> 
> A subarray is a contiguous part of an array.


 And pay attention to these lines:

- `The minimum value in the subarray is equal to minK.`

  - this implies:
    - the presence of minK in the subarray
    - the absence of any x < minK in the subarray

- `The maximum value in the subarray is equal to maxK.`

  - this implies:
    - the presence of maxK in the subarray
    - the absence of any x > maxK in the subarray

---

Let's consider your input:
```
nums: [1,2,3,4,5,3,4,5]
minK: 3
maxK: 5
```
This means: give me the number of subarrays each of which:
- has a minimum value 3
- has a maximum value 5

Since the minimum required value is 3 we **MUST NOT** consider any subarrays with 1 or 2. And after filtering them out from your list we'll be left with:

```
    3 4 5
    3 4 5 3
      4 5 3
        5 3
    3 4 5 3 4
      4 5 3 4
        5 3 4
    3 4 5 3 4 5
      4 5 3 4 5
        5 3 4 5
          3 4 5
```

### **And there are 11 of them❗❗❗**

![](https://c.tenor.com/uRc1vj-bIc4AAAAC/tenor.gif)

**Comment by adityarar** [comment]
@TrickyCat Thank you for the detailed explanation. Could you help me understand why some of my subarrays are invalid?

You are right. I had a brain freeze while working on this example. Cleary my subarrays have items outside the boundry.
