### ISSUE TITLE
637. Average of Levels in Binary Tree, output and expected not matching

### ISSUE THREAD

**Issue by abhasg** [LeetCode-Feedback/LeetCode-Feedback#223]
**What kind of the bug**
- [ ] solution

**Describe the bug**
When I am trying to run the code for question #637, the answer expected and output is not matching as I think expected is wrong. Please check the same attaching the screenshot.

**Screenshots**
<img width="1280" alt="Screen Shot 2020-04-30 at 2 54 54 AM" src="https://user-images.githubusercontent.com/1539534/80691883-7780ca00-8aee-11ea-952b-5cfbe239c7e9.png">

**Comment by soulxhacker** [comment]
I've also posted this on their forums. Leetcode guys, please fix this asap.

**Comment by zhongyin-hu** [comment]
I'm seeing the same issue on my end, too. Will appreciate it if anyone could help fix it.

**Comment by CooperCooperCooper** [comment]
Hi @abhasg ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @abhasg ,
Thank you for your time. We've fixed this issue and the outputs and expected results are back to normal now. 

This issue is found to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution. We appreciate your support and understanding.
