### ISSUE TITLE
[BUG] - Too strict runtime on Submit (but not Run)

### ISSUE THREAD

**Issue by resotto** [LeetCode-Feedback/LeetCode-Feedback#22650]
### LeetCode Username

resotto

### Problem Number, Title, and Link

3165. Maximum Sum of Subsequence With Non-adjacent Elements https://leetcode.com/problems/maximum-sum-of-subsequence-with-non-adjacent-elements/description/

### Bug Category

Problem constraints

### Bug Description

Time complexity of the following code will be `nums.length * 17 + queries.length * 17 <= 2 * 5 * 10^4 * 17 = 1.7 * 10^6` where `nums.length, queries.length <= 5 * 10^4`.

Even by considering constant factors, time complexity would be at most `1.7 * 10^6 * 30 (constant factors) = 5.1 * 10^7`.
And I got TLE on Submit while getting reasonable runtime on Run.

Please fix the too strict runtime on Submit.

Also, please consider this as well: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/22434
Why is 10^8 time complexity accepted for the Medium problem but is 10^7 time complexity TLE for this Hard problem ???

### Language Used for Code

Java

### Code used for Submit/Run operation

```java
class Solution {
    private int n = 7 * (int) 1e4; // < 2^17
    private long mod = (long) 1e9 + 7L;
    private long[][] seg = new long[2 * n][4];
    public int maximumSumSubsequence(int[] nums, int[][] queries) {
        for (int i = 0; i < nums.length; i++) {
            update(i, nums[i]);
        }
        long ans = 0;
        for (int[] q : queries) {
            update(q[0], q[1]);
            ans = (ans + Math.max(Math.max(seg[1][0],seg[1][1]), Math.max(seg[1][2],seg[1][3]))) % mod;
        }
        return (int) ans;
    }
    private void update(int i, long val) {
        i += n;
        seg[i][0] = val;
        while (1 < i) {
            i >>= 1;
            long[] left = seg[i << 1], right = seg[(i << 1) + 1];
            long l0n1 = left[0], l0n2 = left[1], l1n1 = left[2], l1n2 = left[3];
            long r0n1 = right[0], r0n2 = right[1], r1n1 = right[2], r1n2 = right[3];
            seg[i][0] = Math.max(l0n1 + r1n1, l0n2 + r0n1) % mod;
            seg[i][1] = Math.max(l0n1 + r1n2, l0n2 + r0n2) % mod;
            seg[i][2] = Math.max(l1n1 + r1n1, l1n2 + r0n1) % mod;
            seg[i][3] = Math.max(l1n1 + r1n2, l1n2 + r0n2) % mod;
        }
    }
}
```

### Expected behavior

AC on Submit without TLE

### Screenshots

<img width="1440" alt="Screenshot 2024-06-08 at 16 37 18" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/19743841/5080105b-4ff6-47fb-b133-7119b3b72d02">

**Comment by resotto** [comment]
Any updates?

**Comment by tredsused40** [comment]
Complexity != runtime, big O notation is just used to approximate runtime and efficiency, but constant factor is a thing. For example, take a look at the following codes:
```
#include<bits/stdc++.h>
#pragma GCC optimize("O0")

using namespace std;

int main() {
    //freopen("txt.txt", "w", stdout);
    int t = clock();
    int n = 1000000000;
    unsigned int ans = 0;
    for(int i = 0; i < n; i++)
        ans++;
    cout << ans << "\n";
    cout << clock() - t << "\n";
    return 0;
}
```
Runtime is 1.7 seconds on my PC. Now, if we change O0 to O1, the code runs in 0.24 seconds. And if we change it to O2 or O3 or Ofast, then the runtime is 0 seconds, because compiler understands that the result is equal to n. But even without any optimizations whatsoever 1e9 operations take 1.7 seconds.
Now, check this code:
```
#include<bits/stdc++.h>
#pragma GCC optimize("O0")

using namespace std;

int main() {
    //freopen("txt.txt", "w", stdout);
    int t = clock();
    int n = 1000000000;
    unsigned int ans = 0;
    int mod = 3;
    for(int i = 0; i < n; i++)
        ans += 1ll * i * i % mod;
    cout << ans << "\n";
    cout << clock() - t << "\n";
    return 0;
}
```
This code runs in 9.9 seconds. If we change O0 to O1, it runs in 0.87 seconds. If we change it to O2, O3 or Ofast, then it runs in 0.73 seconds. And if we change mod to be equal 59471, then for O0 runtime is 8.3 seconds, and for all O1, O2, O3 and Ofast it is 0.97 seconds. As you can see it is kind of hard to predict the runtime, and complexity of each code is the same O(n).
Lets take a careful look at the very first code: it executes n comparisons i < n, and 2n increments. All of that in 1.6 seconds. It is all about constant factors and compiler optimizations.

And in yours case it is just how leetcode works. The TL criteria seems to be not just runtime on a testcase is at most x seconds, but also total runtime across all testcases is at most y seconds. Your code meets the first one, but for each class creation you initialize ```private long[][] seg = new long[2 * n][4];```, and there are 526 testcases. All you have to do it to make sure that you don't initialize too much unnecessary memory, and your code will pass easily. I rewrote your code to C++ but without initializing more than needed each time, and it passed with 387ms.
