### ISSUE TITLE
[BUG] - Creating a new session is not supported

### ISSUE THREAD

**Issue by liu00222** [LeetCode-Feedback/LeetCode-Feedback#22883]
### LeetCode Username

liu00222

### Problem Number, Title, and Link

N/A

### Bug Category

Editorial

### Bug Description

I cannot create a new session in Leetcode. The button is gray and non-clickable. 

Here is a screenshot:
<img width="1352" alt="Screenshot 2024-06-26 at 2 08 51 PM" src="https://github.com/LeetCode-Feedback/LeetCode-Feedback/assets/42081599/39488701-18b8-4b7a-a3fe-e403098e96a7">

### Language Used for Code

None

### Expected behavior

I should be able to create a new session for problem practice.

**Comment by lizdenhup** [comment]
Hi -- I understand the "new session" feature is deprecated. However, I want to note this deprecation is a huge pain point to me as a user. When I'm preparing for interviews, I typically do so in various "rounds". Not being able to start a new session is horrible. e.g. I don't care if I've solved a problem back in 2021 -- I need to refresh on the problem _now_ and thus it's annoying to see the problem notated as "solved" in my profile. Removing this feature has made Leetcode (almost) unusable in my opinion. It might juice your statistics for time spent on platform (since now I have to manually reset all of my code submissions to be blank and then keep track of whether I've solved the problem myself) but this is a great disservice to the end user.

**Comment by holmes1313** [comment]
any update?

**Comment by luffy-118** [comment]
OMG, this is the most ridiculous change Leetcode made. The alternative problem list feature is not as useful at all. I literally will stop my Leetcode premium account and move to other platforms right now because of this change. Does anyone know any alternative platforms that are a good place to practice coding problems?

**Comment by AZouhair** [comment]
I unsubscribed today from Leetcode Premium because of this change (I've been subscribed for years).

The only way I can see to get back what I had (the option of restarting a new run of problems without having to reset them one by one) is to create a new account, which does not mix with paying for premium. I am still stuck on my account because the next period is already paid, but I will not trade the ease of restarting for the perks on Premium.

Seriously, this is not a good idea.

**Comment by codeAnand** [comment]
Seriously, I have a leetcode premium too.
Just came back to prepare for interviews and then saw this.

Does anyone know any alternative platforms that are a good place to practice coding problems?

**Comment by MayankBatra005** [comment]
Not at all a great idea! It came as a bummer to me. I have been a premium member for many years. There should be at least an option to have two sessions—one for history and one for reset.

**Comment by zavarka** [comment]
Very frustrating, and ridiculous.

**Comment by Selena9955** [comment]
I need to separate records in different languages, and manually adding the lists is really awful.

**Comment by kcnkrt** [comment]
Interview prep is a stressful process filled with self-doubt. Looking up how many problems you solved is a motivating factor, seeing those numbers go up gives more hope in efforts to land that job. I think it shouldn't be disabled until something better replaces it and "problem list" is simply not that.

**Comment by maynouf** [comment]
This is totally a deal-breaker for me

**Comment by nirty-fai** [comment]
This is totally un-useable for now. Please bring back sessions feature.

**Comment by ARogueOtaku** [comment]
Dude, are you kidding me? Who thought it was a good idea to remove such a widely used feature?

**Comment by alebask** [comment]
Huge disappointment.

**Comment by officeMohitDev** [comment]
What is the yellow bar they are talking

**Comment by guda249** [comment]
Had i know this feature has been removed, would have never opted for LC premium. This just kinda sucks. Please a add feature "return back LC subscription" that would be a great addition to LC.

**Comment by caycekoehler** [comment]
Sadly won't be signing up for premium because the lack of this feature. Would be annoyed if it was a feature only for premium users as well, but if you have to give us a reason to sign up might as well include this one....

**Comment by sid2700** [comment]
this is disappointing

**Comment by joellopes03** [comment]
I don't want to organize problems. I want to organize my solutions. I like to code in several languages. Profile helps me organize.

**Comment by satheshshiva** [comment]
This is a deal breaker. Makes using Leetcode frustrating.

**Comment by abidmuin** [comment]
Welp, time to find alternatives.
Not gonna manually reset all the problems that I solved earlier.
Thank God I didn't go for the annual subscription.

**Comment by avovk** [comment]
Create a new account with a new email each time you're interviewing.

**Comment by caycekoehler** [comment]
While a technically correct solution, this is absolutely awful to suggest. The simplicity it is to support this feature is shocking someone would approve to remove it. Even if someone argued there are too many users using it too much or even too many users not using it. Limit it to 5 saves per account.

Beyond that, even if it comes down to tracking total completed solves or some variation of this, you can easily create a "first time solved" value that adds bytes of data to the system per user which wouldn't be extremely bad even over the course of the service.

There are probably a dozen ways this can be supported and has already proved valuable to the process of interviewing from a service that prides itself on being the industry standard... Again. Shocking.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pinkfloyda** [comment]
Agree, on this I also find this is a deal breaker, the moment I know this getting deprecated or not acted on, I immediately cancel my yearly auto-renew

**Comment by theoreticalboypf94** [comment]
LeetCode Support Team are you reall so stuрid?  All peope wrote that update is awfull, return session managment back.

Best regard, your mother's friend.

**Comment by raghav2903** [comment]
Are you kidding me? I just signed up for LC premium today after a 2 year hiatus and saw this. How can I start my prep now? I literally have all my solutions from before. This is horrible!

**Comment by seabeya** [comment]
Well, as a solution I deleted my account and created a new one. When I logged into the new one, I saw all my old account stats still there and said, hell nah, ain't no way. Turns out it was just cache :)). Dude, that gave me a shock for a second, felt like there is no way to escape from your old progress. But we good now.

**Comment by ashiskumar123** [comment]
+1 on above comments. Please bring back this feature. Or add a feature to bulk add problems (leetcode 75) to lists.

**Comment by ashiskumar123** [comment]
I think this has something to do with people sharing subscriptions. With this feature its easy to keep separate sessions, probably bad for the business.

**Comment by bringhurst** [comment]
This change breaks how I use leetcode. I periodically come back to practice problems every few months and reset to a new session each time.

Now, when I go to solve problems, they're already solved.

The new problem list feature isn't a replacement for sessions at all. The only solution I'm seeing is to manually go into every problem I've solved and reset them one by one, which isn't very practical.

**Comment by parasguglani1** [comment]
@bringhurst not from leetcode
but clearning your leetcode cache and cookies should clear all the code which is in the editor for all the problems.

**Comment by sukanyasahaintel** [comment]
I'm also unsubscribing because of this; it's more advantageous to have several free accounts.

**Comment by WeirdJack** [comment]
Dumbcode!

**Comment by KatelynKim** [comment]
What is the alternative to this? Is there any way to reset progress?

**Comment by francisco-camargo** [comment]
Was considering getting back into Leetcode and re-subscribing to Premium if I can reset everything then I will look for other solutions.

**Comment by ajilk** [comment]
I was able to reset progress for a given problem list using the reset progress button

note:
- this action did not remove all my code submissions ✅
- this action did not affect other lists that contained the same question ✅
<hr />
<img width="432" alt="Image" src="https://github.com/user-attachments/assets/3257d6d2-5a52-4f42-a297-42fc60b2d50a" />

<img width="539" alt="Image" src="https://github.com/user-attachments/assets/e1be5002-1a00-4d99-8513-f0c2b94581cf" />

**Comment by wtinch** [comment]
I sign up for all of the above. Suddenly found out that it doesn't work anymore and got frustrated, you're literally forcing people to create new accounts. 
I tried to use problem lists, but it turns out that now I need to manually add all of the problems into it. 
Ugh, LeetCode, **PLEASE** reconsider your decision! Bring this feature back, or at least give something equally convenient!

**Comment by wtinch** [comment]
Just a quick follow-up because I really needed the missing feature.

I made a **userscript** that brings the old workflow back without touching your global stats.  
It adds a **“New Session”** button in the sidebar, creates a private list with *every* problem, resets its counters, and keeps the list auto-synced every day. 

Repo (one-click install with Tampermonkey):  
https://github.com/wallandteen/leetsession

Give it a spin if you’re tired of manually rebuilding lists.  
⭐️ Feedback, stars, and PRs are very welcome. Hope this helps until LC brings this option back.

<img width="1681" height="938" alt="Image" src="https://github.com/user-attachments/assets/a1fc6c76-fb52-47a8-99a2-21bbb89dc55d" />

**Comment by hengliu0919** [comment]
It is such a stupid decision to remove this valuable feature.

**Comment by pinkfloyda** [comment]
Like the ones answered above, the same feature can be mitigated using list and click reset button and seems only work in list. May come into handy if you want to solve problems in company list or topic list, etc.

**Comment by rohitdurvasula** [comment]
Here's my workaround for anyone who depended on Sessions:

**Requirement**: Need to be able to start fresh on entire LeetCode's problem set, track progress, if needed reset progress anytime

**Steps**:

1. Create a new smart list with name of your choice. In my case `XYZ`

<img width="444" height="323" alt="Image" src="https://github.com/user-attachments/assets/6e4a0f00-6ca7-4247-b30c-8aa8071f4ec3" /><br>


2. Edit rule to ONLY include `Status` and add all 3 status's - `Todo`, `Attempted` and `Solved` and hit `Save`.

<img width="510" height="357" alt="Image" src="https://github.com/user-attachments/assets/cd688b8d-2ed4-4b49-8340-8a81af9541f9" /><br>


3. Now at this point, if you have attempted/solved some questions in the past it will show up in the progress widget like so.

<img width="361" height="226" alt="Image" src="https://github.com/user-attachments/assets/009d429f-8f5f-4725-9fe8-414e0185fe42" /><br>


4. At this point, you can reset it, by clicking on top right corner of the progress widget, and hitting the `Reset` button.

<img width="386" height="281" alt="Image" src="https://github.com/user-attachments/assets/11a8860d-a156-4185-99f6-21fbdccb2aeb" />

<img width="494" height="204" alt="Image" src="https://github.com/user-attachments/assets/0c4869d9-2a8d-46d5-9b4d-bcdba8808873" /> <br>

Note: This only resets the List's status and not the global status seen on homepage for problems here https://leetcode.com/problemset. There appears to be no way to reset the solved status here, but luckily looks like it won't come in the way if you are using smart list feature as described here.

5. At this point, you should have a clean slate of Leetcode's all problems as part of this Smart List called `XYZ`

<img width="358" height="527" alt="Image" src="https://github.com/user-attachments/assets/eefc4546-4c8f-49f9-a4b9-2d7b95b6a7b9" /><br>

6. Usage - Solving a problem like 2 SUM in this list should result in a problem URL like this:

https://leetcode.com/problems/two-sum/description/?envType=problem-list-v2&envId=<smart-list-encoded-id>

This is visually visible from the top left of the problem where the list name shows up.

<img width="1008" height="324" alt="Image" src="https://github.com/user-attachments/assets/2d6c817e-2514-41f4-91ab-fbcb57cf1d1e" /><br>
