### ISSUE TITLE
wrong test runtime -------------84. Largest Rectangle in Histogram

### ISSUE THREAD

**Issue by smilelc3** [LeetCode-Feedback/LeetCode-Feedback#2295]
#### Category of the bug
- [ ] Question

https://leetcode.com/problems/largest-rectangle-in-histogram/

#### Description of the bug

Using the 0ms code provided on the submission page, under the current test example, it takes at least 80ms. It is suspected that other complicated test examples have been added later 

#### Code you used for Submit/Run operation

```
func largestRectangleArea(heights []int) int {
    
    stack := make([]int, 0)
    l := len(heights)
    res := 0
    
    for i := 0; i <= l; i++ {
        var h int
        if i == l { 
            h = 0 
        } else {
            h = heights[i]
        }
        
        for len(stack) > 0 && h < heights[stack[len(stack)-1]] {
            currH := heights[stack[len(stack)-1]]
            stack = stack[:len(stack)-1]
            
            prevIdx := -1
            if len(stack) > 0 { prevIdx = stack[len(stack)-1] }
            w := i - prevIdx - 1
            res = max(res, currH*w)
        }
        stack = append(stack, i)
    }
    return res
}

func max(a, b int) int {
    if a > b { return a }
    return b
}
```

#### Expected behavior

![image](https://user-images.githubusercontent.com/35222695/107149789-9f625f80-6995-11eb-8fc2-7c6a9f0e3feb.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/35222695/107149765-85288180-6995-11eb-9e90-fa26714cc018.png)

**Comment by lc-kay** [comment]
@smilelc3 It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

Lastly, we update the distribution graph regularly to account for additional test cases. I hope this explanation answers your doubts.
