### ISSUE TITLE
Incorrect returns - 4. Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by daveachyut** [LeetCode-Feedback/LeetCode-Feedback#2306]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Difference in what the function returns and what it prints for the same variable.

#### Code you used for Submit/Run operation

```
class Solution(object):
    def findMedianSortedArrays(self, nums1, nums2):
        """
        :type nums1: List[int]
        :type nums2: List[int]
        :rtype: float
        """
        res = sorted(nums1 + nums2)
        if len(res) % 2:
            return res[int(len(res) / 2)]
        else:
            print(float(res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2)
            return float((res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2)
```

#### Expected behavior
No difference in print and return for the same variable.

#### Screenshots
![LeetCode 2021-02-07](https://user-images.githubusercontent.com/46184578/107166485-6addac00-6973-11eb-869f-7fc608573630.png)

**Comment by subhamX** [comment]
Hey @daveachyut , actually the two expressions aren't the same, that's why there is a difference in the printed value and returned value.

In `float(res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2`, you are performing `float/integer` division which will implicitly return your answer in `float` after float divison.
```
float(2+3)/2
float(5)/2
2.5000
```
In the case of `float((res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2)` you are performing `integer/integer` division and then typecasting as `float`. 
```
float((2+3)/2)
float(5/2)
float(2)
2.0000
```

### Any fixes?
1. Consider using `(res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2.0`. In this way you are performing `integer/float` division. 
2. You can also do `float(res[int(len(res) / 2) - 1] + res[int(len(res) / 2)]) / 2`. In this way you are performing `float/integer` division.
Both of the above will yield correct solution.

**Comment by lc-kay** [comment]
@daveachyut I hope @subhamX's reply answered your doubts and concerns. Thank you both for your time and support.
