### ISSUE TITLE
lack of required test case

### ISSUE THREAD

**Issue by harshvardhan1212** [LeetCode-Feedback/LeetCode-Feedback#23220]
### LeetCode Username

harshkparekh12

### Problem Number, Title, and Link

Strictly Palindromic Number  https://leetcode.com/problems/strictly-palindromic-number/description/

### Bug Category

Missing test case *(Incorrect/Inefficient Code getting accepted because of missing test cases)*

### Bug Description

for this code, you should add a test case to check for number 2396

### Language Used for Code

C++

### Code used for Submit/Run operation

```bash
class Solution {
public:
    bool isStrictlyPalindromic(int n) {
        return false;
    }
};
```

### Expected behavior

code should be very long

**Comment by stormsunshine** [comment]
If n = 4, then n is NOT strictly palindrome under base 2 (since 4 is represented as "100" under base 2, which is not a palindrome).

If n > 4, then n is NOT strictly palindrome under base n - 2 (since n is represented as "12" under base n - 2, which is not a palindrome).

It can be proven that for any test case, the answer should be false. Why do you think there should be a test case that returns true?

If you think a test case is missing, please provide a concrete test case. If you can't think of such a test case, please think of why the answer is always false.
