### ISSUE TITLE
[BUG] - Example 2 has incorrect answer

### ISSUE THREAD

**Issue by MichaelLeonffu** [LeetCode-Feedback/LeetCode-Feedback#23423]
### LeetCode Username

MichaelLeonfu

### Problem Number, Title, and Link

791. Custom Sort String https://leetcode.com/problems/custom-sort-string

### Bug Category

Problem examples

### Bug Description

In example 2, the example answer `bacd` is incorrect. The order must be `b, c, a`.

### Language Used for Code

None

### Expected behavior

In example 2, the example answer `bacd` should be `bdca` or `dbca`.

Note that `bcad` and `bcda` are already listed

**Comment by MichaelLeonffu** [comment]
I believe `bacd` is still incorrect.

Quoting the explanation:

> Explanation: The characters "b", "c", and "a" from order dictate the order for the characters in s. The character "d" in s does not appear in order, so its position is flexible.

> Following the order of appearance in order, "b", "c", and "a" from s should be arranged as "b", "c", "a". "d" can be placed at any position since it's not in order. The output "bcad" correctly follows this rule. Other arrangements like "bacd" or "bcda" would also be valid, as long as "b", "c", "a" maintain their order.

`bacd` does not follow the order of "b", "c", "a".

**Comment by stormsunshine** [comment]
I also think "bacd" is incorrect. This is regarding the last sentence in Example 2.

> Other arrangements like `"bacd"` or `"bcda"` would also be valid, as long as `"b"`, `"c"`, `"a"` maintain their order.

For the characters that exist in both `order` and `s`, in the result string, these characters should be in the same order as in `order`. In Example 2, the characters that exist in both `order` and `s` are `"a"`, `"b"` and `"c"`. Since `order = "bcafg"`, these three characters should have the order as `"bca"`. Since `s` contains a character `"d"` that is not in `order`, which can be at any index in the result string, the result string should be generated as follows.

1. Add `"bca"` to the result string.
2. Add `"d"` at any indices in the result string. There are four indices to add `"d"`, so the possible result strings include: `"dbca"`, "`bdca`", `"bcda"` and `"bcad"`.

The possible result strings do not include `"bacd"`.
