### ISSUE TITLE
Bug - 801. Is Graph Bipartite?

### ISSUE THREAD

**Issue by Harry-Yang-Huang** [LeetCode-Feedback/LeetCode-Feedback#2380]
#### Category of the bug
- [*] Question
- [ ] Solution
- [ ] Language

#### Code you used for Submit/Run operation

```
N/A
```

**Comment by lc-kay** [comment]
@Harry-Yang-Huang Please provide a more detailed report so we can better troubleshoot the issue.

**Comment by Harry-Yang-Huang** [comment]
Hi,
Actually the steps are:
1) open the link: https://leetcode.com/explore/challenge/card/february-leetcoding-challenge-2021/585/week-2-february-8th-february-14th/3639/
2) Click "Contribute" on the button of the web page
3) The auto-generated title of the bug report says "**801.** Is Graph Bipartite?", but actually the problem number of "Is Graph Bipartite?" is **785**

**Comment by lc-kay** [comment]
@Harry-Yang-Huang The question ID may not be the same between the Explore section and problem page because we have an internal problem ID and a public question ID. The auto-generated title shows the internal question ID, whereas the public question ID is the one mentioned on the problem page. I apologize for the confusion that this may have caused.
