### ISSUE TITLE
Compiler Issues - 18. 4Sum

### ISSUE THREAD

**Issue by de-codes** [LeetCode-Feedback/LeetCode-Feedback#2421]
#### Category of the bug

- [x] Solution
- [x] Language

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public static List<int[]> FourSum(int[] array, int targetSum) {
            var allPairSum=new Dictionary<int,List<int[]>>();
            var result= new List<int[]>();
            for(int i=0;i<array.Length-1;i++){
                for(int j=i+1;j<array.Length;j++){
                    int remainingSum=targetSum- (array[i]+array[j]);
                
                    if(allPairSum.ContainsKey(remainingSum)){
                        foreach(var item in allPairSum[remainingSum]){
                            result.Add(new int[]{item[0],item[1],array[i],array[j]});
                        }
                    }
                }
                for(int k=0;k<i;k++) {
                    int sum=array[i]+array[k];
                    int[] item=new int[] {array[i],array[k]};
                    if(!allPairSum.ContainsKey(sum)){
                        List<int[]> pairGroup=new List<int[]>();
                        pairGroup.Add(item);
                        allPairSum.Add(sum,pairGroup);
                    }else{
                        allPairSum[sum].Add(item);
                    }
                }
            }
        
            var dic = new Dictionary<string, int[]>();
            foreach (var item in result)
            {
                string key = string.Join(",", item.OrderBy(c=>c));
            
                if (!dic.ContainsKey(key))
                {
                    dic.Add(key, item);
                }
            }
            
            return dic.Values.ToList();
            //return result;
        }
};
```

#### Language used for code
C#

#### Expected behavior
The above mentioned code is working perfectly fine in my local machine .
OS- MacOS
Framework- .Net Core
IDE- Rider
But it is giving compiler issues in Leetcode.

input: FourSum.FourSum(new int[] {-2,-1,-1,1,1,2,2}, 0);
output : expected two arrays [-1,-1,1,1],[-2,-1,1,2]

**Comment by lc-kay** [comment]
@de-codes Here is the error message for your code Line 18: Char 19: error CS0176: Member 'Solution.FourSum(int[], int)' cannot be accessed with an instance reference; qualify it with a type name instead (in __Driver__.cs)
Line 19: Char 16: error CS0266: Cannot implicitly convert type 'System.Collections.Generic.List<int[]>' to 'System.Collections.Generic.IList<System.Collections.Generic.IList<int>>'. An explicit conversion exists (are you missing a cast?) (in __Driver__.cs) Since we do not have the necessary information to your local machine, we are unable to troubleshoot the cause of the different results. In the discuss section, I was able to find many accepted C# solutions, so please use them as a reference. https://leetcode.com/problems/4sum/discuss/?currentPage=1&orderBy=most_relevant&query=C%23 Thank you for your time.
