### ISSUE TITLE
People downvoting fresh discuss post to promote their own post with youtube link in it.

### ISSUE THREAD

**Issue by Glazomer** [LeetCode-Feedback/LeetCode-Feedback#2445]
#### Your LeetCode username
dan2000kr

#### Category of the bug
- [X] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
I am here to discuss a issue happening mostly for monthly challenge's daily problems and new problems that appear after contests. Every day there are much people who want to create very intuitive, well explained  solution in discuss section. We start to work on problem right when problem appears and can spend up to one hour doing it with illustrations and well edited text, but there is group of people, who just post their code, link to youtube channel and downvote all other top posts. I would propose to do something with this, one of the solution of this abuse is to **turn off downvote on new post for 24 hours**, so people with fake accounts or a chat of friend wouldn't destroy our posts and reputation (one downvote per 5 minutes doesn't help).
There are actually few more ideas, but I think that proposition would be best and most satisfying for most people/

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code
C++

#### Expected behavior
**Limit downvote for new discuss for 24 hours.**

#### Additional context
We (LeetCode fans) really looking for any response for this problem

**Comment by lc-kay** [comment]
@Glazomer I've relayed your valuable feedback to our team to take into consideration. We understand that the downvoting system needs some improvements to increase the overall quality of our discuss section. Since this issue to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. 
We encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.
