### ISSUE TITLE
"Example testcases" bug: 524. Longest Word in Dictionary through Deleting

### ISSUE THREAD

**Issue by Leader-board** [LeetCode-Feedback/LeetCode-Feedback#2462]
#### Your LeetCode username
Leaderboard

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

Clicking the option to use example test cases inserts only one test, despite there being two in the question itself.

#### Code you used for Submit/Run operation

Not applicable.

#### Language used for code

Not applicable.
#### Expected behaviour

Two test cases should be inserted upon clicking "Use Example Cases", instead of one.

#### Additional context

The only test cases that shows up is
```
"abpcplea"
["ale","apple","monkey","plea"]
```

**Comment by lc-kay** [comment]
@Leader-board I've relayed this issue to our team to investigate. Since this is not a content-related issue, I will close this ticket now. In the future, we encourage you to share more content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). Thank you again for your support and understanding.

**Comment by lc-kay** [comment]
@Leader-board Our team has fixed this issue. Thanks again for reporting it, we greatly appreciate your time and support!
