### ISSUE TITLE
Submission  Problem

### ISSUE THREAD

**Issue by AVNV2201** [LeetCode-Feedback/LeetCode-Feedback#25]
I submitted my solution and got Accepted status during Contest.
Problem No. 1376

After I got Accepted on submitted , T moved to the next problem.
But after the contest was over, when I saw my ranking, there it was not showing my submission.
What this happened ?
Never happened before !!!!

When I saw all my submissions, it was given Internal error.
What is this ?
What should I do now?

My solution was correct as when I submitted again, it got accepted again.

![image](https://user-images.githubusercontent.com/37290032/76157328-6ee2c780-612d-11ea-91cd-3b94041b7079.png)

**Comment by grawlixes** [comment]
I don't know if this is related, but I believe there's an issue with the solution checker for this problem in LeetCode's backend. Right now I'm trying to run a function that simply returns 0 on all input, but I'm getting TLE for some of the sample cases.

**Comment by CooperCooperCooper** [comment]
Hi @AVNV2201,
Thank you for raising these issues to our attention! I am so sorry about your inconvenience. Our engineers have been notified of the "Internal Error" from during the contest, and they are working on resolving the issue.

**Comment by CooperCooperCooper** [comment]
Hi @grawlixes,
Thank you for raising the TLE issue. Are you still experiencing TLE for the problem you were working on? If so, can you please more about the problem by filling out a separate issue template with more details, so we can better assess this issue? We appreciate your support and help.

**Comment by CooperCooperCooper** [comment]
Hi @AVNV2201,
Good news! We've identified the issue for "Internal Error" and have since rejudged the affected submissions properly. Because we're working on recalculating the contest results still, you may notice some inconsistencies or otherwise outdated rankings in the meantime. There will be more updates for this contest on our General Discuss Section. Here's our current update: https://leetcode.com/discuss/general-discussion/535726/Update%3A-Errors-in-Weekly-Contest-179. 

We appreciate your time and support. If you have any other questions about the contest, please ask us in the help-center here: https://support.leetcode.com/hc/en-us.
