### ISSUE TITLE
1054. Distant Barcodes

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#252]
**What kind of the bug**
- [x] problem
- [ ] solution
- [ ] language

**Describe the problem**
The problem is equivalent to [767. Reorganize String](https://leetcode.com/problems/reorganize-string/). There is also no solution provided for 1054 even though both the solutions provided for 767 will work for 1054. 
The problem description could be updated to make users aware of the other problem while also giving them access to solutions already posted with it. Such changes have already been made for pairs like (316, 1081) and (476, 1009).

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @leet212 ,
Thank you for your time. You're right that these two problems are very similar to each other; however, due to the problem conditions, [Distand Barcodes](https://leetcode.com/problems/distant-barcodes/) is more difficult than [Reorganize String](https://leetcode.com/problems/reorganize-string/), which makes them different from each other. Therefore, we've decided to keep these two problems as-is. We appreciate your support and understanding.
