### ISSUE TITLE
Missing Test Case - 628. Maximum Product of Three Numbers

### ISSUE THREAD

**Issue by alexbprofit** [LeetCode-Feedback/LeetCode-Feedback#2536]
#### Your LeetCode username
user8391WG

#### Category of the bug
- [ ] Question

#### Description of the bug
All testcases to work but it fails on submit (time limit exceeded)

#### Code you used for Submit/Run operation

```
import math
import sys
class Solution:
    def maximumProduct(self, nums: List[int]) -> int:
        results = []
        for i in range(len(nums)):
            for j in range(len(nums)):
                for k in range(len(nums)):
                    if i != j and j != k and i != k:
                        results.append(nums[i]*nums[j]*nums[k])
        return max(results)
```

#### Language used for code
Python 3

#### Expected behavior
This solution must work expected ( i.e you write invalid testcases)

#### Screenshots

![image](https://user-images.githubusercontent.com/57172679/109419851-40ae6580-79d8-11eb-877e-2cffb60cbe1c.png)

**Comment by lc-kay** [comment]
@alexbprofit When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page, or posting your code there to get support from other users! Thank you for your time.
