### ISSUE TITLE
637. Average of Levels in Binary Tree

### ISSUE THREAD

**Issue by singinzrain** [LeetCode-Feedback/LeetCode-Feedback#267]
**What kind of the bug**
- [x] problem
- [x] solution
- [ ] language

**Describe the bug**
Pass the submission but indicating wrong when running code result.

**what language is your code written in**
Java

**The code you submit/run**
```
class Solution {
    public List<Double> averageOfLevels(TreeNode root) {
        List<Double> res = new ArrayList<>();
        Queue<TreeNode> queue = new LinkedList<>();
        queue.add(root);
        while (!queue.isEmpty()) {
            int size = queue.size();
            double temp = 0.0;
            for (int i = 0; i < size; i++) {
                TreeNode cur = queue.poll();
                temp += cur.val;
                if (cur.left != null) queue.add(cur.left);
                if (cur.right != null) queue.add(cur.right);
            }
            res.add(temp / size);
        }
        return res;
    }
}
```

**Expected behavior**
Test case: 
[3,9,20,15,7]

Output: 
[3.00000,14.50000,11.00000]

Expected:
11.00000]

The output and expected should be the same. The expected result seems broken.

**Comment by AZAamerZaheer** [comment]
Came here to report the same. See screenshot.
<img width="1440" alt="Screen Shot 2020-05-05 at 10 27 03 PM" src="https://user-images.githubusercontent.com/50094609/81143828-a2708100-8f27-11ea-9669-50a3421c9397.png">

**Comment by CooperCooperCooper** [comment]
Hi @singinzrain ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @singinzrain ,

Thank you for your time. We've fixed this issue and the outputs and expected results are back to normal now. 

This issue is found to be non-content-related (the issue stems from an origin away from the content on this problem); therefore, it's not valid for content contribution reward. We encourage you to share other content-related issues here with us for [valid content contribution rewards](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). We appreciate your support and understanding.
