### ISSUE TITLE
1789. Primary Department for Each Employee Wrong Discription

### ISSUE THREAD

**Issue by xcheng10** [LeetCode-Feedback/LeetCode-Feedback#2756]
#### Your LeetCode username

JenniferYe1997

#### Category of the bug
-   Question
- [ ] Solution
- [ ] Language

#### Description of the bug

As mentioned "Note that when an employee belongs to only one department, their primary column is 'N'.", however in test case #10: {"headers":{"Employee":["employee_id","department_id","primary_flag"]},"rows":{"Employee":[[1,59,"N"],[2,44,"N"],[3,27,"N"],[4,29,"N"],[5,40,"Y"]]}}, employee_id = 5 with one department but the primary flag is 'Y'.

#### Code you used for Submit/Run operation

```
with cte as (
select employee_id,
    department_id,
    count(department_id) over (partition by employee_id) as ct,
    case when primary_flag = 'Y' then 1 else 0 end as flag
from employee
)

select employee_id,
    department_id
from cte
where (ct > 1 and flag = 1) or (ct = 1 and flag = 0)
```

#### Language used for code

MSSQL

**Comment by lc-kay** [comment]
@xcheng10 The primary_flag is an ENUM of type ('Y', 'N'). If the flag is 'Y', the department is the primary department for the employee. If the flag is 'N', the department is not the primary. In test case 10,  employee_id = 5 has multiple departments and department 40 is their primary department, which is why there is a 'Y'. If you have any further doubts, please raise your question in the discuss section of this problem. Thank you for your time.

**Comment by xcheng10** [comment]
Thank you for your update. I can only see one department with department_id = 40 for employee_id = 5 in test case #10.
