### ISSUE TITLE
O(N) solution beats O(LogN) solution in problem 35

### ISSUE THREAD

**Issue by orbitbyrd** [LeetCode-Feedback/LeetCode-Feedback#283]
**What kind of the bug**
- [ ] problem
- [ ] solution
- [ ] language

**Describe the bug**

**what language is your code written in**
C++

**The code you submit/run**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
To help us further assess this issue, would you please provide the related submitted code and what language it was written in here with us? Thank you.

**Comment by CooperCooperCooper** [comment]
Hi @orbitbyrd ,
Since you haven't responded to our previous request, we've reviewed the issue base on the provided information. Most of the time O(N) will beat O(log N) solution, and due to our technical limitations, it won't be possible to devise a large enough test case such that O(log N) solution will prevail. We appreciate your time and support.
