### ISSUE TITLE
Missing Test Case - 1151. Minimum Swaps to Group All 1's Together

### ISSUE THREAD

**Issue by johnhjwu** [LeetCode-Feedback/LeetCode-Feedback#3122]
#### Category of the bug
- [ 1151] Question
- [ ] Solution
- [ C] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test cases are success, but will happen TLE when I submit the code.

#### Code you used for Submit/Run operation

```
int countOnes(int* array, int aSize) {
    
    int counterOfOne = 0;
    for (int index= 0; index< aSize; index++) {
        if (array[index]==1) {
            counterOfOne++;
        }
    }
    return counterOfOne;
}

int minSwaps(int* data, int dataSize){
    
    int totalOnes = countOnes(data, dataSize);
    int maxOnesC = 0; 
    int tmpOnesC = 0;
    
    //printf("Total ones elements are %d.\n", totalOnes);
    
    if (totalOnes == 0) return 0;
    
    for (int hWin = 0; hWin < dataSize-totalOnes; hWin++) {
        tmpOnesC = countOnes(data+hWin, totalOnes);
        // printf("TMP ones elements are %d.\n", tmpOnesC);
        if (maxOnesC< tmpOnesC) {
            maxOnesC = tmpOnesC;
        }
    }
    return totalOnes - maxOnesC;
}
```

**Comment by lc-kay** [comment]
@johnhjwu When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users.

Thank you for your time.

**Comment by johnhjwu** [comment]
Thanks for your reply. But I am afraid the TLE met here is the same test case I passed during run code. Captured screen below, FYR.

**Comment by lc-kay** [comment]
@johnhjwu The test case you see on the "details" page shows which test case the program stops running at when the time limit has exceeded; it's not a test case that causes your program to exceed the time limit. I hope this understands your doubts and concerns.
