### ISSUE TITLE
TLE only while submitting

### ISSUE THREAD

**Issue by Nirav-Madhani** [LeetCode-Feedback/LeetCode-Feedback#3123]
#### Category of the bug

- [x]  Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The same piece of code runs successfully but while submitting it gives TLE 

#### Code you used for Submit/Run operation

```
class Solution {
public:
    vector<string> removeInvalidParentheses(string s) {
        vector<int> pos;
        for(int i=0;i<s.size();i++)
            if(s[i] ==')' || s[i]=='(')pos.push_back(i);
        int n = pos.size(),len=0;
        cout<<pos.size();
        vector<string> ans;
        unordered_set<string> tempans;
        for(int i=0;i<(1<<n);i++){
            string temp = s;
            for(int j=0;j<n;j++){
                if((i>>j)&1)temp[j]='!';
            }
            //cout << temp<< endl;
            auto v = valid(temp);
            if(v!="000"){            
                tempans.insert(v);
                int sz = v.size();
                len=max(len,sz);
            }
        }
        for(auto st:tempans)
            if(st.size()==len)
            ans.push_back(st);
        return ans;
    }
    string valid(string s){
        int cnt=0;
        string str;
        for(char c:s)
        {
            if(c==')' && cnt==0)return "000";
            else if(c==')')cnt--;
            else if(c=='(')cnt++;
            if(c!='!')str+=c;
        }
        if(cnt==0)return str;
        return "000";
    }
};
```

#### Language used for code

C++

#### Expected behavior

TLE should not come in either or come in both

#### Screenshots

![image](https://user-images.githubusercontent.com/77914957/114887343-fd904080-9e25-11eb-86a2-57cb7d0831de.png)

**Comment by lc-kay** [comment]
@Nirav-Madhani When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:
Your code has an underlying infinite loop.
Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users.

Thank you for your time.
