### ISSUE TITLE
Missing Test Case - 19. Remove Nth Node From End of List

### ISSUE THREAD

**Issue by geoff-wasilwa** [LeetCode-Feedback/LeetCode-Feedback#3159]
#### Your LeetCode username

gwasilwa

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This is more of a question really. Are the test cases biased towards removing elements closer to the end? I submitted two solutions one scanning from the beginning and the other from the end. The second one outperforms the first even though both use two passes.

#### Code you used for Submit/Run operation

```
// Two Sum
/* Scans from the beginning */
var removeNthFromEnd = function(head, n) {
    let sz = 1;
    for (let curr = head; curr.next; curr = curr.next, sz++) {
    }
    const dummy = { next: head }
    for (let i = 0, curr = dummy; curr; curr = curr.next, i++) {
        if (sz - i === n) {
            curr.next = curr.next.next;
        }
    }
    return dummy.next;
};

/* Scans from the end */
var removeNthFromEnd = function(head, n) {
    const btm = { next: head };
    const stack = [btm];
    let curr = head;
    while (curr) {
        stack.push(curr)
        curr = curr.next;
    }
    for (let i = 0; i < n; i++) {
        stack.pop();
    }
    const preNth = stack.pop();
    preNth.next = preNth.next.next
    return btm.next;
};
```

#### Language used for code

Javascript

#### Expected behavior

The performance should be nearly the same.

#### Screenshots

<img width="589" alt="Screenshot 2021-04-18 at 17 58 19" src="https://user-images.githubusercontent.com/6013054/115150336-8e5a5c80-a070-11eb-8b02-a7bee62dc80c.png">

<img width="642" alt="Screenshot 2021-04-18 at 17 50 59" src="https://user-images.githubusercontent.com/6013054/115150345-9914f180-a070-11eb-880c-d8f70fa9f019.png">

**Comment by LC-Pamela** [comment]
Hi @geoff-wasilwa 
Thanks for reaching out to us. It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts.

**Comment by geoff-wasilwa** [comment]
I'll keep that in mind. Thanks for the clarification.
