### ISSUE TITLE
Bug Report - 29. Divide Two Integers

### ISSUE THREAD

**Issue by kanhayaKy** [LeetCode-Feedback/LeetCode-Feedback#3233]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

My code gives Time Limit Exceeded error on submission. But when I try to run the same code using the same input values , the code executes successfully and gives the expected output. I believe there is some ambiguity here . Attaching my code below .

#### Code you used for Submit/Run operation

```
// Divide two integers 
class Solution {
public:
    int divide(int dividend, int divisor) {
        long num1 = dividend;
        long num2 = divisor;
        int quotient = 0;
        int sign = (dividend<0 && divisor>0)||(dividend>0 && divisor<0)? -1 : 1; 
        
        if(num1<0) num1*=-1;
        if(num2<0) num2*=-1;
        
        if(num1 == num2) return 1*sign;
        if(num1 < num2) return 0;
        if(num2 == 1){
            if(num1*sign>INT32_MAX) return INT32_MAX;
            return num1*sign;  
        } 
        
        
        while(num1>=num2){
            num1-=num2;
            quotient++;
            if(quotient*sign>INT32_MAX or quotient*sign<INT32_MIN) return INT32_MAX;
        }
        
        return quotient*sign;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Ambiguity in the results for same input values
Input values :
-2147483648
4

Output when testing 
-536870912

Output when submitting
Time limit exceeded

#### Screenshots

![Screenshot from 2021-04-24 16-48-17](https://user-images.githubusercontent.com/54493708/115960223-cc062c00-a52d-11eb-81cd-ecafd91ad75a.png)
![Screenshot from 2021-04-24 16-46-36](https://user-images.githubusercontent.com/54493708/115960228-d0324980-a52d-11eb-9c91-a9311861d484.png)

**Comment by lc-kay** [comment]
@kanhayaKy When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:

- Your code has an underlying infinite loop.
- Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users.
