### ISSUE TITLE
880. Decoded String at Index

### ISSUE THREAD

**Issue by sagarchand9** [LeetCode-Feedback/LeetCode-Feedback#325]
---
name: Bug report (English)
about: Create a bug report to help us improve our content.
title: ''
labels: ''
assignees: ''

---

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language

#### Description of the bug
It is related to the accepted solution. Even if 'K' is greater than length of decoded string, we are receiving in the answer. No where in the question it is mentioned that the length of decoded string should be less than that of 'K'
The problem statement does not talk about what to return in case k is greater than the length of the decoded string.

#### Additional context
More specifically, the case that I am talking about should not be allowed as a valid case, and the problem statement should explicitly mention that. In other words, the 4th point in the Note section should be updated to:

    1 <= K <= min(10^9, length of the decoded string)

**Comment by CooperCooperCooper** [comment]
Hi @sagarchand9 ,
Thank you for reaching out to us. Could you please share a solution here (including its language) that matches the scenario you've mentioned?

**Comment by sagarchand9** [comment]
Actually it is not related to the problem or the solution I submitted, but it is related to the "ACCEPTED SOLUTION" code. In the problem mentioned(#880), the answer is being returned even when K > length of decoded string(which should not be the case). 

Try this
"leet2code3"
1000
It still returns answer as 't', where as it should return something like -1 or empty character as the viable solution is not possible

**Comment by CooperCooperCooper** [comment]
Hi @sagarchand9 ,
Thank you for the information. Can you please further clarify where you found the "ACCEPTED SOLUTION" code from? For example, is it from the [Problem Solution](https://leetcode.com/problems/decoded-string-at-index/solution/) tab?

**Comment by sagarchand9** [comment]
Yes

**Comment by CooperCooperCooper** [comment]
Hi @sagarchand9 ,
Thank you for your answer. Perhaps you did not edit the code editor + you only put in the test case in the console, and then ran the test case?

**Comment by sagarchand9** [comment]
yes. That is correct

**Comment by CooperCooperCooper** [comment]
Hi @sagarchand9 ,
Thank you for your confirmation. We tested the test case you've provided on Run Code in the method you've provided (did not edit the code editor + only put in the test case in the console); however, we got a Compile Error from the test case. Please see screenshots attached for the results we've received.

If you've received different results or noticed that there was a mis-step on our verification process, please share screenshots like this (with the code + results) to help us further identify the issue. We appreciate your support.

<img width="1440" alt="Screen Shot 2020-06-09 at 12 48 55 PM" src="https://user-images.githubusercontent.com/59751300/84193207-eaffea80-aa4f-11ea-9d93-2b7e720c49d6.png">
<img width="1431" alt="Screen Shot 2020-06-09 at 12 49 06 PM" src="https://user-images.githubusercontent.com/59751300/84193225-efc49e80-aa4f-11ea-8e6a-9958016eb965.png">

**Comment by roll-no-1** [comment]
Hi @CooperCooperCooper!
The op is referring to a case when k is greater than the length of the decoded string. I've solved this problem and also didn't consider this case, and I don't think many people did since the problem statement does not talk about what to return in case k is greater than the length of the decoded string.

Here's a screenshot of lee215's code running on the same input: 
![image](https://user-images.githubusercontent.com/36921843/84260215-478a0500-ab37-11ea-832c-1a0c9c508606.png)

More specifically, the case that the op is talking about should not be allowed as a valid case, and the problem statement should explicitly mention that. In other words, the 4th point in the Note section should be updated to:

4. 1 <= K <= min(10^9, length of the decoded string)

**Comment by sagarchand9** [comment]
Yes @roll-no-1, you have correctly understood the issue. 
Thanks

**Comment by sagarchand9** [comment]
Also, I believe, code in the backend should also change

**Comment by CooperCooperCooper** [comment]
Hi @roll-no-1 , thank you for the explanation. 

The issue is we require all information to be filled in in order for us to reproduce the exact issue. 

@sagarchand9 , please edit the issue and fill out all the required information as specified and required on the [issue template](https://github.com/LeetCode-Feedback/LeetCode-Feedback/blob/master/.github/ISSUE_TEMPLATE/bug-report--english-.md). Thank you.

**Comment by sagarchand9** [comment]
@lc-kate , have edited the issue. 
Thanks

**Comment by lc-christina** [comment]
Hi @sagarchand9 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-christina** [comment]
Hi @sagarchand9 
Thank you for your time. We've used your feedback to update the problem. Can you please let us know your leetcode user name so we can reward you with leetcoins?

**Comment by sagarchand9** [comment]
@lc-pam glad I could be helpful.
My username is [sagarchand](https://leetcode.com/sagarchand/) in leetcode

**Comment by lc-pam** [comment]
Hi @sagarchand9 
Thanks for providing your username. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
