### ISSUE TITLE
Solution submission problem for Find All Anagrams problem

### ISSUE THREAD

**Issue by jainilvachhani** [LeetCode-Feedback/LeetCode-Feedback#33]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
 I am facing a problem with Find All Anagrams problem. When I use run code feature for the test case ("cbaebabacd" "abc") I am getting correct output ([0,6]). However, when I submit my code, it shows WA for the same input.

**The code you submit/run**
```
class Solution {
public:
    
    bool isAnagram(string a, string b){
        int hashA[26] = {0}, hashB[26] = {0},i;
        for(i=0;i<a.size();i++){
            hashA[a[i]-'a']++;
            hashB[b[i]-'a']++;
        }
        for(i=0;i<a.size();i++){
            if(hashA[i]!=hashB[i]){
                return false;
            }
        }
        return true;
    }
    
    vector<int> findAnagrams(string s, string p) {
        int i,j,hash[s.size()-p.size()+1],expectedHash=0,tempHash=0,tempSum;
        for(i=0;i<p.size();i++){
            expectedHash += p[i] - 'a' + 1;
            tempHash += s[i] - 'a' + 1;
        }
        hash[0] = tempHash;
        j = 1;
        for(i=p.size();i<s.size();i++){
            tempSum += s[j-1] - 'a' + 1;
            tempHash += s[i] - 'a' + 1;
            hash[j] = tempHash - tempSum;
            j++;
        }
        vector<int> indexes;
        for(i=0;i<s.size()-p.size()+1;i++){
            if(hash[i]==expectedHash){
                string temp = s.substr(i,p.size());
                if(isAnagram(temp,p)){
                    indexes.push_back(i);
                }
            }
        }
        return indexes;
    }
};
```

**Expected behavior**
I should be getting AC or WA/TLE for some other test case.

**Screenshots**
PFA

![Capture](https://user-images.githubusercontent.com/13519441/76344641-ea0fcd80-6327-11ea-8cf3-9e48775d3296.PNG)
![Capture](https://user-images.githubusercontent.com/13519441/76344703-06136f00-6328-11ea-9982-72d10312b762.PNG)

**Comment by CooperCooperCooper** [comment]
Hi @jainilvachhani,
Thank you for your patience. We've found and tested your C++ submission for this problem. In the screenshot you've shared with us, you can see for the same test case, the outputs for "Run Code" and "Submit" are different. This output mismatch is caused by "Run Code" and "Submit" running differently. 

When you click on "Run Code", it runs your code on only 1 test case; and when you click on "Submit", it runs your code on all of the test cases for this problem (i.e. for "Find All Anagrams in a String", it runs all 36 test cases at once). This is a frequently reported issue and we've documented here: https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-.
