### ISSUE TITLE
Merge Sorted Array output is different in Leetcode

### ISSUE THREAD

**Issue by rajesh3151** [LeetCode-Feedback/LeetCode-Feedback#338]
**What kind of the bug**
Merge Sorted Array output is different in Leetcode
solution : nums1 = nums1.Take(m).Concat(nums2.Take(n)).OrderBy(x => x).ToArray();
Language: c#

**Describe the bug**
output is different in leetcode editor 

**what language is your code written in**
C#

**The code you submit/run**
```
public static void Merge(int[] nums1, int m, int n, int[] nums2)
		{		
			nums1 = nums1.Take(m).Concat(nums2.Take(n)).OrderBy(x => x).ToArray();	
		}
```

**Expected behavior**
output in leetcode should match with the output in visual studio

**Comment by CooperCooperCooper** [comment]
Hi @rajesh3151 ,
Thank you for reaching out to us. We were unable to reproduce this issue because when we ran your code on Run Code and Submit, it generated Compile Error for both. 

I've also noticed your code had a static variable, which is a cause known for different "outputs" from "Run Code" and "Submit". This is well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
