### ISSUE TITLE
My solution are not present 

### ISSUE THREAD

**Issue by akashshirale14** [LeetCode-Feedback/LeetCode-Feedback#34]
**What kind of the bug**
- [ ] problem
- [ *] solution
- [ ] language

**Describe the bug**
The solutions are absent from my solved.The problem has a green tick which means I solved the problem but when I open the problem, the solution is not present.It just shows an empty function(programming) like its a new problem remaining to be solved.

**The code you submit/run**
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {
        
    }
};
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/46389232/76357702-8c12c400-62ee-11ea-9bad-e6db953dfca9.png)

The above image shows I have solved the problem 905

![image](https://user-images.githubusercontent.com/46389232/76357529-448c3800-62ee-11ea-95d3-9b8e9ed3f0b1.png)

But in this image the code is not present...this is happening  for alot of problems but not all.

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @akashshirale14,
Thank you for reaching out to us! This issue seems to technical-related (the missing solution is potentially related to editor, sessions, or account). Please file this issue to our technical support channel and include your account username in order for us to further assess this issue. We appreciate your time and support.
