### ISSUE TITLE
TLE in O(n^2) solution - 516. Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by astikraj2207** [LeetCode-Feedback/LeetCode-Feedback#3560]
#### Your LeetCode username

astikraj2207

#### Category of the bug
- [ ] Question
-  Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

As per the given constraints O(n^2) solution should be accepted, but it is giving TLE on certain testcases.

#### Code you used for Submit/Run operation

```
// Longest Palindromic Subsequence
class Solution {
public:
    int dp[1001][1001];
    int longestPalindromeSubseq(string s) {
        memset(dp,-1,sizeof(dp));
        return solve(s,0,s.length()-1);
    }
    int solve(string s, int low, int high)
    {
        if(high<low)
            return dp[low][high]=0;
        if(high==low)
            return dp[low][high]=1;
        
        if(dp[low][high]!=-1)
            return dp[low][high];
        
        if(s[low]==s[high])
            return dp[low][high]=2+solve(s,low+1,high-1);
        
        else
            return dp[low][high]=max(solve(s,low+1,high), solve(s,low,high-1));
            
    }
};
```

#### Language used for code

C++

#### Expected behavior

I expected an AC solution, as this is a standard DP problem I checked my code on other platforms and it is correct .

**Comment by lc-kay** [comment]
@astikraj2207 If your code received TLE on our platform, it is because it is not optimized to run all the test cases. I was able to find many C++ codes in the discuss section https://leetcode.com/problems/longest-palindromic-subsequence/discuss/?currentPage=1&orderBy=most_relevant&query=C%2B%2B Please check them out. Likewise, you can post your code on there to receive support on how to optimize it. Thank you for your time.
