### ISSUE TITLE
What's the deal with memory used?

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3581]
#### Your LeetCode username

mallikab

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [ x ] Submission statistics

#### Description of the bug

https://leetcode.com/problems/target-sum/submissions/ I got rid of 3 variables in my submission
submitted 05/20/2021 19:58, compared to the submission at 05/20/2021 19:52
Yet, my memory consumption *increased* by 0.3 MB. I have noticed this is other problems, as well.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@mallika-b It’s very difficult and an ongoing research to evaluate the program’s memory usage and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s memory usage, but a lot of factors exist that make it extremely hard to quantify the memory usage correctly.

The significance of the program’s memory usage we're providing to you is so that you can compare your code with the peaks in the graph. LeetCode uses internal data structures to read input from the file, call your function with that input, get output from your function. They also consume memory, which can't be excluded from the memory shown to you, so memory usage varies per run as well. It is expected that runtime and memory usage for each program will vary with each execution, and executions on different computers will also cause different results for the same code. But we'd like to provide the best possible learning experience, so our team is working on reducing this variation as much as possible. 

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
