### ISSUE TITLE
Potential bug in notification panel

### ISSUE THREAD

**Issue by paragpachpute** [LeetCode-Feedback/LeetCode-Feedback#364]
I found that when I opened my notification panel today (by clicking on the bell button in the navigation bar) I saw an unresolved value. Attaching the screenshot below for better clarity.
![Screen Shot 2020-05-25 at 7 06 09 PM](https://user-images.githubusercontent.com/8281380/82919067-8c147e80-9f43-11ea-9bf3-5925ab3e4f38.png)

**Comment by CooperCooperCooper** [comment]
Hi @paragpachpute ,
Thank you for sharing this issue with us. Our team is notified of this issue and is fixing it. 

I will close this issue for now because this channel is reserved for [these content issues](https://leetcode.com/discuss/general-discussion/526802/File-Problem-and-Solution-Content-Issues-to-Our-GitHub-Public-Feedback-Repo-Now!). If you have any other questions for this issue, please feel free to reach out to the main channel at support@leetcode.com. Thank you!
