### ISSUE TITLE
1465. Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts - timing

### ISSUE THREAD

**Issue by mallika-b** [LeetCode-Feedback/LeetCode-Feedback#3731]
#### Your LeetCode username

mallikab

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 
- [x] Submission statistics

#### Description of the bug

Hi,

I was wondering if the amount of variation in this particular problem's submissions for the same Python3 code was normal? I saw variations between 280ms and 480ms for test case 52. (my overall submission seemed identical to my test timing of this problem, so I just used that test case instead of submitting every time). That's a variation that spans the gamut from saying better than 5% and better than 91% of submissions.

I understand it is difficult to be exact, but I thought this might merit a check.

-Mallika

#### Code you used for Submit/Run operation

```
class Solution:
    '''courtesy: https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts/discuss/668474/python-faster-then-96'''
    def getMax(self, _max: int, cuts: List[int]) -> int:
        last = 0
        for x in cuts:
            ''' I was going to test this vs max, which came out slower the first time, 
            but on repeated large testcase submission, the variation was between 280ms and 488ms,
            so no reason to eschew _max = max(_max,x-last), I don't think '''
            cur = x-last
            if cur > _max:
                _max = cur
            last = x
        return _max
    
    def maxArea(self, h: int, w: int, horizontalCuts: List[int], verticalCuts: List[int]) -> int:
        mod = 1000000007
        horizontalCuts.sort()
        verticalCuts.sort()
        maxh = self.getMax(h - horizontalCuts[-1], horizontalCuts)
        maxv = self.getMax(w - verticalCuts[-1], verticalCuts)
        
        '''I thought this was a test case miss, but in fact _python3_ treats it as if the result was mod'd:
        >>> (10**9-1)%(10**9+7) * (10**9-1)%(10**9+7)
        64
        >>> (10**9-1)%(10**9+7)
        999999999
        >>> 999999999*999999999
        999999998000000001
        '''
        return maxh%mod * maxv%mod
```

#### Language used for code

Python3

#### Expected behavior

Less variability in execution times between runs

**Comment by lc-kay** [comment]
@mallika-b It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by mallika-b** [comment]
As I said, in this case, it seemed the results ran the gamut of all peaks,
that is the only reason why I thought to report it. If it nevertheless does
not seem worthy of investigation, I will let you be the judge of that.
Thanks, Mallika

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
