### ISSUE TITLE
same code, but giving different runtimes and memory usage

### ISSUE THREAD

**Issue by mskrishnacode** [LeetCode-Feedback/LeetCode-Feedback#3876]
#### Your LeetCode username

code links are here
https://leetcode.com/submissions/detail/509383205/       0ms runtime     
https://leetcode.com/submissions/detail/509383582/        4ms runtime   
https://leetcode.com/submissions/detail/509383312/        4ms runtime

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by lc-kay** [comment]
@mskrishnacode Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.
