### ISSUE TITLE
Bug in Memory and Time Report - 387. First Unique Character in a String

### ISSUE THREAD

**Issue by HabibRh26** [LeetCode-Feedback/LeetCode-Feedback#3932]
#### Category of the bug
- [ ] Solution

#### Description of the bug

I think this is more related to the systematic issue. I submitted the same solution multiple times within 10 min time duration and each time it shows me different memory and running time info. </br>

The first (Time- 06/23/2021 11:55 ) there were some comment lines 

 </br>

Second time(Time- 06/23/2021 11:57) same code but removed the comments 

</br>

Third time(Time- 06/23/2021 11:58) same code as the previous 

</br>

#### Code you used for Submit/Run operation

```
class Solution:
    def firstUniqChar(self, s: str) -> int:
        array = [0]*27
        
        for ch in s:
            indx = ord(ch) - ord('a') + 1

            array[indx] += 1
            
        ln = len(s)
        for i in range(0,ln):
            
            val = ord(s[i]) - ord('a') + 1
            if array[val] == 1:
                return i
        else:
            return -1
    
```

#### Expected behavior

My expectation is - It should not give various memory and time usage info for the same code in such a small time frame.

**Comment by lc-kay** [comment]
@HabibRh26 It’s a very difficult and ongoing research to evaluate the program’s runtime and memory usage and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime and memory usage, but there exist a lot of factors that make it extremely hard to quantify the runtime and memory usage correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
