### ISSUE TITLE
Example description error - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by dxb2306** [LeetCode-Feedback/LeetCode-Feedback#3970]
![Screen Shot 2021-06-26 at 08 41 36](https://user-images.githubusercontent.com/83186423/123514807-52d4a380-d65a-11eb-8c31-0ba0497ebd08.png)

#### Your LeetCode username

xuebindong

#### Category of the bug
- [ *] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

You are given an m x n matrix mat and two integers r and c representing the row number and column number of the wanted reshaped matrix. But in the second example, the r and c both should be 2 so that we can get a 2*2 matrix.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

![Screen Shot 2021-06-26 at 08 41 36](https://user-images.githubusercontent.com/83186423/123514807-52d4a380-d65a-11eb-8c31-0ba0497ebd08.png)

**Comment by lc-kay** [comment]
Hi @dxb2306 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-kay** [comment]
@dxb2306 The description is correct. The statement said clearly
If the reshape operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix.
Since this is an invalid reshape operation, we return the original matrix. Thank you for your time.
