### ISSUE TITLE
Missing Test Case - 566. Reshape the Matrix

### ISSUE THREAD

**Issue by manav-06** [LeetCode-Feedback/LeetCode-Feedback#4060]
#### Your LeetCode username

manavmohata123

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

This is the test case:
[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]
42
5
The number of elements in input and output matrix should be equal.
That is, (m * n == r * c) should be followed.
But in this test case it is not the case. 

#### Code you used for Submit/Run operation

```
public:
    vector<vector<int>> matrixReshape(vector<vector<int>>& mat, int r, int c) {
        int n = mat.size(), m = mat[0].size();
        if(n == r)
            return mat;
        
        vector<vector<int>> ans(r, vector<int>(c));
        
        int row = 0, col = 0;
        for(int i=0; i<n; i++)
        {
            for(int j=0; j<m; j++)
            {
                ans[row][col] = mat[i][j];
                col++;
                if(col == c)
                {
                    col = 0;
                    row++;
                }
            }
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The input should be valid.

**Comment by DenisPanchenko** [comment]
@manav-06 , problem description says:
"If the reshape operation with given parameters is possible and legal, output the new reshaped matrix; Otherwise, output the original matrix."
So your statement about "The number of elements in input and output matrix should be equal." is not valid. If the elements count is not equal you just need to return original matrix according to the description because it is a case of wrong parameters.

**Comment by lc-kay** [comment]
@manav-06 The input is valid. Please check out @DenisPanchenko or raise your doubts in the problem discuss section for further discussion. Thank you for your time.
