### ISSUE TITLE
bug in June Leet Code Challenge  

### ISSUE THREAD

**Issue by palashgdev** [LeetCode-Feedback/LeetCode-Feedback#408]
#### Your LeetCode username
palashgdev

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

in the https://leetcode.com/problems/delete-node-in-a-linked-list/ second parameter is undefined in JS

#### Language used for code

Javascript

#### Expected behavior

there should be value

#### Screenshots

<img width="1058" alt="Screenshot 2020-06-02 at 11 28 05 PM" src="https://user-images.githubusercontent.com/29013861/83553431-d0e27b80-a528-11ea-8b2b-ecce49327a50.png">

**Comment by palashgdev** [comment]
@CooperCooperCooper any update on this one?

**Comment by CooperCooperCooper** [comment]
Hi @palashgdev ,
My apologies for the delay in response. Due to the increasing demand for support, we currently have a backlog of tickets. Our team is working hard to provide you with more insights as soon as possible.

Meanwhile, please take at this comment: https://leetcode.com/problems/delete-node-in-a-linked-list/discuss/65557/Doesn't-this-need-a-variable-pointing-to-the-linked-list-(Javascript)/67451.

And make sure your code "Do not return anything from your function" as noted from the problem description.

**Comment by CooperCooperCooper** [comment]
Hi @palashgdev ,
Thank you for your time. Upon reviewing your submission, we found you're missing 

> given only access to that node.

Also, you must not modify the function signature in LC.
