### ISSUE TITLE
Error in Test Case for (#323) Number of Connected Components in an Undirected Graph

### ISSUE THREAD

**Issue by usman-naveed** [LeetCode-Feedback/LeetCode-Feedback#4116]
#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The following test case seems to be incorrect:
4
[[2,3],[1,2],[1,3]]

Shouldn't n=3 for this case? There are only 3 nodes in the graph, yet the test case has n=4 (which implies there are 4 nodes in the graph) Or have I missed something here?

#### Code you used for Submit/Run operation

```
/// Number of Connected Components in an Undirected Graph

class Solution:
    
    # helper method to convert the edges array into an adjaceny list.
    def to_adj_list(self, edges):
        adj_list = dict()
        for x, y in edges:
            if x not in adj_list.keys():
                adj_list[x] = [y]
            elif x in adj_list.keys():
                adj_list[x].append(y)
            if y not in adj_list.keys():
                adj_list[y] = [x]
            elif y in adj_list.keys():
                adj_list[y].append(x)
        return adj_list
                
    # traverse through graph  
    def dfs(self, adj_list , start=0, visited=None):
        if visited is None:
            visited = set()
        if start == 0: 
            keys = iter(adj_list.keys())
            start = next(keys)
        for node in adj_list[start]:
            if node not in visited:
                visited.add(node)
                print(node)
                self.dfs(adj_list, node, visited)
        return visited
        
        
    def countComponents(self, n: int, edges: List[List[int]]) -> int:
        edges = self.to_adj_list(edges)
        count = 1
        visit = self.dfs(adj_list = edges)
        if len(visit) == n:
            return count
        else:
            while(len(visit) < n):
                for i in visit:
                    if i in edges.keys():
                        del edges[i]
                keys = iter(edges.keys())
                start = next(keys)
                visit = self.dfs(adj_list = edges, start = start, visited=visit)
                count +=1
        return count
```

#### Language used for code

Python3

#### Expected behavior

I use the number of nodes in my solution, as a result of the incorrect test case posted above fails my code. 

#### Additional context

Another user also had a similar issue with the following test case:
4
[[0,1],[0,2],[1,2]]

**Comment by lc-kay** [comment]
@usman-naveed The expected output is correct. Please check out the following discuss posts for further clarifications:
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/discuss/171870/Why-is-4-231213-considered-2-connected-components
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/discuss/748615/why-input-4-231213-result-is-2-not-1
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/discuss/306419/why-result-of-4-231213-is-2-not-1
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/discuss/291179/This-looks-like-one-component-to-me-231213
https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/discuss/77590/Since-it-is-undirected-why-the-answer-of-231213-is-2
