### ISSUE TITLE
A new test case should be added to question 1901

### ISSUE THREAD

**Issue by MomoPeking** [LeetCode-Feedback/LeetCode-Feedback#4149]
#### Your LeetCode username
dqzz369

#### Category of the bug
- Missing Test Cases 

#### Description of the bug
A new test case should be added to this problem, which is [[7,1,3,1,2],[6,5,4,2,1]]. Since this answer https://leetcode.com/problems/find-a-peak-element-ii/discuss/1319281/JAVA-An-elegant-extension-of-Find-Peak-Element-I-(O(MlogN)) can pass all the existing tests but not this one.

**Comment by lc-kay** [comment]
<img width="901" alt="Screen Shot 2021-07-14 at 9 45 42 AM" src="https://user-images.githubusercontent.com/70870126/125660642-53077520-1377-4bb4-a551-d8ca00c85f4d.png">
The solution you provided passes the test case you are trying to contribute. Therefore, we will not consider adding it since it will not fail any accepted solutions. Thank you for your time.

**Comment by MomoPeking** [comment]
Hello my friend,

The poster has just changed his answer due to my reply to him yesterday. You can see our short conversation under his poster. I’m sure this test case is useful. Thank you.

dqzz369
