### ISSUE TITLE
Inconsistent Runtime and Memory consumption results for same solution.

### ISSUE THREAD

**Issue by Pa1sathvik** [LeetCode-Feedback/LeetCode-Feedback#4328]
#### Your LeetCode username
user9932r

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
For this problem https://leetcode.com/problems/single-row-keyboard I have submitted the same solution with in a gap of 30 minutes , but I can see Runtime and memory consumption is different in both submissions even though code is same.

#### Code you used for Submit/Run operation

```
class Solution {
    public int calculateTime(String keyboard, String word) {
		
		Map<Character,Integer> hmap = new HashMap<>(26);
		int cnt = 0;
		for(int j=0;j<keyboard.length();j++) {
			
			hmap.put(keyboard.charAt(j), cnt);
			cnt++;
			
		}
		
		int length = 0;
		int lastPos = 0;
		
		for (int i = 0; i < word.length(); i++) {
			
			length += Math.abs(lastPos - hmap.get(word.charAt(i)));
			lastPos = hmap.get(word.charAt(i));

		}

		return length;

	
	
    }
}
```

#### Language used for code
Java

#### Expected behavior
Irrespective of time , every time i submit the same code , Runtime and Memory consumption of the code should be same.

#### Screenshots
![image](https://user-images.githubusercontent.com/11474676/127494213-4df6d6c3-1032-46ec-ba5c-d1c3c4a6b029.png)

**Comment by lc-kay** [comment]
@Pa1sathvik It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by Pa1sathvik** [comment]
Thanks for the explanation @lc-kay .
