### ISSUE TITLE
Problem 27 has runtime issue for Python language when submitting

### ISSUE THREAD

**Issue by juan7732** [LeetCode-Feedback/LeetCode-Feedback#4389]
#### Your LeetCode username
Juan7732

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Test case that is causing submission to fail passes when running just that test case. Issue is within python script that validates the submission.

#### Code you used for Submit/Run operation

```
class Solution:
    def removeElement(self, nums: List[int], val: int) -> int:
        if len(nums) == 0:
            return 0
        elif len(nums) == 1 and nums[0] == val:
            nums[0] = '_'
            return 1
        else:
            removed = 0
            for i in range(len(nums)):
                # identify and replace all values
                if nums[i] == val:
                    removed += 1
                    nums[i] = '_'
            for i in range(removed):
                # Shift _ to the right
                for j in range(len(nums) - 1):
                    if nums[j] == '_':
                        nums[j+1], nums[j] = nums[j], nums[j+1]
            
            return len(nums) - removed
```

#### Language used for code

Python

#### Expected behavior

Submission follows same logic to validate as the test case validator.

#### Screenshots

![image](https://user-images.githubusercontent.com/19902389/128287016-ba72debb-66b1-4152-9951-2f93a79bdaa8.png)

**Comment by lc-kay** [comment]
@juan7732 When you input the failed test case into the test case console and "Run Code", that action only runs that one test case. Since it's only running one specific test case, your algorithm and time complexity was able to successfully run it. However, when you submit the code, it is running ALL the test cases. Therefore, resulting in TLE for possibly one of the following reasons:

1. Your code has an underlying infinite loop.
2. Your algorithm is too slow and has high time complexity.

I'd recommend checking out accepted submissions from the discuss tab of the problem page or posting your code there to get support from other users.

We appreciate your time and support.
