### ISSUE TITLE
Incorrect Solution - Word search

### ISSUE THREAD

**Issue by jgreenrise** [LeetCode-Feedback/LeetCode-Feedback#4528]
https://leetcode.com/problems/word-search/

#### Category of the bug
- [ ] Question

#### Description of the bug

Question stated the following statement in Constraints "board and word consists of only lowercase and uppercase English letters.". Then how come we can assign '#' to the board matrix ?

    // mark the path before the next exploration
    this.board[row][col] = '#';

**Comment by lc-kay** [comment]
Hi @jgreenrise 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @jgreenrise,
Thank you for reaching out. The reason we can assign '#' to the board is precisely because "board and word consist of only lowercase and uppercase English letters." The statement tells us that our input will only contain lower and upper case English letters, but that does not restrict us from using other characters. So we can choose a character that is guaranteed not to appear in the input (like '#') to mark visited locations.
