### ISSUE TITLE
Missing Test Case - 1989. Maximum Number of People That Can Be Caught in Tag

### ISSUE THREAD

**Issue by nshal** [LeetCode-Feedback/LeetCode-Feedback#4677]
#### Your LeetCode username
nshal

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

I see in the description: "A person who is "it" at index i can catch any one person whose index is in the range [i - dist, i + dist] (inclusive) and is not "it".". It looks like the testing solution does not check dist.
For test case:
[0,1,1,1,0,0]
1
The last zero should be unreachable for dist=1, I expect the correct answer is 2, but it's said expected answer is 3.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="298" alt="image" src="https://user-images.githubusercontent.com/41483108/131744808-0c6f15c2-9b7d-401f-8fe9-60c834262a21.png">

**Comment by stormsunshine** [comment]
I think the standard program of problem 1989 is incorrect. I have randomly generated some test cases, and it seems that the expected output is always the minimum between (the count of zeros, the count of ones) in the array `team`. However, this is not correct. As the test case provided in this issue, when `team = [0,1,1,1,0,0]` and `dist = 1`, the correct output should be 2, not 3.
Another test case is as follows.
```
[1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0]
1
```
The expected output is 9. However, the correct output should be 8, since the 1 at index 18 can catch only one 0, so at least one 0 is not catched.

**Comment by nshal** [comment]
It looks like it's fixed
