### ISSUE TITLE
memory usage - 119. Pascal's Triangle II

### ISSUE THREAD

**Issue by Zairates** [LeetCode-Feedback/LeetCode-Feedback#4822]
#### Your LeetCode username

Zairates

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

How does my code (6400 kb) have more memory usage than the example (6300 kb)?

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> getRow(int rowIndex) {
        vector<int> pascal;
        int t=0;
        pascal.push_back(1);
        
        for(int i=1; i<=rowIndex; i++){
            pascal.push_back(1);
            t=pascal[0];
            for(int j=1; j<i; j++){
                pascal[j]+=t;
                t=pascal[j]-t;                
            }
        }
        
        return pascal;
    }
};
```

example code:

```
class Solution {
public:
    vector<int> getRow(int rowIndex) {
        vector<int> a, b;
        a = {1};
        b = a;
        while(rowIndex > 0) {
            b.clear();
            b.push_back(a[0]);
            for(int i = 0; i < a.size() - 1; i++) b.push_back(a[i] + a[i + 1]);
            b.push_back(a[a.size() - 1]);
            a = b;
            rowIndex--;
        }
        return b;
    }
};
```

#### Language used for code

C++

#### Expected behavior

I only used one vector. I expect that my memory usage would be better than the example.

**Comment by lc-kay** [comment]
@Zairates From my testing, your code got 6.2MB and the sample code got 6.5MB. It’s a very difficult and ongoing research to evaluate the program’s memory usage and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s memory, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s memory usage we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different space complexities would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the memory usage of the same program, introducing some level of discrepancy.
