### ISSUE TITLE
Missing Test Case - 53. Maximum Subarray

### ISSUE THREAD

**Issue by fultonm** [LeetCode-Feedback/LeetCode-Feedback#4959]
#### Your LeetCode username
fultonm

#### Category of the bug
- [ ] Question
- [ x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The runtimes of example solutions are completely wrong. I copy and pasted the example "4ms"solution and got 100ms.

#### Code you used for Submit/Run operation

```
func maxSubArray(nums []int) int {
   		if len(nums) == 0 {
		return 0
	}
	maxSum := nums[0]
	for i := 1; i < len(nums); i++ {
		if nums[i-1] > 0 {
			nums[i] += nums[i-1]
		}
		maxSum = max(nums[i], maxSum)
	}
	return maxSum
}

func max(n1, n2 int) int {
	if n1 > n2 {
		return n1
	}
	return n2
}
```

#### Language used for code

Go

#### Expected behavior

I expected the "4ms" example solution to complete on the order of 10ms of less.

#### Additional context

Differences in runtimes this big make me think my solution is significantly slower than it is. I spent a lot of time trying to figure out what's the issue is before just copy and pasting the "fast" solution to find out leetcode is running my solutions on a potato or something.

I found this on other questions too. I think the example run times needs to be recalculated across the board for Go.

**Comment by fultonm** [comment]
Just as an update, this is actually occurring on every question.

**Comment by lc-kay** [comment]
@fultonm It’s very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of the program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by fultonm** [comment]
![Screenshot from 2021-10-05 14-39-02](https://user-images.githubusercontent.com/13190319/136086624-c1450e81-7d3e-40c1-8162-18573661d726.png)

Ok. I understand there would be some variance run times but I just thought I'd let you know its not even close enough to distinguish between O(1) and O(n^3).
