### ISSUE TITLE
48: rotate-image `AddressSanitizer: heap-buffer-overflow`

### ISSUE THREAD

**Issue by KevinColemanInc** [LeetCode-Feedback/LeetCode-Feedback#497]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug
https://leetcode.com/problems/rotate-image/

This test case in Python3:
```
[[1,3],[4,6],[7,9]]
```
> AddressSanitizer: heap-buffer-overflow on address 0x6020000000f8 at pc 0x000000381e09 bp 0x7ffc4a4ba7c0 sp 0x7ffc4a4ba7b8

I understand that the test case is invalid (the problem says the input must be NxN, not NxM), but it should fail more elegantly instead of the above error.

#### Code you used for Submit/Run operation

```
class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        """
        Do not return anything, modify matrix in-place instead.
        """
```

#### Expected behavior
Not throw stack heap error

#### Screenshots
<img width="327" alt="image" src="https://user-images.githubusercontent.com/2381771/84914182-2d3cb380-b070-11ea-9ee9-00a6f19e45f9.png">

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2381771/84914150-22821e80-b070-11ea-9d05-5e60b571f473.png">

**Comment by CooperCooperCooper** [comment]
Hi @KevinColemanInc ,
Thank you for reaching out to us. I've relayed your feedback for the error feature to our engineers. I will close this issue now because this channel is reserved for content issues. If you want to add more information to this feedback, please feel free to add it here and tag me to the comment. We appreciate your support.
