### ISSUE TITLE
Typo in 590. N-ary Tree Postorder Traversal

### ISSUE THREAD

**Issue by JoshAnderson123** [LeetCode-Feedback/LeetCode-Feedback#5053]
#### Your LeetCode username
joshfanderson1

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Error in the solution article, in the line:

> In the implemented strategy we push nodes into stack following the order Top->Bottom and Left->Right

`Left->Right` should be `Right->Left`.

You can see in the solution code that it is infact traversed `Right->Left` at that stage because children are placed in order (Left->Right) on the stack, making it traversed in the reverse order Right->Left).

Therefore the line should say: "push nodes into stack following the order Top->Bottom and **Right->Left**"

**Comment by LC-Sue** [comment]
Hi @JoshAnderson123,
Thank you for your feedback. the author is not talking about traversal order here, they are talking about the order in which the nodes are pushed onto the stack. Regarding the order in which nodes are pushed onto the stack, your feedback and the author appear to agree with each other:

Author: "we push nodes into stack following the order Top->Bottom and Left->Right"

User: "because children are placed in order (Left->Right) on the stack.
