### ISSUE TITLE
Incorrect Solution of Approach 2: Iteration-100. Same Tree

### ISSUE THREAD

**Issue by RunlinXiao** [LeetCode-Feedback/LeetCode-Feedback#5134]
#### Your LeetCode username

EnjoyJourney

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 
#### Description of the bug

The "Approach 2: Iteration" using ArrayDeque, in the following code: it only checks if p.left is null or not, but at this time, if p.left is not null, yet q.left is null, it will try to add a null value to the deq, which should cause NullPointerExceptioin.
```
if (p.left != null) {
          deqP.addLast(p.left);
          deqQ.addLast(q.left);
        }
```

#### Code you used for Submit/Run operation

```
 Using this test case should have NullPointerException.
[1,2,3]
[1,2,null]

```

#### Language used for code

Java

#### Expected behavior

Should have NullPointerException, yet the program ignores it.

#### Additional context

Array_Deque.addLast(Object element)
Parameters: The parameter element is of the type ArrayDeque and refers to the element to be added.

Return Value: The function does not return any value.

Exceptions: The method throws NullPointerException if the passed parameter is NULL.
Reference:
1. [Java Platform SE ArrayQueue-addLast()](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayDeque.html#addLast(E))
2. [ArrayDeque addLast() Method in Java GeeksforGeeks](https://www.geeksforgeeks.org/arraydeque-addlast-method-in-java/)

**Comment by LC-Sue** [comment]
Hi @RunlinXiao 
Thank you for sharing your concern! If/when this article is next updated we will be sure to add comments to help clarify the issue so that future users do not stumble on this section of code.

The reason why this will not cause a NullPointerException is as follows:

The section of code in question is the second if statement shown below:

    if (!check(p.left, q.left)) return false;
    if (p.left != null) {
      deqP.addLast(p.left);
      deqQ.addLast(q.left);
    }
The important thing to notice here is the first if statement.

Because of this first if statement, your concern "if p.left is not null, yet q.left is null, it will try to add a null value to the deq" will never happen.

Why? Because if p.left is not null and q.left is null, then we will have already returned false from the first if statement.

**Comment by RunlinXiao** [comment]
Hi Sue,
Thanks for letting me know, I get it now. Thanks again for your help.

Best wishes,
Runlin Xiao
