### ISSUE TITLE
disjoint set video no sound 

### ISSUE THREAD

**Issue by bosenli** [LeetCode-Feedback/LeetCode-Feedback#5145]
#### Category of the bug

- [ ] Solution

#### Description of the bug

disjoint set video no sound 

#### Expected behavior

I thought it has sound but i dont hear anything 

#### Additional context

 https://leetcode.com/explore/learn/card/graph/618/disjoint-set/3881/

**Comment by LC-Sue** [comment]
Hi @bosenli 
Since we have not heard from you for a while, we will close this ticket now. If you have any new information to share with us, please don't hesitate to share them here with us. Thank you again for your support and understanding.

**Comment by bytrangle** [comment]
I'm also experience no sound in videos in Graph card. What is puzzling about this issue is:
- I'm using Firefox with no extensions installed, and I can play videos from other sites, so that rules out Firefox as the reason.
- However, when playing these Graph videos in Brave browser, they do have sound. So it seems like there is something about Firefox and the video player that cause the absence of sound.
