### ISSUE TITLE
Inconsistent runtime complexity analysis under leetcode learn - singly linked list - add / delete operation

### ISSUE THREAD

**Issue by RioAraki** [LeetCode-Feedback/LeetCode-Feedback#5217]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In leetcode learn, on this [page](https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1288/) shows linked list's runtime complexity for add operation is **O(1)**. On this [page](https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1289/) shows linked list's runtime complexity for delete operation is **O(N)** because `we have to traverse the linked list from the head node to find out prev which will take O(N)`. 

However, `traverse the linked list from the head node to find out prev` also applies to insert operation so this causes inconsistency between the two operations. They shall be both O(1) if you dont take finding the previous node into account or both O(n) if you take finding previous node into account. From my understanding traverse to the previous node is not part of insert or delete so both operations should have O(1) runtime complexity

reference: 
https://en.wikipedia.org/wiki/Linked_list#Singly_linked_lists
https://stackoverflow.com/questions/40443140/time-complexity-in-singly-link-list

**Comment by LC-Sue** [comment]
Hi @RioAraki 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by IvoBiaus** [comment]
Why was this Issue closed? the misleading information was not fixed i came to report the same and checked if anyone else have raised the same question, and this person did.

I have the same thought, the information should be consistent, you should said wither O(1) for "insert" and "delete" if you dont consider the time it takes to find the "prev" node. Or otherwise O(n) for both of them if you do consider that. You cans say it takes O(1) TC for "insert" and O(n) for "delete" since that makes no sense. Should i open a new issue duplicating this and referring it, or can this be re-open ?
