### ISSUE TITLE
creation of large test sets on demand

### ISSUE THREAD

**Issue by user4856vw** [LeetCode-Feedback/LeetCode-Feedback#522]
#### Category of the bug
- [x ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

we encountered the situation in test sets used for measuring code performance (after code is submitted for it) that measurement is not accurate and introduces skews in the reported performance that can only be explained by fairly small test sets. Specifically, we are talking problem 236 and optimization directed towards exiting the recursion as fast as possible once p and q was found. Both with and without this optimization submitted results are 97% faster than all submitted results. Would it be possible to create on demand some large test sets (in this specific case test tree containing some 100 millions of entries) in order to see the expected difference of some 25% in the time performance?

#### Expected behavior

possibility to test code with large test sets if needed, information about test set size used made available.

**Comment by CooperCooperCooper** [comment]
Hi @user4856vw ,
Thank you for reaching out to us. Do you have large test cases that you would like to contribute (and believe should be covered) and any code that counteracts that test case?

**Comment by user4856vw** [comment]
Hello,
yes, I have a specific test case — binary tree with some 100 million nodes
should be created by the system on demand, on demand because it is clear
that it causes some load and should not be done every time. Why is it
needed? It is needed, as described, in the report because it is clear that
on rather small-ish test cases (we had calculated as we had to because
information is not published — some 200 nodes) the results are skewed
substantially. As also described in the report, in particular, for the
problem #236 we had two correct and accepted as such implementations — one
pretty straightforward recursive and another recursive but optimized to
leave the tree as fast as possible once p and q nodes were found. Both were
reported as 97% faster than all other submissions but this cannot be true
from algorithmic viewpoint as if the implementation is optimized for
leaving the tree as fast as possible, it should be 25% faster (on average
0.5 of the tree is visited for p and 0.5 of the tree is visited for q and
total savings then are 0.5*0.5=0.25) and the only reasonable explanation
for difference not showing is up is the small size of the test tree. So, we
don’t have any code that counteracts the test case (tree) but it is clear
that size of the test case is inadequate.

Kind Regards
Ariel Burbaickij

**Comment by lc-kate** [comment]
Hi @user4856vw ,
Thank you for your answer. Would you please list a specific test case and its counter code (plus its language) that you would like us to take a look at?

**Comment by user4856vw** [comment]
Hello LeetCode,
language is C++, problem is #236 and I do not understand what you mean with
"specific test case"? These 97% faster than all other submissions I wrote
about before were for the standard test case you use on a solution after it
is submitted and this test case is too small (educated guess: some 250
nodes). We would need test case with some sizable amount of say 100
millions of nodes. And the same request of large test set on demand applies
to all other problems as well.  So, I hope it is  clear now.

Kind Regards
Ariel Burbaickij

**Comment by lc-christina** [comment]
Hi @user4856vw ​ ,

Thank you for reaching out to us!
It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.
The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.
I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

Best,
Christina
