### ISSUE TITLE
Missing Test Case - 139. Word Break

### ISSUE THREAD

**Issue by markaldham** [LeetCode-Feedback/LeetCode-Feedback#5257]
#### Your LeetCode username
user4092c

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ X] Missing Test Cases 
    - (incorrect test case description)

#### Description of the bug
For problem 139 "Word Break", test case 3 shows an incorrect results:

Example 3:

Input: s = "catsandog", wordDict = ["cats","dog","sand","and","cat"]
Output: false

Output *should* be true (which when you run this testcase, is the correct answer accepted)

#### Code you used for Submit/Run operation
This is not to do with my code - the problem description's expected output does not match what your code returns for this test case.

```
public class Solution 
{
    public bool WordBreak(string s, IList<string> wordDict) 
    {
    }
}
```

#### Language used for code
c#

#### Expected behavior
For example test case 3, the description says output should be false, but that is not the correct answer.

**Comment by LC-Sue** [comment]
Hi @markaldham 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @markaldham,
Thank you for your time. Regarding example 3, the output should be false. The reason is because "catsandog" only has one "d". To break it down, "catsandog" ends with g and only one word ends with g in the wordDict, so we know the last word used must be "dog". Now we have "catsan" but there are no words in the word dict that end with "n" so there cannot be a valid solution. The answer must be false.
