### ISSUE TITLE
Description Test Case - 1884. Egg Drop With 2 Eggs and N Floors

### ISSUE THREAD

**Issue by ClarifyingYAN** [LeetCode-Feedback/LeetCode-Feedback#5270]
#### Your LeetCode username

clarifyingyan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Is the explanation in example 2 right? 
"If it breaks, we know f is between 0 and 8. Drop the 2nd egg starting from floor 1 and going up one at a time to find f within 7 more drops. Total drops is 1 + 7 = 8."
I think it takes within 8 more steps to find f. And total drops is 1 + 8 = 9.

**Comment by LC-Sue** [comment]
Hi @ClarifyingYAN,
Thank you for reaching out. The explanation appears to be correct, drop the 1st egg at floor 9. If it breaks, we know f is between 0 and 8. Drop the 2nd egg starting from floor 1 and going up one at a time to find f within 7 more drops. Total drops is 1 + 7 = 8 because we are going up from floor 1 and proceeding with 7 more drops after the initial drop breaks because we know that f is between 0 and 8, so the total drop should be 1 +7. Here is a similar feedback in the [discuss](https://leetcode.com/problems/egg-drop-with-2-eggs-and-n-floors/discuss/1428699/I-think-the-explain-in-example-2-is-wrong) section!
