### ISSUE TITLE
Missing Test Case - 1051. Height Checker

### ISSUE THREAD

**Issue by BretMishler** [LeetCode-Feedback/LeetCode-Feedback#5301]
#### Your LeetCode username

positivecharge8

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ x] Missing Test Cases 

#### Description of the bug

Coming from the lessons in Explore: Arrays 101, the exercises seem to place emphasis on implementing in-place operations by hand. Many "top" performing accepted solutions are leveraging framework helpers like Array.Sort(), which defeats the purpose of these exercises.

#### Language used for code

C#

#### Screenshots

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8965315/141671489-cd59b791-7721-48d1-b77a-4d0fd868796d.png">

**Comment by Sky-Nik** [comment]
I don't know reliable ways to prohibit all ways to sort the array upon submission. Therefore, it does not sound possible to reliably remove such submissions from the runtime diagram. Overall, I think that a runtime diagram is a powerful tool that you should use at your own risk. At the interview, they won't judge you as "faster than x%", so I don't pay too much attention to some constant-term optimizations once I get the asymptotics right.

**Comment by LC-Sue** [comment]
Hi @BretMishler thank you for sharing your concern with us. The Arrays101 card demonstrates how to do this by hand so that you can gain a better appreciation/understanding of how these methods actually work.  However, in practice, it is more common to use built-in sorting functions like Arrays.sort().  @Sly-Nik offers good advice in this regard.  It is better to evaluate the efficiency of your code by calculating its time and space complexity rather than basing it on the runtime distribution for a fixed set of test cases. That said, the distribution you are referencing can sometimes be a good place to see how others solved the same problem.
