### ISSUE TITLE
Missing solution approach and Related Topics tag for problem 368

### ISSUE THREAD

**Issue by hss15** [LeetCode-Feedback/LeetCode-Feedback#5308]
Problem 368, https://leetcode.com/problems/largest-divisible-subset/ can be approached as a graph question as well.
My solution using graph + dfs + memoisation: https://leetcode.com/problems/largest-divisible-subset/discuss/1579057/Unique-Java-solution-withough-Math-using-Directecd-Graph-%2B-DFS-%2B-Memoization.-runtime%3A-O(n2)

Missing Tags: DFS, Graph

**Comment by stormsunshine** [comment]
When we talk about DFS, we do not use the memoization approach. In DFS, each node is visited exactly once, so this problem is NOT a DFS problem.

In fact, dynamic programming can be implemented either top-down and bottom-up. The top-down approach is also known as memoization (search with memo), which uses DFS with memo (usually a hash map).

Therefore, the solution that uses graph + DFS + memoization is still a dynamic programming solution, which is a top-down approach.

**Comment by Sky-Nik** [comment]
I agree that "DFS" is more of a confusing label for this question. This suggestion sounds a bit like "label all questions Array because all of them use linear memory layout".

**Comment by LC-Sue** [comment]
Hi @hss15,
Thank you for sharing you feedback with us. A DFS tag may not be necessary for this problem!  @stormsunshine provided a great explanation for why the tag is not needed.
