### ISSUE TITLE
Typo at line # 32. Operations in Dynamic Array

### ISSUE THREAD

**Issue by munirathinavel** [LeetCode-Feedback/LeetCode-Feedback#5368]
#### Your LeetCode username
munirathinavel

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
I think, there's a typo in line # 32 from section **Operations in Dynamic Array** at [Introduction to Dynamic Array](https://leetcode.com/explore/learn/card/array-and-string/201/introduction-to-array/1146/) where v1 is printed instead of v3.

**Comment by LC-Sue** [comment]
Hi @munirathinavel 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @munirathinavel,
 Thank you for your concern. On lines 11 and 12 of the code you mentioned, v2 references v1 while v3 creates a new object that contains the same elements as v1. The reason both lines 30 and 32 print the first element in v1 is to show that changing v2 will also change v1 because it references the same memory, while changing v3 will not change v1 because when we initialized v3 we created a new object.
