### ISSUE TITLE
Explore card - Linked List Summary incorrect Content

### ISSUE THREAD

**Issue by kartikk10** [LeetCode-Feedback/LeetCode-Feedback#5374]
#### Your LeetCode username

kartikkapgate

#### Category of the bug
- [ ] Language

#### Description of the bug

To delete a Given node in a Singly Linked List, it can be done in O(1) Time. But in the article, it is mentioned that it'll take O(n) time. 

#### Code you used for Submit/Run operation

```
// Delete a Node
public:
    ListNode* DeleteNode(ListNode* ptr) {
      if(ptr->next==NULL)    free(ptr);
      ListNode* temp=ptr->next;
      ptr->data = ptr->next->data;
      ptr->next = ptr->next->next;
      free(temp);
    }
};
```

#### Language used for code

C++

#### Expected behavior

-

#### Screenshots

![image](https://user-images.githubusercontent.com/49352855/143289071-c49b78f7-1e22-4359-b12d-e20b004658a2.png)

#### Additional context

This operation can be done in O(1) time.

**Comment by iosdevzone** [comment]
This will crash if you try to delete the last node.

**Comment by kartikk10** [comment]
> 

Point is not that, with proper conditional statements, you can delete that node in O(1) time, But in article, it's listed that it'll take O(n) time.

**Comment by iosdevzone** [comment]
The edit you made has a bug... The next to last node will have a `next` pointer that points to the (now `free`d) node because you did not have a pointer to the `prev` node to set the next to `NULL`. You *can* edit the code in such a way that, as long as the values in the nodes are considered mutable it can O(1) for all but the last node. For the last node you will still have find the `prev` which will be O(N).

**Comment by kartikk10** [comment]
Yeah, That makes sense!
Thanks, I didn't think through but I learned something different because of you today!
Thanks Again!

**Comment by iosdevzone** [comment]
Just to be clear, 
(1) Your idea would work for all but the last node as long as the values were mutable,
(2) But even correctly written the code would not be O(1) in the strictest of senses... It would be something like O(P(N)) where P(N) was the probability where the node to be deleted was the last.
(3) So, your idea is clever, but you did not think about all the edge cases.
(4) I commented on your post, because I thought your idea was clever, but not complete. I hope you did not feel I was picking on you or your code.
Good luck with your coding!
