### ISSUE TITLE
Recursion 1 Card -  Reverse String Solution Python tries to swap letters in String but string is immutable

### ISSUE THREAD

**Issue by tgreenidge** [LeetCode-Feedback/LeetCode-Feedback#5391]
class Solution:
    def reverseString(self, s):
        """
        :type s: List[str]
        :rtype: void Do not return anything, modify s in-place instead.
        """
        def helper(start, end, ls):
            if start >= end:
                return
        
            # swap the first and last element
            ls[start], ls[end] = ls[end], ls[start]        # not legal syntax

            return helper(start+1, end-1, ls)
    
        helper(0, len(s)-1, s)

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by LC-Sue** [comment]
Hi @tgreenidge 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @tgreenidge,
That's a good observation, you're correct that this would be an illegal operation for a string. However, in this example, s which is renamed to ls when it is passed to the helper function is actually a list of strings (characters to be precise). Because lists are mutable data structures, the method for swapping characters is valid in this situation. Thank you for your time.
