### ISSUE TITLE
650. Wrong expected result only when submit

### ISSUE THREAD

**Issue by sandeep-chahal** [LeetCode-Feedback/LeetCode-Feedback#543]
#### Your LeetCode username
 sandeepchahal

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Testcases gives the wrong expected result
I've tried giving input 1,2,3,4,5....60 and the code gives the right output when I run it outside the leetcode editor or use custom test cases in leetcode editor
but when I try to submit it fails and gives wrong expected result

#### Code you used for Submit/Run operation

```
/**
 * @param {number} n
 * @return {number}
 */
let steps = 0;
var minSteps = function(n) {
    if(n%2===0){
        countEvenSteps(n)        
    }else{
        countOddSteps(n)
    }
    return steps
};

function countEvenSteps(n){
     if(n===1) return
     if(n%2===0){
        steps+=2;
        countEvenSteps(n/2)
     }
    else
        countOddSteps(n)

    
}
function countOddSteps(n){
    if(n===1) return
    let halfOdd = Math.ceil(n/2);
    if(halfOdd%2===0) halfOdd--
    for(let i=halfOdd;i>=1;i=i-2){
        if(n%i===0){
            steps+=(n/i);
            if(i===1) return
            if((i)%2===0)
                return countEvenSteps(i)   
            else
               return countOddSteps(i)
        }
    }
     
}



```

#### Language used for code
 Javascript

#### Expected behavior
The expected results should be correct.

#### Screenshots
![{DD81DDB6-8205-4082-99B4-0D65C1F62758} png](https://user-images.githubusercontent.com/25558001/85860190-01da6700-b7dc-11ea-946d-bebfd21f1ff1.jpg)

**Comment by mjcrouch** [comment]
I'm not a leetcode developer, but I believe the problem is you're using a global 'steps' variable to store state - this means your function behaves differently each time you call it.

I believe the 'submit tests' option will import your code once and call your function multiple times - and since your steps variable is never reset it will keep increasing

At the very least you need to reset steps at the start of your function (but you should consider whether you really want to store state outside of your function, because it leads to bugs like this)

**Comment by lc-kate** [comment]
Hi @sandeep-chahal ,
Thank you for reaching out to us. The reasons and solutions for different "outputs" from "Run Code" and "Submit" are well documented in [this support article](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-). Please check it out.
