### ISSUE TITLE
Broken Test Case - 189. Rotate Array

### ISSUE THREAD

**Issue by Goldziher** [LeetCode-Feedback/LeetCode-Feedback#5435]
#### Your LeetCode username

Goldziher

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug

I solved the kata as you can see in the pictures, it still evaluates the original value passed into the function

#### Code you used for Submit/Run operation

```
import "fmt"

func rotate(nums []int, k int) {
	nums = append(nums[len(nums)-k:], nums[:len(nums)-k]...)
	fmt.Println(nums)
}
```

#### Language used for code

golang

#### Expected behavior

i expect that the test either reads stdout, evaluates the modified slice or expect to receive a return value and evaluate it.

#### Screenshots

without returning a value:
<img width="511" alt="Screenshot 2021-12-02 at 19 26 11" src="https://user-images.githubusercontent.com/30733348/144482161-cff9ae36-b012-4859-aba8-eb18f12a3ef7.png">

with returning a value
<img width="593" alt="Screenshot 2021-12-02 at 19 25 37" src="https://user-images.githubusercontent.com/30733348/144482180-084eae10-4db4-4486-8ada-e544af3e54d8.png">

As you can see in both cases, the print function shows that the variable inside the function has been modified correctly, but the return / stdout value is not evaluated.

**Comment by LC-Sue** [comment]
Hi @Goldziher,
Thank you for reaching out to us. This problem requires us to rotate the array nums but the current code is creating a new object nums that contains the rotated values from the original nums object.  Rather than creating a new object, you can copy the values into the given object by replacing nums = append(nums[n - k:], nums[:n - k]...) with copy(nums, append(nums[n - k:], nums[:n - k]...)) although you may want to also consider the case when k is larger than len(nums).
