### ISSUE TITLE
Invalid test case in 1971

### ISSUE THREAD

**Issue by snehasishroy** [LeetCode-Feedback/LeetCode-Feedback#5462]
#### Your LeetCode username
chrisgriffin

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
One of the test case in https://leetcode.com/problems/find-if-path-exists-in-graph/ is
```
1
[]
0
0
```
Expected output is `true`

However, the problem statement clearly indicates that there are no vertex has an edge to itself in the graph, so how is a path from node 0 to node 0 possible in a graph that contains no edges.

#### Expected behavior
Output of the mentioned test case should be `false`

**Comment by LC-Sue** [comment]
Hi @snehasishroy 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @snehasishroy,
Thank you for your time. I have confirmed with the team and the test case is fine. If there is a graph with only one node, then the start node is the same as the destination node and you don't need to move. There is no self edges but since node 0 that you start at is also the same node, you already reach the destination. The constraints allow start == end.
