### ISSUE TITLE
938. Range Sum of BST - type hints don't match description

### ISSUE THREAD

**Issue by yarmash** [LeetCode-Feedback/LeetCode-Feedback#5543]
#### Your LeetCode username

yarmash

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the [938. Range Sum of BST](https://leetcode.com/problems/range-sum-of-bst/) problem the signature is
```
 def rangeSumBST(self, root: Optional[TreeNode], low: int, high: int) -> int:
```
which suggests that root can be `None`. However, this contradicts the description 

> The number of nodes in the tree is in the range [1, 2 * 10^4].

The description seems correct, so the signature should be:

```
def rangeSumBST(self, root: TreeNode, low: int, high: int) -> int:
```

#### Language used for code

Python

**Comment by LC-Sue** [comment]
Hi @yarmash 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @yarmash, 
Thank you for your time, The signature is automatically generated and it is optional because we may or may not have empty input. We kept it like this because while in this problem we don't accept empty nodes, in other problems we do. This should not be an issue as the constraints are clear.
