### ISSUE TITLE
Missing Test Case - 1004. Max Consecutive Ones III

### ISSUE THREAD

**Issue by anujsh2002** [LeetCode-Feedback/LeetCode-Feedback#5589]
#### Your LeetCode username

anujsharma10112002

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [✔ ] Missing Test Cases 

#### Description of the bug

I submitted my code and it got accepted on leetcode but my accepted code does not pass one test case which is not included in your test cases

#### Code you used for Submit/Run operation

```
 int longestOnes(vector<int>& nums, int k) {
        int st=0,end=0,n=nums.size(),zero=0,ans=0;
        while(end<n)
        {
           if(zero<k)
           {
               if(nums[end]==0)
                   zero++;
               end++;
           }
            else if(zero==k)
            {
                if(nums[end]==1)
                    end++;
                else if(nums[st]==1)
                    st++;
                else if(nums[st]==0)
                    zero--,st++;
               
            }
             ans=max(ans,end-st);
        }
        ans=max(ans,end-st);
        return ans;
    }
```

#### Language used for code

C++

#### Expected behavior

Input:
[1,1,1,1,1,0,1,0,0,1]
2

correct output is 8 but my accepted code gives output 7 which is incorrect.

**Comment by LC-Sue** [comment]
Hi @anujsh2002,
Thank you for reaching out to us, the code and test case you provided are both accepted. I've attached a screenshot for your reference. Since there is no missing test case I will close this issue now, thank you for understanding!

![image](https://user-images.githubusercontent.com/92285126/147011304-b50e1d2d-f59b-4c18-b9d4-4a6c90779dcc.png)
