### ISSUE TITLE
Language Error in - 2111. Minimum Operations to Make the Array K-Increasing

### ISSUE THREAD

**Issue by Shubham0599** [LeetCode-Feedback/LeetCode-Feedback#5621]
#### LeetCode username
tenaciousanand01

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

In question number 2111. There is a error in language.
Error Line->"The` array arr is called <u>K-increasing</u> if <u>arr[i-k] <= arr[i]</u> holds for every index i, where k <= i <= n-1."
Here  **Increasing** does not satisfy **arr[i-k] <= arr[i]**
 It Should be

1. Either **Non Descresing**
2. Or **arr[i-k] <arr[i]**

#### Screenshots

![Question Number 2111](https://user-images.githubusercontent.com/61907542/147201133-e05e8a80-801d-4921-b216-d5a0b3619561.jpg)

**Comment by stormsunshine** [comment]
The term "increasing" is not equivalent to "strictly increasing". If an array is strictly increasing, then all elements should be different. Otherwise, it is allowed that the elements have the same value. In this case, "increasing" is equivalent to "non-decreasing".

The term "increasing" can be defined under the context of the problem, and may differ between problems.

**Comment by LC-Sue** [comment]
Hi @Shubham0599,
Thank you for reaching out to us, stormsunshine is correct. The term "increasing" can have different meaning under different context.
