### ISSUE TITLE
Improvement to problem description - 1. Two Sum

### ISSUE THREAD

**Issue by Nevalicjus** [LeetCode-Feedback/LeetCode-Feedback#5641]
#### Your LeetCode username
Nevalicjus

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
In the description of the problem there are two `Output`s, instead of one `Output` and one `Explanation` like in other problems.

#### Language used for code
Python3

#### Screenshots

Problem 1 where two Outputs are displayed
<img width="533" alt="Screenshot 2021-12-25 at 22 06 11" src="https://user-images.githubusercontent.com/50320623/147393623-3b95325b-d797-43d0-b093-767d0ce8f4da.png">

Problem 3 where Output and Explanation are displayed
<img width="533" alt="Screenshot 2021-12-25 at 22 06 35" src="https://user-images.githubusercontent.com/50320623/147393627-ff7fec0b-a235-46c2-ace1-25c560af3f23.png">

**Comment by LC-Sue** [comment]
Hi @Nevalicjus,
Thank you for reaching out to us, different problems have different formats when it comes to test cases. Test case for problem 1 is different from test case for problem 3, hence it cannot be compared as the questions are different and have different solutions! Please feel free to reach out again if you have any other questions!

**Comment by stormsunshine** [comment]
@LC-Sue Could you please read the issue carefully? You really did not get the point!

This issue mentions that in problem 1, the text in example 1 is incorrect. Each example consists of three lines, which are input, output, and explanation. However, in example 1 of problem 1, the third line is wrongly written as "Output", which should be "Explanation".

This issue is not saying that the solution is different. The point is that the word "Explanation" is wrongly written as "Output"!
