### ISSUE TITLE
Put boxes into the warehouse 1

### ISSUE THREAD

**Issue by kushalmahajan** [LeetCode-Feedback/LeetCode-Feedback#5658]
**Problem link** - https://leetcode.com/problems/put-boxes-into-the-warehouse-i/
**Algorithm of Intuition 2**

>For this approach, we do not need to calculate the maximum height allowed for each warehouse room. This is because boxes are sorted in decreasing order, so a room with a low height will automatically omit all boxes that are taller than it.We start from the largest box and the leftmost position of the warehouse. When the box can fit in the warehouse room, we increment the count by 1. Otherwise, we discard the box and try a smaller one.

I don't understand the intuition 2, more so problem becomes more confusing. If the cave analogy is to be held true, then If I place the box of height 4 in room of height 5, then would there practically be a space to move around other boxes? 

Since the problem describes the movement from left to right, then I have to image the rooms linear, like an interconnected chain of rooms but with differential height. So, considering this, if I place a box with most height in the first available room, the rest of the rooms anyway are blocked. So according to intuition 2 and for inputs of boxes = [4,3,4,1], warehouse = [5,3,3,4,1] I shouldn't be able to move to second box after that at all. My return `count` should be 1

**Comment by LC-Sue** [comment]
Hi @kushalmahajan,
Thank you for reaching out to us. The cave analogy is primarily to help the reader understand the first approach.  In the second approach, the analogy is less applicable because we are filling the warehouse from left to right.  That said, the animation for the second approach is there to help the readers better understand why this approach works.
