### ISSUE TITLE
TLE - 204. Count Primes

### ISSUE THREAD

**Issue by D-Minor** [LeetCode-Feedback/LeetCode-Feedback#5708]
#### Category of the bug
- [ ] Question - 1
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Code you used for Submit/Run operation

```
class Solution:
    def countPrimes(self, n: int) -> int:
        st = [False] * (n + 1)
        primes = []
        for i in range(2, n):
            if not st[i]:
                primes.append(i)
            j = 0
            while i * primes[j] < n:
                st[primes[j] * i] = True
                if i % primes[j] == 0:
                    break
                j += 1
        return len(primes)
```

#### Language used for code
 Python

#### Expected behavior

The solution is O(n) time, supposed to be accepted. It was accepted 3 times, but most of times I got TLE error.
But same code can be accepted on https://leetcode-cn.com without any issue.
Is this a bug?

**Comment by LC-Sue** [comment]
Hi @D-Minor,
Thank you for reaching out to us.

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
