### ISSUE TITLE
26. 删除有序数组中的重复项 测试用例有问题

### ISSUE THREAD

**Issue by JohnChenLiang** [LeetCode-Feedback/LeetCode-Feedback#5723]
**Bug 类型**
-  26.删除有序数组中的重复项
- JAVA

**描述**
  同一段代码 同一个输入，leecode页面的输出 与 idea里的输出不一样。

**你使用的语言**
JAVA

**你提交或者运行的代码**
    public int removeDuplicates(int[] nums) {
        return Arrays.stream(nums).distinct().toArray().length;
    }

**期望行为**
输入：
[1,1,2]
输出：
[1,2]

**屏幕截图**
![06c77ca8487ead58c19909177a11221](https://user-images.githubusercontent.com/30498675/147802194-1375ebf1-7916-4f2e-9887-a51dcadd3b75.png)
![a217f3b690c933813c1391fa64dcc55](https://user-images.githubusercontent.com/30498675/147802196-b1768c07-45bf-42d9-a261-66d1fce87b4e.png)
![9c53f081721139573e54b0d6e196865](https://user-images.githubusercontent.com/30498675/147802204-70f7e23b-e548-4d7c-bbc8-b91e52678856.png)

**Comment by stormsunshine** [comment]
You have to modify the elements in `nums`, not changing the reference of `nums`. Otherwise, after the method is returned, the reference of `nums` is not changed.

Suppose the array `nums` in the parameter is at address A, and the array you create with `Arrays.stream(nums).distinct().toArray()` is at address B. Although you change the reference of `nums` to address B in the method, the reference of `nums` will still be at address A. Since you do not modify any element in the array at address A, the array `nums` at address A is still `[1,1,2]`, no matter what you do in the method.

You may write a main method to call the method `removeDuplicates` in your local environment, and check the content of array `nums` in the main method after calling the method `removeDuplicates`.

This is the basic Java knowledge and has nothing to do with the test case itself.

**Comment by JohnChenLiang** [comment]
我还以为这题能用一行代码解呢,看来这题一行代码解决不了.
