### ISSUE TITLE
973 Quick Select TLE for Python3

### ISSUE THREAD

**Issue by Kapporing** [LeetCode-Feedback/LeetCode-Feedback#5767]
#### Your LeetCode username
Kapporing

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
Solutions using quick select will TLE for 973. K Closest Points to Origin.
Previously it didn't TLE for large inputs. Not sure what happened

#### Code you used for Submit/Run operation
```
class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        if k == len(points):
            return points
        
        left = 0
        right = len(points) - 1
        
        while left <= right:
            partition_idx = self.partition(points, left, right)
            
            if partition_idx == k:
                return points[:k]
            if partition_idx > k:
                right = partition_idx - 1
            else:
                left = partition_idx + 1
        
        return []
    
    
    def partition(self, points, left, right):
        current_idx = left
        
        for i in range(left, right):
            if points[i][0] ** 2 + points[i][1] ** 2 < points[right][0] ** 2 + points[right][1] ** 2:
                points[i], points[current_idx] = points[current_idx], points[i]
                current_idx += 1
        
        points[right], points[current_idx] = points[current_idx], points[right]
        return current_idx
```

#### Language used for code
Python3

#### Expected behavior
The solution should not TLE. At the very least it should be accepted.

#### Screenshots
Screenshot showing Accepted Submission ~ 2 weeks ago
![image](https://user-images.githubusercontent.com/46541353/147866499-cade57c9-fb70-4b13-be23-ef5e196b175f.png)
Same code now TLEs
![image](https://user-images.githubusercontent.com/46541353/147866511-0d4c2a60-cfe6-4c09-8d44-248016aec5ac.png)

**Comment by LC-Sue** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
