### ISSUE TITLE
Add Variance/Confidence level of running time.

### ISSUE THREAD

**Issue by bobvo23** [LeetCode-Feedback/LeetCode-Feedback#605]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x]Features

#### Description of the features
The current statistics are actual running time and memory. Due to the variance of running time, the reported time are not constant in some problems. In complex problems with long running time, the running time are quite consistent for every run. However, in some other problems, users may observe high variance between run, hence many complains about this issues.

I suggest leetcode adds another reporting parameter to the statistic of a run. For example, we could share confidence level of the reporting numbers. For example, when the variance is low, we can say that a program completed in 50ms with 95% confidence. When there are huge different between runs, we can say that it completed in 50ms with 50% confidence.

That is the high level idea. I think you can come up with something to add more meaningful info for the run statistic.

**Comment by lc-christina** [comment]
Hi @bobvo23 ​ ,
Thank you for reaching out to us!
It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.
The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.
However, I've relayed your suggestion to the team for investigation.
