### ISSUE TITLE
Missing Test Case - 1032. Stream of Characters

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#6138]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/7938835/1.txt)

#### Code you used for Submit/Run operation

```
class StreamChecker:

    def __init__(self, words: List[str]):
        self.d = {}                 #后缀树初始化
        for word in words:          #遍历单词表
            t = self.d
            for c in word[:: -1]:   #生成后缀树
                if c not in t:
                    t[c] = {}
                t = t[c]
            t['end'] = True
        self.a = ''                 #倒序串初始化

    def query(self, letter: str) -> bool:
        self.a = letter + self.a    #倒序生成字符串
        t = self.d
        for c in self.a:            #后缀树匹配
            if c not in t:
                return False
            t = t[c]
            if 'end' in t:
                return True
        return False
```

#### Language used for code

Python3

#### Expected behavior

The code gets TLE.

**Comment by stormsunshine** [comment]
I wonder what the expected time complexity of the problem is.

The common solution to this problem uses a trie so that each call to `query` costs O(max(word.length)) time complexity, which means the time complexity is determined by the maximum length of any word in the array `words` for initialization.

Since `query` is called at most 4 * 10^4 times and the maximum length of any word in `words` is 2000, each test case has at most 8 * 10^7 operations for `query`. This will make the solution that uses a trie get TLE.

If the trie solution is the expected solution and O(max(word.length)) is the expected time complexity for `query`, then the constraints should be modified to a smaller value. For example, the second constraint should be changed to `1 <= words[i].length <= 200`.

If the expected time complexity is lower than O(max(word.length)), please also modify the constraints to make it clear that time complexity O(max(word.length)) is too high for `query`. If this is the case, I hope LeetCode site can provide a solution with a lower time complexity than the trie solution.

**Comment by LC-Sue** [comment]
Hi @hqztrue 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @hqztrue,
Thank you for your time, our team has decided to reject the test case. The test case is too large and the platform cannot accept it. We may consider it later.

**Comment by stormsunshine** [comment]
@LC-Sue I hope the constraints should be changed as I mentioned above. What is the expected time complexity? If it is expected that each call to `query` costs O(max(word.length)) time complexity, then the constraints should be changed to smaller values. Could you please relay this issue (about constraints) to the team to investigate further?
