### ISSUE TITLE
Wrong expected output - 443. String Compression

### ISSUE THREAD

**Issue by kmathewgit** [LeetCode-Feedback/LeetCode-Feedback#6188]
#### Your LeetCode username
kmathewleet

#### Category of the bug
[ ] Solution

#### Description of the bug

The question asks for size of the output but expects the actual array.
For example

Expected shows
["a","2","b","2","c","3"]

Actual answer should be 6.
#### Language used for code
C++

#### Expected behavior

Actual answer should be integer (size of the output).

**Comment by LC-Sue** [comment]
Hi @kmathewgit,
Thank you for reaching out to us. 
This problem states:
"The compressed string s should not be returned separately, but instead, be stored in the input character array chars."
This means we need to solve the problem in place.  You don't return an array because the online judge will check the array that given to you as an input to ensure it was modified correctly.

You return an integer because this tells the online judge how many characters in the input it should read.

If you return 5, the output will show the first 5 characters that were read.  But this does not mean we should return those characters.
