### ISSUE TITLE
Missing Test Case - 399. Evaluate Division

### ISSUE THREAD

**Issue by alexmalyushtsky** [LeetCode-Feedback/LeetCode-Feedback#6290]
#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

You do not need to know A if you know that A is not 0 to compute A/A
This means that current Java solution is wrong in such case. It will return -1 instead of 1 in case if A is not in the list.
To fix it order of the checks should be changed:
 

The appropriate tests may be written

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by stormsunshine** [comment]
In this problem, if a variable is not in any equation, then its value is NOT determined. Even if the dividend and the divisor are the same, the result still can't be determined since it does not exist.

Example 1 shows this case, where the result of x / x is -1, since x does not exist in any equation.

**Comment by LC-Sue** [comment]
Hi @alexmalyushtsky,
Thank you for reaching out to us, I hope stormsunshine's response as able to answer your doubts! If you have any other questions feel free to reach out again!
