### ISSUE TITLE
Problem 2158 Python3 Codes Not Passing

### ISSUE THREAD

**Issue by ThomasShaw1** [LeetCode-Feedback/LeetCode-Feedback#6370]
#### Your LeetCode username

@AestheticSJTU

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The same code for Java in Python3 is not passing the OJ. The time complexity of the code is within the time constraint.

#### Code you used for Submit/Run operation

```
class Solution:
    def equalDigitFrequency(self, s: str) -> int:
        n = len(s)
        res = 0
        hash_set = set()
        mod = 10 ** 9 + 7
        for i in range(n):
            cur = 0
            cnt = Counter()
            rev = Counter()
            for j in range(i, n):
                cnt[s[j]] += 1
                rev[cnt[s[j]]] += 1
                cur = (cur * 11 + int(s[j]) + 1) % mod
                if rev[cnt[s[j]] - 1] > 0:
                    rev[cnt[s[j]] - 1] -= 1
                    if rev[cnt[s[j]] - 1] == 0:
                        del rev[cnt[s[j]] - 1]
                if cur not in hash_set and len(rev) == 1:
                    res += 1
                    hash_set.add(cur)
        return res
```

#### Language used for code

Python3

**Comment by LC-Sue** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
