### ISSUE TITLE
[Problem 239] Time complexity analysis of solution 2 is incorrect

### ISSUE THREAD

**Issue by mmallis87** [LeetCode-Feedback/LeetCode-Feedback#6429]
#### Your LeetCode username
@majid

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
This is regarding problem 239 (https://leetcode.com/problems/sliding-window-maximum/)
Solution 2 runs on O(nk). Just look at the code: the two for-loops combined go over the whole input array (so exactly n times) and, in worst case when the deque is always at full capacity (i.e. contains k elements), clean_deque function needs to check every element the deque.

Empirical time performance of the tests shows solution 3 performing way better than solution 2.

#### Code you used for Submit/Run operation
Used the code snippets in the proposed solutions

#### Language used for code
All

#### Expected behavior
Time complexity is actually O(nk).

#### Screenshots
N/A

#### Additional context
None

**Comment by LC-Sue** [comment]
Hi @mmallis87 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Sue** [comment]
Hi @mmallis87,
Thank you for your time, this is a common misconception and an easy mistake to make. Notice that in the for loop, we visit each element once, and at each iteration, we append the element to the deque. So over the course of both for loops, we added each element to the deque exactly once. Now take a look at the clean_deque function. It only ever removes elements from the deque. Since we can at most add n elements to the deque, over the course of all calls to clean_deque, we cannot remove more than n elements from the deque. Thus both of these operations are O(n). While a single call to clean_deque could take O(n) time, the amortized complexity of clean_deque is O(1).

**Comment by mmallis87** [comment]
@LC-Sue thank you for the explanation. You are actually right: when I added debugging points in `clean_deque` I noticed it was called exactly `n - k + 1` times.
