### ISSUE TITLE
Missing Test Case - 904. Fruit Into Baskets

### ISSUE THREAD

**Issue by ya7ya1994** [LeetCode-Feedback/LeetCode-Feedback#6512]
#### Your LeetCode username
ya7ya1994

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
This brute force solution passes because of a missing test case 
[0,...<40k zeros>,1,2,3]

#### Code you used for Submit/Run operation
```java
class Solution {
    public int totalFruit(int[] fruits) {
        int maxFruits = 0;
        for (int i = 0; i < fruits.length && maxFruits < fruits.length; i++) {
            maxFruits = Math.max(maxFruits,computeAll(fruits,i));
        }
        
        return maxFruits;
    }
    public int computeAll(int[] fruits, int beg) {
        Map<Integer,Integer> basket = new HashMap();
        int result = 0;
        for(int i = beg; i < fruits.length; i++) {
            if(!basket.containsKey(fruits[i])) {
                if (basket.size() < 2) {
                    basket.put(fruits[i],1);
                }
                else {
                    break;
                }
            }
            else {
                basket.put(fruits[i],basket.get(fruits[i]) + 1);
            }
        }
        
        for(int i : basket.values())
            result += i;
        
        return result;

    }
}
```

#### Language used for code
Java

**Comment by LC-Sue** [comment]
Hi @ya7ya1994,
Thank you for reaching out to us, please provide the test case as a txt file!

**Comment by stormsunshine** [comment]
@LC-Sue Please refer to the following two files.

Test case 1 is a test case with the first 40000 elements equal to 0 and the last 3 elements equal to 1, 2 and 3, respectively.

Test case 2 is a test case similar to test case 1 but with more zeros so that the length of the array is 10<sup>5</sup>.

[Test case 1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8131399/Test.case.1.txt)
[Test case 2.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8131400/Test.case.2.txt)

**Comment by LC-Sue** [comment]
Hi @ya7ya1994 
I've relayed this issue to our team to investigate.,

**Comment by LC-Yani** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
