### ISSUE TITLE
Missing Test Case - 413. Arithmetic Slices

### ISSUE THREAD

**Issue by dassoumyamoy00** [LeetCode-Feedback/LeetCode-Feedback#6613]
#### Your LeetCode username
 soumya00

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Additional context

Username: soumya00
Bug: I have coded the solution in n^2, but then also, it is slowing faster than 100% in Java. How is this possible? Means, for both O(n) and O(n^2), it is showing faster than 100%

I think there must be some bugs.

Or kindly, restrict the time limit,

O(n) soln: https://leetcode.com/submissions/detail/596734563/
O(n^2) soln: https://leetcode.com/submissions/detail/653279591/

Thank you.

**Comment by LC-Sue** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
