### ISSUE TITLE
2212: Runtime too strict

### ISSUE THREAD

**Issue by kaiwangx** [LeetCode-Feedback/LeetCode-Feedback#6754]
#### Your LeetCode username
dragonzz

#### Category of the bug
- [ *] Language

#### Description of the bug
Same dp logic, java code can pass but python cannot

#### Code you used for Submit/Run operation
// Java version
```class Solution {
    public int[] maximumBobPoints(int numArrows, int[] aliceArrows) {
        int[][] opt = new int[numArrows + 1][12];

        for (int i = 1; i <= numArrows; i++) {
            for (int j = 1; j <= 11; j++) {
                if (i > aliceArrows[j]) {
                    opt[i][j] = Math.max(opt[i - aliceArrows[j] - 1][j - 1] + j,opt[i][j - 1]);
                }
                else {
                    opt[i][j] = opt[i][j-1];
                }
            }
        }

        int i = numArrows;
        int[] res = new int[12];
        for (int j = 11; j > 0; j--) {
            if (i > aliceArrows[j] && opt[i - aliceArrows[j] - 1][j - 1] + j > opt[i][j - 1]) {
                res[j] = aliceArrows[j] + 1;
                i -= aliceArrows[j] + 1;
            }
            else {
                res[j] = 0;
            }
        }
        res[0] = i;
        return res;
    }
}
```
// Python version
```
class Solution:
    def maximumBobPoints(self, numArrows: int, aliceArrows: List[int]) -> List[int]:
        
        opt = [[0 for j in range(12)] for i in range(numArrows + 1)]
        
        for i in range(1, numArrows + 1):
            for j in range(1, 12):
                if i > aliceArrows[j]: 
                    opt[i][j] = max(opt[i-aliceArrows[j]-1][j-1] + j, opt[i][j-1])
                else:
                    opt[i][j] = opt[i][j-1]
        
        i, j = numArrows, 11
        res = []
        for j in range(1, 12)[::-1]:
            if i > aliceArrows[j] and opt[i-aliceArrows[j]-1][j-1] + j > opt[i][j-1]:
                res.append(aliceArrows[j] + 1)
                i -= aliceArrows[j] + 1
            else:
                res.append(0)
        res.append(i)
        return res[::-1]
```

#### Language used for code
Python, Java

#### Expected behavior
Since both solution result in O(12 * num Arrow) time complexity, the runtime for python is too strict

**Comment by bogoconic1** [comment]
I feel you, this question and biweekly q4 (2209) was a wreck for python users, losing AC because of this TLE issue that could be solved by changing languages

**Comment by LC-Sue** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
