### ISSUE TITLE
Solution Problem - 1641. Count Sorted Vowel Strings

### ISSUE THREAD

**Issue by ashmit35** [LeetCode-Feedback/LeetCode-Feedback#6830]
Ido_Ash

[]Solution
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

My solution got submitted two times but the same solution got time limit three times

'''
class Solution {
    
    List<String> list = new ArrayList<>();
    char a[] = {'a','e','i','o','u'};
    
    public void f(String temp,int i,int n){
        
        if(i==n){
            list.add(new String(temp));
            return;
        }
        
        for(int idx=0;idx<a.length;idx++){
            
            if(temp.equals(""))
                f(temp.concat(String.valueOf(a[idx])),i+1,n);
            
            else if(a[idx]>=temp.charAt(temp.length()-1))
                f(temp.concat(String.valueOf(a[idx])),i+1,n);
        }
    }
    
    public int countVowelStrings(int n) {
        f("",0,n);
        return list.size();
    }
}
'''

Java

Time Limit exceeded for every Submission i made using this code

![Screenshot (27)](https://user-images.githubusercontent.com/100089020/160271935-bb15ff2d-c10b-4546-b0a4-1bfe738af8af.png)

**Comment by LC-Sue** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
