### ISSUE TITLE
220. Contains Duplicate III

### ISSUE THREAD

**Issue by agatagruza** [LeetCode-Feedback/LeetCode-Feedback#700]
#### Your LeetCode username

gordonek

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

Approach 1: (Naive Linear Search) [Time Limit Exceeded] has incorrect description

#### Code you used for Submit/Run operation

```
class Solution {
    public boolean containsNearbyAlmostDuplicate(int[] nums, int k, int t) {
        for (int i = 0; i < nums.length; ++i) {
            for (int j = Math.max(i - k, 0); j < i; ++j) {
                if (Math.abs(nums[i] - nums[j]) <= t) return true;
            }
        }
        return false;

    // Time limit exceeded.         
    }
}
```

#### Language used for code

Java

#### Expected behavior

It doesn't TLE and submission was accepted.

#### Screenshots

<img width="473" alt="Capture" src="https://user-images.githubusercontent.com/7014697/88446676-dbaae580-cde0-11ea-8f2e-a250b36bbaa8.PNG">

**Comment by lc-ivan** [comment]
Hi @agatagruza ,
Thanks for reaching out to us and for your feedback. Upon reviewing this ticket and submitting the code you have provided, we have received "Wrong Answer" multiple times instead of TLE or Accepted. I noticed in the screenshot you provided that the test case you ran was accepted. Please note that **running code from a test case only tests that one test case** whereas **submitting the code tests all tests cases**. 

![Screen Shot 2020-07-31 at 1 11 21 PM](https://user-images.githubusercontent.com/68418560/89073476-6fc00400-d32f-11ea-9484-9bb1b8e4a528.png)
