### ISSUE TITLE
Missing Test Case - 2205. The Number of Users That Are Eligible for Discount

### ISSUE THREAD

**Issue by aastha3** [LeetCode-Feedback/LeetCode-Feedback#7049]
#### Your LeetCode username

duaaastha3@gmail.com

#### Category of the bug
- [ ] Question
- [ 1 ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

Problem the evaluation engine. The date() function of SQL is not working as expected. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Language used for code

SQL 

#### Expected behavior

The following two queries should give identical result, but they do not. 
```
Query1 : CREATE FUNCTION getUserIDs(startDate DATE, endDate DATE, minAmount INT) RETURNS INT
BEGIN
  RETURN (
      # Write your MySQL query statement below.
    
select count(distinct user_id)  as user_cnt from Purchases 
where time_stamp between startDate and endDate  
and  amount >= minAmount       
  );
END
```
```
Query 2: CREATE FUNCTION getUserIDs(startDate DATE, endDate DATE, minAmount INT) RETURNS INT
BEGIN
  RETURN (
      # Write your MySQL query statement below.
    
select count(distinct user_id)  as user_cnt from Purchases 
where date(time_stamp) between startDate and endDate  
and  amount >= minAmount       
  );
END
```

**Comment by LC-Yani** [comment]
Hi @aastha3 

Thank you for reaching out to us. The first query actually can receive result if you run your code first instead of submit. 
Second query code that you provided is wrong after we test it, the judger appears to be working correctly, please feel free to refer to the discuss section of the problem to see how other users' have optimized their codes!
