### ISSUE TITLE
Missing Test Case - 1847. Closest Room

### ISSUE THREAD

**Issue by jweatherspoon** [LeetCode-Feedback/LeetCode-Feedback#7248]
#### Your LeetCode username
jweatherspoon

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug
There are no test cases for the constraints of the problem. 

#### Code you used for Submit/Run operation
```
function closestRoom(rooms: number[][], queries: number[][]): number[] {
    rooms.sort((a, b) => a[1] - b[1]);
    
    const answer = [];
    for (const [preferred, minSize] of queries) {
        let left = 0;
        let right = rooms.length;
        
        while (left < right) {
            const mid = left + Math.floor((right - left) / 2);
            if (rooms[mid][1] >= minSize) {
                right = mid;
            }
            else {
                left = mid + 1;
            }
        }
        
        if (left === rooms.length) {
            answer.push(-1);
        }
        else {
            let minId = rooms[left][0];
            let minDiff = 9999999999999999;
            while (left < rooms.length) {
                const room = rooms[left];
                
                const diff = Math.abs(room[0] - preferred);
                if (diff < minDiff || (diff === minDiff && room[0] < minId)) {
                    minId = room[0];
                    minDiff = diff;
                }
                
                left++;
            }
            
            answer.push(minId);
        }
    }
    
    return answer;
};
```

#### Language used for code
Typescript

#### Expected behavior

My implementation took 5-7 seconds to run against my single test case (attached as a file). I expected my submission to timeout; however, when I hit submit my code only took two seconds to pass all of the test cases.

#### Screenshots
My test case:
![image](https://user-images.githubusercontent.com/14151973/167529278-6503fd70-c2bd-498d-9edf-0e1a2e98270a.png)

My submissions to the problem:
![image](https://user-images.githubusercontent.com/14151973/167529328-dc79dc14-887d-4cf7-87a6-20be8e6be2f1.png)

#### Additional context

Test case attached as a file:
[closest-room-testcase.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/8656549/closest-room-testcase.txt)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.
