### ISSUE TITLE
Find Pivot Index - bad hint - reopen

### ISSUE THREAD

**Issue by An1s9n** [LeetCode-Feedback/LeetCode-Feedback#7262]
Hi! I've already opened such an issue  (#6870), but you closed it too fast and I have to reopen in, because I still do not agree with you. I'll copy the description and write my comment after that.

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

in [this](https://leetcode.com/explore/learn/card/array-and-string/201/introduction-to-array/1144) task there is a Hint which says following:
`We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is P[P.length - 1] - P[i] - nums[i].`
I assume there is `nums[nums.length - 1]` summand missing and it should be added as follows:
`We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]. Then for each index, the left sum is P[i], and the right sum is P[P.length - 1] + nums[nums.length - 1] - P[i] - nums[i].`

#### Code you used for Submit/Run operation

N/A

#### Language used for code
N/A

#### Expected behavior

N/A

#### Screenshots

N/A

#### Additional context

N/A

You say following:
```
Let's break down the statement.
P[P.length - 1] equals the sum of all of the numbers
P[i] equals the sum of all the numbers to the left of index i
```
but it contradicts itself. `P[P.length - 1]` equals the sum of all of the numbers EXCEPT FOR THE LAST ONE, because the `i`-th element itself is excluded from calculation of `P[i]` and it has to be added manually! So `P[P.length - 1] + nums[nums.length - 1]` equals to the sum of all of the numbers.

So I kindly ask you to reconsider the issue.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate again.

**Comment by LPRowe** [comment]
Hi @An1s9n I believe I may be able to help clarify.  I think your suggestion is correct if we stopped builidng P once it reached nums.length, however in most cases (this problem included) it is cleaner to have P[P.length - 1] equal the sum of the nums array rather than stopping one number short, so P.length == nums.length + 1. 

Let's walk through an example just to verify that the existing hint works:

```
nums = [1, 7, 3,  6,  5,  6]
P    = [0, 1, 8, 11, 17, 22, 28]
```

So P.length = 7 and nums.length = 6

Let's find the result for i = 3, 

right_sum[i] = P[P.length - 1] - P[i] - nums[i] = P[6] - P[3] - nums[3] = 28 - 11 - 6 = 11

left_sum[i] = P[i] = P[3] = 11

We see that right_sum[3] == left_sum[3], which is expected since 3 is the pivot index for the array.  

So the existing instructions in the hint result in the correct answer.

**Comment by An1s9n** [comment]
@LPRowe, thank you for a reply!

Yes, if `P.length == nums.length + 1`, than I totally agree with everything. Maybe it will a bit more clear to write
`We can precompute prefix sums P[0]...P[nums.length + 1] where P[i] = nums[0] + nums[1] + ... + nums[i-1]` instead of just
`We can precompute prefix sums P[i] = nums[0] + nums[1] + ... + nums[i-1]`, but it's up to you :)

You can close this issue, thank you once again for your time!
