### ISSUE TITLE
Unclear/Incorrect Information in Dynamic Programming Chapter

### ISSUE THREAD

**Issue by marwanmek** [LeetCode-Feedback/LeetCode-Feedback#7352]
Chapter on dynamic programming
      Intro to Dynamic Programming > What is Dynamic Programming?
https://leetcode.com/explore/featured/card/dynamic-programming/630/an-introduction-to-dynamic-programming/4034/

States: "For example, the brute force solution for calculating the Fibonacci sequence has exponential time complexity, while the dynamic programming solution will have linear time complexity."

Assuming:

    Dynamic Programming Solution: 
        //Something Like:
        int fibonacci (int n) {
            if(n == 0) {
                return 0;
            } else if (n == 1) {
                return 1;
            } else {
                return fibonacci(n-1) + fibonacci(n-2);
            }
        }
    
    Brute Force Solution: 
        //Something Like:
        int fibonacci (int n) {
            if (n == 0) {
                return 0;
            }
        
            int prev = 0, ans = 1, temp;
        
            for (int i = 1; i < n ; i++) {
                temp = ans;
                ans  = temp + prev;
                prev = temp;
            }
        
            return ans;
        }

Assuming the 'dynamic programming solution' is a recursive method to calculate the Fibonacci sequence, where the function returns the sum of itself for n-1 and n-2, which is what I understood from the text preceding this statement, the recursive method has an exponential time complexity and the 'brute force solution' has linear time complexity. The opposite of what the chapter states.

The statement is either wrong or very unclear about what it's referring to with he two solutions.

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. You're on the right track, but your assumption is backwards. Your brute-force solution is actually the bottom-up dynamic programming solution, you start at the base case (fibonacci(0) is 0 and fibonacci(1) is 1) and then you are reusing the results (stored in ans and prev) to calulate the result for the current subproblem, fibonacci(i). On the other hand, your dynamic programming solution is a brute-force approach because it recalculates the values necessary to solve the current subproblem every time. In order for it to be a dynamic progamming solution, it would need to reuse the results of these subproblems (by adding memoization). A sentence or two will be added to help clarify, but this issue should become clear as you progress through the card (in particular after reaching the slideshow on the next page).
