### ISSUE TITLE
56. Merge Intervals - new test cases and fix for a solution

### ISSUE THREAD

**Issue by iamantony** [LeetCode-Feedback/LeetCode-Feedback#748]
#### Your LeetCode username

iamantony

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

It seems that the judger's code can't properly process intervals if their numbers are swapped. Description of the issue does not have any constraints or assumptions about input, so I decided to play around with it and came up with these test cases:

##### Example 1:
- Input: [[1,-1]]
- Judger's output: [[1,-1],[1,-1]]
- Expected: [[-1, 1]]

##### Example 2:
- Input: [[5,3], [2,1]]
- Judger's output: [[2,1],[2,1],[5,3]]
- Expected: [[1, 2], [3, 5]]

#### Code you used for Submit/Run operation

```
// Merge Intervals
class Solution {
public:
    vector<vector<int>> merge(vector<vector<int>>& intervals) {
        std::for_each(intervals.begin(), intervals.end(), [](auto& i){ if (i[0] > i[1]) { std::swap(i[0], i[1]); } });
        std::sort(intervals.begin(), intervals.end(), [](const auto& left, const auto& right){ return left[0] < right[0]; });
        if (intervals.size() < 2) { return intervals; }
        
        std::vector<std::vector<int>> result;
        result.push_back(intervals.front());
        for (const auto& i : intervals) {
            auto& prev = result.back();
            if (i[0] >= prev[0] && i[0] <= prev[1]) {
                prev[1] = std::max(prev[1], i[1]);
            }
            else {
                result.push_back(i);
            }
        }
        
        
        return result;
    }
};
```

#### Language used for code

C++

#### Expected behavior

Function `merge()` should check order of values in each interval. If it detects that some interval have values in wrong order:
- stop execution due to invalid input or
- fix such interval by swapping numbers

#### Screenshots

<img width="1075" alt="example" src="https://user-images.githubusercontent.com/2803436/89043183-cc7fe680-d350-11ea-8b46-ef5b81caa4f8.png">

**Comment by lc-ivan** [comment]
Hi @iamantony ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
hi @iamantony ,
Thank you for your feedback and suggestion regarding this problem. I've checked with the content management team and it's a known issue that some problems are missing constraints and validators. Since these problems are very old, we are in the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that since it's a well-known issue, though you're welcome to issue tickets on Github, we will not be rewarding you with LeetCoins for the following tickets regarding constraints and validators. Thank you once again and happy LeetCoding!
