### ISSUE TITLE
489. Robot Room Cleaner (incorrect starting cond.)

### ISSUE THREAD

**Issue by dlqqq** [LeetCode-Feedback/LeetCode-Feedback#7505]
#### Your LeetCode username

david-qiu

(P.S. I still want a t-shirt for https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/7237)

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The question states that the robot is initially facing up. However, from my testing and from looking at the official solution code, it is quite apparent that the robot is initially facing left. From the official solution:

```java
  int[][] directions = {{-1, 0}, {0, 1}, {1, 0}, {0, -1}};
  ...
    public void cleanRoom(Robot robot) {
    this.robot = robot;
    backtrack(0, 0, 0);
  }
```

#### Code you used for Submit/Run operation

My code also demonstrates this:

```java
class Solution {
  boolean[][] grid = new boolean[199][399];
  int[][] DIRECTIONS = {
    { 0, 1 },
    { 1, 0 },
    { 0, -1 },
    { -1, 0 }
  };
  
  public void cleanRoom(Robot robot) {
    clean(robot, 99, 199, 3);
  }
  
  void clean(Robot robot, int row, int col, int dir) {
    if (grid[row][col]) return;
    robot.clean();
    grid[row][col] = true;
    
    int origDir = dir;
    // move in all 4 directions
    for (int i = 0; i < 4; i++) {
      if (robot.move()) {
        clean(robot, row + DIRECTIONS[dir][0], col + DIRECTIONS[dir][1], dir);
        reverse(robot);
      }
      robot.turnRight();
      dir = (dir + 1) % 4;
    }
  }
  
  void reverse(Robot robot) {
    robot.turnLeft();
    robot.turnLeft();
    robot.move();
    robot.turnLeft();
    robot.turnLeft();
  }
}
```

Replacing `clean(robot, 99, 199, 3)` with `clean(robot, 99, 199, 0)` results in an index out of bounds error for one test case.

#### Language used for code

Java.

#### Expected behavior

I expect the question to give me the correct starting condition.

#### Screenshots

N/A.

#### Additional context

N/A.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. 
Here is response from our develping team:
-In the bug description, the user claimed the direction vector {-1, 0} meant the robot was initially facing left instead of up.
The user claims replacing clean(robot, 99, 199, 3) with clean(robot, 99, 199, 0) means the robot is initially facing left instead of up.
- In the user's code, DIRECTIONS[3] = {-1, 0}, and DIRECTIONS[0] = {0, 1}.
- So, in the user's code, the initial direction vector is {-1, 0}, which is up.
- The user thought that {-1, 0} was moving to the left. However, it is clear that {-1, 0} is up.
- {-1, 0} is up because [row][col] ==> [row - 1][col] is up.

The user was not confused by the problem statement, they understood the code and official solution incorrectly. No issues here. "
We appreciate your support!
