### ISSUE TITLE
2290. Minimum Obstacle Removal to Reach Corner

### ISSUE THREAD

**Issue by Evil-Incorporated** [LeetCode-Feedback/LeetCode-Feedback#7540]
#### Leet Code ID
rajarshi_banerjee

#### Category of the bug
- The question in concern gave three different submission results for the same code (with the exception of commented out print statement), with the first one being a TLE and the third one being better than 90% execution
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
First time when I submitted the code it resulted in TLE, while the same code with an extra print statement got appected. After noticing this I submitted the code again after removing the print statement and this time it showed my code ran 90% faster than all submitted code (Previously it was somewhere near 43%). Why did this happen? (The print statement in concern was ```# print(i, j, count, is_path)``` )

#### Code you used for Submit/Run operation

```
import heapq
class Solution:
    def minimumObstacles(self, grid: List[List[int]]) -> int:
        m = len(grid)
        n = len(grid[0])
        visited = [[False] * n for _ in range(m)]
        path_queue = [[0, 0, 0]]
        obstacle_queue = []
        max_obs = 0
        while path_queue or obstacle_queue:
            
            is_path = len(path_queue) > 0
            
            cur_queue = path_queue if path_queue else obstacle_queue
                
            i, j, count = cur_queue.pop(0)
            if visited[i][j]:
                continue
            
            # print(i, j, count, is_path)
            
            max_obs = max(max_obs, count)
            if i == m - 1 and j == n - 1:
                return max_obs
            visited[i][j] = True
            
            if i != 0:
                if grid[i-1][j] == 0:
                    path_queue.append([i-1, j, count])
                else:
                    obstacle_queue.append([i-1, j, count + 1])
            if j != 0:
                if grid[i][j-1] == 0:
                    path_queue.append([i, j-1, count])
                else:
                    obstacle_queue.append([i, j-1, count + 1])
            if i != m - 1:
                if grid[i+1][j] == 0:
                    path_queue.append([i + 1, j, count])
                else:
                    obstacle_queue.append([i + 1, j, count + 1])
            if j != n - 1:
                if grid[i][j+1] == 0:
                    path_queue.append([i, j + 1, count])
                else:
                    obstacle_queue.append([i, j + 1, count + 1])
```

#### Language used for code
Python 3

#### Expected behavior

I expected my code to be accepted on the first try as the logic and time complexity was optimal, yet it resulted in TLE. Moreover the same code got accepted and even showed to be beating 90% of other submissions in execution time by simply tweaking a single print statement. This should happen.

#### Additional context
Here are all the submissions I made:

1. https://leetcode.com/submissions/detail/711471864/
2. https://leetcode.com/submissions/detail/711474517/
3. https://leetcode.com/submissions/detail/711475570/
4. https://leetcode.com/submissions/detail/711484865/

The first link is of the first submission getting TLE.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
