### ISSUE TITLE
Submission Issue - 354. Russian Doll Envelopes

### ISSUE THREAD

**Issue by raunak111** [LeetCode-Feedback/LeetCode-Feedback#7562]
#### Your LeetCode username
rexrener

#### Category of the bug
- [ ] Solution

#### Description of the bug

My code runs fine when I run it in console but gives TLE error upon submission

#### Code you used for Submit/Run operation

```
class Solution {
    
    static bool cmp(vector<int> a, vector<int> b){
        if(a[0]==b[0]) return a[1]>b[1];
        return a[0] < b[0];    
    }
    
public:
    
    int maxEnvelopes(vector<vector<int>>& envelopes) {
        
        int n = envelopes.size();
        
        sort(envelopes.begin(),envelopes.end(),cmp);
        
        vector<int> lis;
        
        lis.push_back(envelopes[0][1]);
        
        for(int i = 1;i<n;i++){
            int val = envelopes[i][1];
            auto it = lower_bound(lis.begin(),lis.end(),val);
            
            if(it == lis.end()) lis.push_back(val);
            else *it = val;
        }   
        return lis.size();
    }
};

```

#### Language used for code
C++

#### Expected behavior

If the code runs fine when using the console to run it, it should also be accepted when submitting

**Comment by LC-Pam** [comment]
The issue you experienced is runtime variation. It normally happens when your code is at the edge of the time limit that can pass the problem. Therefore, your code may have different results at different submissions.

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make different executions have runtime variation.
 
I've passed your feedback to our engineering team and they'll investigate in order to provide consistent results for our users. However, I'm afraid that we won't have a quick fix for the issue that you're facing. I recommend that you optimize your code to pass the time limit. We apologize for the inconvenience and thank you for your support!
