### ISSUE TITLE
1046. Last Stone Weight

### ISSUE THREAD

**Issue by HZ2412** [LeetCode-Feedback/LeetCode-Feedback#7579]
#### Your LeetCode username

kd8sp

#### Category of the bug
- [ ] Question
- [x ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

A Typo in the slides for diagram for Approach 4. Affected slides: 14 - 42
See screenshot section for more detailed explanation.

#### Code you used for Submit/Run operation

```


#### Language used for code
<!-- C++ -->


#### Expected behavior
<!-- A clear and concise description of what you expected to happen in
contrast with what actually happened. -->



#### Screenshots
<!-- If applicable, add screenshots to explain your issue. -->
Slide 13 (correct):
![image](https://user-images.githubusercontent.com/24820371/171744524-3d7c1fc5-c0fb-45cc-9d3a-176beafecca2.png)

Slide 14 (incorrect):
![image](https://user-images.githubusercontent.com/24820371/171744549-3b55bd4d-dcfa-42c9-9750-fea4202c92ae.png)

In slide 13, the biggestWeight is 17, and the next largest number in the array is 8, so when 17 and 8 clash, we're left with a stone of 9. Because according to the problem description, when two stones of different weights clash, the smaller one is destroyed, and the larger one's weight becomes the difference of the weight. This means 8 is destroyed, and 17 becomes a stone of weight 9. 
However, in the array, slot 17 still has a 1, and that 1 remained there until slide 42.
The 1 in slot 17 should be 0 in slide 14 - 42.

#### Additional context
<!-- Add any other additional context about the bug. -->

**Comment by LPRowe** [comment]
Just repasting so the images can be viewed.

> #### Screenshots
> 
> Slide 13 (correct):
> ![image](https://user-images.githubusercontent.com/24820371/171744524-3d7c1fc5-c0fb-45cc-9d3a-176beafecca2.png)
> 
> Slide 14 (incorrect):
> ![image](https://user-images.githubusercontent.com/24820371/171744549-3b55bd4d-dcfa-42c9-9750-fea4202c92ae.png)
> 
> In slide 13, the biggestWeight is 17, and the next largest number in the array is 8, so when 17 and 8 clash, we're left with a stone of 9. Because according to the problem description, when two stones of different weights clash, the smaller one is destroyed, and the larger one's weight becomes the difference of the weight. This means 8 is destroyed, and 17 becomes a stone of weight 9. 
> However, in the array, slot 17 still has a 1, and that 1 remained there until slide 42.
> The 1 in slot 17 should be 0 in slide 14 - 42.

**Comment by LPRowe** [comment]
@HZ2412 this is a good observation.  The buckets array does not always accurately represent the set of remaining stones.  

The reason the bucket array does not always represent the stones that are remaining is because when `biggest_weight` is zero and `buckets[current_weight]` is 1, we set the `biggest_weight` as the `current_weight` and move on to the next weight. We will never revisit this weight, so it does not affect our solution if `buckets[current_weight]` is left as 1. 

That said, in this implementation, this is okay. We do not need to perfectly maintain the bucket array in order to arrive at the correct result.  The current slideshow accurately shows the bucket array at each step - according to the given solution.  This can be verified by printing the bucket array at each step for this test case. 

While the gain from making this change is too small compared to the effort required to update the code and all of the slides, it would be possible to have the buckets array accurately portray the remaining stones by decrementing the `current_weight` count when the `biggest_weight` is reset:

```python
            elif biggest_weight == 0:
                buckets[current_weight] %= 2
                if buckets[current_weight] == 1:
                    biggest_weight = current_weight
                    buckets[current_weight] -= 1  # by adding this line
                current_weight -= 1
```
