### ISSUE TITLE
201. Bitwise AND of Numbers Range

### ISSUE THREAD

**Issue by liverdance** [LeetCode-Feedback/LeetCode-Feedback#759]
#### Your LeetCode username
liverdance

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Description of the problem:
"Given a range [m, n] where 0 <= m <= n <= 2147483647, return the bitwise AND of all numbers in this range, inclusive."
Which implies that input [0, 2147483647] is valid.
However it results in "Invalid Testcase".

#### Code you used for Submit/Run operation

```
func rangeBitwiseAnd(m int, n int) int {
    return 0
}
```

#### Language used for code
Go

#### Expected behavior
Test passed

#### Actual behavior
Line 7: Char 17: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int' (solution.cpp)

**Comment by lc-ivan** [comment]
Hi @liverdance ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @liverdance ,
Thank you for your feedback regarding this problem! I've checked with the content management team and it's a known issue that some problems don't have validators since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues.
