### ISSUE TITLE
comment was misleading the concept

### ISSUE THREAD

**Issue by pradeep9redddy** [LeetCode-Feedback/LeetCode-Feedback#7624]
#### Your LeetCode username

pradeep_rvv

#### Category of the bug
- [ ] Solution - yes

#### Description of the bug

In **Array Insertions page** (here is the link for the page) - https://leetcode.com/explore/learn/card/fun-with-arrays/525/inserting-items-into-an-array/3244/

Go to **Inserting Anywhere in the Array:**
Here in java code snippet, the first comment was wrong: "// Say we want to insert the element at **index 2.**"
The correct comment should be: "// Say we want to insert the element at **index 4.**"

#### Code you used for Submit/Run operation

```
// Say we want to insert the element at index 4.
```

#### Language used for code

Java

#### Expected behavior

Correct the comment in the java code. 
The first comment.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Added a follow up but the difficulty will not be changed. We appreciate your support!

**Comment by LC-Pam** [comment]
Thank you for sharing your concern. Lines 3 through 7 are moving all of the elements from index 2 and later, to the right by one space. This allows us to (on line 11) add a new value at index 2 without writing over any of the previous values in the array. As such, we are performing these steps so that we can insert an element at index 2.
