### ISSUE TITLE
What is the different between the 2 solutions given in implementation of design linked list question

### ISSUE THREAD

**Issue by Drk1006** [LeetCode-Feedback/LeetCode-Feedback#7699]
There are 2 solutions provided for design a linked list question.
1.https://leetcode.com/problems/design-linked-list/solution/
2.https://leetcode.com/explore/learn/card/linked-list/209/singly-linked-list/1298/

1st one is easier to understand however the 2nd one is bit difficult. May I know why there are 2 different solutions given and which one is the better in those 2 for an interview or complexity wise.2nd one is different than 1st one as in there is no sentinel node in 2nd and it considers head as the first element of  node.
Could you please provide an explanation between the 2 solutions?Thanks in advance.

**Comment by LC-Pam** [comment]
We have delivered  your needs to our team. Since the main responsibility of the content team is to deal with content-related issues, the question about the explanation of the solution code cannot be answered to you in a timely manner.  Please also feel free to refer to the discussion section of the question to see if other users can provide an explanation!
