### ISSUE TITLE
Wrong problem constraints or solution: Problem #4 median-of-two-sorted-arrays

### ISSUE THREAD

**Issue by dlitvak** [LeetCode-Feedback/LeetCode-Feedback#770]
#### Your LeetCode username
dilit

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
https://leetcode.com/problems/median-of-two-sorted-arrays/
The problem states: "You may assume nums1 and nums2 cannot be both empty."  This implies that 1 of the array might be empty (not both).  The solution does not address this case.  Change the solution or the problem constraint: both arrays are not empty.

#### Code you used for Submit/Run operation

```
# Python Solution code: error raised when n==0!
def median(A, B):
    m, n = len(A), len(B)
    if m > n:
        A, B, m, n = B, A, n, m
    if n == 0:
        raise ValueError
 .....
  
```

#### Language used for code

Python2

#### Expected behavior

Either change the problem description: both arrays are not empty
 or update solution: if n==0: return the median of the other array

Much better explanation is here:
https://medium.com/@hazemu/finding-the-median-of-2-sorted-arrays-in-logarithmic-time-1d3f2ecbeb46

**Comment by lc-ivan** [comment]
Hi @dlitvak ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @dlitvak ,
Thanks for your feedback regarding this question. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
