### ISSUE TITLE
BLOCKED - Missing Constraints - 23. Merge k Sorted Lists

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#771]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
23. Merge k Sorted Lists
https://leetcode.com/problems/merge-k-sorted-lists/

Please add constraints for this question, to be able to solve this question.
- What is the length of `lists`?
- What is the length of each linked list element in `lists`?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior
A question must have Constraints section, it is missing here.

This is an Easy question, but unable to attempt. Pl act on this.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your valuable feedback regarding this problem. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
