### ISSUE TITLE
A DFA related code problem is not actually solved with DFA 

### ISSUE THREAD

**Issue by patrik-lambert** [LeetCode-Feedback/LeetCode-Feedback#7729]
#### Category of the bug
- [ ] Question
- [ X ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

In the solution to string-to-integer-atoi problem (https://leetcode.com/problems/string-to-integer-atoi/solution/), under "Approach 2: Deterministic Finite Automaton (DFA)", a number of problems are mentioned as "Some other LeetCode problems which can be solved using DFA". In order to practice a bit more with DFAs, I thus tried one of the problems appearing in this list, namely "[Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)". I tried for several hours to solve this problem with DFA, but failed and when I looked at the solution, I saw that the problem is not at all solved with DFA, but with recursion or dynamic programming. Thus please, remove it from the list of "Some other LeetCode problems which can be solved using DFA".

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Expected behavior

"[Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)" problem is actually solved with recursion or dynamic programming, thus please, remove it from the list of "Some other LeetCode problems which can be solved using DFA" in the string-to-integer-atoi problem.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LPRowe** [comment]
@patrik-lambert Thank you for sharing your concern, that's a good observation. This list of problems is intended to guide users to problems that could be solved using DFA - just for practice not because the DFA is the optimal solution.  There are not a lot of problems that are optimally solved using DFA, and the solution articles try to guide users towards an efficient solution that can be completed in an interview setting. The list provides problems where you can practice implementing DFA, and the [discussion section](https://leetcode.com/problems/regular-expression-matching/discuss/?currentPage=1&orderBy=most_votes&query=DFA) will contain DFA implementations from other users, but in cases where DFA is not the optimal approach in an interview setting, it might not be included in the official solution article. Hope this helps to clarify!
