### ISSUE TITLE
536. Construct Binary Tree from String - Invalid Test Case Passes

### ISSUE THREAD

**Issue by cohenna** [LeetCode-Feedback/LeetCode-Feedback#777]
#### Your LeetCode username
nohm22

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language

#### Description of the bug

The bug is present in problem [536. Construct Binary Tree from String](https://leetcode.com/problems/construct-binary-tree-from-string/).

The system returns a valid result for an invalid test case: 

`"4-(3(4))(2)"`

The test case is invalid because there is a hanging minus sign not attached to an integer.  The only acceptable placement of a minus sign is before the integer according to the description of the input:

> The whole input represents a binary tree. It contains an integer followed by zero, one or two pairs of parenthesis. 

#### Code you used for Submit/Run operation

N/A because the problem is with the system returning a valid result for an invalid test case.  However, here is a simple non-solution which you can use to observe the bug in the system.

```
class Solution:
    def str2tree(self, s: str) -> TreeNode:
        return None
```

#### Language used for code
Python3

#### Expected behavior
The system shall report an error due to the invalid test case, not a valid solution.

**Comment by lc-ivan** [comment]
Hi @cohenna ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @cohenna ,
Thank you for your valuable feedback regarding this problem! I've checked with the content management team and it's a known issue that some problems don't have validators since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
