### ISSUE TITLE
132. Palindrome Partitioning II

### ISSUE THREAD

**Issue by leet212** [LeetCode-Feedback/LeetCode-Feedback#779]
#### Your LeetCode username
habaj

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug
Missing test cases

#### Code you used for Submit/Run operation

```
class Solution(object):
    def minCut(self, s):
        def f(i,d):
            if i==n:
                return 0
            if i not in d:
                t=""
                z=n
                for j in xrange(i,n):
                    t+=s[j]
                    if t==t[::-1]:
                        z=min(z,1+f(j+1,d))
                d[i]=z
            return d[i]
        n=len(s)
        return f(0,{})-1
```

#### Language used for code
Python

#### Expected behavior
Fails for test case

```
""
```

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @leet212 
Thank you for your time. The team reviewed the test case and considered it invalid. We've used your feedback to add missing constraints to the problem. Since missing constraints is a well-known issue to the old problems, this report won't be eligible for LeetCoins reward. We appreciate your support!
