### ISSUE TITLE
2307: OJ result for test case 127 seems incorrect

### ISSUE THREAD

**Issue by votrubac** [LeetCode-Feedback/LeetCode-Feedback#7863]
#### Your LeetCode username
votrubac

#### Category of the bug
- [ ] Question
- [X] Solution
- [ ] Language
- [X] Missing Test Cases 

#### Description of the bug
OJ result for test case 127 is `true`. I checked in manually, and there is no contradiction (see screenshot below).
```
[["aaa","zzz"],["zzz","aab"],["aab","aac"],["aac","aad"],["aad","aae"],["aaa","aag"],["aag","aah"],["aah","aai"],["aai","aae"]]
[1.000009,1.990,2.020,2.040,2.050,2.000,2.010,2.030,2.060]
```

#### Screenshots
![image](https://user-images.githubusercontent.com/17731201/174943295-914f97a2-8d5e-4ea6-9375-1c9aabfbe2a8.png)

#### Additional context
Solutions posted under **Discuss** return `false` for this test case.

**Comment by hqztrue** [comment]
I totally agree with your observation, and apologize for wasting your time investigating. This testcase is designed by me in order to provide a proof to LeetCode officials, showing that this problem is ill-defined and has inevitable precision issues.

I first mentioned the precision issue in #7780, but didn't seem to get enough attention. So I used similar ideas to create 4 testcases #7794, #7795, #7797 and #7823. As a result, no known solution can pass them all.

**Comment by abaransy** [comment]
@hqztrue bruh

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time.The problem has been updated, especially the constraints and testcases.
Please let us know if there are solutions that fail under the new constraints.
Your LeetCode account has received 100 LeetCoins as the reward for this feedback. 
We appreciate your support!
