### ISSUE TITLE
Go results wildly differ with same code

### ISSUE THREAD

**Issue by SHA65536** [LeetCode-Feedback/LeetCode-Feedback#7927]
#### Your LeetCode username

SHA2048

#### Category of the bug
- [ ] Question
- [ ] Solution
- [x] Language
- [ ] Missing Test Cases 

#### Description of the bug

Submitting the same code twice gives wildly different run-times and memory

#### Code you used for Submit/Run operation

```go
func maxScore(cardPoints []int, k int) int {
	// We are using a sliding window technique to find the
	// minimum sum group that lives inside cardPoints
	var subLength = len(cardPoints) - k
	var minSubsum, curSubsum, totalSum int
	// Getting sum of full group
	for i := 0; i < subLength; i++ {
		curSubsum += cardPoints[i]
		totalSum += cardPoints[i]
	}
	minSubsum = curSubsum
	// Moving the group slowly
	for i := subLength; i < len(cardPoints); i++ {
		curSubsum += cardPoints[i]
		totalSum += cardPoints[i]
		curSubsum -= cardPoints[i-subLength]
		if curSubsum < minSubsum {
			minSubsum = curSubsum
		}
	}
	// Subtracting the sum of min subgroup to get the sum of the outter cards
	return totalSum - minSubsum
}
```

#### Language used for code

Go (Golang)

#### Expected behavior

Submitting the same code should result in same or near same results

#### Screenshots

I submitted the same code twice and one of them was more than twice faster than the other one, along with 0.2MB difference
https://ibb.co/4sdp8DC

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. To help us further assess this issue and reproduce this issue on our end, would you please share the following information with us:

The problem name.

We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.

**Comment by SHA65536** [comment]
Hey!
For the screenshot i've shared the problem is 1423. Maximum Points You Can Obtain from Cards
Although I have found this happens for almost any question written in Go

**Comment by LC-Pam** [comment]
Thank you very much for reaching out to the Support Team.
 
This is a very great question here. Since you first submitted, there have been 11 new test cases that have been added. Furthermore, the backup queue is always enabled, and this can lead to a wide fluctuation in runtime at the moment. Other factors for this variation include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. There has been quite a bit of change on LeetCode on the backend of things since you first submitted, and I think those would also play apart in a very different runtime here.
 
Let me know if you have any further questions here at the moment.
