### ISSUE TITLE
Missing constraints - 676. Implement Magic Dictionary

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#801]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

676. Implement Magic Dictionary
https://leetcode.com/problems/implement-magic-dictionary/

Question is missing constraints:

Please add below:
1. How many words can be there in `buildDict` array ?
2. How many operations in total, in the input?
3. What is the max length of `insert` & `search` word?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Constraints are required to solve the problem, with right algorithm.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, we have updated the problem to the latest standards. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
