### ISSUE TITLE
Improper Time Limit - 2334. Subarray With Elements Greater Than Varying Threshold

### ISSUE THREAD

**Issue by u5n** [LeetCode-Feedback/LeetCode-Feedback#8115]
#### Your LeetCode username

migeater

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The time limit which is 10 seconds, is too narrow for the python segment tree.

#### Code you used for Submit/Run operation

This is what I submitted in the contest: https://leetcode.cn/contest/biweekly-contest-82/submissions/detail/334790107/

In the contest, I reuse the [code](https://leetcode.cn/submissions/detail/287861753/) which runs 4400ms in this [problem](https://leetcode.cn/problems/longest-substring-of-one-repeating-character/). This is an O(n*lgn) bottom-up segment tree algorithm.

However, the contest submission uses 9600ms. As we all know, leetcode calculates the total time spent. I am afraid that my submission failed after adding some large test cases.

I hope leetcode can increase the total time limit for this problem so the segment tree algorithm can pass. 
I suggest leetcode learn from codeforces, divide test cases into several groups, and only calculate time for each group.

#### Language used for code

python3

#### Expected behavior

My submission gets accepted after adding some large test cases.

**Comment by LC-Pam** [comment]
Thank you very much for reaching out to the Support Team.
 
This is a very great question here. Since you first submitted, there have been 11 new test cases that have been added. Furthermore, the backup queue is always enabled, and this can lead to a wide fluctuation in runtime at the moment. Other factors for this variation include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. There has been quite a bit of change on LeetCode on the backend of things since you first submitted, and I think those would also play apart in a very different runtime here.
 
Let me know if you have any further questions here at the moment.

**Comment by u5n** [comment]
Only very few changes, it can still pass:
https://leetcode.cn/submissions/detail/336113523/
So I think the time limit is too tight.
