### ISSUE TITLE
967 Numbers With Same Consecutive Differences, wrong test case.

### ISSUE THREAD

**Issue by bytebeats** [LeetCode-Feedback/LeetCode-Feedback#825]
In problem of [967 Numbers With Same Consecutive Differences](https://leetcode-cn.com/problems/numbers-with-same-consecutive-differences/), I thought server has some wrong solution for some test cases.
For **N = 1, K > 0**, I think solution should be **[]**. But when **Run Code** is clicked, response said **[0,1,2,3,4,5,6,7,8,9]** is expected. This is **NOT** right!. **Empty array [**] should be expected!

**Comment by Hilb3r7** [comment]
Actually it should be changed so that 2<=N<=9 because as stated the problem makes no sense with numbers of length 1 as there are no consecutive integers. That would remove the test case for N = 1 and for the user to have to guess whether the answer that's going to be graded correct is the empty array or the array [0,1,2,3,4,5,6,7,8,9]. (I guessed the latter because that's the only way you could ever have 0 and thus why I figured they explicitly stated 0 is valid)

**Comment by bytebeats** [comment]
@Hilb3r7 **2<=N<=9** and No **N=1**!

**Comment by feiceh** [comment]
这个 LCCN 无法处理，请美国团队协助查看～

**Comment by lc-pam** [comment]
Hi @bytebeats 
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-pam** [comment]
Hi @bytebeats 
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

**Comment by Hilb3r7** [comment]
> 
> 
> Hi @bytebeats
> Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!

*cough* *cough*
