### ISSUE TITLE
[Javascript][K Closest points from origin] Leetcode solution gives runtime error for big inputs

### ISSUE THREAD

**Issue by rakesh25** [LeetCode-Feedback/LeetCode-Feedback#8461]
#### Your LeetCode username

krakesh25

#### Category of the bug
- [ ] Solution

#### Description of the bug

Solution provided from leetcode for Javascript/Typescript that uses Max priority queue doesn't submit. It fails with Runtime error for big inputs

```
Runtime Error Message:
/.nvm/versions/node/v16.13.2/lib/node_modules/@datastructures-js/priority-queue/src/priorityQueue.js:79
      throw new Error('missing priority number or constructor callback');
            ^
Error: missing priority number or constructor callback
    Line 79: Char 13 in priorityQueue.js (MaxPriorityQueue.enqueue)
    Line 7: Char 19 in solution.ts (kClosest)
    Line 32: Char 19 in solution.ts (Object.<anonymous>)
    Line 16: Char 8 in runner.js (Object.runner)
    Line 21: Char 26 in solution.ts (Object.<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

#### Code you used for Submit/Run operation

```
function kClosest(points: number[][], k: number): number[][] {
    let maxPQ = new MaxPriorityQueue();
    for (let point of points) {
        let dist = calculateDistance(point);
        if (maxPQ.size() < k) {
            //dist is the priority
            maxPQ.enqueue(point, dist); //biggest dist will be first in the queue
        } else if (dist < maxPQ.front().priority) {
            maxPQ.dequeue(); //removes the element with max priority (distance)
            maxPQ.enqueue(point, dist);
        }
    }
    
    return maxPQ.toArray().map(el => el.element);
};

function calculateDistance(point: number[]) {
    let [x, y] = point;
    return x ** 2 + y ** 2;
}
```

#### Language used for code

Typescript

#### Screenshots

<img width="1285" alt="Screen Shot 2022-07-31 at 11 10 09 PM" src="https://user-images.githubusercontent.com/6858188/182083480-9d531026-3434-48db-96cc-7c3d409426ef.png">

#### Additional context

Failing for big inputs.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. Actually, we've not provided any solution involved with either TS/JS or priority queue/heap in our official solution for problem 973. The RE code was written by the user himself/herself.

For the problematic code by the user, we corrected it by adding 1 to the dist variable. (see  AC version based on it: https://leetcode.com/submissions/detail/762736778/). The user's code is wrong because PriorityQueue requires a number > 0 as its priority number when enqueue is called. It is a language/library feature in old version of datastructures-js and optimized in later versions (see [Release @datastructures-js/priority-queue-v4.1.2 · datastructures-js/priority-queue](https://github.com/datastructures-js/priority-queue/releases/tag/v4.1.2)), but LeetCode still applies the older version of the library. So our users have to be careful to keep the priority number positive when using JS/TS.
