### ISSUE TITLE
Missing Constraints - 336. Palindrome Pairs

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#863]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

336. Palindrome Pairs
https://leetcode.com/problems/palindrome-pairs/

Constraints are missing.

- What is the max length of Array?
- What is the domain for each string? lower case, upppr case, special symbols? etc.

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

Constraints must be present to solve the problem, also in an optimal way.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hello @manoharreddyporeddy ,
Thanks for your feedback regarding this problem. We have updated the problem with missing constraints. In addition, I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
