### ISSUE TITLE
Missing Test Case - 1249. Minimum Remove to Make Valid Parentheses

### ISSUE THREAD

**Issue by zeus8525** [LeetCode-Feedback/LeetCode-Feedback#8670]
#### Your LeetCode username

zeus1985

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

The 10^5 char long test case is missing. The test case is memory intensive and takes almost 1000ms. If the first half of the string are ) and second half of the string are (, it takes the longest time for a 100000 char long string. 

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution:
    def minRemoveToMakeValid(self, s: str) -> str:
        cps = s +''
        s = self.rem(s, '(',')')
        s = self.rem(s[::-1],')','(')
        return s[::-1]
      
            
    def rem(self, s, l, r):
        i = 0
        k = 0
        cnt = len(s)
        while i < cnt:
            if s[i] == l:
                k += 1
            elif s[i] == r:
                k -= 1
                
            if k < 0:
                s = s[:i] + s[i+1:]        
                cnt -= 1
                k = 0
            else:
                i+= 1

        return s
        
```

#### Language used for code

Python

#### Expected behavior

It should take a long time to complete this test case. 1008ms

#### Screenshots

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/38299929/184554893-60b42fd6-d4ee-4db7-88c6-e7edc4daf19a.png">

#### Additional context
 input:
Attached the input that is tested. 
[input.log](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/9334119/input.log)

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that makes it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
