### ISSUE TITLE
Binary Search Template 2 'right' variable value supposed to be 'len(nums)-1'

### ISSUE THREAD

**Issue by salahuddin975** [LeetCode-Feedback/LeetCode-Feedback#8703]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[The Binary Search Template 2](https://leetcode.com/explore/learn/card/binary-search/126/template-ii/937/) accesses to the right index. It has a post-processing end condition. If the 'right' variable value gets 'len(nums)-1', it works correctly. 

#### Code you used for Submit/Run operation

```
def binarySearch(nums, target):
    """
    :type nums: List[int]
    :type target: int
    :rtype: int
    """
    if len(nums) == 0:
        return -1

    left, right = 0, len(nums) - 1
    while left < right:
        mid = (left + right) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            left = mid + 1
        else:
            right = mid

    # Post-processing:
    # End Condition: left == right
    if left != len(nums) and nums[left] == target:
        return left
    return -1
```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to investigated. The initialization of right = len(nums) works. This is the classic binary search template using the range [lower, upper), the right endpoint of the range could be something infeasible. As you indicates, len(nums)-1 also works because we have early return when mid is target, so we don't need to go to len(nums) to confirm there is no target value in nums.  Thanks for the your feedback. We appreciate your support!
