### ISSUE TITLE
Missing Constraints - 97. Interleaving String

### ISSUE THREAD

**Issue by manoharreddyporeddy** [LeetCode-Feedback/LeetCode-Feedback#889]
#### Your LeetCode username
pgmreddy

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language

#### Description of the bug

97. Interleaving String
https://leetcode.com/problems/interleaving-string/

Constraints are missing

1. What is the length of s1, s2 & s3?
2. What characters s1, s2 & s3 will have? [a-z] only?

#### Code you used for Submit/Run operation

```
```

#### Language used for code
JS

#### Expected behavior

A hard question might run into Timeout errors.
Constraints will help solve in full.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @manoharreddyporeddy ,
Thank you for your feedback regarding this problem. Upon review, our team has added constraints to the problem. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
