### ISSUE TITLE
Run Code and Submission outputs do not match - Python3

### ISSUE THREAD

**Issue by PrateekAdhikaree** [LeetCode-Feedback/LeetCode-Feedback#89]
**What kind of the bug**
- [ ] problem
- [x] solution
- [ ] language

**Describe the bug**
Running a solution shows a test as passed but submitting the solution shows a different output for the same test case.

**what language is your code written in**
Python3

**The code you submit/run**
```
# Definition for singly-linked list.
# class ListNode:
#     def __init__(self, x):
#         self.val = x
#         self.next = None

class Solution:
    def detectCycle(self, head: ListNode, vals=[]) -> ListNode:
        node = None
        if head.next is None:
            return node
        elif head.val in vals:
            return head
        else:
            vals.append(head.val)
            node = self.detectCycle(head.next, vals)
            
        return node
```

**Expected behavior**
The submission should be accepted.

**Screenshots**
![Screen Shot 2020-03-31 at 10 33 14 AM](https://user-images.githubusercontent.com/34014127/78058126-d5868a00-7355-11ea-861e-ea01f8e41e92.jpg)

**Additional context**

**Comment by CooperCooperCooper** [comment]
Hi @PrateekAdhikaree,
Thank you for reaching out to us! The difference in "Output" from "Run Code" and "Wrong Answer" is likely due to the static variable. We've documented this issue and its various solutions thoroughly in this "[I encountered Wrong Answer/Runtime Error for a specific test case](https://support.leetcode.com/hc/en-us/articles/360011834174-I-encountered-Wrong-Answer-Runtime-Error-for-a-specific-test-case-When-I-test-my-code-using-this-test-case-it-produced-the-correct-output-Why-)" article. Please take a look.
