### ISSUE TITLE
Missing Test Case - 415. Add Strings

### ISSUE THREAD

**Issue by chiragdhouni** [LeetCode-Feedback/LeetCode-Feedback#8960]
![Screenshot (3)](https://user-images.githubusercontent.com/94050461/188955518-3ea9b911-ee76-4e29-a6ea-68585872b38a.png)

what to do

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.
