### ISSUE TITLE
Arrays 101 problems with Rust use Vec instead of a fixed-size array

### ISSUE THREAD

**Issue by danandreicarp** [LeetCode-Feedback/LeetCode-Feedback#9004]
#### Your LeetCode username
carpdan

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

The Arrays 101 content uses the `Vec` data structure for all Rust problems, in the template. This is an issue because it should use a fixed-size data structure, i.e. an array, not a data structure that can modify its size.

The reason I'm stating this is this line from the [A Better Repeated Deletion Algorithm - Intro](https://leetcode.com/explore/learn/card/fun-with-arrays/511/in-place-operations/3256/) section:

> One potential problem is that we actually don't know how long the result Array needs to be. Remember how that must be decided when the Array is created?

Find more details about "arrays" in Rust [here](https://doc.rust-lang.org/book/ch03-02-data-types.html#the-array-type) and [here](https://doc.rust-lang.org/std/primitive.array.html). About `Vec` [here](https://doc.rust-lang.org/std/vec/struct.Vec.html).

#### Code you used for Submit/Run operation

I argue that the function signature shouldn't be:

```rust
pub fn remove_duplicates(nums: &mut Vec<i32>) -> i32
```

but rather:

```rust
pub fn remove_dup(nums: &mut [i32]) -> i32
```

#### Language used for code

Rust

#### Expected behavior

I expect the method signatures to actually allow the use of the primitive Array type, instead of the List-like `Vec`.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We don't actually provide any Rust code sample in explore card. The user was confused by a practice problem in this section that gives a default function signature of vectors instead of arrays (which is supposed to be practiced in this section). The user may make sense, but the problem is selected from the LeetCode problem collection, thus the problem won't be limited to array just for matching our explore card. We appreciate your support!
