### ISSUE TITLE
450. Delete Node in a BST: Missing Constraint or Solution doesn't cover Test cases

### ISSUE THREAD

**Issue by hamidgasmi** [LeetCode-Feedback/LeetCode-Feedback#902]
#### Your LeetCode username
O_Leet_Code

#### Category of the bug
- [x] Question
- [x] Solution
- [ ] Language

#### Description of the bug
The constraints are missing in the description or the solution doesn't cover some cases where the key is duplicated in the BST.

Example 1:
 - Inputs: [5,7,null,7], 7
 - Leetcode displayed expected output: [5,7]
 - Expected output: [5]

Example 2:
 - Inputs: [5,3,6,2,4,6], 6
 - Leetcode displayed expected output: [5,3,6,2,4]
 - Expected output: [5,3,null,2,4]

#### Code you used for Submit/Run operation

```
```

#### Language used for code
Python3

#### Expected behavior
See Description of the bug above

**Comment by lc-ivan** [comment]
Hi @hamidgasmi ,
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by lc-ivan** [comment]
Hi @hamidgasmi ,
Thank you for your feedback regarding this problem. Upon review, our team has updated the problem with constraints. I've checked with the content management team and it's a known issue that some problems don't have constraints since these problems are very old, and we are on the process of adding those case by case. This process will take some time, so please be patient. The team also mentioned that though you're welcome to issue tickets on GitHub, we will not be rewarding users with LeetCoins for the following tickets as these are known issues. Thank you once again and happy LeetCoding!
