### ISSUE TITLE
Missing Test Case - 1870. Minimum Speed to Arrive on Time

### ISSUE THREAD

**Issue by aospiridonov** [LeetCode-Feedback/LeetCode-Feedback#9094]
#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

_Runtime Error Message:_
Line 43: type 'int' is not a subtype of type 'double'
#0      main (file:///solution.dart:43:13)
<asynchronous suspension>
_Last executed input:_
[1,3,2]
6

#### Code you used for Submit/Run operation

```
class Solution {
  int minSpeedOnTime(List<int> dist, double hour) {
    int left = 1, right = 10000000, middle = 0;
    while (left <= right) {
      middle = (left + right) ~/ 2;
      double sum = 0;
      for (int i = 0; i < dist.length - 1; i++) {
        sum += (dist[i] + middle - 1) ~/ middle;
      }
      sum += dist[dist.length - 1] ~/ middle;
      if (sum > hour) {
        left = middle + 1;
      } else {
        right = middle - 1;
      }
    }
    return middle;
  }
}
```

#### Language used for code

Dart

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!

It’s a very difficult and ongoing research to evaluate the program’s runtime and get the same value for different runs of the same program. We have tried our best to make sure we isolate your program’s runtime, but there exist a lot of factors that make it extremely hard to quantify the runtime correctly.

The significance of program’s runtime we're providing to you is so that you can compare your code with the peaks in the graph, where programs that have different time complexities like O(n), O(n^2) would be around different peaks (at least in most of the cases). Other factors include compiler changes, optimizations, and more features that our developers keep on working on to provide better UX. These factors all also affect the runtime of the same program, introducing some level of discrepancy.

I hope this explanation answers your doubts. If you have any other questions, please don't hesitate to let us know.

**Comment by aospiridonov** [comment]
The decision is not related to time.
A problem with type conversion!
