### ISSUE TITLE
Vague Problem Description- 1509. Minimum Difference Between Largest and Smallest Value in Three Moves

### ISSUE THREAD

**Issue by Freeze777** [LeetCode-Feedback/LeetCode-Feedback#9499]
#### Your LeetCode username
freeze_francis

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug
The problem statement is very confusing/vague.
Please refer this : https://leetcode.com/problems/minimum-difference-between-largest-and-smallest-value-in-three-moves/discuss/1369313/Help-understanding-the-question

#### Expected behavior
Existing misleading description: `Given an array nums, you are allowed to choose one element of nums and change it by any value in one move.`

What I think is correct:`Given an array of nums, you are allowed to choose one element of nums and change it by any value that exists in nums in one move.`

#### Screenshots
https://leetcode.com/problems/minimum-difference-between-largest-and-smallest-value-in-three-moves/

**Comment by LC-Pam** [comment]
Thank you for your time. The problem is clear. We said can change any array element to any value, we bold it, and we meant it.
It is also clear that we are interested in the difference after at most 3 moves. That was mentioned and bolded in the statement.
Changed the explanations of test cases and added one more test case to make everything clear.
Checked the feedback and did not find similar issues about the statement. We appreciate your support!
