### ISSUE TITLE
Elixir - 855. Exam Room

### ISSUE THREAD

**Issue by ah0y** [LeetCode-Feedback/LeetCode-Feedback#9576]
Is this problem actually solvable in elixir? Elixir is a listed supported language for this problem, but Elixir has no state so how exactly is there supposed to be an `init` function...?

Should the comments in the problem instead maybe say something like this?
```
# Your functions will be called as such:
# ExamRoom.init_(n)
# |> ExamRoom.seat()
# |> ExamRoom.seat()
# |> ExamRoom.leave(p)
# |> ExamRoom.seat()
# |> ExamRoom.leave(p)

```

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Hello,

Thank you for bringing this concern to our attention. We've conducted a thorough investigation, and indeed, the problem is solvable in Elixir. You can initialize a global state that can be used across functions within the init function.

For a reference solution, you can check out the implementation here: [Exam Room Elixir Solution](https://leetcode.com/problems/exam-room/submissions/1119912920).

If you have any more questions or if there's anything else I can assist you with, feel free to let me know!

Best regards,
Support team
