### ISSUE TITLE
Missing Test Case - 33. Search in Rotated Sorted Array

### ISSUE THREAD

**Issue by arcticOak2** [LeetCode-Feedback/LeetCode-Feedback#9760]
#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

I wrote a code where I'm doing a linear search still the solution is accepted and it beats 80 percent of the existing submissions.

#### Code you used for Submit/Run operation

```
// Search in Rotated Sorted Array
class Solution {
    public int search(int[] nums, int target) {
        for (int i = 0; i < nums.length; i++) {
            if (nums[i] == target) {
                return i;
            }
        }

        return -1;
    }
}
```

#### Language used for code

Java

#### Expected behavior

Time Limit exceeded should come

#### Screenshots

<img width="911" alt="Screenshot 2022-11-05 at 3 50 36 PM" src="https://user-images.githubusercontent.com/20299940/200115077-ea5e6ec5-66c9-47f2-bf02-f1345c8a7b8c.png">

**Comment by 0504Shreyansh** [comment]
Bro, these details are actually based on leetcode servers and I completely understand your situation and I do agree with you, but there's something even funny about it as you submit this after sometime, it might give better Time and Space complexities.
Let me tell you my case, when I used bubble sort (O(N2)) , it showed a 100% TC, but when I used a better a searching algo, it showed 70%. Another situation when I got TLE in a question, I just removed all the comments and cout statements, the problem was solved.😂
