### ISSUE TITLE
Poor Pigs

### ISSUE THREAD

**Issue by nryotaro** [LeetCode-Feedback/LeetCode-Feedback#9807]
#### Your LeetCode username

nryotaro

#### Category of the bug
- [ ] Question
- [x] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

[Poor Pigs](https://leetcode.com/problems/poor-pigs/solution/)

The following Python code in the solution page fails if you pass a test case whose values are (125, 1, 4).

```python
class Solution:
    def poorPigs(self, buckets: int, minutesToDie: int, minutesToTest: int) -> int:
        states = minutesToTest // minutesToDie + 1
        return math.ceil(math.log(buckets) / math.log(states))
```

**Comment by LC-Pam** [comment]
Thank you for your time. The approach is correct, but there is an error with floating point precision that makes it fail on this test case (image attached).

It's very cumbersome to edit the approach to account for the error, you would need to double the code. Because the approach is correct,  we will not make any change and consider the ticket done. We appreciate your support!
