### ISSUE TITLE
Missing Test Case - 1672. Richest Customer Wealth

### ISSUE THREAD

**Issue by shuishiyuan** [LeetCode-Feedback/LeetCode-Feedback#9821]
#### Your LeetCode username

StoneMason

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Code you used for Submit/Run operation

```
// one loop solution in C using col and row calculating algebra
int maximumWealth(int** accounts, int accountsSize, int* accountsColSize){
    int max = **accounts;
    int sum = 0;
    int rowIdx = 0;
    int colIdx = 0;
    for (int i = 0; i < accountsSize * *accountsColSize; ++i) {
        rowIdx = i / *accountsColSize;
        colIdx = i % *accountsColSize;
        if (colIdx == 0) {
            max = max < sum ? sum : max;
            sum = 0;
        }
        sum += accounts[rowIdx][colIdx];
    }
    max = max < sum ? sum : max;
    return max;
}
```

#### Language used for code

C

#### Expected behavior

expected the test case below

```
[[1]]
```

**Comment by nskybytskyi** [comment]
Hello! Additional test cases are added when there is some sort of a problem with the current test suite. For example, when there is a solution that currently gets AC, but should get WA/TLE on the suggested test case. However, your solution works equally well on this test case and the current test suite. Hence I see no reasons to add it, as enlarging the test suite just because we can is not always a good idea.
