### ISSUE TITLE
My profile info regarding contest is not correct

### ISSUE THREAD

**Issue by byegates** [LeetCode-Feedback/LeetCode-Feedback#9834]
#### Your LeetCode username

byegates

#### Category of the bug
- [x] Question
- [ ] Solution
- [ ] Language
- [ ] Missing Test Cases 

#### Description of the bug

My profile says for Weekly contest 318, I got 0 out of 4 solved, and the rank is 0, both are not correct, my rank should be 3704 and I got 3 out of 4 right.

#### Code you used for Submit/Run operation

```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

#### Screenshots

<img width="395" alt="Screenshot 2022-11-10 at 11 42 10 PM" src="https://user-images.githubusercontent.com/3407579/201290873-1a9a0bab-4545-4374-90c4-a1834b356647.png">

<img width="1095" alt="Screenshot 2022-11-10 at 11 41 55 PM" src="https://user-images.githubusercontent.com/3407579/201290823-7e4cff77-8102-44d9-b075-b7262e89739f.png">

**Comment by nskybytskyi** [comment]
It will take some time to process all 22,819 participants. If you look at the people next to you on the leaderboard, you'll see that their ranking updates are also pending. Please give it some time, and your data will be fetched soon. Congratulations on a good performance! 🥳

**Comment by LC-Pam** [comment]
Thank you for reaching out to us!
 
I am so sorry this happened. This is a known error that happens when contest rankings are first published. They update after a bit of time, and should be successfully published very soon. Let me know if you are encountering any issues at this time. Our team is looking for improvements for the future.
 
We appreciate your time and support. If you have any other questions, please don't hesitate to let us know.
