### ISSUE TITLE
Missing Test Case - 7. Reverse Integer

### ISSUE THREAD

**Issue by errinku44** [LeetCode-Feedback/LeetCode-Feedback#9947]
#### Your LeetCode username

rinku_kumar_mean

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 
Missing Test Cases 

#### Description of the bug

what is we provide any number with leading 0.

#### Code you used for Submit/Run operation

`01231
```
// Two Sum
class Solution {
public:
    vector<int> twoSum(vector<int> &a, int s) {

    }
};
```

**Comment by nskybytskyi** [comment]
Thank you for reaching out. The suggested test case is invalid. You should have seen this message when trying to run any solution on such a test case 

<img width="350" src="https://user-images.githubusercontent.com/25816558/202616789-f9946408-9237-435e-97f8-3d45753aa8fa.png">

Unless otherwise specified, integers and other numbers cannot contain extra leading zeroes, unline strings, and other containers.
