### ISSUE TITLE
Missing Test Case - 2476. Closest Nodes Queries in a Binary Search Tree

### ISSUE THREAD

**Issue by hqztrue** [LeetCode-Feedback/LeetCode-Feedback#9984]
#### Your LeetCode username

hqztrue

#### Category of the bug
- [ ] Question
- [ ] Solution
- [ ] Language
- [x] Missing Test Cases 

#### Description of the bug

An accepted solution gets TLE on the following testcase:
[1.txt](https://github.com/LeetCode-Feedback/LeetCode-Feedback/files/10048916/1.txt)

#### Code you used for Submit/Run operation

```
/**
 * Definition for a binary tree node.
 * struct TreeNode {
 *     int val;
 *     TreeNode *left;
 *     TreeNode *right;
 *     TreeNode() : val(0), left(nullptr), right(nullptr) {}
 *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}
 *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}
 * };
 */
class Solution {
public:
    vector<vector<int>> closestNodes(TreeNode* root, vector<int>& queries) {
        if (root == nullptr) return {};
        vector<vector<int>> ans;
        for (auto nums: queries)
        {
            TreeNode *tmp = root;
            vector<int> v1(2, nums);
            int maxi = -1;
            int mini = -1;
            while (tmp != nullptr)
            {
                if (nums == tmp->val)
                {
                    maxi = nums;
                    mini = nums;
                    break;
                }
                else if (nums < tmp->val)
                {
                    maxi = tmp->val;
                    tmp = tmp->left;
                }
                else
                {
                    mini = tmp->val;
                    tmp = tmp->right;
                }
            }
            v1[0] = mini;
            v1[1] = maxi;
            ans.emplace_back(v1);
        }
        return ans;
    }
};
```

#### Language used for code

C++

#### Expected behavior

The code gets TLE.

**Comment by ArshadAQ** [comment]
Just my few cents:

Given that this is the 2nd problem of the contest(which is generally at an easy-medium level), I don't think this test case should be added. I guess, perhaps adding a constraint to the input so that the input is a balanced BST would be a better route to take for this question.

Also, finding the answer, by traversing the BST in-place has more scope of learning and is more interesting, rather than just unravelling the whole tree into an array and just doing a binary search. The later just becomes an array problem having nothing to do with trees.

I know there are other arguments/merits for not restricting the input to a balanced BST, but given that this problem is an easy-medium level(3 points), I think not restricting the input to a balanced BST would be a better decision.

Just my opinion.

**Comment by LC-Pam** [comment]
Thank you for reaching out to us. I've relayed this issue to our team to investigate.

**Comment by LC-Pam** [comment]
Thank you for your time. We've used your feedback to update the problem. Your LeetCode account has received 100 LeetCoins as the reward for this feedback. We appreciate your support!
